# 方正 {#05}
## 5.1
> 陈太丘与友期行，期日中，过中不至，太丘舍去，去后乃至。元方时年七岁，门外戏。客问元方：“尊君在不？”答曰：“待君久不至，已去。”友人便怒，曰：“非人哉！与人期行，相委而去！”元方曰：“君与家君期日中。日中不至，则是无信；对子骂父，则是无礼。”友人惭，下车引之。元方入门不顾。  

- *陈太丘*：陈寔。
- *尊君在不*:不，否。
- *相委*：舍弃对方。
- *非人哉*：《论语》：“人而不信，不知其可也”
- *下车引之*：这个朋友是在车上问，车上骂，很不妥当。引之：拉手，表示接纳和歉意。陈纪七岁就能思路很清楚地说理，陈寔的友人虽然能知错道歉，但陈纪还是以直报怨，不愧为“元方”。  

古人说这个孩子聪明，时间点往往是七岁。譬如孔子拜七岁神童项橐为师，唐代骆宾王七岁咏诗，刘晏七岁“举神童”，宋代晏殊七岁“能属文”，《世说新语》中王戎七岁识苦李，何晏七岁“明慧若神”，孔融的女儿七岁了悟生死，顾敷七岁说“忘情故不泣，不能忘情故泣”，民谚“三岁看大七岁看老”，我想，一般来说，七其实是个虚数，举数为七，或言其多，举岁为七，当言其小。《说文解字》中说：“七，阳之正也”。七从一，有微阴介入；《易纬》中指出：“易变而为一，一变而为七，七变而为九，九复变而为一。”在中外文化中，七是个很有趣的数字。

## 5.2
>南阳宗世林，魏武同时，而甚薄其为人，不与之交。及魏武作司空，总朝政，从容问宗曰：“可以交未？”答曰：“松柏之志犹存。”世林既以忤旨见疏，位不配德。文帝兄弟每造其门，皆独拜床下。其见礼如此。

- *宗世林*：河南宗承字世林，年轻时候名望比曹操高很多，“闻德而至者如林”，家里“宾客猥积”，但他交的朋友是袁术这样出身高贵的人，看不起曹操宦官家庭出身的“任侠放荡”之人，“拒而不纳”。曹魏政权后来被司马家取代，很大的原因是其家族出生不好，司马懿则是“醇儒”之家。
- *司空*：建安元年八月，曹操迎汉献帝于许昌建都，挟天子以令诸侯，自任司空（三公之一），行车骑将军事，百官总己以听。
- *松柏之志犹存*：《论语》：“岁寒，然后知松柏之后凋也。”后凋的理解一向有争议，一般人认为是最后凋谢，松柏坚持到最后；何晏、段玉裁等说凋是半伤；还有人说，凋不是凋谢，而是凋衰，形小凋衰，而心性犹存；还有人说，后凋就是不凋，因为《庄子》引用孔子的话是“大寒既至，霜雪既降，吾是以知松柏之茂也！”《世说新语?言语?57》：“蒲柳之姿，望秋而落；松柏之质，经霜弥茂。”；还有人说，凋总是要凋的，但它凋的时候，新的又跟上去了，还是很茂盛。后面的几种说法，都是为了把孔子的话说圆，属于过度阐述。比喻总难免无法达到圆满，孔子的本意大概就是司马迁解释的那样：“举世混浊，清士乃见。”  

宗世林的回答使用比喻，比较委婉，没有像边让、祢衡那样激烈，“多轻侮之言”，曹操这点胸怀还是有的，于是没下毒手，“薄其位而优其礼”。至于陈琳，虽然骂曹操“赘阉遗丑”、“ 豺狼野心”，无非是“箭在弦上，不得不发”，另当别论。后来曹操杀了好些看不起他的清流，引发了士族的大反抗和广泛的不合作，于是曹操又打出宗承的牌，叫曹丕等兄弟经常去拜访宗承，行弟子礼，以表示他还是想和士族合作，以缓和他与士族意识形态上的矛盾。这种类似的做法，康熙、蒋介石、毛泽东都是这样的。譬如蒋介石杀左派学者一点不手软，但对钱穆、胡适、郭沫若等却比较包容甚至优待，尽管这些人也经常批评国民党政府。  
曹魏时期刘桢有首诗，说的和宗承差不多是一个意思，我在 2.10 引用过：“亭亭山上松，瑟瑟谷中风。风声一何盛，松枝一何劲。冰霜正惨凄，终岁常端正。岂不罹凝寒，松柏有本性。”

## 5.3
>魏文帝受禅，陈群有戚容。帝问曰：“朕应天受命，卿何以不乐？”群曰：“臣与华歆服膺先朝，今虽欣圣化，犹义形于色。”

- *服膺*：心中记着。
- *圣化*：曹丕登基。
- *形于色*：对先朝的忠义形于颜色。  

这个故事在《德行》中介绍过，见 1.6。  
观曹丕作为皇帝的一生，算不得什么明君，就像陈寿讲的那样，曹丕做皇帝如果心胸开阔，做事公平，加上能有点志向，看问题不糊涂，品性能做到善良，那就和古代的贤君不远了，这种含着讽刺的评价就说明曹丕做皇帝实在很糟糕。不过作为个人，我却蛮喜欢曹丕的一些生活细节，他有想法而无大志，有精明但无智慧，是很真实的一个人，做狗肉朋友是蛮好的。譬如他在王粲坟前学驴叫，譬如他和夏侯尚从小关系就很好，当了皇帝后，有一次居然给夏侯尚写了个手诏，上面说：“卿腹心重将，特当任使。恩施足死，慧爱可怀。作威作福，杀人活人”，夏侯尚和他一个脾气，拿着这份信显摆，结果被大臣蒋济劝告后收回手诏。  
这次受禅，曹丕也表现得很有趣。首先他花了不少心思开创了一个禅让制度，《三国志》和《三国志 注》里花了巨大篇幅讲述曹丕受禅前后的种种细节和程序，而且搞得规模很宏大，“魏王登坛受禅，公卿、列侯、诸将、匈奴单于、四夷朝者数万人陪位，燎祭天地、五岳、四渎”，从此以后魏晋南北朝多次“禅让”，就有先例可以照搬照抄。其次，禅让礼毕，他立刻志得意满地对大臣们说了一句直接剥了儒家学说的画皮的妙语：“舜禹之事，吾知之矣！”（被儒家吹捧到天上去的舜禹禅让，原来就是这么一回事，一语中的）。这次他就问陈群：“我当了皇帝，你怎么脸色不好，好像没有为我而高兴嘛！”  
当然，这个故事应该是编造的，陈群哪有爷爷的风骨，在劝进表中，尚书令陈群，相国华歆署名非常靠前，说华歆、陈群有“戚容”、“不怡”，选自于华峤的《谱叙》，无非是抬举祖先罢了。想当年华歆把躲在柜子的汉献帝的伏皇后里拉出来咔嚓掉，哪有什么忠和礼可言！  
曹丕有一点很像他的父亲——通达。譬如他在诏书里很实在地讲：“自古及今，未有不亡之国，亦无不掘之墓也。”就是说曹魏也肯定要灭亡的，老头子的墓总是要被挖掉的，与其让别人来盗墓，不如由他自己把曹操的高陵给填平算了。他对厚葬和鬼神之说不以为然，“骨无痛痒之知，冢非栖神之宅”，“自今敢设非祀之祭，巫祝之言，皆以执左道论”。他把汉代的很多行宫给拆了，用这些大木料造自己的房子，并解释说：“夏朝灭亡，商汤就拆毁夏王的宫殿；商朝灭亡，姬发就拆毁商王的宫殿；周朝灭亡，诸侯就拆毁周天子的宫殿；六国灭亡，嬴政就拆毁除他自己之外所有君主的宫殿。现在汉道衰亡，我拆它几座行宫算得了什么！”这些文章肯定是出于他的手笔，别人是不敢说这种实话的。他写《典论》，原因是当时瘟疫大起，他想自己能留下一些名声：“生有七尺之形，死唯一棺之土，唯立德扬名，可以不朽，其次莫如著篇籍。疫疠数起，士人凋落，余独何人，能全其寿?”于是以“著述为务”。曹丕活了40岁，他在皇帝的位置上没有取得多大成就，但他的不少作品和言论令人钦佩。  

## 5.4
>郭淮作关中都督，甚得民情，亦屡有战庸。淮妻，太尉王凌之妹，坐凌事，当并诛。使者征摄甚急，淮使戒装，克日当发。州府文武及百姓劝淮举兵，淮不许。至期遣妻，百姓号泣追呼者数万人。行数十里，淮乃命左右追夫人还，于是文武奔驰，如徇身首之急。既至，淮与宣帝书曰：“五子哀恋，思念其母。其母既亡，则无五子。五子若殒，亦复无淮。”宣帝乃表特原淮妻。

这个故事放在“方正”这里比较奇怪，方正从字面上理解，就是为人比较严肃，守礼法，有操守。它在汉代第一个辟举科目，西汉文帝时，设“贤良方正、能直言极谏者，以匡朕之不逮。”当时选拔官员，就是按贤良方正这种科目来的。后来也有其他如茂才、文学、孝悌、力田等科目。对“方正”的要求，按照汉景帝时晁错所说，应该是“察身而不敢诬，奉法令而不容私，尽心力不敢矜，遭患难不避死，见贤不居其上，收禄不过其量，不以无能居尊显之位”。  
“方正”在后来也有一些变化，譬如我们看世说新语，作者把上等人不与下等人吃饭讲话也列入“方正”，说这个是“方正”也不难理解，它本来就是当时新出来的礼法，维护的是阶级利益。但郭淮搞阴谋诡计保护妻子怎么也变成“方正”了呢？也许我们可以这样理解，魏晋时期家族利益上升，超过忠君思想，那么谁能够据理力争，维护家族利益比较成功，谁就是方正！  

- *郭淮*：曹魏名将。215年，在黄忠对夏侯渊一役中崭露头角，而后一直在西北前线带兵打战。249年，任征西将军，都督雍州凉州诸军事。250年，为车骑将军，仪同三司，进封阳曲侯。251年，家族就遇到了这么一件大事。</br> 郭淮开始并不依附与司马家族，他还是曹魏的忠臣，颇得曹丕的信任。他是王凌的妹夫，王凌是东汉末大臣王允的侄儿，曹家没有亏待王凌，在曹魏期间，王凌一直做到三公中的太尉。249年，司馬懿发动高平陵政变，执政大臣、大將軍曹爽被杀，司马氏掌握魏国大权。251年，司马懿宣布，王凌虽然已经年近八十，仍图谋决定拥立楚王曹彪为帝，推翻司马氏，他的阴谋暴露了，我要诛王凌的三族。王凌的妹妹也就牵连进去，要杀。
- *战庸*：战功。庸，功也。《三国志 - 郭淮传》：“（淮）在关右三十余年，外征寇虏，内绥民夷。比岁以来，摧破廖化，禽虏句安，功绩显著，朕甚嘉之。”
- *征摄*：抓捕。
- *戒装*：准备行装。戒，准备，《诗 - 小雅 - 大田》：“既种既戒。”
- *克日*：定期。《三国志 - 武帝纪》：“公乃与克日会战。”
- *劝淮举兵*：七十多岁的司马懿何尝不想善始善终，之所以下决心诛杀曹爽，完全是少年得志、“蠢笨如猪”的曹爽步步紧逼，而后曹爽又突然放手，进退失据的结果。高平陵政变后，司马懿先杀曹爽、何晏等曹家人，牵连有五千多人，后诛夏侯玄、王凌、母丘俭、诸葛诞等，其中夏侯霸投靠蜀汉，文钦投靠东吴。郭淮之所以没有举兵，也是因为曹爽在道义上毫无上风，曹家也没有杰出人才，自己又偏于一地，兵微将寡，手里没牌可打，只能退而求其次，保存家族凝聚力。
- *如徇身首之急*：身首，脑袋离开身体；徇身首:谋求性命；如徇身首之急，保命般急切。  

郭淮在这件事的处理上，可圈可点，先以部下不服要造反表示力量，然后摆出姿态服从司马懿的权威，送妻子上路，又派出数万人尾随纠缠，接着五个儿子请愿表现仁孝，于是追回妻子，给司马懿写信，意思是说，五个儿子没有老太太，就要去死，我没继承人了，我也要去死（至于我用什么方法去死，你是有数的）！郭淮给了司马懿很多个台阶下，加上郭淮这时候估计也七老八十了，郭淮弟弟郭配和投靠司马懿的裴秀、贾充等都有联姻，司马懿也就放过了郭的妻子，但派出陈群之子陈泰任雍州刺史分权牵制。公元255年正月，郭淮去世，朝廷即任命陈泰为征西将军，假节都督雍、凉二州的军事，取代了郭淮。

## 5.5
>诸葛亮之次渭滨，关中震动。魏明帝深惧晋宣王战，乃遣辛毗为军司马。宣王既与亮对渭而陈，亮设诱谲万方，宣王果大忿，将欲应之以重兵。亮遣间谍觇之，还曰：“有一老夫，毅然仗黄钺，当军门立，军不得出。”亮曰：“此必辛佐治也。”

- *次*：驻军。234年2月，诸葛亮出兵渭水南岸的五丈原，曹丕的儿子曹睿派司马懿（司马昭追尊司马懿为晋宣王，司马炎追尊为宣皇帝）对敌。

司马懿和诸葛亮年岁相仿，早期经历也基本相同，两个人年轻时都有蛮好的名声，襄阳大名士司马徽以诸葛亮为“伏龙”，南阳太守杨俊以司马懿为“非常之器”，但两人皆知汉室已倾，事不可为，诸葛亮“不求闻达于诸侯”，司马懿“不欲屈节曹氏”。207年，刘备三顾茅庐，诸葛亮为其感动，出三分天下之计，而后刘备一直信任重用诸葛，很快出任军师中郎将、军师将军；208年，曹操直接和司马懿说，不到我手下干活，坐牢！司马懿这才扔掉装病的拐杖，到曹操手下当参谋，直到曹操去世，曹丕重用司马懿；诸葛亮在刘备手下，“先主外出，亮常镇守成都，足食足兵”；曹丕外出征伐，司马懿镇守许昌，“吾东，抚军当总西事；吾西，抚军当总东事”；刘备托孤，“若嗣子可辅，辅之；若其不才，君可自取”，大小政事皆出于诸葛亮；曹丕托孤，司马懿是辅政大臣之一，“有间此三公者，慎勿疑之”；两人的功绩也很相似，对各自朝廷可算忠心耿耿，“各受保阿之任，辅翼幼主，不负然诺之诚，亦一国之宗臣，霸王之贤佐也”；两人的军事才能很高，都得到了各自敌人的赞许，司马懿说诸葛亮“天下奇才”，孙权说司马懿“善用兵，所向无前。”  
至于诸葛亮和司马懿军事才能孰优孰劣，两人都是士人出身，多次对仗，互有胜负，司马懿防守多，就一般的军事常识而言，条件相仿的情况下，攻比守难，虽然诸葛亮六出无功，司马懿还认为诸葛亮驻军五丈原是个错误，但并不能说明两人换位，司马懿能取得胜利。在五丈原之战中，司马懿评价诸葛亮：“志大而不见机，多谋而少决，好兵而无权，虽提卒十万，已堕吾画中，破之必矣！”这种说法无非是宽慰后方的家人，他有依靠后勤相持的把握而并无决战决胜的信心。至于司马懿通过询问诸葛亮的饮食状况推断出其命不久，这只是一种民间传说。  

- *辛毗*：字佐治，河南颍川人，陈寔、荀彧的老乡，原事袁谭，后投靠曹操。他当时在司马懿营中任军师，不是军司马。
- *陈*：通“阵”，陈兵。
- *诱谲万方*：百般引诱试图决战，据说诸葛亮派使者送司马懿以妇女服装加以侮辱挑衅。
- *觇*：窥视、侦察。
- *钺*：斧头，一种礼器，相当于传说中的打王鞭、尚方宝剑之类，象征除皇帝外的最高权力。一般而言，这个东西曹睿应该给司马懿而不是辛毗，但曹睿不放心司马懿和他的部下，是司马懿出兵后再派出辛毗加以节制。

这个故事是说，曹睿远程指示部队不准决战，所以派为人方正的辛毗监督司马懿部队，“六军皆肃，准毗节度，莫敢犯违”。 这大概是在演戏，实质恐怕是司马懿不愿出战，又弹压不了部下的战斗热情。当时人对辛毗的评价是“亮直（光明正直），然性刚而专”。当年曹丕喜欢打猎，辛毗随从。曹丕射中了几只野鸡，高兴地说：“射雉乐哉!” 辛毗说：“于陛下甚乐，而于群下甚苦。”  
此战诸葛亮病死军中，辛毗随后去世，比诸葛亮大两岁的司马懿又活了16年。

## 5.6
>夏侯玄既被桎梏，时钟毓为廷尉，钟会先不与玄相知，因便狎之。玄曰：“虽复刑余之人，未敢闻命。”考掠初无一言。临刑东市，颜色不异。

- *夏侯玄*：曹操的亲戚。曹操的祖父曹腾是宦官，父亲曹嵩是曹腾的养子。据史料记载，曹嵩本姓夏侯，过继给曹腾。曹操和夏侯敦、夏侯渊是平辈的亲戚关系，“夏侯、曹氏，世为婚姻”，夏侯渊的妻子是曹操妻子的妹妹，儿子娶了曹操的女儿。夏侯渊的女儿还是张飞的妻子，夏侯玄的堂叔夏侯霸是夏侯渊的侄子，也就和张飞有亲戚关系，夏侯玄的父亲夏侯尚和曹丕是亲戚兼好朋友。夏侯玄还是曹芳时期执政大臣曹爽的表弟，妹妹夏侯徽还是司马师的第一任妻子。249年，高平陵政变，曹爽被司马懿杀了后，夏侯霸投靠蜀汉，叫侄子夏侯玄也去，夏侯玄拒绝了。251年，司马懿去世，夏侯玄说，司马懿能够以世代的交情善待我，而司马师、司马昭不会容忍我。  
夏侯玄字太初，是当时著名的玄学家，和何晏、王弼同为正始名士的代表，而夏侯玄政治地位更高，可谓当时玄学的“宗主”。 254年，中书令李丰与皇后父光禄大夫张缉密谋杀司马师，计划安排夏侯玄取代司马师为大将军，张缉为骠骑将军，事泄，牵连到夏侯玄。
- *钟毓*：见2?11，神童，14岁当官，后来钟毓不赞成曹爽、夏侯玄征西，被曹爽赶出朝廷到地方当太守去了，曹爽被杀后，钟毓回京师当了御史中丞、侍中廷尉，相当于中纪委书记廉政公署专员之类的。
- *钟会*：当时任中书侍郎，中书令的佐官，司马家的智囊。审问夏侯玄的时候他也在座。当时钟毓37岁，钟会30岁，夏侯玄46岁，以前夏侯玄不和钟会交往，这次钟会想利用机会和夏侯玄结交。
- *虽复*：即使。《论语 子罕》；“譬如平地，虽复一篑，进，吾往也”，就像平地，即使倒下一筐土，那也是进步，这是我想要的（万丈高楼平地起）。
- *刑余之人*：受过刑的人。
- *闻命*：遵命。
- *初无一言*：全无一言。夏侯玄没有具体介入政变的行为，零口供。作为中纪委书记的钟毓亲自找他谈话，夏侯玄说：“我没有什么可说的（我没有什么罪），你自甘堕落要替司马师当下手（现在是曹魏的朝廷，不是司马师的朝廷），那你就给我写吧。”钟毓于是连夜替夏侯玄写了个口供，攀附上李丰、张缉的政变，哭着拿给夏侯玄看。夏侯玄说：“行，那就这样吧。”
- *东市*：西汉在长安东市处决犯人，后来泛称刑场为“东市”。买东西，本意也是指汉代长安城有东西两个大市场。

南北朝时候的史学家范晔因谋反罪被抓，他在狱中写诗说：“虽无嵇生琴，颇同夏侯色。寄言生存子，此路行复即。”，临刑时家人来告别，母亲哭着责备范晔，用手拍打他的脖项，范晔还毫不为意，等到他的妹妹和歌姬妻妾来告别，范晔居然悲涕流涟。一同被杀的侄子谢综说：“舅舅实在不像夏侯玄的风采（舅殊不同夏侯色）”，“晔收泪而止。”  
置生死于度外在中国文化中一向有很高的地位，它与上天堂、回归神的怀抱的宗教情怀无管，而是很高的道德修养——方正。孟子讲舍生取义，还过于着相，佛教实在怕死，把死看成了不起的大事和苦难，所以一心要超越生死，而中国文化的对生死问题最根本的主张来源于庄子的《大宗师》——通达：“夫大块载我以形，劳我以生，佚我以老，息我以死。故善吾生者，乃所以善吾死也。”
有人说，中国需要宗教，因为宗教提供了终极关怀。不过在中国文化中，我们不需要终极关怀，而是忘记。生死就是一个整体，对于死，我们没有喜悦，没有恐惧，没有沉迷于生，没有拒绝于死，就像庄子说的那样：“不知悦生，不知恶死；其出不欣，其入不距；翛然而往，翛然而来而已矣。不忘其所始，不求其所终；受而喜之，忘而复之。”（不喜悦生存，也不厌恶死亡；出生不欣喜，入死不推辞；无拘无束地就来来去去罢了。不忘记自己从哪儿来，也不寻求自己往哪儿去，承受什么际遇都欢喜，忘掉死生像是回到本来。）

## 5.7
>夏侯泰初与广陵陈本善。本与玄在本母前宴饮，本弟骞行还，径入，至堂户。泰初因起曰：“可得同，不可得而杂。”

- *夏侯泰初*：夏侯玄夏侯太初，古时“泰”同“太”。
- *广陵*：今淮扬一带。
- *行还*：外出回来。
- *“可得同”句*：我和陈本志趣相投，于是一起宴饮。你陈骞和我志趣不投，不可建立私交，彼此间没有规矩。（陈骞当时任中领军，皇家卫士长，是司马家的亲信）。

东汉末乃至魏晋士人交往比较讲究，有很多门槛，譬如门第、地域、集团、为人、志趣等。我们已经见识了曹操被宗承拒绝，钟会被嵇康、夏侯玄拒绝，这次好朋友的弟弟被夏侯玄拒绝。在《世说新语》中，嵇康与吕安交好，一次嵇康去吕家，吕安不在，哥哥吕喜想请嵇康进家门，嵇康不入，还讽刺吕喜为“凡鸟”，结果结仇。这种不随便交友的奇特作风，分析起来包含着复杂的动机。过分地选择朋友，本来就是树立自己崖岸自高乃至狂傲的形象，另一方面，谨慎地选择朋友，就容易形成铁杆集团，成为一种政治力量。所以葛洪在《抱朴子》中说：“汉末俗弊，朋党分部。许子将之徒，以口舌取戒，争讼论议，门宗成仇。”当然，对于嵇康和夏侯玄而言，他们的择友并没有刻意或者需要求名，而是当时的一种名士风气，而这种风气也就埋下了他们的杀身之祸。不过他们对生死得失并不在意，他们不是道家，也不是儒家——我就是我，颜色不一样的烟火。

## 5.8
> 高贵乡公薨，内外喧哗。司马文王问侍中陈泰曰：“何以静之？”泰云：“唯杀贾充以谢天下。”文王曰：“可复下此不？”对曰：“但见其上，未见其下。”

249年，高平陵政变，司马懿杀执政大臣曹爽兄弟。251年，司马懿去世。254年，司马师废当了15年皇帝的曹芳，另立15岁的曹髦当皇帝。255年，司马师病死，司马昭执政。260年，20岁的曹髦不甘心当傀儡，决定带着几百个宫中侍卫、仆人出宫杀死野心路人皆知的司马昭。途中遇到禁军头目、司马昭的儿女亲家贾充，曹髦大声呵斥抵抗部队，诸人欲避不敢战，这时候贾充对手下的成济兄弟说：“司马昭养了你们这么些年是干什么的，司马昭死的话，还有你们吗？你们就是为今天准备的！”成济兄弟于是刺杀曹髦。曹髦死后，司马昭的叔父司马孚和侍中陈泰抚摸着曹髦的尸体痛哭自责。曹髦被谥“高贵乡公”。  
曹髦在钟会眼里是“才同陈思，武类 ”，陈寿评价曹髦“才慧夙成”，在朝臣眼里，有较高的声誉，他意图杀死司马昭，有合法性，所以很多人同情他。当然，曹髦犯了文学青年的毛病，做事毛糙，先告诉与自己异心的文官自己的计划，结果泄密，然后皇帝自己带领几百个仆人出宫去杀死权臣，古往今来也只有这么一例，客场作战失败免不了。而后世的宇文邕诛杀宇文护，康熙诛杀鳌拜都在自己的主场，结果就不一样。  
陈泰是陈寔的玄孙，司空陈群的儿子，他自幼与司马师、司马昭是好朋友，当年就是他去西北接替郭淮的，见5.4。当时他在京城，任尚书右仆射，加侍中光禄大夫。另有记录说，陈泰不愿意介入这件事，不上朝，“子弟内外咸逼之，垂涕而入”，司马昭问他该怎么善后。  

- *何以静之*：有什么办法安定事态。
- *可复下此不*：贾充是司马昭的亲信，舍不得杀，“有没有再下面一点的办法？” “但见其上”句：我只知道有更上面的追责，不知道有更下面的追责。后来司马昭灭了成济的三族来平息舆论。《三国志 注》中说：“成济兄弟不即伏罪，袒而升屋，丑言悖慢，自下射之，乃殪。”陈泰回去后吐血而死，以后汉魏著名的颍川陈家逐渐没落。  
贾充在当时被认为是奸佞小人，“充为人巧谄，……朝野恶之”。司马昭击败孙皓后，孙皓被押至洛阳，贾充对他说：“听说你在南方挖人眼睛，剥人面皮，这是什么样的刑罚？”孙皓说：“有做为臣子却弑杀他的国君，以及奸险狡诈不忠的人，就对他用这种刑罚。”贾充无言以对。还有一次，若干年过去了，晋朝的大臣们一起宴饮，河南尹庾纯和贾充发生争吵。贾充说：“你父亲年老，你却不回乡供养，难道认为天地神明看不到吗？”庾纯反问：“高贵乡公安在！”这是贾充一块巨大的心病，就连他的侄子在他临死时，也毫不犹豫地批判他： “充自忧谥传，从子模曰：‘是非久自见，不可掩也！’”“及太常议谥，博士秦秀曰：‘充悖礼溺情，以乱大伦。……绝父祖之血食，开朝廷之乱原。按《谥法》昏乱纪度曰荒，请谥荒公。’帝不从，更谥曰武”。  
司马懿没有谋逆的打算，但到了司马师以后，司马家当皇帝的心思已经明了，蔫蔫乎乎搞了15年，司马师、司马昭、司马炎换了三届，表现十分残忍且虚伪，用各种手段愚弄舆论，以为天下人是傻子，在《世说新语》后面的故事里，以至于司马家的子孙晋明帝司马绍，听了王导讲司马家祖先如何杀戮和虚伪的做派，十分惭愧，“覆面著床曰：‘若如公言，祚安得长！’”其实谁当皇帝对魏晋时期的大臣来说，并不是什么大事，因为家族利益逐渐超越了忠臣的概念，不过司马家的手段确实不光彩，天天在夜总会做反腐报告，让人作呕。  
晋代名臣张华在《博物记》中说：太丘长陈寔、寔子鸿胪纪、纪子司空群、群子泰四世，於汉、魏二朝并有重名,而其德渐渐小减。时人为其语曰:“公惭卿,卿惭长。”（陈群是国公，陈纪是九卿，陈寔是县官）不过这主要是讽刺陈群，陈泰在这件大事上，超越了他的父亲，就像他对司马昭的亲信、舅舅荀彧的儿子荀顗说:“世之论者，以泰方于舅，今舅不如泰也。”明代王世懋评价陈泰：“千载凛凛，陈群有愧色矣！”

## 5.9
>和峤为武帝所亲重，语峙曰：“东宫顷似更成进，卿试往看。”还，问何如，答云：“皇太子圣质如初。”

- *和峤*：字长舆，河南西平人。魏国吏部尚书和逌之子，夏侯玄的外甥，有钱癖，不过以清廉和直爽见称。
- *顷似更成进*：最近好像更加成长进步。晋惠帝司马衷的智力大约与毛三相仿，淳朴乃至愚鲁，但他能书写、能生育，当个普通人没什么问题，说他是白痴无非是因为皇帝这个位置要日理万机，能决断，就不相称了。作为父亲的司马炎肯定首先注意到司马衷的智力低于正常水准，但自己家的孩子，特别是嫡长子（司马衷前面有个哥哥早死），不免有偏爱，废长也有很大的顾虑（三国时候袁绍、刘表乃至曹操的两个儿子之间的纷争历历在目），所以他多次考验，并多次征求臣下的意见，臣下也多次发表不同的意见。譬如和峤在从前就说过：“皇太子有淳古之风，而季世多伪，恐不了陛下家事。”司马炎曾经叫很多心腹和著名的饱学之士当司马衷的老师，譬如我们前面认识的荀顗、山涛、卫瓘、贾充、王衍、乐广等，这有两面性，一是双方建立师生的私人感情，二是各大臣都比较清楚地察觉太子的智力问题。这次他再次派大学者和峤、荀勖去考察司马衷。喜欢揣摩、迎合上司的荀勖就夸奖司马衷正如司马炎的感觉那样，“明识弘新”，而和峤带有讽刺地回答：和从前一样。  

290年，32岁的晋惠帝即位，皇后贾南风叫惠帝问和峤：“卿昔谓我不了家事，今日定云何？”和峤曰：“臣昔事先帝，曾有斯言。言之不效，国之福也。臣敢逃其罪乎！”和峤确实直率，惠帝确实淳朴，不以为意。和峤拜太子少傅，加散骑常侍、光禄大夫。292年，和峤去世。  
立愚鲁的司马衷为太子，这是司马炎一生中最重大的抉择之一，在晋代这个话题也反反复复被讨论，譬如到了东晋还有争论，譬如《世说新语 品藻 32》就反映讨论的情况，世人多半认为立司马衷是个重大错误  
那么司马炎为什么不选择有较好声誉的弟弟司马攸或者另一个嫡子司马柬？首先，立司马衷为太子的时候，他只有九岁，九岁的孩子是否一直愚鲁，长大后还会不会变化很难说，所以司马柬的选项可以排除，而且长大后的司马柬智力好像也有问题，“性仁讷，无机辩之誉”。那么司马衷长大后，智力没有明显变化，是不是再考虑废除他，另立司马攸？这好像没有什么问题，不过朝廷的政治格局就可能因为另立皇帝而发生巨大变化，这种后果不是司马炎愿意看到的，他肯定抱着多一事不如少一事的态度；这更不是司马衷的母亲杨艳、姨母杨芷（司马炎的后一任皇后）乃至母党愿意看到的，不是后党贾南风家族愿意看到的，所以她们后背后庞大的家族一定要牢牢确定司马衷当皇帝的格局决不能变化。这三个原因使年老的司马炎犹豫再三，最终还是决定“不折腾”，没有废除司马衷。而且司马炎用心良苦，对他死后的情况做了政治安排，他曾经派很多大臣当司马衷的老师，这些老师后来都出任高官，在遗诏中，还给已经32岁的儿子还安排了两位辅政大臣，叔公汝南王司马亮和外公杨骏，就是希望保持政局稳定。  
在君主专制的宗法制社会，立嫡长子是争议和风险最小的一种选择，家是这样，国家也是这样，这早在西周时期就基本确立了，其他国家也一般遵守这个基本原则。齐桓公的葵丘盟约中说：“无树易子”，《春秋 公羊传》中说：“立嫡以长不以贤，立子以贵不以长”。尽管后世的皇帝，很多不是立嫡长子的，但其引发的政治动荡非同小可，三国时期那些割据势力的覆灭，不少是因为不遵守这个制度，而是以主子的私人感情为出发点。作为司马炎，选择司马衷不能说是一个错误的选项。而解决这个问题比较好的办法，君王们一直要到18世纪的雍正期间才找到。司马炎的错误并不在于选择了司马衷，而是选择了分封制和对后戚的倚重。于是在291年，晋惠帝建年的第一年，皇后贾南风就杀了皇太后杨芷和辅政大臣杨骏、司马亮，西晋迅速陷入内乱，“八王之乱”开始。

## 5.10
>诸葛靓后入晋，除大司马，召不起。以与晋室有仇，常背洛水而坐。与武帝有旧，帝欲见之而无由，乃请诸葛妃呼靓。既来，帝就太妃间相见。礼毕，酒酣，帝曰：“卿故复忆竹马之好不？”靓曰：“臣不能吞炭漆身，今日复睹圣颜。”因涕泗百行。帝于是惭悔而出。

这个故事见2.21的解释。  

- *除大司马*：误，司马炎不会任命诸葛靓大司马这种最为高级的军事职位，据近现代学者程炎震说，是任命为侍中，诸葛靓拒绝。侍中是个清贵的散职，可以出入禁中、顾问应对，常为加衔。
- *诸葛妃*：当作诸葛太妃。诸葛靓的姐姐是司马炎叔叔司马伷的妻子，诸葛靓按辈分是司马炎的舅舅，但两人年龄相仿，小时候常常一起玩，所以说是“竹马之好”。
- *吞炭漆身*：《史记?刺客列传》晋国赵襄子灭了智伯，智伯家臣豫让多次刺杀赵襄子，后来他怕赵襄子认出来，用漆涂身使身上长疮，吞炭弄坏嗓子变音，结果被围。赵襄子问他为什么如此孜孜不倦，舍生忘死。豫让说：“臣事范、中行氏，范、中行氏众人遇我，我故众人报之。至于智伯，国士遇我，我故国士报之。”然后要求赵襄子脱下衣服，拔剑三次刺衣，最后自杀。

《礼记》中说：“父之仇弗与共戴天，兄弟之仇不反兵。”意思是说，对于杀父仇人，无论仇人身处何处，儿子们非得找到并干掉他；兄弟被杀，要时刻随身带着兵器，见了仇人就砍。在古代，报杀父之仇，动用私刑天经地义，并不受刑法约束。诸葛靓背向洛阳而坐，就是表现不忘父仇，不做晋臣，被迫见到司马炎，为自己无法刺杀他而大哭，这是一种孝的表现，占据了道义的制高点。  
当然，这种允许动用私刑是有限度的，《周礼》中设置，朝廷有个叫“朝士”的机构，“凡报仇雠者，书于士，杀之无罪”，如果自己的父兄为人所杀，就到“朝士”处登记仇人的姓名，以后杀死仇人而无罪。还有一个“调人”的机构，“凡和难，父之仇辟诸海外，兄弟之仇辟诸千里之外，从父兄弟之仇不同国”，凡发生杀伤行为，就要把仇人互相调开来避仇。不愿离开的就要抓起来，防止冤冤相报。已经发生了复仇，就以一次为限，不许仇杀不已。从这个意义上讲，诸葛靓已经战败，也没必要当面刺杀了。

## 5.11
>武帝语和峤曰：“我欲先痛骂王武子，然后爵之。”峤曰：“武子俊爽，恐不可屈。”帝遂召武子，苦责之，因曰：“知愧不？”武子曰：“‘尺布斗粟’之谣，常为陛下耻之。它人能令疏亲，臣不能使亲疏。以此愧陛下。”

- *王武子*：王济王武子，见2.24等，他是司马炎的女婿，和峤的小舅子。和峤家有棵李子树结好果，但和峤小气，就给王济几十个尝尝鲜，王济大怒，于是带人把李子树砍了。王济有学问，前面的一些故事多次讲王济好争斗，“言语伤物”，所以和峤说他“俊爽”。</br> 司马炎晚年，为了避免弟弟司马攸窥觊皇位，就命令司马攸离开京都回到封国去。王济带着家属多次劝丈人司马炎收回成命，触怒了司马炎。
- *“尺布斗粟”之谣*：西汉文帝的弟弟淮南王刘长谋反，被流放到蜀郡，途中绝食而死。民间以歌谣唱这件事：“一尺布，尚可缝；一斗粟，尚可舂；兄弟二人不相容。”讽刺司马炎失和兄弟。
- *它人能令疏亲，臣不能使亲疏*：反讽。意思是说，其他人能够令疏远的人成为亲近，我做不到顺从你的意思，使亲人变为疏远，所以有愧。

司马昭和妻子活着的时候，就担心司马炎兄弟反目，多次以汉文帝、曹丕兄弟的故事告诫司马炎，据《晋书》载：“及帝寝疾，虑攸不安，为武帝叙汉淮南王、魏陈思故事而泣。临崩，执攸手以授帝。”但是这种家天下的体制，必须使司马炎做出驱逐司马攸的举动，司马攸抱病辞行，不久吐血而死，36岁。  
侍中王济由此被贬为国子祭酒。  
魏晋南北朝，很多皇子没有善终，甚至没出娘胎就被人干掉了。刘宋皇子刘子鸾哀叹：“愿后身不再生帝王家。”末代皇帝刘准说：“愿生生世世，再不生于帝王家。”生于帝王家如此，生于富豪权贵之家何尝不是如此，眼观近世，有多少人天生就占了便宜的，成功来的太简单，结果却欲苟全性命、免于牢狱之宅尚不可得。《菜根谭》中说：“进步处便思退步，庶免触藩之祸；著手时先图放手，才脱骑虎之危。”

## 5.12
>杜预之荆州，顿七里桥，朝士悉祖。预少贱，好豪侠，不为物所许。杨济既名氏雄俊，不堪，不坐而去。须臾，和长舆来，问：“杨右卫何在？”客曰：“向来，不坐而去。”长舆曰：“必大夏门下盘马。”往大夏门，果大阅骑。长舆抱内车，共载归，坐如初。

- *杜预*：杜甫的祖先，军事家，大学者，人称“杜武库”，形容他学问大。杜预通晓法律，汉律有二万六千余条，七百七十余万字，经他建议并参与修改，变成了二千九百余条，十二万六千余字。杜预精通《左传》，注释《左传》并把它和《春秋》编成一本书，对后世理解《春秋》有很大帮助。杜预武功杰出，虽不会骑马射箭，但深受羊祜赏识，接替羊祜出任镇南大将军，然后灭吴，并协调南北矛盾，采取了安抚怀柔政策，当时南方歌咏：“后世无叛由杜翁，孰识智名与功勇”。</br> 278年11月,羊祜病重,推举杜预代替自己的位置，杜预出任荆州，这是一次非常重大的战略部署，所以朝廷要求大臣都来送他。
- *顿*：停留驻扎。陆机“南归憩永安，北迈顿承明。”或解释为聚会、宿食之所。
- *七里桥*：洛阳城东七里涧上面的桥叫七里桥，是洛阳城东面尽头，多为古人送别之处。《洛阳伽蓝记?卷二?城东》：“崇义里东有七里桥，以石为之。中朝时，杜预之荆州，出顿之所也。”
- *祖*：祭“祖”，祖取“险阻”之意，祭祖也就是祭路神，祭路神后，在路上设宴送行。饯行也称祖帐、祖送、祖道等。。《汉书?刘屈牦传》：“贰师将军李广利将兵出击匈奴，丞相为祖道，送至渭桥。”《仪礼》：“出祖，释戟，祭酒脯，乃饮酒于其侧。”《五经要义》：“祖道，行祭，为道路祈也。”郑玄注释说：“道路以险阻为难，是以委土为山，或伏牲其上，使者为軷祭，酒脯祈告也。卿大夫处者，于是饯之，饮酒于其侧。礼毕，乘车轹之而遂行，舍于近郊矣。”
- *预少贱，好豪侠，不为物所许*：杜预的父亲杜恕曾被判为死刑，后贬为庶人。杜预就成了罪人之子。而且杜预赞赏、交结豪侠，东汉以后，游侠以武犯禁，多被视为犯义侵礼之徒，不为时之所许。</br> 杨济是晋武帝司马炎的妻子杨艳、杨芷的叔父，右卫将军。弘农杨家是东汉的高门望族，从“天知地知你知我知”的杨震出任太尉以后，杨家一直有人出任朝廷的高官。他认为，杜预同为外戚，是罪人之子，官位居然爬得比他快，十分不快，所以不堪忍受被群星捧月般的杜预，不愿意捧场，所以叫“方正”。
- *和长舆*：和峤。
- *向*：刚才。见4.56“亦觉殊不及向”。
- *大夏门*：《洛阳伽蓝记》：（洛阳）北面有二门。西头曰“大夏门”，尝造三层楼，去地二十丈。洛阳城门楼皆两重，去地百尺，惟大夏门甍栋干云。
- *盘马*：跨马盘旋驰骋。。”《儒林外史?五二回》：“看见苏堤上柳阴树下，一丛人围着两个人在那里盘马。”
- *大阅骑*：“大”疑为衍字。《洛阳伽蓝记》：“禅虚寺在大夏门御道西。寺前有阅武场，岁终农隙，甲士习战，千乘万骑常在于此。有羽林马僧相善抵角戏，掷戟与百尺树齐等。虎贲张车渠，掷刀出楼一丈。”杨济在阅兵。他善骑射，“雄俊”，所以喜欢看部队操练。
- *抱内车*：“内”同“纳”，搂着拉进车里。

杜预出镇荆襄后，还“数饷遗洛中贵要”。或问其故，预曰：“吾但恐为害，不求益也。”（我不求好处，就怕京城显贵使绊子。）

## 5.13
>杜预拜镇南将军，朝士悉至，皆在连榻坐。时亦有裴叔则、羊稚舒后至，曰：“杜元凯乃复连榻坐客！”不坐便去。杜请裴追之，羊去数里住马，既而俱还杜许。

这个故事和前面类似，都说明有些朝臣鄙视杜预，特别是外戚。杜预是司马懿的女婿，杨济是司马炎的叔岳父，而本文中的羊稚舒羊琇是司马师妻子的弟弟，从这个意义上讲，他们三人是同一辈的司马家的外戚，他们的杜预的鄙视不用埋在心里，当场就可以发作。  

- *连榻*：当时的座位有独榻和两人坐的连榻，独榻自然显示出地位尊贵。
- *裴叔则*：裴楷，他的一个儿子娶了司马懿的孙女，另一个儿子娶了司马炎皇后杨芷的妹妹，同为外戚。
- *乃复*：竟然。见2.98 等。
- *许*：处，地方。《五柳先生传》“先生不知何许人也”，贺铸“试问闲愁都几许？一川烟草，满城风絮，梅子黄时雨。”

杨济、羊琇敢于鄙视当时最风光的、甚至是军人集团最高头目的杜预，无论理由是否正当（当时肯定有正当性），《世说新语》都给予了正面评价。

## 5.14
> 晋武帝时，荀勖为中书监，和峤为令。故事监、令由来共车。峤性雅正，常疾勖谄谀。后公车来，峤便登，正向前坐，不复容勖。勖方更觅车，然后得去。监令各给车，自此始。

- *荀勖*：颍川荀氏，字公曾。他对公务员过多有自己的看法：“省吏不如省官，省官不如省事，省事不如清心。……领导对工作要全面斟酌，能省则省，令下必行。如不这样，恐怕只是迷惑视听，会造成前面省去，后面恢复，或更加繁杂。”他是音乐家、懂法律，更是政治上的一把好手，“久管机密，有才思，探得人主微旨，不犯颜忤争，故得始终全其宠禄”，当时的舆论也因此批评他“谄谀”。 他是贾充的亲信，贾充的社会评价很低，人以群分；贾南风很丑，他硬说是绝世美女，司马衷愚鲁，他硬说是德行无双。
- *中书监*：汉武帝时候设中书，掌管机要，为了出入方便，一般是宦官担任。司马迁就当过中书令。曹丕设中书省，设监、令各一人，监、令之下置中书郎若干人，官员由士人充任，从此中书省与尚书台并立。原来由尚书台负责诏令文书起草，转由中书省担任。它开始的品级不高，相当于太守，不过和皇帝接触最为频繁，位卑权重，荀勖称为“凤凰池”。到了唐代，中书省的长官品级和宰相一样了。后世其职能还有一些变化，不细说。监和令平级，不过排名在前。
- *故事*：惯例。
- *正向前坐*：马车有两个位置，和峤居中前坐。
- *方更*：同义反复。方和更都有“重新”、“又”的意思。《宋书?谢方明传》：“刘牢之、谢琰等讨恩，恩走入海，嗣之等不得同去，方更聚合。”

 《龙文鞭影》中说：“管宁割席，和峤专车”，一个放在“德行”，一个放在“方正”，管宁因为志趣不投，而和峤厌恶小人。厌恶小人，于是引发了一场公车改革。后世使用各式专车的领导干部，要感谢和峤。  
 公车据说基本将于2015年在中国结束。大批驾驶员下岗，事省则人员自然减少，就连会议、出差也会少一些吧。

## 5.15
>山公大儿著短帢，车中倚。武帝欲见之，山公不敢辞，问儿，儿不肯行。时论乃云胜山公。

孔子对着装有很高的要求，《论语?尧》中说:“君子正其衣冠，尊其瞻视，俨然人望而畏之”。在《礼记?劝学》中说：“见人不可不饰，不饰无貌，无貌不敬，不敬无礼，无礼不立。”大意是说，着装工整，是尊重别人，是讲礼貌，人如果没有礼貌，就难以在世上立足。南北朝时，南齐有个人叫刘琎，史称“方毅正直”，史书上马上举了个例子：他和哥哥住在一起，刘琎先睡下了，哥哥刘瓛住在隔壁，想跟弟弟闲谈，就叫了他一声，没听见应答，以为刘琎睡着了。谁知过了半晌，刘琎却应了一声。刘瓛感到奇怪，问他为什么半天才应？刘琎答是因为听到哥哥呼唤，便马上起来穿衣束冠，只因带子没系好，人没站正，才不敢非礼回答，所以应得晚了。</br> 平心而论，孔子的要求并无不妥，对待客人，着装严肃就是对客人的尊重之一。当年刘邦因为出身卑微，看不起读书人，就通过糟践他们的帽子来表现地位，释放自卑，“诸客冠儒冠来者，沛公辄解其冠，溲溺其中”，见郦食其，“郦生至，入谒，沛公方倨床使两女子洗足，而见郦生。郦生入，则长揖不拜”。他后来做了自我否定：“吾遭乱世，当秦禁学，自喜，谓读书无益。洎践祚以来，时方省书，乃使人知作者之意，追思昔所行，多不是。”</br> 现在穿奇装异服的年轻人多了，即使在社会交往或公共场合，有些女性也刻意表现男权主义下的性挑逗，不太妥当。在古代这种表现称为“服妖”，是会发生政局动荡的先兆，班固说：“风俗狂慢，变节易度，则为剽轻奇怪之服，故有服妖。”记得好莱坞有部《漂亮女人（麻雀变凤凰）》，男主角陪女主角买衣服，女主角挑了好些随便的衣服，形成一个笑点。不过影片通过女主角给男主角打正式领带结的细节，来表现她其实出身富豪，懂得礼节、规矩，配得上男财主。  

- *山公大儿*：山该。山涛的叔祖母是司马懿的岳母，他和司马炎是中表亲，所以司马炎提出见山该。
- *帢*：便帽。古人重视冠礼，孩子二十岁后外出要戴皮帽，《礼记 冠义》说：“冠者，礼之始也，嘉事之重者也，是故古者重冠。”曹操创制另一种布便帽。《晋书 五行志》：“魏武帝以天下凶荒，资财乏匮，始拟古皮弁，裁缣帛为白帢，以易旧服。傅玄曰：‘白乃军容，非国容也。’干宝以为‘缟素，凶丧之象也。’名之为帢，毁辱之言也。盖代革之后，劫杀之妖也。”书中接着说，曹魏短命，关键就是服装改变：“魏明帝著绣帽，披缥纨半袖，常以见直臣杨阜，谏曰：‘此礼何法服邪！’帝默然。近服妖也。夫缥，非礼之色。亵服尚不以红紫，况接臣下乎？人主亲御非法之章，所谓自作孽不可禳也。帝既不享永年，身没而禄去王室，后嗣不终，遂亡天下。”个人短命，也是因为穿奇装异服：“妹嬉冠男子之冠，桀亡天下；何晏服妇人之服，亦亡其家，其咎均也。”这些当然是古人的特定思维，不过在当时戴便帽见皇帝或者尊长不合适，即使现在，我看到一些人纹身、着装暴露或古怪，也不太舒服，我们是礼仪之邦，和西方文化总有些区别的，没有文化自觉就没有文化尊严。

 守礼即为“方正”。

## 5.16
>向雄为河内主簿，有公事不及雄，而太守刘淮横怒，遂与杖遣之。雄后为黄门郎，刘为侍中，初不交言。武帝闻之，敕雄复君臣之好。雄不得已，诣刘，再拜曰：“向受诏而来，而君臣之义绝，何如？”于是即去。武帝闻尚不和，乃怒问雄曰：“我令卿复君臣之好，何以犹绝？”雄曰：“古之君子，进人以礼，退人以礼；今之君子，进入若将加诸膝，退人若将坠诸渊。臣于刘河内不为戎首，亦已幸甚，安复为君臣之好！”武帝从之。

- *向雄*：字茂伯，河南河内郡人。
- *刘淮*：刘准，《晋书》的另一种说法是太守吴奋。事情经过是这样的，向雄授命要送祭祀用的牛到洛阳，按一般程序是先送到郡里，然后再送洛阳。但天气很热，向雄就做主就近送到洛阳去了。结果有些牛病死了。郡里要追责。向雄说：先送到郡里，再转送洛阳，会死的更多，我当时的主意没错，事实上那些郡里转送的比我送的死多多了。于是被打了。
- *横怒*：横眉怒目，暴怒。
- *黄门郎*：黄门侍郎，负责皇帝和尚书令之间公事处理的往来传达，能自由出入禁中的外官，地位清要，和侍中相仿。侍中为加官，往往另有职务。
- *君臣之好*：太守也称府君，君臣代指上下级。《易?序卦》：“有父子，然后有君臣；有君臣，然后有上下。”
- *君臣之义绝*：《论语》：“君使臣以礼，臣事君以忠。”《孟子》：“君之视臣如手足，则臣视君如腹心；君之视臣如犬马，则臣视君如国人；君之视臣如土芥，则臣视君如寇仇。”我按照皇帝的要求来，但我们之间已经恩断义绝，怎么样？
- *“古之君子，进人以礼，退人以礼；今之君子，进入若将加诸膝，退人若将坠诸渊。*：全文出自《礼记 - 檀弓下》：“穆公问于子思曰：‘为旧君反服，古与？’子思曰：‘古之君子，进人以礼，退人以礼，故有旧君反服之礼也。今之君子，进人若将加诸膝，退人若将队诸渊，无为戎首，不亦善乎？又何反服之礼之有？’”大意是说，鲁穆公向子思请教说：“故国国君死了，从前的官员奔回故国为旧君服丧，这是古来就有的礼节吗？”子思说：“古代的国君，在用人时是以礼相待，在不用人时也是以礼相待，所以才有为旧君服丧之礼。现在的国君，需要用人时，就像要把人家抱到怀里，亲热得无以复加，不需要用人时，就像要把人家推入深渊，必欲置之死地。这样对待臣子，臣子不带领他国军队前来讨伐就不错了，哪里还谈得上为旧君服丧呢？”
- *戎首*：发动战争的主谋，挑起争端的主动一方。  

有些网友经常说：我爱祖国，但祖国不爱我。其思想来源就是此。英国作家约翰逊认为：“爱国主义是恶棍们的最后一个堡垒”。安布罗斯.比尔斯在《魔鬼辞典》中说：“爱国主义是一堆易燃的垃圾，任何一个想要点亮他们名字的人轻轻一擦就可燃烧。”罗素在《我的信仰》中说：“义务这个概念是掌握权力的人用来诱使人们为他们的主人的利益而生存，而不是为自己的利益而生存的一手段。”  
在古代是家天下，搞私人依附，没有无条件报效祖国的概念，只有忠君的思想。上司怎么对我，我就怎么对待上司！这就是儒家礼教的方正，儒家的直道。

## 5.17
>齐王冏为大司马，辅政，嵇绍为侍中，诣冏咨事。冏设宰会，召葛旟、董艾等共论时宜。旟等白冏：“嵇侍中善于丝竹，公可令操之。”遂送乐器，绍推却不受。冏曰：“今日共为欢，卿何却邪？”绍曰：“公协辅皇室，令作事可法。绍虽官卑，职备常伯，操丝比竹，盖乐官之事，不可以先王法服为伶人之业。今逼高命，不敢苟辞，当释冠冕，袭私服。此绍之心也。”旟等不自得而退。

- *齐王冏*：司马冏，字景冶，司马攸的儿子，老爹被司马炎逼死，他继承封爵，少年时“少称仁惠，好振施，有父风”，不过通过政变执政后，“沈于酒色，选举不均，惟宠亲昵……”，从这个意义上讲，好德行、坏德行，聪明、愚鲁对皇子来说关系不大的，因为权力将深刻地改变人的思维方式。譬如司马囧后来把亲哥哥给杀了，至于其他亲戚，自然杀的更多了。当年宋美龄曾经评价延安的共产党干部为什么看上去蛮廉洁和富有朝气：“那是因为他们还没有尝到权力的滋味。”权力有什么滋味？权力就是春药，使男人的睾丸走路时都会发出梆梆梆梆的声音，焕发无穷的青春；权力就是醇酒，使人失去自制，勇往直前；权力就是共产主义，下属们推着他一个人进入共产主义；权力就是神话的光环，绝对的权力必定使他成为永久的传奇。
- *嵇绍*：嵇康的儿子，嵇康冤死前托付给山涛照顾。他成年后，山涛举荐他做官，后在一场战争中因保护晋惠帝司马衷被杀死。他的血溅在司马衷衣服上，司马衷后来嘱咐洗衣工，这件衣服不要洗，上面有嵇侍中的血。有人因此说司马衷不傻。嵇绍不在乎杀父之仇，为司马家卖命，这违背最根本的孝道，所以多为人诟病。不过他有一些勉强的解释，不孝有三，无后为大，他出来当官，是为了延续血脉。或者从玄学的角度出发，我要吃饭，吃饭就要当官，当官是顺应人自然的天性。再或者拿出大禹和鲧的故事来引证，大禹尚且如此，何况我嵇绍！山涛给出的理由见3.8，是“大地四时，犹有消息，而况人乎！”只是无论从何种角度辩解，嵇绍当官无法得到中国文化最根本的哲学支撑。
- *宰会*：费解。有人说，是“宴会”之误，有人说，是官宰会议的意思。不过好像日语里保留着“宰会”的说法，大意是年宰，年度会议。开会时候燕乐，表明“仁惠”的司马囧沉迷酒色。
- *董艾、葛旟*：据说“董艾放纵，无所畏忌。……葛旟小竖，维持国命，操弄王爵，货赂公行，群奸聚党，擅断杀生，密署腹心，实为货谋，斥罪忠良，伺窥神器”。
- *时宜*：当时的需求，时政。
- *职备常伯*：常伯是古时官名，《尚书 立政》说：“王左右常伯、常任、淮人、缀衣、虎贲。”汉人多以侍中比常伯。
- *先王法服*：古时朝廷按尊卑等级制定五服，《孝经》：“非先王之法服不敢服，非先王之法言不敢道，非先王之德行不敢行。”郑玄注：“法服，谓先王制五服。天子服日月星辰，诸侯服山龙华虫，卿大夫服藻火，士服粉米，皆谓文绣也。”
- *高命*：上司的命令。
- *私服*：便服。</br>  
嵇绍先夸司马囧，您现在辅佐皇上，做事都要让大家能够仿效。接着又说，我虽然官不大，但毕竟是天子左右亲近的官员，不能穿着先王的法服作优伶的工作。然后又把话锋圜转回来道：但是您今天的高命我也不能随便推辞。奏乐的事得等我脱去官服，换上便装时才成。 </br>
现在在宴会接访中，领导干部高歌一曲是亲民作秀，但在古代不是这样。士人在特定的场合展示音乐才能，是一种修养和礼仪，是情感的自然流露，在朝廷上表演才艺是伶人的把戏，卑贱的营生，所以蔺相如逼着秦王敲缻来换取赵王的尊严，祢衡有击鼓骂曹。现在唱歌跳舞的戏子都能穿上将军的服装，在古代是非常忌讳和腐败的象征。
- *不自得*：“自”疑为衍字。  

上司要听我唱歌？行!买菜？行！甚至可以共享情妇，买凶杀人。这个才是专制社会的常态，像嵇绍这样拒绝一下，就记录进了《晋书》，不过“顷之，以公事免”。

## 5.18
>卢志于众坐问陆士衡：“陆逊、陆抗是君何物？”答曰：“如卿于卢毓，卢珽。”士龙失色。既出户，谓兄曰：“何至如此！彼容不相知也。”士衡正色曰：“我父、祖名播海内，宁有不知？鬼子敢尔！”议者疑二陆优劣，谢公以此定之。

东吴被西晋吞并后，陆机才10来岁，曾被俘虏到洛阳，后放回。289年，有感于“吴人趑睢，屡作妖寇”、“吴人轻锐，易动难安”的形势，司马炎发布诏令“内外群官举清能，拔寒素”，作为江东四大家族中的杰出人物陆机、陆云兄弟等江东名士自然在征召之列。这时候陆机刚好30岁，他在途中写诗说：“总辔登长路，呜咽辞密亲。借问子何之，世网婴我身。……虎啸深谷底，鸡鸣高树巅。哀风中夜流，孤兽更我前。悲情触物感，沉思郁缠绵。伫立望故乡，顾影凄自怜。”  
陆机的诗写的很感伤，但这个“世网”不仅仅是晋武帝的诏令，而是他们肩上的家族责任。“欲述其祖父功业”，向往着“绍季札之遐踪，结鬲肝于中夏，光东州之幽昧，流荣勋于朝野” 甘愿“生亦何惜，功名所叹”  
到了洛阳，陆机等人立刻感到北方人对南方人的歧视，而南方人也有自己的骄傲。江东士人认为，东吴确实被西晋打败，不过司马炎篡位，北方士人屈节，他们的投降比东吴早得多，他们是五十步，北方人才是一百步。每次在宴会交际中，南北争端屡屡被挑起，大家互相贬低，北人蔑称南人为“貉子”，南方人就称北方人为“伧鬼”。“陆机兄弟志气高爽，自以吴之名家，初入洛，不推中国人士”，争论一般是南方人获胜。这次卢志直呼陆机爷爷、父亲的名讳，陆机针锋相对。  

- *卢志*：河北范阳卢氏，自东汉大儒卢植起，卢氏一直是北方的大族，卢志是卢植的曾孙，祖父卢毓、父亲卢珽都是曹魏的高官，不过和陆逊、陆抗比起来名望差很多。
- *陆机、陆云* 入洛后，一味钻营，先后交结投靠权贵杨骏、司马晏、贾谧、司马伦，不过当时政局动荡，这四个人先后被杀。蹉跎十年后，成都王司马颖伸出了橄榄枝，任命陆机、陆云类似太守的内史官职，三品。卢志称陆机为君，陆机称卢志为卿，因为陆机的地位比卢志高。不过卢志是司马颖的智囊。
- *容*：也许，容或。《后汉书 李固传》：“自数年以来，灾怪屡见，比无雨润，而沈阴郁泱。宫省之内，容有阴谋。”陆云这种说法是犬儒主义的推却之词，陆机兄弟是江东名士，著名学者。在重视门第的西晋，哪有官员不了解他们的出身，就连陆机也知道历史上的小角色卢毓、卢珽。
- *鬼子*：日本鬼子，洋鬼子的“鬼子”， 伧鬼之子。刘孝标的注中居然引用了晋代一个民间故事，说卢植是卢充在野外与一个女鬼生的，所以称卢志为“鬼子”，这种说法不能作为解释。

303年，司马颖以平原内史陆机为前锋都督、前将军、假节，带领20余万兵马，南向洛阳讨伐哥哥长沙王司马乂。陆机以为南人不能率领北人作战，“机吴人，羁旅单宦，顿居群士之右，多不厌服”，再三推辞：“从前齐桓公信用管仲建立了霸业，燕惠王由于疑忌乐毅而失去了即将成功的事业。这次讨伐长沙王行动的成败，在您不在我。”卢志就进谗说：“陆机自比乐毅，却把您比做昏君燕惠王，将帅出征前不考虑制胜之道，而想着这些问题，注定成就不了什么大事。”陆机根本指挥不动部下，兵败后被诛杀，卢志又唆使司马颖：“从前赵王杀中护军赵浚，赦免了他儿子赵骧，赵骧后来又进攻赵国，就是前车之鉴。”于是名闻天下的“二陆”被杀。这对其他南士震动很大，“不意三陆（陆机、陆云、陆耽三兄弟）相携暗朝，一旦湮灭，道业沦丧，痛酷之深，荼毒难言。国丧俊望，悲岂一人！”随后顾荣、张翰等相继返归江东，西晋南士入北求仕的活动结束。  
像陆机这样当时最杰出的文学家，他想当大官的功利思想害死了他。爱因斯坦拒绝出任以色列总统，他说：“方程对我更重要些，因为政治是为当前，而方程却是一种永恒的东西。”古人没有这种见识。

## 5.19
>羊忱性甚贞烈。赵王伦为相国，忱为太傅长史，乃版以参相国军事。使者卒至，忱深惧豫祸，不暇被马，于是帖骑而避。使者追之，忱善射，矢左右发，使者不敢进，遂得免。

- *羊忱*：泰山南城羊氏，另有一名叫羊陶，羊祜的从侄辈。</br>300 年，司马懿的儿子司马伦杀皇后贾南风等，自为相国。曹操、司马昭、司马炎等都曾担任过相国，所以西晋开国以后，这个官就不设立了。这次司马伦又把这个职务封给自己，意思很明白。所以羊忱不想当这个官。据资料说，羊忱当时不是太傅长史，另有职务。301年，司马伦被杀，羊忱任太傅司马越的太傅长史。
- *版：笏板，不是皇帝的文书而是诸侯王的任命。
- *豫祸*：招致祸患。301年，司马伦被杀，他亲近的下属基本也被杀了。
- *被马*：上马鞍，就像给马穿上衣服。
- *帖骑*：骑裸马，贴身于马上。

羊忱不愿意当官，甚至匆匆跑路，左一箭右一箭地射退组织部的官员，比当年洗耳的许由还狠，古往今来似乎就这么一例，不过羊忱没有像巢父那样跑到深山去，后来当过扬州刺史，侍中。

## 5.20
>王太尉不与庾子嵩交，庾卿之不置。王曰：“君不得为尔。”庾曰：“卿自君我，我自卿卿；我自用我法，卿自用卿法。”

这个故事应该是说王衍方正，庾敳另搞一套，得到王衍的看重，“甚奇之”，于是庾敳成为王衍的“四友”之一。</br>王衍自幼以外貌和悟性著名，“盛才美貌，明悟若神”， 庾敳是个大胖子， “长不满七尺，而腰带十围”；王衍豪爽散财，“家资罄尽”，而庾敳“聚敛积实，谈者讥之”；王衍自幼受到朝廷重用，后来当过司空、司徒、太尉，都是顶顶的高官，而庾敳虽然也当官，不过是中下级官员，吏部郎、军谘祭酒之类，也许因为这些原因，王衍和庾敳没有私交。</br>按魏晋的习俗，晚辈称长辈、位卑者称位尊者用“公”；同辈之间或同等职位之间互称为“君”；而比较熟悉或亲昵的朋友、以及上级称呼下级则使用“卿”，地位低的人不能称地位高的人为“卿”，王衍自谓地位高于庾敳，所以很“方正”地称庾敳为“君”，不让庾敳对他称“卿”。但庾敳“我自用我法，卿自用卿法”，这说明颍川庾敳要么不拘礼法，要么并不承认琅玡王衍社会地位高于自己，因为当时的王家，远没有达到东晋王家的巨大、强盛。</br> 中国人重视称谓，谈不上什么“方正”，而是腐朽的等级社会的标志。礼貌并没有错，但现代的“礼”实质是尊重而不是区分等级。

## 5.21
>阮宣子伐社树，有人止之。宣子曰：“社而为树，伐树则社亡；树而为社，伐树则社移矣。”

- *阮宣子*：阮修。也是王衍的“四友”之一，见4.18“三语掾”的阮修。
- *社树*：社就是纪念后土“勾龙”的土地庙。传说共工触倒不周山，女娲补天，共工的儿子勾龙弥补地上的裂缝，后人就建庙以土地神纪念他。在土地庙边上一般种有大树。发展到后世，村里也不一定建土地庙，而常常建一些淫祠，祭祀各路神鬼怪，有些村没有土地庙，就以大树代替土地菩萨或其他神怪。我们去景点游玩，有时看到大树上寄着很多许愿带，有人还围绕树走几圈，都是以树为神风俗的延续。在儒教学者看来，这些淫祠拜祭的是一些不知所谓甚至邪恶的神灵，《礼记 曲礼下》中说：“非其所祭而祭之，名曰‘淫祀’”，它不但没有起到教化的作用，反而以异端崇拜劳民伤财，“乡人祭，必以太牢。不尔致祸，州里惧之。每岁烹宰，不知纪极”，而且搞乱意识形态，不正当，《唐国史补》中说：“每岁有司行祀典者，不可胜记，一乡一里，必有祠庙焉。为人祸福，其弊甚矣。”在《世说新语?排调?15》中说：“卿类社树，远望之，峨峨拂青天；就而视之，其根则群狐所托，下聚溷而已。”  

阮修看不惯这种迷信，把“树神”给砍了。他的理由是：如果神就是这棵树，我砍了，神就死了，有什么好在意的；如果树仅仅是神的寄托，我砍了树，神就跑到其他地方去了，对它也没什么事，这又有什么好在意的？  
和阮修类似的，唐代有个禅师丹霞天然，挂单在惠林寺，一天天寒，他就把佛像劈了当柴烧，庙里的大和尚闻讯赶来，急了，质问他想干什么。他说，找舍利子。大和尚说木像哪里来的舍利？丹霞天然应口而答：没有舍利？那烧了有什么关系，再来几个！  
无论是儒家、道家还是佛教，其核心本质是无神论，这是中国哲学的一个特点，它比其他地方的信仰更加正当。


## 5.22
>阮宣子论鬼神有无者。或以人死有鬼，宣子独以为无，曰；“今见鬼者云著生时衣服，若人死有鬼，衣服复有鬼邪？”

阮修是无神论者，他引用并深化了王充《论衡》的比喻：“世谓人死为鬼，非也。人死不为鬼，无知，不能害人。如审鬼者死人精神，人见之宜从裸袒之形，无为见衣带被服也。何则？衣无精神也。由此言之，见衣服象人，则形体亦象人。象人，知非死人之精神也。凡天地之间有鬼，非人死之精神也。”王充并不是传说中的无神论者，他是相信有鬼的，但他不认为人死了会变鬼，鬼其实是妖，“鬼之见也，人之妖也”，“鬼，阳气也，时藏时见。阳气赤，故世人尽见鬼，其色纯朱。”而阮修则否定有鬼。  
世上一般人认为鬼就是人死后的灵魂，阮修说：就算人有灵魂，会变鬼，但是那些宣称看到鬼的人，都没有说鬼是赤身裸体的。那是不是衣服也有灵魂呢？这个反驳似乎很有力，但从逻辑上考察，其实有漏洞。有些宗教持有万物有灵说，山有山鬼火水神，水有水鬼或水神，难道就不允许衣服有衣神衣鬼？而且鬼的能力是不是就等同于人的能力，你不能拿人的活动能力去揣测鬼。  
那么，人究竟有没有灵魂？灵魂的概念又是怎么产生的呢？古人观察到，人离开呼吸就死了，他们就很直接地把呼吸当作人活力的源泉。呼吸就是气，“人之生，气之聚也。聚则为生，散则为死”，古人无法认识到氧气对于细胞的作用，这无可厚非。于是古人又接着产生宏观的“气”的概念。他们认为，空间充满了气，气就是活力，就是精灵。“道始于虚，虚生宇宙，宇宙生气”，“天地初间，只是阴阳之气，这一个气运行，磨来磨去，磨得急了，便拶许多渣滓，里面无处出，便结成个地在中央。”  
古人很自然接着推理，人是有两部分组成的，一是肉体，二是思想，或者叫精神（所以有神气、精气的说法），当呼吸停止了，肉体就僵硬，这时候思想精神作为一个独立物体就分离出了人体。如果这个人身前精神旺盛，他的精神就不太会消失，成为鬼，如果精神力不够，魂魄又变成了气，消失在空间里（佛教轮回转世观点进入后，古人就认为魂魄会到地域去，而不是消失）。王充的说法是：“夫人所以生者，阴、阳气也。阴气主为骨肉，阳气主为精神，人之生也。”  
万物有灵说在逻辑中有个破绽：没有生命的东西也有灵魂，那么一块铁，一块石头有多少个灵魂，如果它反复分裂，是不是证明这块铁里面有无数个灵魂的聚合体？它是以分子为单位还是以电子为单位？一个物体之内含有无数个灵魂的说法站不住脚，以此推理，植物有灵说靠不住，动物有灵说也靠不住。  
人们之所以有灵魂的概念产生，是因为思想的独立性特点，思考和肉体有对立性，于是思想和肉体分离了。  
宇宙是由气组成，这是一种古人的世界观，以此来解释世界，在某些方面可以解释世界，但这是一种很简单的思维，完全是错误的。  
非常遗憾，人有思想，可是人没有魂魄，世界上没有灵魂，也没有鬼。  
阮修并不是“独以为无”，刘义庆把这个故事归之于“方正”，说明当时社会上有识之士的态度。而这种卓识，正是现代文明的精髓之处。神鬼学说，本来就是一种快捷的、靠不住的、遗祸无穷的世界观，它放弃了对世界深入的观察和追问。

## 5.23
>元皇帝既登阼，以郑后之宠，欲舍明帝而立简文。时议者咸谓，舍长立少，既于理非伦，且明帝以聪亮英断，益宜为储副。周、王诸公，并苦争恳切。唯刁玄亮独欲奉少主，以阿帝旨。元帝便欲施行，虑诸公不奉诏。于是先唤周侯、丞相入，然后欲出诏付刁。周、王既入，始至阶头，帝逆遣传诏，遏使就东厢。周侯未悟，即却略下阶。丞相披拨传诏，径至御床前曰：“不审陛下何以见臣！”帝默然无言，乃探怀中黄纸诏裂掷之。由此皇储始定。周侯方慨然愧叹曰：“我常自言胜茂弘，今始知不如也！”

318年，晋元帝司马睿在王导等人的帮助下在南京登基，同年，立晋明帝司马绍为太子，而简文帝司马昱是320年出生的。所以这个故事不确。一般认为，如果故事有的话，是司马睿想在大儿子司马绍和二儿子司马裒里面选一个，而王导、周敳倾向于立长。  

- *登阼*：见2.19，登基。
- *明帝*：司马绍，以后来的皇帝谥号来称呼他。
- *益宜*：更加适合。
- *储副*：储君，国之副君，指太子。
- *周、王*：武城侯、太子少傅、吏部尚书周顗，丞相、骠骑大将军、中书监王导。
- *刁玄亮*：尚书左仆射刁协。司马睿虽然拉着王导要一起坐龙椅表示感激，但君权和相权本来就存在矛盾，而且王家这时候势力很大，作为一个有中国梦的皇帝来说，就必然要想办法牵制王家和各门阀的势力。刁协就是司马睿用来振兴皇家的一张牌。因为当时司马睿手下的那些官员，大都不是西晋朝廷中的人，不过是地方官员，刁协曾经在西晋当太常博士，熟悉朝廷的礼仪规矩，于是刁协帮助东晋朝廷建立了典章礼仪制度，对确定尊卑、巩固皇权有一定作用，很得司马睿的信任和重用。
- *欲奉少主*：想树立拥戴少主之功。去讨好原太子司马绍，人家记不住你，而赞成另立储君，就是天大的功劳。
- *阿*：顺从。
- *虑诸公不奉诏*：在清代以前，一般的诏书要皇帝和尚书等大臣共同签署才能生效，晋代估计是有中书起草，门下审核，皇帝签发，尚书执行。如果直接出于皇帝个人的旨意，自汉代开始，大臣如果觉得不妥，可以封还（封驳），所以司马睿决定绕过周顗等直接下旨。于是他决定先假装召见王导他们，然后借口叫他们去东厢房等着，再叫来刁协，由他去宣布立太子的诏令。
- *逆遣*：逆有预先的意思，事先派遣。《三国志?张嶷传》：“嶷逆遣亲近赍牛酒劳赐”，《资治通鉴?卷五十一》：“元孟惧诛，逆遣使乞降，张朗径入焉耆。受降而还。”
- *却略*：却步、却行，停步、退步。《汉乐府?陇西行》：“酌酒持与客，客言主人持。却略再跪拜，然后持一杯。”
- *披拨*：推开，拨开。《建康实录?晋安帝纪》：“乃以手披拨其衿领，悉解散”。
- *御床*：这里就说明床是坐具，从书画和文物看，是大约高于地面20、30厘米的木板、垫子。
- *不审*：不知道。《汉书?英布传》：“谒者随何进曰：‘不审陛下所谓。’”赵翼：“不审势即宽严皆误”。
- *黄纸诏*：晋代的诏书开始以青纸或黄纸代替木简或帛。后来桓玄还下诏，要求公文一律用黄纸。

这个故事从情理上推测，是虚构。因为司马睿立太子的时候司马昱还没出生。编这个故事，大概是王家人想说王导、周敳对司马绍有拥立之功吧。不过这个故事反映的内涵，恐怕不是“方正”，而是王导的强势，充分说明了当时的政治体制是“祭在司马，政在王家”。赵翼说当时“高门大族，门户已成。令仆三司，可安流平进，不屑竭智尽心，以邀恩宠”，于是“晋主虽有南面之尊，无总御之实，宰辅执政，政出多门，权去公家，遂成习俗”。王导与司马睿的关系，相当于诸葛亮和刘禅的关系，所以简文帝的遗诏中对桓温说：“家国事一禀大司马，如诸葛武侯、王丞相故事”，可见王导在当时多么显赫，几十年后大家还记得他执政时的权威。

## 5.24
>王丞相初在江左，欲结援吴人，请婚陆太尉。对曰：“培塿无松柏，薰莸不同器。玩虽不才，义不为乱伦之始。”

307年，永嘉元年，王导建议琅琊王、安东将军、都督扬州诸军事司马睿把治所从徐州迁移到南京，而西晋灭亡于317年。当时南方大族不会把王导和司马睿放在眼里，“徙镇建康，吴人不附，居月余，士庶莫有至者”，倒是王敦在南方人眼里地位比较高贵，“琅邪王仁德虽厚，而名论犹轻，兄威风已振”，他是驸马、扬州刺史、名士。于是王导要王敦配合演戏，表明王敦也很尊重司马睿，这时候南方士族才稍稍看重一点司马睿。  

- *陆太尉*：陆玩，见3.13，陆抗的堂兄弟。303年，陆机、陆云、陆耽三兄弟被司马越杀害，到北方求仕的顾荣、张翰等南归，南方士族和北方朝廷的关系趋于冰点。如果王陆联姻，可能还牵涉到一些财产问题，我们注意到，整个东晋，江苏依旧是南方士族的土地，而北方王、谢、孔等的土地财产，基本在浙江、福建一带发展。
- *培塿无松柏*：出自《左传》，培塿，小土丘或坟墓。
- *薰莸不同器*：出自《孔子家语》，薰，香草；莸，臭草。

这两个典故是陆玩的谦辞，后面的话却十分具有攻击性，“义不为乱伦之始”，他非常傲慢地说：“道义上我不能带头乱了伦常”，你以为你真的是松树和香草啊，别自作多情了，其实我们才不和北方的伧鬼联姻，否则世界上就没伦理道德了。这种南北士族不婚的情况决非个例，在整个东晋时期我们都找不到通婚的例子，也许就是陆玩定的这个“方正”的调子。  
调和南北矛盾，努力使南方士族接受侨居南京的北方士族，这始终是王导多年的执政指导思想，他不仅试图通婚，而且经常接见夸奖南方人，“3?12王丞相拜扬州，宾客数百人并加沾接，人人有悦色”，他带头学吴地方言，经常引导南方士族清谈，更重要是在政治上的宽松。史书上说北方人认为王导“昏聩”，其实西晋虽然吞并了吴国，但没有触动原来吴地的基层政权，“其牧守已下皆因吴所置，除其苛政，示之简易，吴人大悦”，统一天下的司马炎尚且不搞运动，你一个亡命侨居的司马睿如果大搞吏治整顿，肯定会动了南方人的奶酪，所以南方大族的顾和冷冷地对王导说：“明公作辅，宁使网漏吞舟，何缘采听风闻，以察察为政。”“导咨嗟称善。”山涛的孙子山遐当余姚县令，清查户口搞税收，“江左初基，法禁宽弛，豪族多挟藏户口，以为私附”，查出豪强隐瞒荫庇人丁一万多人，结果山遐被王导撤职了事。王导认为，余姚是江南大姓聚居之所，霸占人口是他们的传统，山遐无端干预，惹出江南士族的反感，得不偿失。  
外来人口和本地人口的融合，至今都是很难的事情，譬如新疆问题，各地治安问题和世界政治格局等，我们都可以看到人口迁移是多么重大的事情。这方面的教训，我们可以讲很多很多，而其中的基本原则，却很少有人去深入研究和把握。

## 5.25
>诸葛恢大女适太尉庾亮儿，次女适徐州刺史羊忱儿。亮子被苏峻害，改适江虨。恢儿娶邓攸女。于时谢尚书求其小女婚，恢乃云：“羊、邓是世婚，江家我顾伊，庾家伊顾我，不能复与谢裒儿婚。”及恢亡，遂婚。于是王右军往谢家看新妇，犹有恢之遗法，威仪端详，容服光整。王叹曰：“我在遣女，裁得尔耳！”

- *诸葛恢*：与司马炎不共戴天的诸葛靓之子，曹魏征东大将军、司空诸葛诞之孙，和诸葛亮、诸葛瑾都有亲戚关系。在西晋和东晋初期，当然是第一流的高门，世称“王、葛”，而谢家虽然门第还算好，不过王谢并称，那是谢安出山后的事情了，当时人们认为谢家是“新出门户，笃而无礼”。诸葛恢在东晋也是高官，“避地江左，名亚王导、庾亮”，历任吏部尚书、尚书右仆射、散骑常侍、尚书令等。342年，晋成帝司马衍病重时，遗诏以诸葛恢和司马晞、司马昱、庾冰、何充为顾命大臣。
- *亮子被苏峻害*：327 年，历阳内史苏峻造反，期间庾亮的儿子庾会被杀，庾会妻子诸葛文彪改嫁江统之子江虨。
- *邓攸*：把儿子绑在树上的“邓攸无儿”。他和诸葛恢都当过会稽太守。羊忱是羊祜的堂侄，羊祜和诸葛诞有亲戚关系。
- *谢尚书*：谢裒，谢安的父亲，曾任吏部尚书，五子谢石。谢石“既无他才望，直以宰相弟兼有大才，遂居清显，而聚敛无餍，取讥当世。”
- *江家我顾伊，庾家伊顾我，不能复与谢裒儿婚。*：江统早死，庾亮是接替王导的大族家主，其势力前已多见。我照顾江家，庾家照顾我。晋人也就是几个小故事看着潇洒，其实这种近亲繁殖的世家婚姻，社会危害很大，没有随机性就没有活力。
- *及恢亡*：345年诸葛恢去世，是年谢石19岁。346年，谢裒去世。父死应守孝应27个月。
- *看新妇*：《齐书 顾协传》：“晋、宋以来，初婚三日，妇见舅姑，众宾皆列见。”《梁书 曹景宗传》：“景宗谓所亲曰：‘今来扬州作贵人，动转不得，路行开车幔，小人辄言不可。闭置车中，如三日新妇。遭此邑邑，使人无气。’”而诸葛文熊表现得落落大方。
- *王叹曰：“我在遣女，裁得尔耳！”*：王羲之很关心这桩婚姻，他曾经写信说：“二族旧对，故欲结援，诸葛若以家穷，自当供助昏事。”这说明诸葛恢死后，诸葛家经济情况不好，据史书上说，诸葛恢以“清”出名，“京都三明各有名，蔡氏儒雅荀葛清”，“蔡葛知名，或雅或清”。王羲之的意思是：诸葛恢已经去世了，但其家嫁女儿尚能如此；我还活着，嫁女儿也仅仅能做到这个地步（“裁”通“才”）。这是夸诸葛恢家规教养好。

## 5.26
>周叔治作晋陵太守，周侯、仲智往别。叔治以将别，涕泗不止。仲智恚之，曰：“斯人乃妇女，与人别，唯啼泣。”便舍去。周侯独留与饮酒言话，临别流涕，抚其背曰：“奴好自爱！”

- *周叔治*：汝南周氏，周顗（伯仁）、周嵩（仲智）、周谟（叔治）是西晋成武侯、都督扬州诸军事、安东将军周浚的三个儿子，其中以周顗最为有名，继爵成武侯，所以称他为周侯。
- *晋陵*：现常州、无锡、镇江一代，就在建康边上，这不是去海南、广州，也不是去行刺秦王，不知道周顗、周谟这两兄弟为什么这么夸张地痛哭流涕，要么是两人多情，要么是当时风气是宁在朝廷，不下地方。这个故事列入“方正”，是说周嵩骂得直爽，譬如后面的“雅量”记载，周嵩有一次酒后曾经对周顗说：“君才不及弟，何乃横得重名！”而不是说兄弟情深是“方正”。
- *妇女*：王勃诗句“无为在歧路，儿女共沾巾”。
- *言话*：现在叫做“说话”、“话语”。现在上海等吴方言区人说聊天叫“闲话”，其实发音和本意大约是保留古音中的“言话”，而不是“闲话”。
- *抚其背*：古人表示亲密、信任等的举动。《三国志?注》：又王（曹丕）近出，乘小辇，执达（孟达）手，抚其背戏之曰：“卿得无为刘备刺客邪？” ……权（孙权）抚其背（周瑜）曰：“公瑾，卿言至此，甚合孤心”等。
- *奴*：刘孝标说奴是周谟的小名。也有人说“阿奴”是当时亲属或爱人之间的常见昵称，现在有些方言中还有保留这种用法。古代以奴为小名的并不罕见，譬如潘安小名“檀奴”，刘裕“寄奴”，王濛“阿奴”，陶侃儿子陶范“胡奴”，隋朝有个猛将叫任蛮奴，唐玄宗有个歌姬叫“念奴”。从情理上讲，身处六朝间的刘孝标不可能不知道当时人昵称为“阿奴”，但偏偏注明“奴”是周谟的小名，想来周谟的小名中肯定有个“奴”字。至于为什么不用全称的小名，这不难理解，因为现在亲属、爱人之间明明是双名，但为了表示亲昵，有些人也会称呼单字或者重字。现在有些人自称是“房奴”，自卑中还带有喜悦，这也是很有趣的语法现象。
- *自爱*：《道德经》“圣人自知不自见，自爱不自贵”，自己爱护自己（身体或名誉）。

## 5.27
>周伯仁为吏部尚书，在省内夜疾危急。时刁玄亮为尚书令，营救备亲好之至，良久小损。明旦，报仲智，仲智狼狈来。始入户，刁下床对之大泣，说伯仁昨危急之状。仲智手批之，刁为辟易于户侧。既前，都不问病，直云：“君在中朝，与和长舆齐名，那与佞人刁协有情！”径便出。

- *省内*：中央官府或皇宫。皇宫内设办事机构，三国时候中央政府逐渐形成尚书、中书、门下三个部门主要部门。
- *刁玄亮*：刁协字玄亮，见5.23，晋元帝司马睿的亲信，尊皇权而抑门阀，“排抑豪强”、“崇上抑下”，反对门阀特权，多为大族和他们把持的舆论不喜甚至厌恶，后被王敦以“清君侧”名义起兵所杀。
- *备亲好之至*：尽亲朋好友的感情和行为到了极点（极尽亲密友好）。
- *小损*：疾病稍稍减退。损是《易》的一卦“六四，损其疾，使遄有喜。无咎。”
- *狼狈*：狼狈不堪，引申为匆忙。
- *手批之*：一个耳光。
- *辟易*：退避。“神鬼辟易”，顾况 《从军行》：“怒目时一呼，万骑皆辟易。”
- *户侧*：门边。
- *中朝*：见2.27，西晋时期。
- *和长舆*：和峤字长舆，5.14“和峤专车”，不近奸臣荀勖。
- *佞人*：周嵩性急刚愎，连哥哥也要打的，所以对打人一点也没顾虑，他还因为使气砍人被司马睿的另外一个亲信大臣刘隗弹劾免官，牵连周顗。他称刁协为谄佞得宠之人，实质是对司马睿重用刘隗、刁协的不满。作者很照顾细节，周嵩称和峤为字，呼刁协为名，就是为了表明周嵩对刁协的不屑。

干部之间动手，是县、乡镇层次的干部素质，而中央高级干部直接动手，在现在看来不可思议。即使周嵩性格再“绞直果侠”，这种做法也非常愚蠢，况且刁协还细心照顾周嵩的亲哥哥。我们从另一个方面理解，周嵩临别骂弟弟，打哥哥，打哥哥朋友的这种不近人情的行为，来源于其本我要求。不掩饰感情，极尽喜怒哀乐乃至于放荡怪诞，是魏晋风度的重要组成部分，甚至是最显著的特征。我们后人所理解的魏晋风度，雅量、平和、心机并不是重点。  
后来周顗、周嵩、刁协都被王敦所杀。

## 5.28
>王含作庐江郡，贪浊狼籍。王敦护其兄，故于众坐称：“家兄在郡定佳，庐江人士咸称之。”时何充为敦主簿，在坐，正色曰：“充即庐江人，所闻异于此。”敦默然。旁人为之反侧，充晏然，神意自若。

有人说，西晋是中央皇族和官员大面积腐化，东晋则是地方官员大面积腐化，这只是从一些事例上得出的简单结论。从整体看，两晋风气相似，一脉相承，皇帝和他的大臣们奢侈炫富，持强凌弱，污浊不堪。《晋书?惠帝纪》中说，“纲纪大坏，货赂公行，势位之家，以贵陵物，忠贤路绝，谗邪得志，更相荐举，天下谓之互市焉”，在晋代，仿佛一切都可以用金钱交易，金钱是世界上唯一真实的超能力，称之为“钱神”，这种情况只有当代中国才堪与之一比。更让人吃惊的是，西晋大富翁石崇当荆州刺史，派人当劫匪在长江上大肆打劫杀害客商，所以暴富；东晋王族司马羕也同样叫人冒充大别山区的“蛮人”，在长江中当“江贼”打劫杀人。但从另一个方面考量，据史书资料，两晋也是清官留名最多的时期，对比鲜明。而魏晋风度，很多是种植在极度滥杀、极度腐败、极度空虚的烂泥中的灿烂花朵，他们的光荣和自豪，往往是痛饮人生的甘泉，不问政事、不问民生、不问诉讼、不问军事，醉生梦死。诸多名士之标新立异自有高下之别，但放而无节确是共同的特征。  

- *王含*：字处弘，王敦的亲哥，以贪污无能著名。后来当了征东将军，都督扬州江西诸军事。王敦举兵时为敦军元帅，兵败投靠堂弟荆州刺史王舒，被堂弟杀了。
- *狼籍*：今“狼藉”，唐代苏鹗说：“狼藉草而卧，去则灭乱。故凡物之纵横散乱者，谓之狼藉”，引申为没有节制。《史记 滑稽列传》：“日暮酒阑，合尊促坐，男女同席，履舃交错，杯盘狼藉。” 。《后汉书 张酺传》：“郑据小人，为所侵冤。闻其儿为吏，放纵狼藉。”
- *何充* 前已多见，东晋后来的名臣宰相，独自执政多年。他是王导、庾亮的亲戚，晋明帝司马绍的连襟。这个故事发生在西晋时期，王敦当时是扬州刺史，后来何充因此离开了王敦的幕府。像郭璞这样没有背景的人直言不讳被王敦杀了，像何充这样有底牌的，合则来不合则去。
- *反侧*：辗转反侧，不安貌。

当时人认为王敦有英雄气，但从其一生事迹看，他除了雄心和会唱歌外，有什么优点我是看不出来，这是一个充满肮脏的“名士”。

## 5.29
>顾孟著尝以酒劝周伯仁，伯仁不受。顾因移劝柱，而语柱曰：“讵可便作栋梁自遇！”周得之欣然，遂为衿契。

- *顾孟著*：顾显（或作顾禺），吴郡顾家子弟，东晋初期江南士族领袖顾荣的侄子，早逝。
- *因移劝柱*：于是来到房屋的柱子边敬柱子酒。
- *讵*：岂，难道。
- *栋梁自遇*：遇，对待。自许栋梁。难道可以自许为栋梁之才吗？周顗你不喝酒是因为崖岸自高吗？汉代以后，多把能干之人比喻成柱石、栋梁。顾显直言不讳，讽刺周顗，又有狂态，周顗一向以正直和大度著称，赞赏这种行为，所以加他作好友。
- *得之欣然*：费解，闻之？但大意肯定是听了很高兴。
- *衿契*：衿，胸怀；契，投合，引申为名词，感情好的朋友；衿契，志趣相投的朋友。

## 5.30
>明帝在西堂，会诸公饮酒，未大醉，帝问：“今名臣共集，何如尧舜？”时周伯仁为仆射，因厉声曰：“今虽同人主，复那得等于圣治！”帝大怒，还内，作手诏满一黄纸，遂付廷尉令收，因欲杀之。后数日，诏出周。群臣往省之，周曰：“近知当不死，罪不足至此。”

- *明帝*：刘孝标的注中说是东晋开国皇帝元帝司马睿（318年－323年在位），而不是晋明帝司马绍，因为周顗在322年被王敦所杀。周顗当尚书仆射是在320年以后，这个故事发生在321年前后。
- *西堂*：建康皇宫正殿是太极殿，有东西两堂。按魏晋惯例，一般而言，东堂办公，西堂居住。西堂可能分内外两间，一间起居，一间会客聊天吃饭。“西堂”表明这次可能是私人宴会性质。
- *未大醉*：还没有很醉。作者写这个词真是意味深长，做了皇帝，大凡情不自禁会做一些中国梦。头脑清醒点的，喝酒半醉时候做；头脑糊涂的，醒的时候也要喊。其实无论是世袭制也好，禅让制也罢，靠这些制度，本来就很难有什么杰出人物产生。但那些幸运儿一旦获得这个位置，就往往会迅速进入角色，把领袖的头衔当做自己的超能力，开始神游狂想。古代帝王，他做的梦最高境界就是儒家传说中的完美社会——尧舜时期；当代领袖和他们的秘书们，接受过一些考古知识，知道尧舜的原始社会真相，不容易吸引老百姓，于是他们做梦的最高境界是活生生的“现代尧舜时期“——当代美国！</br>美国啊，它的名字为什么这么美？尽管我从周小平网友那里得知，美国工资购买力并不算特别高，不收费的高速公路裂纹和坑洼遍地，没人敢把自己小孩送去美国的公立学校念书，猪肉也是合法使用瘦肉精……但这些，我们的当代领导人和富翁们并不介意，他们把子孙、老婆情妇乃至下属佣人全送到那里受苦去了，因为那里才是他们的梦——“去美国的梦”。不，不能说是受苦去了，尽管美国的月亮不如中国圆，但在中国勤奋工作的领袖和富豪们，会提供美好的一切，让他们心爱的和关心的人，用金钱克服美国的种种困难，在美国生活的很美。</br>领袖们对有强烈爱国情怀的人民当然不能说自己“去美国的梦”，他可以换个字眼，譬如中国梦。中国梦，据说是要实现中华民族的伟大复兴！复兴？兴哪个时代？其标杆自然不是尧舜，也不是贞观开元、康乾盛世，具体就是二战以后一直雄霸天下的当代美国！所以习也有时候似醉非醉地说，中国梦和美国梦相通，和非洲梦共鸣，与欧洲梦交汇……</br>当然，习在说什么美啊梦啊，老百姓听不懂也不关心。因为每个人的梦，都是自己的；梦里的自己，往往是见不得人的绝对隐私。
- *何如尧舜*：在座各位都是这个时代的杰出人物，那我和尧舜比怎么样（《论语》：“舜有臣五人而天下治”）？司马睿这其实还是互相吹捧的说法，不算得意忘形。
- *复那得等于圣治*：又怎么能够把自己等同于圣人治理天下！
- *黄纸*：晋代的纸张前面介绍过，当时开始使用潢纸。作者强调司马睿写满一张字，为了具体体现他的气愤。不过古人用毛笔写，一张字也写不了多少字。司马睿的书法作品现在还有摹本。
- *近知*：费解。本意大概是指“当初就知道”，但“近”很难引申为“起初、开始”的意思，或为“即”，就，音近而误。或者理解成“这两天就知道”。意思可能是“要杀就在气头上杀了，隔了几天不杀，我就知道我不会死刑。”  

在专制国家中，往往是有法律而无法纪。在这种体制之下，对上司和君王诚实，是极为罕见的高贵品德，所以有几个说不好听实话的大臣，就可能被史书记录下来歌颂，所以有几个能容纳一点刺耳声音的君王，就可能被记录下来歌颂，譬如和峤、周顗、李世民。而要在一个专制体制中生存，迎合上司是最重要的处事原则，中国古代有多少人因为言论和文字狱被处死！当然，古人这个数目也未必惊人，最惊人的数目肯定在是建国后的三十年，世界上最大规模的言论迫害在我国横行，所以有个领导同志在回忆录中说：我们一定要感谢中国人民，他们对我们实在是太宽容了！这也是我对社会上有人称一些老百姓为“刁民”的答复：谁更宽容!  
扯远了，我并不喜欢这个故事。随便说了句大实话，也要冒着生命危险，也要被打入大牢几天或者一段时间，这在任何时候，都令人恐惧和愤怒；而且任何不经过审判的处决，都是犯罪；任何死刑，从理性的角度观察，都是整个社会团体在犯罪。

## 5.31
>王大将军当下，时咸谓无缘尔。伯仁曰：“今主非尧舜，何能无过！且人臣安得称兵以向朝廷！处仲狼抗刚愎，王平子何在!”

- *王大将军当下*：“当下”或当作“东下”，322年初，镇东大将军、江州刺史、都督江、扬、荆、湘、交、广六州诸军事王敦以清君侧为名，在武汉起兵造反，一路向东打到建康，得到了一些豪门大臣的暗中支持，所以没有遇到有效抵抗，最终周顗、刁协死，刘隗出逃。
- *时咸谓无缘尔*：此句费解，不过刘孝标的注和唐代的《晋书》中有更详细的解释，使我们大致了解意思。当时是温峤提问：“王敦这次起兵好像也有一些理由，他不会做得很过分吧？”（就是晋元帝不愿意和门阀分治天下，使用刁协、刘隗等采取了一系列限制门阀特权和建立忠于自己军队的措施。而王敦想，论现实，你这个皇帝是我扶持起来的，当年我不捧你的场，南方人谁看得起你？论身份，我是司马炎的驸马，而你不过是司马炎的远房侄子，我比你还和皇室亲近！论实力，我掌握天下精锐，你才组建起一只游民部队而已。你以为你是谁啊，怎么妄想大权独揽、蠢蠢欲动，要干掉我们？）正是由于晋元帝限制门阀特权的举措不得门阀之心，所以温峤有此代表性的提问，立场偏向王敦。  </br>周顗的回答容易理解：司马睿又不是尧舜那样的圣人，怎么会不犯过错。但他犯过错，并不是臣子可以起兵反抗、讨伐朝廷的理由。何况王敦一向凶狠和自以为是，他可是杀人不眨眼的角色！我们也不知道他的要求究竟是什么？
- *狼抗*：抗，同亢，狼毛竖立的样子，比喻凶狠、自大。
- *王平子*：见1.23等，王澄字平子，荆州刺史，王敦的远房堂弟，因为治理不善和暴政，荆州流民反叛，王澄后辞去职务任司马睿的军谘祭酒。经过江西南昌，江州刺史王敦接待。王澄为人倨傲狂放，目中无人，是当时“掏鸟窝”的大名士（王衍说：“阿平第一，子嵩第二，处仲第三”，王澄、庾敳、王敦），王敦受不了，派勇士暗杀了族弟。  

周顗和王敦私交很好，王敦也曾经对周顗有救命之恩，后来在同样与周顗私交很好的王导的怨恨怂恿之下，王敦把周顗杀了。

## 5.32
>王敦既下，住船石头，欲有废明帝意。宾客盈坐，敦知帝聪明，欲以不孝废之。每言帝不孝之状，而皆云：“温大真所说。温常为东宫率，后为吾司马，甚悉之。”须臾，温来，敦便奋其威容，问温曰：“皇太子作人何似？”温曰：“小人无以测君子。”敦声色并厉，欲以威力使从己，乃重问温：“太子何以称佳？”温曰：“钩深致远，盖非浅识所测；然以礼侍亲，可称为孝。”

- *既下*：5.31是当下，“当下”我以为是“东下”的笔误，但也有人说，“当下”就是“将下”，如郑玄说：“当事，将有事而未至”。现在王敦打到了建康，驻扎在建康城外的石头城。晋元帝见大势已去，于是“令公卿百官诣石头见敦。”
- *聪明*：322年，晋明帝司马绍23岁，“长安日远”，他从小有应变之智，《世说新语 假谲》中有他遗鞭脱身的故事，充分证明了他聪明才智。不过司马绍26岁就死了。
- *温大真*：温峤字太真，317年，他作为刘琨的使者来到南京劝司马睿继承皇位，而后在东晋得到重用，任太子中庶子，教导司马绍（非东宫率）。司马绍即位后，温峤任中书令，王敦此时执掌朝政，便要求温峤当他的左司马。所以此处言语有一些错误，温峤任左司马在后。
- *奋其威容*：王敦平时名士作风，不讲究威仪，“敦眉目疏朗，性简脱”。
- *作人*：做人、为人。
- *小人无以测君子*：《礼记 中庸》：“君子之道费而隐……及其至也，虽圣人亦有所不知焉”，温峤很保守地说自己不知道太子的底细，不想得罪王敦，也不想构陷司马绍。于是王敦步步紧逼，温峤反击。
- *钩深致远*：《周易?系辞上》：“探赜索隐，钩深致远，以定天下之凶吉，成天下之亹亹”，意思是说太子是否已经探求到宇宙的奥妙道理，能够了解天下事物的成败，成就天下的变化与前进，我不知道。但说他不孝，那是没有的事情。

温峤是东晋初期的杰出人物，智勇兼备。在他死后，“江州士庶闻之，莫不相顾而泣。”

## 5.33
>王大将军既反，至石头，周伯仁往见之。谓周曰：“卿何以相负？”对曰：“公戎车犯正，下官忝率六军，而王师不振，以此负公。”

周顗和王敦私交很好，从小一起玩。311年，杜弢带领流民起义，期间击败了荆州刺史周顗，周顗就避难到王敦那里，又有收留之谊。但周顗忠于皇室，率领军队对付王敦的叛乱。失败后，刘隗、刁协奔走，周顗拒绝逃亡，和王敦谈判。  

- *戎车犯正*：王敦一路东下，到了建康，自己驻扎在石头城，放纵士兵劫掠建康。
- *忝*：谦辞，不才有愧。我没有能力制止你的反叛，这是我对不起你的地方。  

 在《尤悔 8》中，322年，王敦杀了周顗，事后也很后悔。他说，我当年和周顗一见如故，推心置腹。只是世事难料，竟落得这般田地。324年，王敦再次反叛，征尘中病死。

## 5.34
>苏峻既至石头，百僚奔散，唯侍中钟雅独在帝侧。或谓钟曰：“见可而进，知难而退，古之道也。君性亮直，必不容于寇仇。何不用随时之宜，而坐待其弊邪？”钟曰：“国乱不能匡，君危不能济，而各逊遁以求免，吾惧董狐将执简而进矣！”

东晋开国不易，司马睿缺乏名分、力量和才能，甚至有人传说，司马睿是他妈和一个姓牛的小吏所生，“觐妃谯国夏侯氏与金通奸，遂生睿，因冒姓司马仍为觐子”，这些都是质疑他的执政合法性和对司马家族的否定。东晋内部纠纷不断，东渡的侨姓士族和江南的吴地士族的矛盾，寒庶与士族的矛盾，皇族和士族的矛盾，地方与中央的矛盾一直困扰着那个时代。距322年王敦之乱后，328年，又爆发了苏峻之乱。  
苏峻是流民帅，在乱世中带领民众南渡，拥有了自己的武装，并在王敦之乱中击败其部将钱凤、沈充，有大功，被任命为冠军将军、历阳内史。司马绍死后，37岁的中书令庾亮以司马衍舅父的身份执政，王导退居二线。庾亮看不起王导的和稀泥，采取了一些改革措施，其中包括处理地方军阀苏峻。  
钟雅是苏峻叛乱中最早的起因。庾亮先是杀了司马宗室南顿王司马宗，这是因为御史中丞钟雅弹劾司马宗想取代小皇帝司马衍。司马宗死后，其部下卞阐逃到苏峻处，庾亮命苏峻交出，苏峻推说没有这人。“峻颇怀骄溢，自负其众，潜有异志，抚纳亡命，得罪之家有逃死者，峻辄蔽匿之”。庾亮和苏峻的关系恶化。327年，庾亮要求苏峻入朝当“大司农”，这是一个管国家仓库的闲职。苏峻拒绝，提出自己离开历阳，北上去一个边远小郡搞光复事业，“乞补青州界一荒郡，以展鹰犬之用”。庾亮还是催他来京城。苏峻决定“清君侧”了。庾亮兵败而逃，苏峻占领建康。但由于当时的社会制度和苏峻的实力有限，他无法控制东晋的整个疆域，也不可能自立为皇帝，无法再有进一步的动作，自任骠骑领军将军、录尚书事。然后温峤、陶侃等又起兵讨伐苏峻。苏峻挟持司马衍坚守石头城，钟雅等人伴随司马衍左右。而后苏峻在一次战斗中意外身死，其弟苏逸接替了他的位置，钟雅等人又想带着司马衍逃离石头城，被苏逸发现，斩杀钟雅等人，最后苏逸兵败，“清君侧”的内战结束（钟雅被杀事见3.11）。这次事变时间长达10个月，各方势力都参与其中，东晋的各种矛盾基本都在这次事件中体现，结果东晋元气大伤。  

- *独在帝侧*：这是一种夸张的写法，苏峻入城，“（王）导及光禄大夫陆晔、荀崧、尚书张闿共登御床，拥卫帝。以刘超为右卫将军，使与钟雅、褚翜侍立左右，太常孔愉朝服守宗庙。”
- *见可而进，知难而退，古之道也*：出自《左传》：“见可而进，知难而退，军之善政也；兼弱攻昧，武之善经也。”
- *坐待其弊*：坐以待毙
- *随时之宜*：出自《易》，随卦。“随。大亨贞无咎。而天下随时，随时之义大矣哉！”顺应时势，适宜举动。
- *逊遁*：本作“逊遯”，退避。
- *惧董狐将执简而进*：董狐，战国良史。怕史官记载下来，我遗臭万年。

一些古代官员敬畏历史，敬畏未来，现在官员这种敬畏心被唯物主义克服了。但正如食指在《相信未来》中所说：“我之所以坚定地相信未来，是我相信未来人们的眼睛——她有拨开历史风尘的睫毛，她有看透岁月篇章的瞳孔。……我坚信人们对于我们的脊骨，那无数次的探索、迷途、失败和成功，一定会给予热情、客观、公正的评定。是的，我焦急地等待着他们的评定。”

## 5.35
>庾公临去，顾语钟后事，深以相委。钟曰：“栋折榱崩，谁之责邪？”庾曰：“今日之事，不容复言，卿当期克复之效耳！”钟曰：“想足下不愧荀林父耳！”

- *顾语*：同“顾谓”，未必是真的转身回头说话或和四周人说话，这里暗指庾亮要逃走投奔温峤，所以应该有“顾”的意思。钟雅是侍中，和庾亮是一路人，苏峻叛乱最早的起因是钟雅弹劾司马宗，王导靠边站，于是庾亮把朝廷应对苏峻的重任嘱托给钟雅。
- *栋折榱崩*：语出《左传》“栋折榱崩,侨将厌焉,敢不尽言”，“房屋要倒塌了，我也要被压在里面，哪里敢不尽心建言？”栋是正梁，榱是柱子，比喻朝廷即将倾覆。
- *不容复言*：苏峻叛乱，朝廷众臣纷纷在事前劝告庾亮，不要一而再，再而三地要架空苏峻，把他召回朝廷。即使要召回，也要预防他反抗。但庾亮坚信自己是对的，胸有大志，于是一意孤行，而后的举措也多有失误之处，导致兵败。但庾亮认为谋事在人，成事在天，不检讨。“现在的局面，容不得再多说什么了！你应当期待有平定叛乱的一天！”
- *荀林父*：春秋时期晋国将领。公元前前597年，楚庄王进攻郑国，郑国向晋国求助，晋景公派荀林父为中军主帅，迎战楚军，但三军号令不一，晋军被楚庄王、孙叔敖击败。荀林父请死罪，但晋国大臣士贞子认为，荀林父是国家的护卫，战败如同日月之蚀，何损光明。而后荀林父伐郑、灭狄，成就功业。钟雅说：这次苏峻叛乱，朝廷兵败是你庾亮的责任，不容回避。但希望你效仿荀林父，将功赎罪！

庾亮以外戚而得以执政，所以他有块心病，怕别人说他靠裙带关系上位，“则示天下以私”，因而“冒亲以求一才之用，未若防嫌以明公道”。他举止多有名士的风度，为人所仰慕，“达人忘怀，形随运通。再潜再跃，婉若游龙”；但这个心病使他过于激进，且不明军事，为人所诟病，“智小谋大，昧经邦之远图；才高识寡，阙安国之长算”。

## 5.36
>苏峻时，孔群在横塘为匡术所逼。王丞相保存术，因众坐戏语，令术劝群酒，以释横塘之憾。群答曰：“德非孔子，厄同匡人。虽阳和布气，鹰化为鸠，至于识者，犹憎其眼。”

匡术本来是苏峻的部将，攻占建康后，守石头城。329年，被陆晔、陆玩说服，兵变归正，投靠王导。王导因王敦失败后，失去了武力依靠，有意在军中扶持势力，匡术等降将就成了王导的爪牙。而孔群曾经得罪过匡术，差点被杀，王导欲调和关系，要匡术向孔群道歉，孔群拒绝了。当然，会稽孔氏应该算是庾亮一系，或者说更倾向于皇权，和王导的关系比较糟糕，也是孔群拒绝的一个原因。
- *保存术*：“峻党路永、匡术、贾宁中途悉以众归顺，王导将褒显之，峤曰：‘术辈首乱，罪莫大焉。晚虽改悟，未足以补前失。全其首领，为幸已过，何可复宠授哉！’导无以夺。”《晋书?温峤传》
- *因*：顺着。
- *戏语*：谈笑。
- *厄同匡人*：孔子周游列国，到了卫国匡地。由于鲁国阳虎曾攻击匡地，孔子与阳虎长得又很像，于是匡人以为阳虎又来了，赶快报告给匡地政府，于是匡人将孔子一行人围困了五天。在《论语》中，孔子留下了名言：“文王既没，文不在兹乎？天之将丧斯文也，后死者不得与于斯文也；天之未丧斯文也，匡人其如予何?” （周文王死后，中国文化难道不在我这里吗？如果上天要毁灭文化，那么后来之人就不能拥有这种文化。上天如果不想毁灭这种文化，那匡人又能把我怎样呢？）孔群姓孔，匡术姓匡，这是高级的修辞手法。估计孔群当年被辱，心中愤懑，就苦思冥想排解心中的怒火，于是找到这个比喻来自我安慰，现在终于临场发挥：“我虽然不是孔子，但遭遇就像孔子在匡地的经历。”
- *鹰化为鸠*：传说惊蛰的时候，老鹰会因为春天和暖、气息变化，化作鸠鸟。汉代历书《夏小正》中说，鸠和鹰是随季节变化，一月鹰化鸠，五月则鸠为鹰。类似的说法古代有不少，譬如冬虫夏草，譬如《论衡》中说：“瑞应之出，殆无种类，因善而起，气和而生。亦或政平气和，众物变化，犹春则鹰变为鸠，秋则鸠化为鹰，蛇鼠之类辄为鱼鳖，虾蟆为鹑，雀为蜃蛤。”这是因为古人观察条件有限，产生了错误。产生错误不奇怪，但学者以“专家”自居，以讹传讹，强作解人，则是中国文化的弊病之一。而且，中国文化中的阴阳五行和气的学说等，以现在的科学知识来鉴别，不堪一击，但就有些“国学大师”和古文化爱好者，胡搅蛮缠，混淆黑白，这就无法对话了。
- *犹憎其眼*：鹰眼和鸠鸟的眼睛很相似，也许肉食类鸟的眼睛结构都差不多。

王导喜欢和稀泥，温峤、孔群不喜欢。

## 5.37
>苏子高事平，王、庾诸公欲用孔廷尉为丹阳。乱离之后，百姓凋弊。孔慨然曰：“昔肃祖临崩，诸君亲升御床，并蒙眷识，共奉遗诏。孔坦疏贱，不在顾命之列。既有艰难，则以微臣为先，今犹俎上腐肉，任人脍截耳！”于是拂衣而去。诸公亦止。

- *苏子高*：苏峻字子高。
- *孔廷尉*：孔坦，字君平，会稽孔家，孔群的侄子辈。他本是太子舍人，尚书郎，尚书左丞，在平定苏峻之乱中，多有预见和出谋划策之功。他而后曾出任侍中、廷尉等。
- *王、庾*：王导、庾亮。
- *丹阳*：丹阳尹，“元帝渡江，建都扬州，改丹阳太守为尹”，首都市长。晋朝南迁，一般任用北方人居多，因为北方人才是自己人。这次在南方人中选用市长，也许因为王敦、苏峻这些造反派也是北方人，“红二代”也未必靠得住，苏峻之乱中，丹阳尹羊曼战死，朝廷打算搞五湖四海，选了南方人和晋明帝司马绍身边的人孔坦。司马绍临死前曾下旨说：“吴时将相名贤之胄，有能纂修家训，又忠孝仁义，静己守真，不闻于时者，州郡中正亟以名闻，勿有所遗。”这也算是落实先帝的“最高指示”之一吧。
- *乱离*：破败流离。也有解释认为乱离是指政治动荡给国家带来忧患。《诗?小雅?四月》：“乱离瘼矣，爰其适归。”离，忧也，离骚。
- *凋弊*：衰败凄惨。
- *肃祖*：指司马绍，庙号肃宗。325年去世，给5岁儿子晋成帝司马衍的顾命大臣是司马羕、王导、卞壶、郗鉴、庾亮、陆晔、温峤。327年，苏峻叛乱。
- *今犹俎上腐肉，任人脍截耳*：“腐”费解，疑为“糜”，字近而误；或为“鱼”，音近而误。《晋书?惠帝纪》：“及天下荒乱，百姓饿死，帝曰：‘何不食肉糜？’” 《史记?项羽本纪》：“如今人方为刀俎，我为鱼肉。” 脍，剁细的肉，对应“糜肉”。在《晋书》中，原文改为：“今由俎上肉，任人脍截耳！”就是考虑到“腐”不可解，直接当做衍字。“人方为刀俎，我为鱼肉”是比喻，“俎上腐肉，任人脍截”是歇后语。

孔坦后改任吴兴内史（湖州太守），在任上“以岁饥，运家米以振穷乏，百姓赖之”。  
孔坦在《晋书》中的几个故事，“少方直，有雅望”，“深为台中之所敬惮”，基本都以“方正”为特点，但这个故事是拒绝当丹阳尹，不想给别人“擦屁股”，大发牢骚，怎么也能算“方正”呢？故事的逻辑可能是这样的，丹阳尹是比较特别的位置，责任重大，而且主要是为侨居门阀服务的，作为“保皇派”，孔家和王导又有一些冲突，不想和王家搅和在一起，敢于硬碰硬，和领导叫板，“老子不干”！这个大概算“方正”。

## 5.38
>孔车骑与中丞共行，在御道逢匡术，宾从甚盛。因往与车骑共语。中丞初不视，直云：“鹰化为鸠，众鸟犹恶其眼。”术大怒，便欲刃之。车骑下车抱术曰：“族弟发狂，卿为我宥之！”始得全首领。

- *孔车骑*：孔愉，会稽孔家，死后赠车骑将军。他与孔群（御史中丞）是堂兄弟，孔坦（侍中、廷尉）的堂叔。
- *御道*：大概就是长安街之类皇宫前的马路，或者皇帝经常要走的马路。横塘是秦淮河的河岸，和御道总有点路。
- *初不视*：不屑一顾。“初”费解，开始？
- *直云*：直接说。此句可删。因为在“5?36”中说，是讽刺匡术投降朝廷，而这里缺乏语境。也许孔群说了其他难听的话，没有记录。

这件事有点怪，《世说新语》每一章中各个故事一般以时间为序，所以它应放在“5.36”前，解释孔群和匡术纠纷的起源，“孔群在横塘为匡术所逼”，但编者放在了后面。而且“鹰化为鸠，众鸟犹恶其眼”与“5.36”重复，疑为衍文。所以有人认为是同一事而传闻异辞。

## 5.39
>梅颐尝有惠于陶公。后为豫章太守，有事，王丞相遣收之。侃曰：“天子富于春秋，万机自诸侯出；王公既得录，陶公何为不可放！”乃遣人于江口夺之。颐见陶公，拜，陶公止之。颐曰：“梅仲真膝，明日岂可复屈邪！”

- *梅颐*：“颐”程炎震说当作“賾”，梅颐字仲真。魏晋时期取字常见“真”字，盖当时崇尚道教，《说文解字》中说，真，仙人变形而登天也。
- *陶公*：陶侃。荆州刺史陶侃曾是镇东大将军、开府仪同三司，加都督江扬荆湘交广六州诸军事王敦的部下，因为妒忌陶侃战功赫赫，王敦派堂弟王廙取代陶侃，贬陶侃为广州刺史，加上钱凤在王敦面前经常诋毁，王敦曾想杀了陶侃，后来由于王敦的咨议参军、梅颐的弟弟梅陶等人劝说等原因，王敦没有动手。所以说梅賾（梅陶）有恩于陶侃。现在王敦死了，陶侃是侍中、太尉，加授都督交州、广州、宁州等七州军事，长沙郡公，他拥有东晋最强大的军事力量，又有崇高的政治地位，足以与王导相抗衡，甚至可以藐视王导。
- *王丞相*：王导。
- *富于春秋*：还有很多岁月，指小孩子。司马衍5岁当皇帝。
- *万机*：万事。

陶侃的意思是，现在皇帝年幼，大臣把持朝政，王导能抓梅颐，我也是公爵重臣，也能够放了梅颐。后来陶侃要废掉王导，但是庾亮和郗鉴反对，此事才作罢。这个故事反映了东晋门阀权力的特点。  
陶侃“微时所荷，一餐咸报”，快意恩仇不算方正。如果陶侃救了梅陶，梅陶自不必相拜，但梅颐和梅陶格了一层，所以梅颐要叩拜表示感激，但梅颐说今后再不会向人跪拜了（决不向王导屈服），这个勉勉强强算是方正。  
梅陶后来对亲人说，陶侃机神明鉴似曹操，忠顺勤劳似孔明。这种评价陶侃当得起。而且他少数民族出生，又处在门阀政治之中，一步一个脚印，位极人臣，其付出的努力远远大于二者。

## 5.40
>王丞相作女伎，施设床席。蔡公先在坐，不悦而去，王亦不留。

- *王丞相*：王导。古代人喜欢在酒宴中看歌舞，大概是原始人的习性，所以《诗经 小雅 宾之初筵》中说：宾之初筵，温温其恭……舍其坐迁，屡舞仙仙。” 鸿门宴有剑舞，这些包含有向主人或宾客表达尊敬的意思。至于李白，一个人喝着喝着进入场景，也会不由自主地在月下歌舞，“我歌月徘徊，我舞影零乱。醒时同交欢，醉后各分散。”当然，这种习性不排除原始歌舞本身就是性交的形式演变，本身带有求欢的含义。酒桌歌舞发展到后来，就是家里养戏班子，喝酒时歌伎助兴，隋唐而且多以少数民族的歌舞为时尚，称之为“燕乐”。现在搞党风廉政建设，除了少数民族保留原始习性，这两年一般酒桌上歌姬助兴是不敢了，只有一场年夜饭还在搞春节联欢晚会歌舞表演。当代毕福剑在酒桌上因为缺乏女子表演，他又是戏子出生，于是亲自上阵，发挥讽刺才艺，结果下岗。
- *施设床席*：意思大概是给戏子安排座位，从当时的礼仪上讲下等人不配有座位，蔡谟看不惯王导没有等级制度，所以发脾气。当然，不排除王导叫戏子坐在自己和宾客边上，方便男人搞三搞四，蔡谟正经脾气发作。
- *蔡公*：蔡谟字道明，河南兰考人，蔡邕的后代，寿命长，当过司徒，所以称“公”。
- *不悦而去*：彭德怀看不惯毛泽东搞中南海文工团，周恩来看不惯高岗的东交民巷家庭舞会，都不悦而去或者直说不去，还背后嘀嘀咕咕，结果结下了不大不小的仇恨。王导和蔡谟的关系也好不到哪里去，他多次讽刺过王导，讽刺王导怕老婆多小妾，讽刺王导的小妾受贿。以至于王导恼羞成怒，大骂蔡谟，直呼蔡谟父亲的名字：“吾往与群贤共游洛中，何曾闻有蔡充儿也！”

## 5.41
>何次道、庾季坚二人并为元辅。成帝初崩，于时嗣君未定。何欲立嗣子，庾及朝议以外寇方强，嗣子冲幼，乃立康帝。康帝登阼，会群臣，谓何曰：“朕今所以承大业，为谁之议？”何答曰：“陛下龙飞，此是庾冰之功，非臣之力。于时用微臣之议，今不睹盛明之世。”帝有惭色。

- *何次道*：何充何骠骑，外戚，前已多见，当年当面揭穿王敦吹捧王含的嘴脸，现在他已经成长为执政大臣了。
- *庾季坚*：庾冰，庾亮的弟弟，外戚，晋成帝司马衍的舅舅。342年，司马衍病重，有司马丕和司马奕两个儿子，但都是小孩子，庾冰自以为庾家掌权已久，怕成帝之子继位后会因与皇帝血缘变疏而被离间，失去权力。于是常常向成帝说东晋仍有强大外族政权，应该立年长的君主，并建议由司马衍弟弟琅邪王司马岳继位。司马衍最终答应。司马岳为晋康帝。元辅：元，起始，重要，辅，大臣。重臣，有时候专指宰相。司马衍临死前，命司马晞、司马昱、庾冰、何充、诸葛恢一并接受遗诏，辅佐司马岳。司马岳条件有限，也不是 ，即使何充讲话不好听，也没杀这个顾命大臣，反而反躬自省。
- *外寇*：主要指后赵石虎。
- *冲幼*：冲就是小。曹冲。
- *“为谁之议”*：《晋书》中司马岳说：“朕嗣鸿业，二君之力也”，直接夸奖庾冰、何充。
- *龙飞*：飞龙在天，君主登位。
- *盛明之世*：刚登位哪来太平盛世，何充意含讽刺。在这次推荐皇帝活动中，何充的意见没有被采纳，为了避祸，中书令何充改任为骠骑将军、都督徐州、扬州之晋陵诸军事、领徐州刺史，出镇京口。  
过了3年，344年，没想到已守制三年，才20几岁的司马岳也病重了，庾家还是打算立司马岳的叔叔（庾家的小舅子）司马昱为帝，何充坚持立嗣子司马聃为帝，这次司马岳答应。庾家就十分憎恨何充。344年、345年，庾家的顶梁柱庾冰、庾翼先后去世，庾翼临终前，请求朝廷将他征西将军的职位继承给次子庾爰之，何充否决，并推出桓温。从此之后，庾家没落。

何充刚强果敢，正气凛然，不树朋党，不过有些人认为，何充信任重用的人，大都不堪用，这是他的缺点。甚至使用堪用的桓温，最终导致东晋政局大变。


## 5.42
>江仆射年少，王丞相呼与共棋。王手尝不如两道许，而欲敌道戏，试以观之。江不即下，王曰：“君何以不行？”江曰：“恐不得尔。”傍有客曰：“此年少戏乃不恶。”王徐举首曰：“此年少非唯围棋见胜。”

- *江仆射*：江虨，字思玄，江统的儿子，曾任吏部尚书，尚书左仆射，当时围棋第一，一品。王导五品。三国时候，邯郸淳将围棋划分为九品：一品入神，二品坐照，三品具体，四品通幽，五品用智，六品小巧，七品斗力，八品若愚，九品守拙。
- *手*：技艺，手段。
- *不如两道许*：饶两子的样子，王导要先摆两子，那么水平相差极远。
- *敌道戏*：不饶子，平等对敌。江虨觉得和这种对手下这种棋没意思，不想下。
- *试以观之*：费解，意思是看看自己水平提高没有？
- *恐不得尔*：恐怕你不行或者是恐怕不能这样下的意思。是为“方正”。这句话也许隐含典故。
- *年少*：小年轻，名词。前面是词组，这里是词。
- *戏乃不恶*：这句话费解。难道是门客对王导说，江虨下围棋不错的？也许门客没见过王导和江虨下围棋。戏还有一层意思是玄谈，如“2?23”，“诸名士共至洛水戏”；“4?67”，“恒与谈戏”等。也许门客是说，江虨清谈也不错。但这样解释语境有点问题。
- *徐举首*：王导决定评价人物，这对江虨今后的发展至关重要，他要深思熟虑后一锤定音。
- *非唯围棋见胜*：江虨不仅仅只有围棋比我厉害（江虨为人方正超过我）。

## 5.43
>孔君平疾笃，庾司空为会稽，省之，相问讯甚至，为之流涕。庾既下床，孔慨然曰：“大丈夫将终，不问安国宁家之术，乃作儿女子相问！”庾闻，回谢之，请其话言。

- *孔君平*：会稽孔坦，孔侍中，孔廷尉。
- *庾司空*：庾冰，当时会稽内史（太守）。孔家和庾家交好，和王家后来关系不好。有些古人多情胜似女子，朋友送别会哭，探病会哭，看风景也会哭。
- *甚至*：甚为周到。大概就像现在大佬去世，政府有义务过问、安排子女入学、就业，老婆工作、住房，是否进八宝山之类的。
- *宁家*：“家”实指“邦”。
- *儿女子*：妇孺。“无为在歧路，儿女共沾巾”。
- *话言*：《诗 大雅 抑》：“其维哲人，告之话言，顺德之行。”《毛诗传》：“话言，古之善言也。”

孔坦临死仍以国事为忧，不稀奇，但自信到似有良策远谋，就很少见了。他也许是一辈子都端着的人。

## 5.44
>桓大司马诣刘尹，卧不起。桓弯弹弹刘枕，丸迸碎床褥间。刘作色而起曰：“使君如馨地，宁可斗战求胜！”桓甚有恨容。

- *桓温和刘惔*，故事发生时桓温还不是大司马，而在荆州刺史任上，故称桓温为“使君”。363年，桓温加授侍中、大司马，刘惔早就去世了（349年前后？）。
- *卧不起*：古人对看不起的人就不去理他，高卧不起。《三国志?陈登传》:“后许汜与刘备并在荆州牧刘表坐，表与备共论天下人，汜曰：‘陈元龙湖海之士，豪气不除。’备谓表曰：‘许君论是非？’表曰：‘欲言非，此君为善士，不宜虚言；欲言是，元龙名重天下。’备问汜：‘君言豪，宁有事邪？’汜曰：‘昔遭乱过下邳，见元龙。元龙无客主之意，久不相与语，自上大床卧，使客卧下床。’备曰：‘君有国士之名，今天下大乱，帝主失所，望君忧国忘家，有救世之意，而君求田问舍，言无可采，是元龙所讳也，何缘当与君语？如小人，欲卧百尺楼上，卧君於地，何但上下床之间邪？’”在《三国演义》中，刘备三顾茅庐，诸葛亮高卧不起，其虚构的典故也许就来源于此。不过刘惔也就是看不起桓温的清谈水平，与他来往很密切。
- *桓温343年任徐州刺史，345年任荆州刺史，347年，刘惔任丹阳尹。
- *弯弹*：古人的弹弓游戏，青少年尤其喜欢，随身带一把弹弓玩（当时没有皮筋，弹弓类似弓），成为风气。西汉《说苑》寓言“螳螂捕蝉黄雀在后”，在黄雀背后就还有一把弹弓。汉武帝时，韩嫣以金（黄铜）为弹丸，好打弹弓，后边都会有很多儿童跟随，去拣韩嫣打掉的金弹丸，长安有民谣说“苦饥寒，逐金丸。”汉王符《潜夫论》：“怀丸挟弹，携手遨游。或取好土作丸卖之，于弹外不可以御寇，内不足以禁鼠，晋灵好之以增其恶，未尝闻志义之士喜操以游者也。惟无心之人，群竖小子，接而持之，妄弹鸟雀，百发不得一，而反中面目，此最无用而有害也。”孟浩然《大堤行寄万七》：“王孙挟珠弹，游女矜罗袜。”
- *如馨地*：如此，有人说发音相当于吴方言中的“奈夯”。馨、地类似词缀语助，特别是“馨”多次出现在《世说》中，给我们的理解增添了不少麻烦。现在一般认为宁馨、尔馨、如馨，就是如此这般的意思。地、底也多为古人语助词，相当于者、之。
- *宁可*：岂可。见“1.13” “宁可以急相弃邪？”
- *斗战求胜*：君子动口不动手。
- *恨*：悔恨，后悔。

能直接指出别人的缺点就是“方正”，虽然很多谚语或心灵鸡汤说祸从口出，不过马克思也说过：“人类要清洗自己的罪过，就只有说出这些罪过的真象。”真正高贵的品质不是圆滑和忍受，而是正直与勇敢。雨果在《悲惨世界》中说：“为了使人类前进，就必须从高峰上不断地发出鼓舞人的勇气、使人意志高昂的教导。大无畏精神照耀着史册，并且是人类的奇光异彩之一。”不过我的这段话，和刘惔的“方正”无关。

## 5.45
>后来年少多有道深公者，深公谓曰：“黄吻年少，勿为评论宿士。昔尝与元、明二帝，王、庾二公周旋。”

- *道*：说三道四。
- *深公*：竺法深，名潜，或称道潜，字法深（或作法琛）。见“1?30”，“ 2?48”等。此条与“1、30”有重叠之处，“桓常侍闻人道深公者，辄曰：‘此公既有宿名，加先达知称，又与先人至交，不宜说之’”。
- *“深公谓曰”之“深公”，疑作“桓公（桓温）”，一般而言，自卖自夸算哪门子“方正”，系誊抄之误也。
- *黄吻年少*：黄口小儿，比喻，小鸟出生时候嘴是黄的，大一些才褪掉。古代户役制度称小孩为黄，引申为无知的年轻人。《孔子家语?六本》：“孔子见罗雀者，所得皆黄口小雀。夫子问之曰：‘大雀独不得，何也？’罗曰：‘大雀善惊而难得，黄口贪食而易得。……’”
- *宿士*：老成博学之人,资深人士。
- *周旋*：交往。竺法深游走与朱门，交际广博，并不很符合佛教教义，为时人所讥笑。东晋权贵虽多好佛教，但文化底子还是儒、道，佛教也多有人抨击。而骂大人物，也是出名的捷径之一。梁实秋说，你要骂人，那人无论在好的一方面或坏的一方面都要能胜过你，你才不吃亏的。你骂大人物，就怕他不理你，他一回骂，你就算骂着了。骂大人物骂到他回骂的时候，便不可再骂；再骂则一般人对你必无同情，以为你是无理取闹。

不要随意指责别人，他上面有人。

## 5.46
>王中郎年少时，江虨为仆射，领选，欲拟之为尚书郎。有语王者，王曰：“自过江来，尚书郎正用第二人，何得拟我！”江闻而止。

- *王中郎*：王坦之，“江东独步王文度”，太原王氏，非琅琊王氏，前已多见。
江虨接替王彪之任尚书仆射，应该在360年前后。王坦之这时候30来岁。
- *领选*：兼任选部（吏部尚书）。古代官职和现在有区别，尚书省仆射大致类似副总理、中央书记处书记、办公厅主任兼任组织部部长。
- *尚书郎*：东晋尚书省有20来个郎官，略相当于现在的处长。在中央尚书郎岗位很重要，“尚书郎选极精美，号为大臣之副”，但就中央而言，尚书郎不算领导而是具体办事人员，特别是人事部门要做很多具体文字工作，比较繁琐；而在东晋门阀制度下，特别是南迁高门杰出人士往往官位起点是五品官，而尚书郎是六、七品，所以东晋时期这个职位不像西晋那样吸引人。但无论怎么说，尚书郎中的吏部郎还是非常重要的岗位，“中兴膏腴之族，惟作吏部，不为余曹郎”，王坦之的这种说法比较矫情，但正因为矫情，所以一鸣惊人。
- *自过江来*：东晋。
- *第二人*：第二流的家族之人。

王坦之没有去中央，而是先后在会稽王司马昱、桓温手下工作，,大概7、8年间，世袭蓝田侯，侍中。  
东晋高门享有巨大的特权，但门阀大族的弟子往往不屑从事具体的事物，而且他们恐惧和二、三流的人放在同一个考核机制下检验才干，因为这样考核，就显出他们的无能和昏聩，所以天长日久，军人、寒族逐渐崛起。后来“江东独步”的王坦之和谢安一起去见桓温，“既见温，坦之流汗沾衣，倒执手版，安从容就席”……“坦之与安初齐名，至是方知坦之之劣”。“当今的官场把处理公务当成庸俗，把恪守法律当成苛刻，把待人有礼当成谄谀，把游手好闲当成高妙，把放荡无行当成通达，把傲慢无礼当成风雅。” 这是因为这种傲慢浮夸的风气，红三代、红四代最终成了酒囊饭袋，刘裕这样的基层军人颠覆了东晋，当了皇帝。

## 5.47
> 王述转尚书令，事行便拜。文度曰：“故应让。”杜许。蓝田云：“汝谓我堪此不？”文度曰：“何为不堪！但克让自是美事，恐不可阙。”蓝田慨然曰：“既云堪，何为复让？人言汝胜我，定不如我。”

- *王述*：王坦之的父亲王怀祖，蓝田侯，364年升任尚书令、散骑常侍。他不以才干著称，而以直率闻名。
- *事行便拜*：按照当时的惯例，应该上表虚让。而王述“每受职，不为虚让，其有所辞，必不受”。
- *文度*：王坦之。
- *杜许*：费解，或疑作“不许”。其他标点常做“故应让杜、许（杜许）”，也不好理解。《晋书》索性删掉了“杜许”。
- *何为不堪*：据《艺林散叶》，李鸿章说过，天下最容易的事便是做官，倘使这人连官都不会做，那就太不中用了。
- *美事*：按照礼教，授官时本有辞让的要求，不辞让不符合当时的礼仪。“齐依元嘉制，其拜吏部郎，亦有表让之礼”，所以沈约说：“宋元嘉中，范晔让吏部，朱修之让黄门，蔡兴宗让中书，并三表诏答，具事宛然。近世小官不让，遂成恒俗，恐此有乖让意。”

辞让之心本是善念，担心自己才德无以胜任职位，但中国古代的礼仪后来非常繁琐虚伪，推动着中国官员的人格分裂，直到现在还是这样。今年单位居然人手一册《 用典》，老板还突发奇想，打算自己再印一本《 批示学习材料》，即使是文字秘书，我也一个字没看，打算在学习会上玩手机。

## 5.48
>孙兴公作《庾公诔》：，文多托寄之辞。既成，示庾道恩。庾见，慨然送还之，曰：“先君与君，自不至于此。”

- *孙兴公作《庾公诔》*，袁羊曰：“见此张缓。”于时以为名赏。诔文大意见4?78注释。

孙绰《庾公诔》把自己和庾亮相提并论，说和庾亮是师友之间，交情深的很。其实庾亮去世时50几岁，孙绰才20几岁，官位差很远，交集很少。他一个小年轻这样说，就是“寄托之词”，是借着庾亮乱攀交情、表现自己、突出自己，他写的不像悼词而是推销广告，所以显得庸俗轻薄，庾亮的儿子庾羲就很不高兴地发脾气了。  
但碑和诔不同，碑主要就是吹捧死者功业，当时全东晋就数孙绰最拿手，所以大家还是要请孙绰，“温（温峤？时间不太对，329年孙绰才10来岁）、王（王导）、郗（郗鉴）、庾（庾亮、庾冰）诸公之薨，必须绰为碑文，然后刊石焉”。  

- *庾道恩*：庾羲，庾亮的儿子。
- *慨然*：激愤的样子。我爹和您没熟到这个地步！东晋前期显赫一时的庾家，因为庾亮、庾冰的去世，迅速下滑。倒是孙绰成了“一代文宗”。

你碑文里夸死者如何如何好，无论怎么吹家里人听着就舒服，你在诔文里抬高自己，家里人就是不答应！不过《阅微草堂笔记》里有个故事，一人在外地野外遇到去世的李老丈，问他怎么流离失所？李老丈不好意思了半天，扭扭捏捏地说：家里人请人给我写的碑文，把我写的天花乱坠，邻居的鬼看了都笑话我，经常拿这个开玩笑，我实在受不了，所以只好躲到外地了。

## 5.49
>王长史求东阳，抚军不用。后疾笃，临终，抚军哀叹曰：“吾将负仲祖于此。”命用之。长史曰：“人言会稽王痴，真痴。”

王述和孙绰是亲家，孙绰的女儿嫁给了王坦之的弟弟。孙绰和竺法深多有交往，他还给三个人写过诔，刘惔、庾亮、王濛。桓温父亲桓彝的碑文也是请孙绰补写的。王濛就是王长史，他和王坦之是堂兄弟，和刘惔齐名。本节见“3?21”，“王长史就简文索东阳”，司马昱没答应。王濛年轻时候照镜子自恋：“王文开生如此儿邪！”临死前孤芳自赏：“如此人，曾不得四十也！”
- *负仲祖*：王濛和司马昱交好，“简文帝辅政，益贵幸之，与刘惔号为入室之宾。”
- *人言会稽王痴*：谢安曾这样评价司马昱:“为惠帝之流,清谈差胜耳！”王濛虽然和司马昱来往密切，但看到司马昱这样做，就讽刺他不识时务：“我都要死了，你再给我，派我去山沟沟立当官，然而有个什么用！难道是给我冲喜吗？”

临死终于看清司马昱的蠢相，毫不留情地讽刺赏识自己的辅政大臣，勉勉强强算是“方正”。

## 5.50
>刘简作桓宣武别驾，后为东曹参军，颇以刚直见疏。尝听记，简都无言。宣武问：“刘东曹何以不下意？”答曰：“会不能用。”宣武亦无怪色。

- *桓宣武*：桓温谥号。
- *别驾*：刺史的副手，当时桓温估计是徐州刺史或荆州刺史。
- *东曹参军*：后来桓温升职做“公”，带上了刘简，“晋初凡位从公以上，置长史，西阁东阁祭酒，西曹、东曹、户曹、仓曹，贼曹属各一人，分曹治事”。五曹的首长叫参军。
- *听记*：记是公文的一种，礼记，奏记。听记大概就是参与公文起草研讨会议。
- *都*：丝毫。
- *下意*：表达意见。见“3?6”“冲乃粗下意”。桓温直呼刘简的官名，就表现出了细节上的疏远。
- *会不能用*：我提意见你肯定不会采用，我提什么意见！这是讽刺民主集中制。民主制就是少数服从多数，而墨索里尼好像说过，民主集中制是老百姓干活，少数人讨论，一个人决定。  
- *怪色*：责怪之色。桓温自讨没趣，干笑两声，表现出雅量。刘简后来官至大司马参军，363年，桓温加授侍中、大司马、都督中外诸军事，如果刘简还是在桓温手下，那么桓温其实蛮赏识刘简。要么当时桓温就是大司马了，东曹参军就是大司马参军。

这个故事其实蛮有趣的。在很多情况下，“方正”被理解成刚言直谏，但在东晋，个人意识高涨，你不听我的，我说什么啊！沉默就是反对，维护个人尊严也是“方正”。

## 5.51
>刘真长、王仲祖共行，日旰未食。有相识小人贻其餐，肴案甚盛，真长辞焉。仲祖曰：“聊以充虚，何苦辞！”真长曰：“小人都不可与作缘。”

- *刘惔* 和王濛至交，王濛大刘惔 4、5岁，但并不妨碍他们的友情，经常在《世说新语》里双入双出，宛然是里面最好的一对基友。宋代有句诗说：“江左一世称名公，首出刘惔与王濛”。不过两人性格有些差异，刘惔顶真，王濛通达。也许可以说，刘惔是树立自己世界观的人，而王濛没有坚定的原则。
- *旰*：天色晚。旰食宵衣。
- *小人*：平民百姓，或者是寒门小吏。
- *肴案*：偏义复词，菜肴。案，食桌。晋代实行分餐制，一人一案。
- *作缘*：交往、结缘。  

君子慎交游没问题，阮籍青白眼看人也没问题，刘惔以门第为沟壑也正常，但放在历史的长河中，对平民的藐视却直接导致了门阀的没落。到了宋代，苏轼就说了：“吾上可陪玉皇大帝，下可以陪卑田院乞儿，眼前见天下无一不好人。”平等待人是现代社会的特征，以身份和权力作为傲慢的资本才是“小人”。

## 5.52
>王修龄尝在东山，甚贫乏。陶胡奴为乌程令，送一船米遗之。却不肯取，直答语：“王修龄若饥，自当就谢仁祖索食，不须陶胡奴米。”

- *王修龄*：王胡之字修龄，见“2?81”“日月清朗王司州”，和王羲之同辈。王家是大族，王胡之父亲王廙是长年的太守、刺史，不知道为什么“贫乏”。
- *东山*：谢安隐居上虞东山，难道琅琊王家在上虞也有别墅？不过东山的地名比比皆是，乌程是现在的湖州，也许湖州附近有东山，南京也有东山。
- *陶胡奴*：陶范，陶侃的儿子，小名胡奴，“4?97”逼袁宏歌颂陶侃的那位。陶家有钱，据说陶侃“媵妾数十，家僮千余，珍奇宝货富于天府”，王家虽然是大户人家，倒有几个“身无长物”、“家无遗财”的穷光蛋。而陶氏疑有少数民族血统，是江南平民家庭，陶侃中年以后才以军功起家，为门阀圈子所鄙视，“王、谢家儿不免犹以老兵视之”，即使陶范向王胡之表达善意，但你不是名士、高门，还是挤不进那个圈子。
- *谢仁祖*：谢尚，谢安的堂哥，前已多见。估计和谢尚关系很好，“司州都督谢尚以疾不行，以丹阳尹王胡之代之”。  

谢安听说这件事，认为王胡之过了，“太厉”：严肃是厉，愎狠无礼也是厉。  
我也是这样认为，你坚持原则可以，谢绝可以，但标榜自己、挖苦人家就过了——通向真正荣耀之路的就是谦卑。

## 5.53
>阮光禄赴山陵，至都，不往殷、刘许，过事便还。诸人相与追之。阮亦知时流必当逐己，乃遄疾而去，至方山不相及。刘尹时为会稽，乃叹曰：“我入，当泊安石渚下耳，不敢复近思旷旁。伊便能捉杖打人，不易。”

- *阮光禄*：阮裕阮思旷，曾被聘任金紫光禄大夫，但不接受，见“1.32”阮裕焚车注释。阮裕远房堂兄阮籍是大名鼎鼎的竹林七贤，阮家在西晋时期也出过几个高官，阮裕占了堂兄和家族的光，在东晋即使他再毫无作为，但声誉极高，像王导、王敦这样的大人物，也必须很尊重他，因为这是当时的游戏规则。王、谢等门阀甚至司马家族，都是这种游戏规则的受益者，就必须做出维护这种游戏规则的姿态。哪怕一心要隐居，一辈子好像没做过什么大事的阮裕，也就有了很高的职位。

我们看《世说新语》，其中有大量的人物评鉴，这是汉代举荐政治制度逐渐演变的社会风俗，所以即使到了门阀时代，高门基本把持了官场的上升通道，但人们还是一直对各种名人说三道四，当然，基本都是夸奖高门子弟。譬如像王某，就是一个吃喝玩乐的主，也没什么才华，也没什么官位，但他只要做到我行我素，旁若无人，就肯定有很好的美誉度。如果皮肤白、个子高，那他能得到“玉树”、“玉山”的称号；如果丑陋，起码也是“爽朗”、“疏通”之类的；如果非常残暴，也许就被人说成“不羁之才”……

- *赴山陵*：342年，参加晋成帝司马衍的葬礼。司马衍曾经拜阮裕为侍中，阮裕虽然没接受，但大概按照礼仪，也是治丧委员会的成员，应当出席葬礼。司马衍葬在南京边上的鸡笼山，所以阮裕要从绍兴新昌赶过来。
- *殷、刘许*：殷浩、刘惔处。葬礼本来就有社会整合、会见老朋友、增进感情的功能，但阮裕是东晋前期著名的名士领袖，“兼有诸人之美”，谢安还要靠阮裕提携，“谢安年少时，请阮光禄道白马论”，王羲之的模仿对象是阮裕，“汝是我佳子弟，当不减阮主簿”，他是真正的隐士，“内足于怀”，不想和其他名士打交道。
- *时流*：世俗之人。“4?90”，“时流年少”。
- *遄疾*：同义复词，急速。
- *方山*：地名，南京江宁区东南，秦淮河东岸。四面等方，孤绝耸立，故名方山，又名天印山。方山为交通要道，由于距南京有四十里，古人大多要住一晚才坐船走，所以方山是魏晋六朝时离别送行的重要渡口。
- *时为会稽*：清代沈宝砚本《世说新语》，“为”做“索”，“当时想去当会稽太守（内史）”，刘惔没有当过会稽太守。不过342年刘惔很年轻，不到30岁，他有没有资格求任会稽太守？也许其中有漏字，大意可能是“当时想去会稽玩”。
- *安石*：谢安，当时23岁，在上虞隐居。
- *渚下*：湖边。上虞是水乡，也是海边。此句大意是说，我去会稽的话，自然是到谢安那边去做客。刘惔是谢安的大舅子，谢安性格又比较随和深沉，不拘于物，做不出阮裕那种高高在上，一尘不染的姿态。
- *复近*：再近。
- *捉杖*：持杖，如捉刀。
- *不易*：肯定是这样。

阮裕，别人追你是找你聊天，又不是让你当天子，你逃做什么！是想表明你是阮专一，一心一意来奔丧的？专一就是“方正”。  
王修龄尝在东山，也许东山在东晋已经是隐居的代名词，不是实指。“2.69”“若保全此处，殊胜东山”，“2.93”“从都下还东山”，“戴安道既厉操东山”等等。

## 5.54
> 王、刘与桓公共至覆舟山看。酒酣后，刘牵脚加桓公颈，桓公甚不堪，举手拨去。既还，王长史语刘曰：“伊讵可以形色加人不！”

- *王、刘*：王濛、刘惔，桓温。王濛是晋哀帝司马丕（晋明帝司马绍的孙子）的丈人，刘惔、桓温是司马绍的女婿。
- *覆舟山*：南京钟山和玄武湖边上，又叫玄武山、九华山，因其临湖一侧陡峻如削，像一只倾覆的行船而得名。在当时它离宫城很近，是皇家花园、贵族活动区。
- *看*：观赏游玩。吴地方言，“我到某地去看看”，就是参观的意思。李璟《摊破浣溪沙》：“菡萏香销翠叶残，西风愁起绿波间。还与韶光共憔悴，不堪看。”
- *讵可*：岂可，怎么可以。《后汉书?光武帝纪上》：“天下讵可知”。
- *形色加人不*：盛气凌人乎。刘惔酒喝多了，和桓温关系也比较亲密，就把脚搁在桓温的脖子上，桓温拨开。在王濛眼里，桓温不能把脚拨开，因为桓温门第低，又投身行伍。二流人物怎么可以无礼拒绝一流人物的无礼呢？

这个故事好像有点搞笑。但是，张良对黄石公的无礼要求接受了，韩信对无赖的侮辱忍受了，苏轼对此赞不绝口：“古之所谓豪杰之士者，必有过人之节。人情有所不能忍者，匹夫见辱，拔剑而起，挺身而斗，此不足为勇也。天下有大勇者，卒然临之而不惊，无故加之而不怒，此其所挟持者甚大，而其志甚远也。”不过更多人的忍让没有带来张良、韩信的功业，他们不停地忍让，不停地退步，然后身上满是伤痕默默无闻地死去。爱因斯坦曾经来过上海，他后来满腹同情地写道：“他们（中国劳动人民）似乎鲁钝得不理解他们命运的可怕。”桓温显然不是这样的人，他戎马一生，18岁就手刃杀父仇人的3个儿子。对付刘惔，你昨天把脚放在我脖子上，今天我就用弹弓弹破你的枕头，吓你一跳！  
说到张良、韩信，张良的故事无非是故弄玄虚的神话鸡汤，至于韩信，他并非是看淡风云、宽容大度的容忍，而是直接导致心灵扭曲的残忍，与勇又有什么关系？苏轼才气纵横，危言耸听罢了。

## 5.55
>桓公问桓子野：“谢安石料万石必败，何以不谏？”子野答曰：“故当出于难犯耳。”桓作色曰：“万石挠弱凡才，有何严颜难犯！”

- *桓子野*：桓伊字叔夏，小名子野（或野王），与桓温同乡远亲，“伊与桓温疏宗”。桓温是安徽谯国龙亢桓氏，桓伊是谯国轾县桓氏，他年纪比桓温小，当过桓温的参军。
- *万石*：谢万谢中郎，字万石，谢安的四弟，前已多见。358年，谢家顶梁柱豫州刺史老大谢奕去世，老二谢据已去世，老三谢安不愿意当官，于是老四谢万任西中郎将、豫州刺史、假节、监司豫冀并四州诸军事，领淮南太守。谢家和桓温关系极为亲密。王羲之和谢安都劝说桓温不要让谢万出任军职，但桓温不听。谢安放不下心，赶赴谢万军中当参谋，“审其必败，乃俱行”，“2?82”中，高崧也“便为谢道形势，作数百语”，但谢万本性难改，在军中还是我行我素的名士风范，将士离心。359年谢万伐前燕，未战而兵溃。所以这个故事存疑。
- *难犯*：不可触犯。众怒难犯。
- *挠弱*：挠，弯曲。百折不挠。挠弱，软弱。

谢万名士傲慢，但这种傲慢是“佻率”，轻佻草率，他性格中有软弱的一面，譬如他在“雅量”中和老牌名士蔡谟的儿子蔡系争座位，蔡推倒了谢，谢毫无愠色，整理衣冠后从容坐在边上。这说他雅量也好，说他软弱也没错。在“简傲”中，他去拜访王导的儿子王恬，王恬眼里就没他这个客人，他只好回去向谢安诉说委屈。桓温说他软弱，是直率的批评。

## 5.56
> 罗君章曾在人家，主人令与坐上客共语，答曰：“相识已多，不烦复尔。”

- *罗君章*：罗含，湖南耒阳人，当过桓温的参军，被他称为“江左之清秀”，谢尚称之为“湘中之琳琅”。后升任散骑常侍、廷尉等职。
- *共语*：谈天，专指“谈玄”。当时的一种风气，士人聚会不问房产股票，不问子女入学，只谈宇宙人生，彼此理解对方的文化水准。《南齐书 刘绘传》：“父勔，宋末权贵，门多人客，使绘与之共语，应接流畅。”
- *相识已多，不烦复尔*：知道我清谈水平的人已经很多了，不需要搞得这么繁复。

2013年10月19日，耒阳市召开纪念罗含诞生1721年暨会刊发放仪式。耒阳市副县级干部、市总工会主席罗育锋，市文联主席熊艾春参加座谈会。  
2015年7月4日，耒阳市市文联主席熊艾春因为在社区网站贴诗被差评，率人“恕灿”社区网站电脑。其诗多有佳句，惜人不识：“乐游此地喜气洋洋，耒阳人民要弘扬正能量”，“中央八项规定，视作自己情侣”、“党兴国强人民欢叫”……  
熊某的直率媲美于罗含，可谓魏晋风采。

## 5.57
>韩康伯病，拄杖前庭消摇。见诸谢皆富贵，轰隐交路，叹曰：“此复何异王莽时！”

- *韩康伯*：韩伯字康伯，或称韩豫章，见“1?38”、“1?47”等，殷浩的外甥。
- *消摇*：逍遥。《礼记?檀弓上》：““孔子蚤作，负手曳杖，消摇于门。”
- *诸谢*：谢家。故事大概发生在淝水之战前3年的380年前后，这个时候谢家已经发达，谢安是司徒、侍中、都督扬、豫、徐、兖、青五州及幽州的燕国诸军事、假节，弟弟谢石，尚书，谢铁，永嘉太守，子侄辈谢玄兖州刺史、冠军将军、加领徐州刺史，其他还有一些朝廷高管，在当时为第一门阀。但谢家崛起比较晚，属于新贵。
- *轰隐交路*:车马排场很大。轰,群车声。殷，雷声。《史记?苏秦传》：“民之众，车马之多，日夜行不绝，轰轰殷殷，若有三军之众。”《阿房宫赋》：“雷霆乍惊，宫车过也；辘辘远听，杳不知其所之也。”
- *王莽时*：西汉末期，王政君是汉元帝的皇后，儿子汉成帝刘骜。接着汉哀帝刘欣、平帝刘衎先后即位，王政君都是太皇太后。王家是西汉一代中最显贵的家族，刘骜即位后，一日封王家舅舅五人为侯。王家先后有五人担任过当时最为权贵的大司马，一家有十人封侯，各郡国的地方长官也大多出自王氏门下。王家自然“争为奢侈”，“群弟世权，更持国柄，五将十侯，卒成新都”。

韩伯为什么看不起谢安和谢家，固然任何大政客的家人总有几个王八蛋，也总有人政敌，但韩伯的情况比较特殊。他舅舅殷浩，“浩甥韩伯，浩素赏爱之”，殷浩也曾经“殷浩不起，当如苍生何”，也曾经是执政大臣，也多次北伐，但结果并不一样。353年，殷浩兵败声名裂；379年，秦晋淮南之战，谢玄多有胜绩，380年，谢安因功任为卫将军、开府仪同三司，进封建昌县公。韩伯的看法也许带有个人偏见，也许就是正直。

## 5.58
>王文度为桓公长史时，桓为儿求王女，王许咨蓝田。既还，蓝田爱念文度，虽长大，犹抱著膝上。文度因言桓求己女婚。蓝田大怒，排文度下膝，曰：“恶见文度已复痴，畏桓温面！兵，那可嫁女与之！”文度还报云：“下官家中先得婚处。”桓公曰：“吾知矣，此尊府君不肯耳。”后桓女遂嫁文度儿。

- *王文度*：江东独步的北中郎将王坦之，前已多见。早年他曾在桓温军中做过长史，谢安当司马。桓温比王坦之大18岁，比谢安大10岁。大概在此期间，谢安、桓温的女儿嫁了王坦之的两个儿子。但从其他资料看，王坦之和谢安对桓温并不团结，东晋门阀之间的政治联姻也并不代表他们会共同进退，而是维系家族利益。
- *蓝田*：王坦之父亲王述。
- *爱念*：爱怜。晋代名士风范，情感直露，老头子王述还抱30来岁的儿子王坦之在膝盖上。这个故事给人印象深，倒不是门阀之间的婚姻规则，父子之间的溺爱之情。后来辛弃疾《南乡子》写道：“日日老莱衣。更解风流蜡凤嬉。膝上放教文度去，须知。要使人看玉树枝。”辛弃疾四句诗用了四个典故，所以有人批评他是在“掉书袋”。
- *恶见文度已复痴*：“恶见”大约为“乐见”的反义词，讨厌。已复痴，已经又成为傻子了。有个《世说》的版本，不见“恶见文度已复痴，畏桓温面”，确实可以删去，干脆利落，怒气勃勃。
- *兵*：骂人的话，类似“丘八”，当时士族看不起行伍出身的军人家庭和个人，直到近代估计还是这样，因为近古军人一般不识字，没有话语权。就连宋代威名赫赫的狄青，“诵咏其材武。青每出入，辄聚观之，至壅路不得行”，也因为是行伍出身而多次受辱。宋尹洙说：“状元登第，虽将兵数十万，恢复幽蓟，逐强藩于穷漠，凯歌劳还，献捷太庙，其荣不可及也。”你无论立了天大的军功，还是比不上状元及第！狄青某次为部将焦用向韩琦求情，说：“焦用有军功，好儿。”韩琦冷笑说：“东华门外以状元唱出者乃好儿，此岂得为好儿耶！”立青而面诛之。
- *先得婚处*：已经婚配。贵族可以娶低等女子，而不喜欢女儿嫁次一等的门阀子弟，觉得这个才是门当户对的正理。所以后来反了一下，王坦之的儿子娶了桓温的女儿。

## 5.59
>王子敬数岁时，尝看诸门生樗蒲，见有胜负，因曰：“南风不竞。”门生辈轻其小儿，乃曰：“此郎亦管中窥豹，时见一斑。”子敬瞋目曰：“远惭荀奉倩，近愧刘真长。”遂拂衣而去。

- *王子敬*：王献之，王羲之儿子，再婚做简文帝司马昱女婿，前已多见。
- *门生*：中国东汉称儒学宗师亲自授业者为弟子，转相传授者为门生。东汉中后期渐与宗师形成私人依附关系；魏晋南北朝时，有的不一定有师生关系，而是做部曲、佃户以逃避徭役，成为世族地主的一种依附人口，“都下人多为诸王公贵人左右佃客、典计、衣食客之类，皆无课役”，又称门附。顾炎武《日知录》中说：“南史所称门生，今之门下人也。其人所执者，奔走仆隶之役。其初至，皆入钱为之。”唐代科举制度以后，考生得中进士后，对主考官亦称门生。  
哈维尔在《存在的意义和道德的政治》中说：“权力从来不会独自存在，它支配人也来源于这些人。我们这个社会的权力运作，并不简单地是一些人以赤裸裸的权力支配另一些人，每个人都被迫成为权力机器上的一个部件，因此常常很难指出谁要为政权的所作所为负责。在每个人的内心深处，他一方面是奴仆，畏上司，另一方面又是奴隶主，想践踏下属。专制制度就是以这种方式把整个社会纳入它的系统，使人不仅是它的受害者，又是创建者；人们既是囚徒，又是狱吏。”哈维尔说的不全对，非但是专制体制，现在的所知道的政治体制都很难避免这种人身依附，权力无处不在。
- *樗蒲*：一种赌博游戏，类似掷五颗骰子，不同的组合排列比大小。
- *南风不竞*：出自《左传•襄公十八年》：晋人闻有楚师，师旷曰：“不害。吾骤歌北风，又歌南风。南风不竞，多死声。楚必无功。”意思是说，楚国出兵攻打郑国，晋国乐师师旷预言说：我屡次唱北方的曲调，又唱南方的曲调。南风声部偏弱，有衰微之气，楚国不会获胜。人类文化至今带有这种异类相比的联想方式，把两件毫不相关的事情联系在一起，中国文化再次上升，提出“天人合一”的哲学概念。一个小孩子能知道这个生僻的典故，以此比喻坐南边的手气不好，要输，说明当时家庭教育很重视《左传》的教学。
- *郎*：郎是郎官，汉代贵族子弟多先出任此官，于是多把贵族家的年轻人称之为郎。也有人说是从“良人”这个称呼演变而来，良人，乡官名，即乡大夫。《国语•齐语》：“十连为乡（二千家），乡有良人焉。”良人转为郎，郎君，再转为少爷、相公。解放后不用这种称呼，现在少爷、相公代指男性性工作者。这种词义的转换耐人寻味。
- *管中窥豹*：《庄子•秋水》“子乃规规然而求之以察，索之以辨，是直用管窥天，用锥指地也，不亦小乎!”《韩诗外传》：“譬如以管窥天，以锥刺地——所窥者大，所见者小，所刺者巨，所中者少。”《三国志•注》：“议者或以军吏虽有功能；德行不足堪任郡国之选……论者之言；一似管窥虎欤！”这是说，你这个娃娃，只见树木，不见森林，靠手气的东西你知道什么！
- *荀奉倩、刘真长*：曹魏荀粲，爱美人爱到死的那个。东晋“天之自高”的刘惔，拒绝祭祀鬼神以祈福。两人以清高著称，“不能与常人交接，所交皆一时俊杰”，“小人都不可与作缘”。

从古代文化看，孔子就搞阶层蔑视，大谈君子小人，这种思想观念下的“方正”，到了宋代世家豪门皆成云烟，佛教众生平等的思想深入人心，就终于大不同了。苏轼说：“吾上可陪玉皇大帝，下可以陪卑田院乞儿，眼前见天下无一个不好人”（林语堂《苏东坡传》），明代张岱说：“上陪玉皇大帝而不谄，下陪悲田院乞儿而不骄”（《自为墓志铭》）。

## 5.60
>谢公闻羊绥佳，致意令来，终不肯诣。后绥为太学博士，因事见谢公，公即取以为主簿。

- *羊绥*：泰山羊氏，他岁数不大就死了。

谢安要羊绥来见他，他不肯接受这种命令式的邀请，崖岸自高，是清高方正。谢安一见到他，立刻选拔为幕僚长，而不是人云亦云地给他一个官职，这是为国家选拔人才计，也是方正。

## 5.61
>王右军与谢公诣阮公，至门，语谢：“故当共推主人。”谢曰：“推人正自难。”

王羲之和谢安去拜访隐居在新昌的阮裕，阮裕是王羲之、谢安的前辈，而且他曾经发表过看不起谢安这种后进家族的言论，“新出门户，笃而无礼”，虽然谢安小时候向阮裕求学过，但是现在的谢家已经不是当初二三流的家族了，谢安的态度就针锋相对了：“推崇恰恰是很难的”。  
这个故事也许还有另一种解释，王羲之和谢安去见阮裕，目的是推举阮裕出山做官，而谢安认为隐居是阮裕的本心，如果硬要推举阮裕，这恰恰是很难的，因为在“赏誉•77”中有类似一则故事：王右军语刘尹：“故当共推安石。”刘尹曰：“若安石东山志立，当与天下共推之。”

## 5.62
>太极殿始成，王子敬时为谢公长史，谢送版使王题之。王有不平色，语信云：“可掷著门外。”谢后见王，曰：“题之上殿何若？昔魏朝韦诞诸人亦自为也。”王曰：“魏祚所以不长。”谢以为名言。

- *太极殿*：魏晋以来的正殿。曹魏建于洛阳，后毁于战火。东晋建于南京，居中，上应北极星，出自《庄子》：“大道，在太极之上而不为高；在六极之下而不为深；先天地而不为久；长于上古而不为。”金銮殿一般就指太极殿，清代叫太和殿。
- *信*：使者。
- *韦诞*：曹魏侍中，当时的大书法家，多次题写过曹魏宫殿的匾额。据说魏明帝筑陵云台，工匠误先把匾钉在上面，取不下来，字还没血。于是韦诞凌空题匾，恐高害怕，题完后须发全白了。
- *自为*：亲自写。

王献之是当时最出色的书法家，请他题词按理说是极高的荣誉，但是在王献之看来，这些是书匠的手艺，他是大臣显贵，只写他想写的东西，不屑去写匾额。当然，朝廷硬要他离婚，把公主塞给他当妻子，他也很不满意，借题发作也大有可能。谢安认可这种说法，后来叫写隶书的刘环和韦昶两人题了匾额。  
到了当代，有些领导人和官员题词就显得可笑，谢安恐怕不会请王献之写了，而是自己动手：“国家博物馆”、“上海菜市场”、“一师是所好学校”……

## 5.63
>王恭欲请江卢奴为长史，晨往诣江，江犹在帐中。王坐，不敢即言，良久乃得及。江不应，直唤人取酒，自饮一碗，又不与王。王且笑且言：“那得独饮！”江云：“卿亦复须邪？”更使酌与王。王饮酒毕，因得自解去。未出户，江叹曰：“人自量，固为难！”

- *王恭*：身无长物的王恭。390年，孝武帝司马曜任命姐夫王恭为都督兖、青、冀、幽、并、徐及扬州之晋陵诸军事，前将军，兖、青二州刺史，假节，镇守京口。他想请江敳当他的长史。江敳是当时西晋贤人江统的孙子，国子祭酒江虨（5.46）的儿子。
- *犹在帐中*：还没起床。
- *得及*：提及此事，请他做长史。
- *卿亦复须邪*：你也要喝一碗吗？叫王恭为卿，表示轻视。须大概通“需”，羌笛何须怨杨柳。
- *自解*：自我解脱，自己给自己下了台阶。
- *人自量，固为难*：人有自知之明，确实是很难的。

*江敳独饮*，也许有用意。庄子说，鹪鹩巢于深林不过一枝，偃鼠饮河不过满腹。我是清晨起来喝酒的酒徒，我只要喝我这杯酒够了。我不会谢你对我的赏识，我们各自走在自己的路上。  
拒绝别人的赏识就是“方正”，傲慢就是“方正”，不合作就是“方正”。

## 5.64
>孝武问王爽：“卿何如卿兄？”王答曰：“风流秀出，臣不如恭。忠孝亦何可以假人！”

孝武帝司马曜问姐夫，你们王爽、王恭两个姐夫，哪家强！这个是魏晋人清谈的习惯，“比起你来怎么样？”我们可以看到大量类似的问话。而大多数名士的回答和当代的官员一样，“虽然那个人优点多多，但我在某些方面还比他强。”当然，因为价值取向不同，人物品藻主要不是指彼此工作能力的强弱，道德水平的高下，学问见识的大小，而集中在灵魂与肉体上，在审美上，在气质风度上；而气质风度的内容也非常广泛，我们将看到大量的分类和一些云山雾罩的词语。
> 作者：耶利歌城下 </br>
司马曜和王恭是郎舅关系，王恭是孝武皇后王法慧的老哥。楼主把二者关系搞错了. 王恭是司马曜的大舅子，司马曜是王恭的妹婿

- *风流*：风流是当时最高的评价。“风流”一词最初见于班固《汉书•赵充国辛庆忌传赞》：“山西、天水、陇西、安定北地处势迫近羌胡，民俗修习战备，高上勇力，鞍马骑射。故秦诗日：‘王于兴师，修我甲兵，与子偕行。’其风声气俗，自古而然，今之歌谣慷慨，风流犹存耳。”这里“风流”是“流风”的倒用，流传下来的教化，意同 “风化”，指文化影响。  
到了魏晋以后，“风流”开始形容人物，如《三国志•刘琰传》中说：“有风流，善谈论。”庾信《枯树赋》：“殷仲文风流儒雅，海内知名。””《晋书•王献之传》说：“高迈不羁，风流为一时之冠。”这里基本就是风度翩翩的意思。所谓最高评价，因为风流就是时代文化的宗主，就是马云、马化腾，鸡汤励志至极，他们负责了教化，类似的例子比比皆是。《晋书•乐广传》：“广与王衍俱宅心事外，名重于时。故天下言风流者，谓王、乐为称首焉。”《晋书•王濛传》“时人以惔方荀奉倩，濛比袁曜卿，凡称风流者，举濛、惔为宗焉。”  
那什么叫风度翩翩呢？《晋书•礼志》说：“晋末风流相尚，宽衣博带。”。”《南史•张绪传》说：“武帝以植于太昌灵和殿前。常赏玩咨嗟日：‘此柳风流可爱，似张绪当年。’”司空图《诗品•含蓄》：“不著一字，尽得风流。语不涉已，若不堪忧。是有真宰，与之沉浮。如渌满酒，花返时秋。悠悠空尘，忽忽海沤。浅深聚散，万取一收。”  
哦，风流就是着装要宽大，加蓝血技力的鹤氅当为首选。要柳枝般迎风飘动，顺势而行，自由自在，起早摸黑的老黄牛工作态度肯定不行。要心存宇宙人生，意在言外，心领神会，发言时间超过超短裙的长度一票否决。  
王恭颜值高，确实风流。晋书中说他：美姿仪，人多爱悦，或目之云“濯濯如春月柳”。尝被鹤氅裘，涉雪而行，孟昶窥见之，叹曰：“此真神仙中人也！”  
网友饮酒抽烟读世说会心大笑是风流，我低头打字调动记忆苦思冥想解释世说是不风流。  

- *秀出*：木秀于林，高人一大截。《国语•齐语》：“于子之乡，有拳勇股肱之力，秀出于众者，有则以告。有而不以告，谓之蔽贤。”
- *忠孝*：此处做偏义复词，就是指忠君。  
王恭、王爽在孝武帝死后和权臣司马道子对着干，398年起兵造反，兵败被杀。后平反。

## 5.65
>王爽与司马太傅饮酒，太博醉，呼王为小子。王曰：“亡祖长史，与简文皇帝为布衣之交；亡姑、亡姊伉俪二宫。何小子之有！”

- *司马太傅*：会稽王司马道子，简文帝司马昱的儿子，孝武帝司马曜的弟弟。司马曜死后，他是托孤之臣，太子太傅，领徐州刺史，爱喝酒，“为长夜之饮，蓬首昏目”，常常“昏醉”，说些让别人记恨的话，前已多见。这次得罪王爽，王恭、王爽兄弟起兵造反。前一次得罪桓玄，桓玄造反把他弄死了，“道子酣纵不孝，当弃市”。
- *亡祖*：已故的祖父王濛，想当东阳太守的司徒左长史，前已多见。王爽姑妈王穆之是晋哀帝司马丕的妻子，姐姐王法慧是孝武帝的妻子，司马道之的嫂子。
- *布衣之交*：贵人与平民之间的友谊，以平辈相待的友谊。这是王爽的谦辞，太原王家在西晋就很显赫了，甚至后来比司马这个姓氏还显赫，因为晋亡，司马家的人或死或改姓。
- *伉俪二宫*：两任皇帝的配偶。
- *何小子之有*：何陋之有，有什么可以称我为小子的呢！

喜欢喝酒没什么的，每酒必醉，借酒说心里肮脏的话，做肮脏的事，一定就是一个肮脏的人。

## 5.66
>张玄与王建武先不相识，后遇于范豫章许，范令二人共语。张因正坐敛袄，王熟视良久，不对。张大失望，便去，范苦譬留之，遂不肯往。范是王之舅，乃让王曰：“张玄，吴士之秀，亦见遇于时，而使至于此，深不可解。”王笑曰：“张祖希若欲相识，自应见诣。”范驰报张，张便束带造之。遂举觞对语，宾主无愧色。

- *张玄*：会稽张玄之，字祖希。江南望族，历任吏部尚书、吴兴太守、会稽内史等，见2.51，小时候评价佛像哭不哭的那位。
- *王建武*：王忱，曾任建武将军，王坦之的儿子，又叫王大，要拿堂侄儿王恭席子的那位，见3.24等。
- *范豫章*：范宁，曾任豫章太守，见2.97。太原王氏多信佛教，琅琊王氏多信道教，张玄之名字中有个“之”字，信道教。
- *许*：处，那里。
- *共语*：清谈。
- *因*：于是。
- *正坐敛袄*：正襟危坐，清谈是剧烈的脑力活动，大事情。
- *苦譬*：苦，苦思冥想，努力，竭力；譬，说服，劝说，《后汉书•第五伦传》“今虽有精兵，难以赴敌，羽请往譬降之”。
- *让*：责备。
- *而使至于此*：而使之至于此，迫使他到这种地步。
- *自应见诣*：王忱知道张玄之的字，说明早有耳闻。但他认为自己家族比张玄之家族地位高，名望大，张应该执晚辈礼来拜访他。张玄之认可这种定位，于是“束带”正装拜见王忱。
- *驰报*：快马报告。既然是快报，那么王忱还在范宁家里？从常理推测，应该是去了王忱家里，所以有宾主之分。这种礼节比较繁琐和奇怪，晋书中说这是“风流”，“ 宁谓曰：‘卿风流隽望，真后来之秀。’忱曰：‘不有此舅，焉有此甥！’”，这里的风流应该就是指摆谱蛮大。但我看还应该归之于儒家对“礼”的重视，王、张、范虽然有不同的宗教信仰，但根子还是等级观念中的“礼”。

这“方正”最后一个故事提醒我们，所谓方正，很多地方反映出来的是儒家的“礼”和对抗“无礼”的各种运用。

## 方正小结
方正在《世说新语》中，紧随孔门四科之后，大概因为汉文帝时期选拔官员就设了“贤良方正”这一特科，“贤良方正”有时候也叫“贤良文学”。此后，两汉屡有诏举“贤良方正”之令，有时贤良方正连言能直言极谏者，有时单举能直言者，所以“文学”之后就是“方正”。从字面上理解，方正就是正直，具体表现往往是直言不讳，甚至针锋相对，去批评他人，去反击他人，然后拂袖而去。如第一则，陈元方“入门不顾”。按现在的说法，主人公未免情商偏低，在现在就往往不被认可，不受欢迎，但在古代，却是一种高尚的品德。其实智商高的人情商怎么就会偏低啊，无非因为他有自己的原则。人无刚骨，安身不牢，这个原则是他安身立命所在，如果因一时迁而丧失原则，就如孟子所言：“所养的浩然正气，如果有一次行为问心有愧，那就气馁——没有力量了”。所以宗世林松柏之志犹存：“我就是不想和你曹丞相做朋友！”何充对王敦大将军说：“哪怕你是我顶头上司，你杀人如麻，我还是要说，你哥哥就是一个王八蛋！”钟雅说：“我如果怕被苏峻杀死而跑掉，我不知道历史会怎么记载我！”这就是刘向在《新序》中说的：“义死不避斧钺之罪，义穷不受轩冕之服。”也就是北岛所说的：“为了在审判之前,宣读那些被判决的声音。告诉你吧，世界，我——不——相——信!纵使你脚下有一千名挑战者，那就把我算作第一千零一名。”  
假如在这个世界上，知识分子个个“情商”很高，圆转如意，进退自如，那还要谈什么骨气，谈什么正义！佛教大和尚拾得说：“忍他，让他，由他，避他，耐他，敬他，不要理他，再过几年，你再看他”，无非是佛教阴险，相信对方野心膨胀、得志猖狂后自有报应。娄师德唾面自干，无非是武则天时期告密成风的形势所逼，也绝不是中华文化的正道。最近几年，社会上流行“感恩”，说什么“感谢那些迫害我的人”，却是强盗逻辑的拥护者，不但心理会极度扭曲，往往转身一变成为迫害他人的恶臭制造者和共谋者。  
在当时的社会环境中，“方正”还表现在坚持门第等级观念，坚守尊卑的社会秩序。所以“方正”的不少故事，就是反映那些高门是如何看不起寒门和庶民的。这起源于东汉后期知识分子掌握话语权的情况，然后由于制度的固定，不断流变。起初一些学者看不起太监、看不起外戚，看不起没有学问的人，然后就看不起不是自己同类的人，“监、令不同车”。接着这些人的子孙、学生当了朝廷的大官，建设和把持了官员的考评制度，构建了复杂的关系网，进而为维护利益共同体，固化阶层，形成一种东晋时期排斥那些寒族庶民的风尚。周敳的弟弟周嵩看不起迅速晋升的刁协，刘惔不和“小人”结交，陶侃的儿子陶范送王胡之粮食救济，王胡之还侮辱陶范等，他们看不起在智力和才能并不逊色于他们的同僚和“贱民”，堵塞他们上升的通道。他们在伤害对方的同时，也伤害了社会活力，伤害了自己的家族，伤害了人民。这种既得利益者的丑恶嘴脸，以丑为美的舆论取向，终于被唐宋科举制度逐渐打破。但是我们还是要警惕和谴责当下的这种思潮，“红二代”、“富二代”、人身依附的官场圈子，阶层固化始终是社会发展的大敌。看了“世说”里面的几则故事，我们也可以知道当时的有识之士和后世的杰出人士，也并不赞同并否定他们这种错误的言行。  
“方正”又体现在士族对“礼”和社会秩序的维护上。我曾经说过，儒家的核心并不是是“仁”，而是“礼”。古代社会的内核“三纲”就是“礼”包含的社会秩序的具体体现。一些人说，古代社会是“外儒内法”，这不对，而是以礼为法，所以叫礼教、礼法。韩非子的法家思想，并不贯彻于2000年的封建社会中，他的一些言论，合符礼法的也许有所体现，但他的根本和比较重要的思想，并没有在文化教学和实践中得以表现，它没有摆上台面，也没有成为潜规则。而礼法是传统中国法律体系的基本特征，等级观念和纲常名教是其两大支柱，全部社会成员的社会生活行为都被纳入礼法规范。这就是儒家的统治术。在“方正”中，我们就可以看到一些士人是如何维持“礼法”，作为对抗上级或君主，并达成共识和尊重的武器。如陈群对曹丕登位表示不高兴（尽管这个故事是编造的），郭淮追回要被处以死刑的妻子，陈泰要诛杀贾充，嵇绍拒绝在朝廷宴会上演奏乐器，王献之拒绝写匾额，都赢得了社会的认可。当然，这种礼法还具体体现在如何接待宾客，如何称呼，怎么安排婚礼，怎么安排座位等，这些看似是小事，但就像现在一样，他们维护这种细节，并以此为乐，这就是等级制度。最近几年，店掌柜多次讲“讲规矩”，规矩不是纪律，也不是礼法，但其实质表明，他要建立新的等级制度，从反面表现出其合法性和威权体制受到的威胁。  
“方正”也表现在坚持无神论上。阮修不信鬼神，舆论认为这是正直的表现。当我们考虑到古代的文化背景，作者和舆论都表示肯定，我们就能得出结论，我们中国人在这个方面早就领先于世界。现在有些观点认为，中国人没有信仰导致缺乏敬畏感，导致社会道德堕落。这很荒诞，就像有鬼神一样荒诞。敬畏没有的东西而能使道德上升，这种思维模式的逻辑推理是什么呢？难道古代不是因为是熟人社会和生产力低下的原因而社会治安问题少吗？难道西方发达国家现在无神论者比率较大上升而其道德水准也在较大下降吗？难道 有“主体信仰”而道德水准很高吗？难道当今宗教和极端宗教思想的冲突导致的巨大纷争和给予人民巨大的痛苦是道德的吗？我曾经和西方著名宗教学者交流过，他们对中国和中国政府作出了自己的批评，特别是有关宗教政策。我问：“我可以承认你们说的都有道理，我们有很多事情要做，要改进。但是，我想问一下，你们基督教已经有2000年了，有没有问题？”七位教授集体沉默许久，然后有两位说：“我们认为，基督教分裂了，这是问题。其他我们不认为有问题。”  
我比七位教授更加方正。


# 雅量 {#06}  
## 6.1
> 豫章太守顾劭，是雍之子。劭在郡卒，雍盛集僚属，自围棋。外启信至，而无儿书。虽神气不变，而心了其故；以爪掐掌，血流沾褥。宾客既散，方叹曰：“已无延陵之高，岂可有丧明之责！”于是豁情散哀，颜色自若。

- *顾雍*：东吴宰相，魏晋江南顾家是大族，奠基人就是顾雍，前已多见。其长子顾劭，妻子是孙策的女儿，28岁当南昌太守，32岁去世。
- *外启信至*：外边禀告有信使（书信）来了。
- *延陵之高*：指春秋时候的季札，吴王的儿子，封地延陵。见1•32，“季札挂剑”。季札出使期间，中途儿子去世，他为儿子办理丧葬时，孔子专门带一帮学生去学习葬礼，并赞叹说：“延陵季子之于礼也，其合矣乎！”顾雍在南京，儿子在江西，不能赶过去像季札那样办儿子的葬礼。这个故事早期见于裴启的《语林》：“已无延陵之遗累，宁有丧明之责邪？”意思是说：“我现在没有了像季札那样的世俗牵挂，需要办葬礼。”《世说》修改这句话，是突出老年丧子是人生的大悲痛，用“遗累”的说法不合人之常情。
- *丧明之责*：孔子弟子子夏死了儿子，伤心得哭瞎了眼睛，并叫嚷：“我有什么罪过啊，老天爷这样惩罚我！”曾参批评子夏：“你在西河讲学，西河的人只知道你而不知道你的老师孔子，这是你的第一个罪过；你父母去世，你不彰显孝道，西河人都不晓得，这是你的第二个罪过：你儿子死了，你却哭瞎了眼睛，这是你的第三个罪过！”
- *豁情*：散放情怀，放下痛苦。宋代周守忠说：“知喜怒之损性，故豁情以宽心；知思虑之销神，故损情而内守；知语烦之侵气，故闭口而忘言；知哀乐之损寿，故抑之而不有；知情欲之窃命，故忍之而不为。”养生豁情之道是为了像甲鱼乌龟一样长寿，而荣辱得失不系于怀则是道德情操的高深修养  

我们当然记得，谢安得到淝水大战的喜报而继续不动声色地下完围棋，但出门时候由于欣喜，屐齿碰到门槛而折断。其前辈顾雍知道自己孩子去世，继续不动声色地下完围棋，但指甲紧紧握住掌心，把手刺破了。虽然这个故事没有谢安的有名，但喜悦容易控制，一千次欢乐也抵不上一次痛苦，顾雍深蕴悲情比谢安抑制狂喜更为深沉。雅量并非风雅的气量，而是宏达的器量。雅，正也。如果说，狗屁不通的“正能量”要强加解释，它不是歌功颂德，自以为是的愚昧无知，而应该指宏大宽广的胸怀见识。

## 6.2
>嵇中散临刑东市，神气不变，索琴弹之，奏《广陵散》。曲终，曰：“袁孝尼尝请学此散，吾靳固不与，《广陵散》于今绝矣！”太学生三千人上书，请以为师，不许。文王亦寻悔焉。

中散大夫嵇康因吕安一事被收入狱，钟会向司马炎指出，嵇康名望很大，非议朝廷和礼教，又是曹家的女婿，并涉嫌谋反，“嵇康，卧龙也，不可起。公无忧天下，顾以康为虑耳”，嵇康还要搞社会思想多元化，冲击君主专政社会的核心价值观，是一场意识形态领域严峻复杂的你死我活的斗争，“负才乱群惑众”，杀了最好。过去姜太公、孔老二是这么干的，现在曹操、诸葛亮也都是这么干的，以言论、思想治罪在三国时期是家常便饭，司马炎自然心领神会，得心应手。但嵇康和边让、孔融、彭羕还有点区别，他“能属词，善鼓琴，工书画，美风仪”，不仅是著名的音乐家、诗人，而且“龙章凤姿”，颜值很高，起码是“都教授”一个等级，他在野外攀岩，“时有樵苏者遇之，咸谓为神”，是当之无愧的大明星，他被抓起来，众多太学生希望赦免他而让他去当教授，传说还有豪杰随嵇康入狱，我们就可以想见他的风采。

- *东市*：在洛阳东大门建春门外一里。
- *广陵散*：广陵散的意思大概是说这是流行于扬州地区的琴曲，传说就是《聂政刺韩王曲》的异名，作者不详。故事中说嵇康由鬼神所授，并答应不教授于其他人。该曲是叙事音乐，有“刺韩”、“冲冠”、“发怒”、“报剑”等章节，高潮部分的旋律慷慨激昂。嵇康临刑弹奏此曲，不是表现其看穿生死的豁达，而是无惧生死的英雄气概。但刘孝标的注中说，嵇康弹奏的是《太平引》，太平引曲调无流传，或为同曲。
- *袁孝尼*：袁准字孝尼，据说是嵇康的外甥。
- *靳固*：吝惜固执。《后汉书•崔石传》：悔不小靳，可至千万（后悔没有再稍微的吝惜一下，500万就把官位给卖了否则可以卖到1000万）。
- *寻悔*：不久后悔了。王夫之说：“孔融死而士气灰，嵇康死而清议绝。”司马炎比曹操手软，没有杀嵇康全家，杀了嵇康还有点后悔。

嵇康随后获得了崇高的荣誉，他是两晋期间名士的楷模。名士们认为，嵇康走在人生的正道上，是顺应天命的杰出人才，是他们的精神领袖。嵇康喜欢打铁，我们可以想象，在洛阳的竹林边，“都教授”挥动铁锤，击向火红的铁具，铁花四溅，声音响彻原野，世界寂静无声。遗憾的是，嵇康的无惧生死的器局被后世演变为醉生梦死的堕落。吕安曾经给嵇康写过一封信，信中说：“顾影中原，愤气云涌。哀物悼世，激情风厉。……平涤九区，恢维宇宙，斯吾之鄙愿也。”这种气度在两晋名士中寥若晨星。

> last updated 2018-04-03

## 6.2  
>夏侯太初尝倚柱作书。时大雨，霹雳破所倚柱，衣服焦然，神色无变，书亦如故。宾客左右，皆跌荡不得住。  

- *夏侯玄* 字泰初，夏侯尚之子，夏侯渊的侄孙，司马师的舅子，与何晏等开创魏晋玄学先河，是当时的玄学领袖。这个故事就是他贯彻玄学精神的体现。  
故事来自于《易》震卦，“震来虩虩，笑言哑哑。震惊百里，不丧匕鬯。”大意是，雷声如猛虎来临般令人恐惧，但我依旧谈笑自若。雷声震惊百里，但我依旧饮食如常（手里拿着酒勺子，连一滴酒都没有洒出来。也许是说我祭祀如常）。  
故事来自于《庄子》，“之人也，物莫之伤：大浸稽天而不溺，大旱金石流，土山焦而不热”。大意是说，这样的人（仙人）不被外物所伤害，洪水滔天淹不着他，大旱把金石熔化，把土山烧焦，他也不觉得灼热。  
这种临危不乱、处乱不惊的气度是因为后天修养，只有克服恐惧才能获得人的尊严。恐惧并不来自肉体的感受记忆，而是源于对未知、痛苦和死亡的想象。只有看透事物本质才能气量宽广，只有充分体察恐惧的来源才能无所畏惧。按老子的说法就是“致虚极，守静笃”“及吾无身，吾有何患”，建立宏大的世界观，把自己定位于无，与世界一体，使心灵保持虚和静的至极笃定状态。  
夏侯玄不怕打雷的故事过于夸张，不怕雷声也许有，但雷打得衣服都焦了，人却没事就不真实；打中夏侯玄没伤着，其书写如故更不靠谱。在裴松之的注中就说，故事有另一个版本，夏侯玄是站在树下，霹雳打中树，夏侯玄“颜色不改”。这还差不多，但不够传奇。世说新语终究是走自媒体八卦流，不耸人听闻没有点击量和转发数。  
- *面不改色* 发展到后来，在苏洵那里就是“泰山崩于前而色不变，麋鹿兴于左而目不瞬”（《权书•心术》）。它和喜怒不露于形色是两种气量，一是不为生死所扰的强大无惧，一是性格圆融涵养深沉。  

## 6.4  
>戎七岁，尝与诸小儿游。看道边李树多子折枝。诸儿竞走取之，唯戎不动。人问之，答曰：“ 树在道边而多子，此必苦李。”取之，信然。  

这个故事令人费解，好像放错位置，应该在“夙慧”。难道是说王戎不和小朋友一起去抢李子，显得从容不迫，这算是雅量？  
我是浙江人，小时候看过一本民间故事《鸳鸯湖》，大意是说西施被献夫差，路过嘉兴桐乡，尝过路边的李子，吃李时留下了指甲印，所以桐乡的携李从此以后有了“西施爪痕”。那时我就想，不是说路边的水果都是苦的吗，西施怎么就能吃到甜李子啊？后来涉略民间故事文本学，对解释性神话颇为着迷。  
年轻时候看过一篇经济学家的散文，大意是说为什么欧美路边的橘子没人摘，而南美路边的果树没果子，主要是市场供给的原因，和道德素质无关。  

## 6.5  
>魏明帝于宣武场上断虎爪牙，纵百姓观之。王戎七岁，亦往看。虎承间攀栏而吼，其声震地，观者无不辟易颠仆。戎湛然不动，了无恐色。  

- *魏明帝*：曹叡，曹丕和甄后之子，死于239年正月初一，当时王戎五岁（234年生），故事存在疑问。  
- *宣武场*：原洛阳城北，练兵操场。《水经注》中说：“大夏门东宣武观，凭城结构，南望天渊池，北瞩宣武场。”  
- *承间*：乘机。《三国志•武帝纪》裴松之注:“太祖被甲婴胄，亲巡将士，明劝赏罚，众乃复奋，承间讨击，贼稍折退。”  
- *辟易*：退避。《史记•项羽本纪》：“是时，赤泉侯为骑将，追项王，项王瞋目而叱之，赤泉侯人马俱惊，辟易数里。”  

决不恐惧是魏晋第一流人物的标志，亚里士多德也说过，超越了恐惧的人才能获得真正的自由。杀人放火的亡命之徒不是无惧，苏轼说，“拔剑而起，挺身而斗，此不足为勇也。天下有大勇者，卒然临之而不惊，无故加之而不怒”，他在乌台诗案中也恐惧，一番生死经历后，“平时种种心，次第去莫留”，精神力量回蓝见长，终于写出了“谁怕？一蓑烟雨任平生”，此心正大光明，于是“山头斜照却相迎”。  

## 6.6  
>王戎为侍中，南郡太守刘肇遗筒中笺布五端，戎虽不受，厚报其书。  

- *刘肇*：《晋书》无传，但有一段文字说：“右长史、杨丘亭侯刘肇，便辟善柔，苟于阿顺”，王戎从征吴前线立功回朝，当了侍中，善柔、尊重领导的原荆州下级官员太守刘肇送东西表示祝贺。  
《晋书》的作者们觉得，堂堂一个省市级官员给相当于宰相的高官送礼，五端（五匹，每端二丈以上）布怎么拿得出手啊，这根本谈不上行贿，顶多也就是人情往来，就改成了“五十端”。当年戴笠回浙江，一买金华火腿几千只，回重庆送何应钦400只，送蒋介石4只。无非是何应钦是军事总长，重礼以表诚意，蒋介石简朴，意思一下以表敬意和戴某人的清廉。  
- *筒中笺布*：一种四川产的筒装细麻布，据说整匹布能卷置于一节竹筒之内，在当时比较名贵，“一端数金”。古时候的“金”有时候指黄金、有时候白银，有时候黄铜，不好琢磨。  
- *厚报其书*：指回信表示深切的感谢。  

世说故事里，有好几段记录王戎吝啬爱财的小故事，但也有他不爱财的记录，譬如“德行”中讲，他父亲王浑“卒于凉州，故吏赙赠数百万，戎辞而不受，由是显名”。这个故事也说他不接受贿赂，但放在“雅量”就有点费解。也许我们要从刘孝标的注中去体会：  
>“戎报肇书，议者会以为讥。世祖思之，乃发口诏曰：‘以戎之为士，义岂怀私？’议者乃息，戎亦不谢。”  

《晋书》中进一步解释司马炎的话，帝谓朝臣曰：“戎之为行，岂怀私苟得，正当不欲为异耳！”  
这两段话的大意是说，这桩受贿案虽然王戎没收礼，没罪，但当时的“清议”“月旦”舆情发酵，键盘侠们指责王戎没有像杨震那样“天知地知你找我”般“方正”，他居然还写了深情厚貌的感谢信，其中肯定有猫腻！这时候司马炎发话：像王戎这样品行的人，怎么可能会怀有私心，苟且贪婪呢？他不过是不想做特立独行的事让人难堪罢了。于是舆情平息了，王戎也没发微博解释道歉。  

不收礼，但写信感谢算雅量。也许不道歉算雅量，不像高铁霸座男装模作样。对于大度的人，遇到事情道歉并不难，不道歉有点难。  

## 6.7  
>裴叔则被收，神气无变，举止自若，求纸笔作书。书成，救者多，乃得免。后位仪同三司。  

- *王 裴* 裴楷，王戎 年岁相仿（裴小三岁），皆官宦之后，当时齐名。钟会说：裴楷清通，王戎简要，都是吏部郎的候选人。  
裴楷的二儿子裴瓒娶外戚杨骏之女，司马炎因为丈人杨骏没有儿子，能力又差，一帮子大臣看不起他，估计他会老老实实，不至于做霍光和王莽，就选他作为笨蛋儿子司马衷的辅政大臣。谁料到杨骏统摄朝政、总领百官后，正因为别人长期看不起他，决心奋发图强，大干一番事业，“因辄改易公卿，树其心腹”，“多树亲党，皆领禁兵”，于是“公室怨望，天下愤然”。最终没两年祸起萧墙，皇后贾南风勾连宦官和秘书人员等发起宫廷政变，一举诛杀杨骏亲戚、党羽等达数千人，西晋立刻进入混乱破溃的境地。裴楷因为姻亲关系，加上尚书仆射荀恺举报陷害，也被双规。裴楷要来纸笔写自白书兼救援书，来博取同情，而后侍中傅祗“证楷无罪，有诏赦之”。  
领导干部被收监后写材料，以前有写诗歌咏志的，有写遗言抗争的，有写著作不朽的……现在估计都是在准备法庭上的忏悔书吧，“我是农民的儿子”“清晨，听到树上响起清脆的鸟鸣声，呼吸到窗外涌进来的新鲜空气，我的心跳就会加速，忍不住泪水直流，想起那些不堪回首的往事”……  

## 6.8  
>王夷甫尝属族人事，经时未行，遇于一处饮燕，因语之曰：“近属尊事，那得不行？”族人大怒，便举樏掷其面。夷甫都无言，盥洗毕，牵王丞相臂，与共载去。在车中照镜，语丞相曰：“汝看我眼光，迺出牛背上。”  

- *王衍* 和 *王导* 是远房兄弟。王衍256年生，王导276年生。一个是西晋的宰辅，一个是东晋的宰相。从故事情节上看，王衍那时候还不是高官，所以被族人侮辱。  
- *属*：嘱咐，托人办事。  
- *饮燕*：宴饮。  
- *那得不行*：怎么还没办啊？  
- *樏*：食盒。  
- *迺出牛背上*：“迺”同“乃”，这句话费解，但后来的书籍历来引用如此。譬如黄庭坚有句诗夸朋友说：“往来涧谷中，神光射牛背”，南宋董更论王安石书法说：“萧散简远，如高人胜士，敝衣破履，行乎高车驷马之间，而目光已在乎牛背矣”，起码在宋代人的的眼里，这句话是不难理解的，大意就是说：我不在乎，我的情绪没有受到被打的影响，我的注意力在牛背上。用“目光在牛背”来形容高人胜士的萧散简远。  
但为什么要看牛背上呢？这是什么梗？王衍坐的是牛车，当时确实以乘马车为耻，以乘牛车为荣，难道王衍的潜台词是我的情绪像牛车一样平稳，或者是说，现在我的注意力在坐车上了，被打的事情我没放心上？又或者是说，打我的人不过是一条蛮牛，我早就超越了他？当然，也不能排除王衍在使用《庄子•逍遥游》里的典故，“今夫斄牛，其大若垂天之云。此能为大矣，而不能执鼠”，我是牛人，和老鼠计较什么！  
今人李天华说，牛背疑为是奴辈的音讹，这很难解释“眼光”。  

## 6.9  
>裴遐在周馥所，馥设主人。遐正戏，不时为饮。司马恚，因曳遐坠地。遐还坐，举止如常，颜色不变，复戏如故。王夷甫问遐：“当时何得颜色不异？”答曰：“直是暗当故耳。”   

- *裴遐*：裴绰之子，裴楷之侄，王衍的女婿。  
- *周馥*：曾任尚书郎、司隶校尉、河南尹、平东将军、镇东将军等，“振缨中朝，素有俊彦之称”。  
- *设主人*：不通，设酒作主人。  
- *戏*：下围棋。  
- *司马恚*：当时的饮酒风俗，因为是分案吃饭，就专门设酒保给你倒酒。因为在周馥军中，所以由司马倒酒，而裴遐不喝，肯定是一种比较失礼的行为。就像石崇请王敦喝酒，不喝就斩行酒的美人，王敦不为所动。我曾经看到媒体报道，王岐山去河南某县，县里的办公室主任拿起一杯酒顶在头顶，跪在地上说，你不喝我就不起来。王岐山不屑一顾。他说，你喜欢跪着就跪着吧，继续和其他吃饭的人谈笑风生。也许自古以来河南劝酒恶俗一贯如此，绵延近两千年。  
- *暗当故耳*：费解，似乎当时的书籍中都没有出现过“暗当”的用法，后来有人提出是“默默承受”的意思，这缺乏旁证，也没有现在的方言可以引证。也有人说暗当就是斗将，暗和斗繁体字比较接近，意思是说，我和一个武夫计较啥啊。  

## 6.10  
>刘庆孙在太傅府，于时人士多为所构。唯庾子嵩纵心事外，无迹可间。后以其性俭家富，说太傅令换千万，冀其有吝，于此可乘。太傅于众坐中问庾，庾时颓然已醉，帻坠几上，以头就穿取，徐答云：“下官家故可有两娑千万，随公所取。”于是乃服。后有人向庾道此，庾曰：“可谓以小人之虑，度君子之心。”   

- *刘庆孙*：刘舆或刘玙，“闻鸡起舞”刘琨的哥哥，汉室宗亲，世代官宦，年少成名，两人和石崇、潘岳等人同为“金谷二十四友”之一，当时有吹捧他们两兄弟是洛阳杰出人物的口号，“洛中奕奕，庆孙越石”。西晋五胡乱华时，刘琨能在北方作为敌后的“并州刺史”有一番作为，主要是依靠刘舆向太傅司马越举荐，从而“何意百炼钢，化为绕指柔”的刘琨名垂史册。  
- *太傅*：司马越。306年，晋惠帝封司马越太傅、录尚书事，11月，晋惠帝去世，晋怀帝司马炽即位，委政事于司马越。刘舆本来是司马虓手下做事，为魏郡太守，司马虓去世后，到了司马越那里。一开始有人对司马越说：“舆犹腻也，近则污人。”（大意是说，刘舆是油腻男，接近他就会被弄脏），所以一开始司马越”“疏淡用之”。不过“是时军国多事，每会议，自潘滔以下，莫知所对。舆既见越，应机辩画，越倾膝酬接，即以为左长史。越既总录，以舆为上佐，宾客满筵，文案盈机，远近书记日有数千，终日不倦，或以夜继之，皆人人欢畅，莫不悦附。”人家有真本事，又有白加黑的苦干精神，立刻脱颖而出，当了司马越的秘书长。司马越执政后，“疑朝臣贰己”，一方面把宫里的武官侍卫罢免掉，换成自己的人，“时殿中武官并封侯，由是出者略尽，皆泣涕而去”，一方面杀了中书监缪播、尚书何绥、散骑常侍王延、散骑侍郎高韬等，这些人的罪名都是谋反和妄议中央之类的，“诬帝舅王延等为乱”，“散骑侍郎高韬有忧国之言，越诬以讪谤时政害之”，其中必定包含刘舆的出谋划策。  
- *庾子嵩*：庾敳，见4.15，4.75。他称《庄子》“了不异人意”，也就是说自己是和庄子差不多的人物。在“八王之乱”中，“是时天下多故，机变屡起，敳常静默无为”，他当时在司马越手下任军谘祭酒，相当于参谋长，但“常自袖手”，不做事就不犯错误，“无迹可间”，没有什么好用来挑拨离间的。当然，像庾敳这种当官无所作为、贪财无节操的人，也许不是因为忧患避祸，而是一种玄学的本性表现，老庄理论发展到官员的具体生活中，就会大量出现“处官不亲所司，谓之雅远；奉身散其廉操，谓之旷达”的丑陋现象，如同一个理论上追求公正平等的为人民服务的政权会自然演变成集权主义。  
- *换*：借贷。庾敳是当时的富翁，多次被人抨击聚敛钱财。  
- *帻*：头巾，汉代成年男性正规场合头上带冠，职位卑下的执事者带巾，到了晋代，正规场合带巾成为常态，并且巾子的形制在王公贵族和平民百姓之间并没有明显区别。这段“帻坠几上，以头就穿取”是闲笔，但真是这种闲笔细节，体现出《世说新语》作者很高的写作修养。作品依靠细节而还原真实，绘出动态图，使笔下的人物活起来，引发读者想象空间和共鸣情感。细节使作品表现得精致和熠熠生辉，使作者具有鲜明个性风格，细节决定小说的价值。  
- *徐答云*：庾敳在酒醉中依旧深思熟虑。  
- *娑*：今人刘盼遂认为，北方人“多读三如沙”，“娑”也是当时的方言。在唐代成书的《晋书》直接把娑删了，说明那时候也搞不清楚娑是什么意思了。  

刘舆和庾敳的矛盾，不一定是个人恩怨，而可能是务虚派和实干派的分歧，务虚是君子，实干是小人。  

## 6.11  
>王夷甫与裴景声志好不同。景声恶欲取之，卒不能回。乃故诣王，肆言极骂，要王答己，欲以分谤。王不为动色，徐曰：“白眼儿遂作。”  

魏晋玄学起先是夏侯玄、何晏、王弼等形成的正始名士和竹林七贤，正始十年（249年），司马懿发动高平陵事变，“同日斩戮，名士减半”，接着10来年司马师、司马炎等又诛杀吕安、嵇康等人，正始之音绝焉。到了元康年间(公元291—299年)，魏晋玄学的第二次浪潮起动，当年残余的正始、竹林名士和他们的后辈此时已成为朝中重臣。张华、裴頠、裴楷、王戎四人“并管机要”，在他们的推动下，玄学思潮风靡西晋士族社会，“朝野翕然，谓之‘一世龙门’矣。累居显职，后进之士，莫不景慕放效。选举登朝，皆以为称首，矜高浮诞，遂成风俗焉”，年轻一代玄学士人走上了历史舞台，史称元康玄学。其中包含王衍、乐广为首的“贵无”派，裴頠、欧阳建以及“金谷二十四友”形成的“崇有”派。彼此意见分歧主要一是世界统一本质是有还是无，二是对生活实践是“任自然”还是“重名教”等。  
王衍的“贵无”派，既然贵无，就无著述，所以他们的思想现在保存的资料很少，但大意总是“无”是世间万物的共性，而且我们可以从“崇有”著作中获取“贵无”的信息。譬如裴頠批评王衍他们 “薄综世之务，贱功烈之用，高浮游之业，埤经实之贤”，批评他们“心非事也，而制事必由于心，然不可以制事以非事，谓心为无也。匠非器也，而制器必须于匠，然不可以制器以非器，谓匠非有也”。大意是说贵无派崇尚不干政务经济实事，认为心思的本质是无之类的。而裴頠、裴邈认为，有是客观存在，本体就是有的存在方式，无是有发展到消失的一种状态。世界本源“道”就是世界自身，道是万物的统一体，离开自生也就没有本体。有的存在，必须依靠自身的行为去获取外资，而不是靠无为，不垂钓就不能钓到鱼，靠静拱，也抓不到天上的禽鸟。真正的贤人君子应该“惟夫用天之道，分地之利，躬其力任，劳而后飨。居以仁顺，守以恭俭，率以忠信，行以敬让，志无盈求，事无过用，乃可济乎！故大建厥极，绥理群生，训物垂范，于是乎在，斯则圣人为政之由也”  
裴邈裴景声是裴頠的远房堂弟，“从兄頠器赏之。每与清言，终日达曙”。6.10说刘舆和庾敳的矛盾，也许类似本则裴邈和王衍在玄学理念分歧而造成冲突，“志好不同”。  
- *恶欲取之*：费解。大多数人理解成王衍要裴邈任命做官（取之），裴邈不肯，但没办法拒绝朝廷。所以他决定上门挑事，最好两人对骂互相伤害，然后都遭人弹劾。谁想到王衍早就在女婿裴遐那里学了“颜色不变”一招，不为动色。  
- *白眼儿遂作*：有点费解，大意是说，你这个白眼儿（一向自视甚高的人）这下子发作了吧。  

## 6.12  
>王夷甫长裴成公四岁，不与相知。时共集一处，皆当时名士。谓王曰：“裴令令望何足计！”王便卿裴。裴曰：“自可全君雅志。”   

这是王衍、裴頠人生中的第一次相遇。  
- *裴頠* 见2.23等，他是司空裴秀的儿子，司徒王戎的女婿，皇后贾南风母亲郭槐的侄儿，儿子裴该是晋惠帝司马衷的女婿。裴頠34岁被司马伦所杀，谥号“成”。  
王衍是王戎的堂兄弟，看似比裴頠高一辈，但王衍妻子是郭槐的堂侄女，女儿是晋惠帝的儿媳（太子妃），这又是平辈了。  
王衍和裴頠在玄学思想上有分歧，前已介绍。从从政经历看，裴頠在政治上非常努力，尽忠职守，当时人认为他虽贵为皇亲，但是凭能力居高位的，生怕他离开中央（尚书左仆射，侍中），“雅望素隆，四海不谓之以亲戚进也，惟恐其不居位”。而王衍做官就没干过什么事情，主要是引领文化领域的时代潮流。我们从中可以得出一个结论，一般来说，哪怕你当官不做事，只要在文化领域有成绩，足以名垂青史。即使你当官做事很努力，但在人的精神层面没有什么建树，也迅速被人遗忘。从这个意思上讲，功业都是过眼烟云，而文艺足以不朽。譬如现在几乎没有人记得裴頠，而清谈误国的王衍没有被忘记。  
- *谓王曰*：此句费解，裴令是指裴楷，和裴頠没有直接关系。难道裴令是裴公的笔误？但结合前后文，这句话引发歧义，可删去。  

高姿雅量的王衍以“卿”称呼裴頠，他居然主动挑事，在称呼上藐视裴頠，可见“主义”之争是原则性问题。而裴頠以奉承的反话予以回击：“我当然可以成全您的高雅情趣。”潜台词就是王衍你没有雅量——在口角之辨中，夸你对手的缺点，就是对对手宽厚的讽刺。  
而后两人多次在清谈中交锋，“王衍之徒攻难交至，并莫能屈”。辩论次数多了，不打不相知，王衍也开始夸裴頠。我们自然记得4.11和4.12的故事，“中朝时有怀道之流，有诣王夷甫咨疑者，值王昨已语多，小极，不复相酬答，乃谓客曰‘身今少恶，裴逸民亦近在此，君可往问’”，“裴成公作《崇有论》，时人攻难之，莫能折。唯王夷甫来，如小屈。时人即以王理难裴，理还复申”。  

宋代苏轼有句诗说：“说有陋裴頠，谈无笑王衍”，他是写给僧人的。魏晋南北朝以后，佛教成为中国最流行的文化思想，华夏民族被西方佛教文化所渗透和改造，玄学被指责为“陋”，被知识分子所“笑”，抛弃。佛教成为主流意识形态的局面，直到民国时候才被另外的西方文化思想所渗透和改造。然后世界和中国进入高速发展时期，我国的西方马克思主义又被西方自由主义冲击，近5年以来，复兴中华优秀传统文化的口号反复被提及，但我不知道什么才是优秀传统文化，就像玄学被佛学所替代一样，这个潮流不可逆转。  

## 6.13  
>有往来者云：庾公有东下意。或谓王公：“可潜稍严，以备不虞。”王公曰：“我与元规虽俱王臣，本怀布衣之好。若其欲来，吾角巾径还乌衣，何所稍严。”  

*庾亮*和*王导* 是东晋元帝、明帝和成帝三朝政坛的两大巨头，前已多次介绍。这个故事发生在苏峻之乱后，庾亮觉得因为是自己执政错误引发叛乱而引咎辞职，朝廷下诏安慰，庾亮就请求在外镇效命，出任为持节、都督豫州、扬州之江西宣城诸军事，陶侃死后。又代其为征西将军，兼领江、荆、豫三州刺史，都督七州诸军事。这样王导在中央，庾亮在地方。  
两人的执政思想有重大分歧，就譬如王导主张保守疗法，最终无非是安乐死，庾亮一定要动手术，老是做出在肉体上铲除政见不同者的举动，两人时有矛盾，明争暗斗。庾亮手握重兵，完全占了上风。王导虽然在中央，但总是觉得朝廷中还是庾亮在遥控指挥，内心愤愤不平。每当刮起西风的时候，王导就用扇子挡住灰尘，说：这是庾亮吹起的灰尘吧，身上都被弄脏了。在这种局面下，两人时有猜忌，边上打小报告的人也不断。譬如这次，有从湖北来的官员说，庾亮有到南京来的意思（杀回中央）。建议王导暗中早做准备。晋书中说，是陶侃的儿子陶称举报的：“南蛮校尉陶称间说南蛮校尉陶称间说亮当举兵内向，劝导密为之防。”  
- *稍严*：逐渐加强戒备。  
- *布衣之好*：当老百姓时建立的交情。王导大庾亮13岁，两人都是年轻时候就显贵了，说他们是布衣之交并非事实。王导无非就是引用典故来表明，我们心怀平民百姓之间那样的交情。言下之意可以理解成，达官显贵之间是没有真正友情，只有人情。现在的社会，成功的标志已经简化成有钱有权了，但是对于人的情感需要来说，深挚的友谊是人生最大的一种安慰。甚至有人说，飞黄腾达的路上一定点缀着破碎的友谊。即使是权贵，他们也向往并拥有宝贵的友谊，但你获得了什么，就会失去另外一些东西，这是没有办法的事情。  
- *角巾径还乌衣*：这里的角巾专指居家闲居戴的头巾，与布衣相应，辞官归故里的意思。  
《晋书》中说，庾亮和王导彼此暗中猜忌，孙盛就劝庾亮：王导常有世外之情、归隐之志，怎么会屈身做那些凡夫俗子的事情，必定有小人在挑拨离间。后来一查，是陶侃的儿子陶称在作祟，庾亮杀陶称。  
从实际效果看，庾亮不断做事，不断制造麻烦，今人田余庆评价说，庾亮起自外戚，无功晋室，而又措置乖谬，与王、谢家族的历史很不一样。庾氏家族不能比齐王、谢，是可以理解的。  

## 6.14  
>王丞相主簿欲检校帐下。公语主簿：“欲与主簿周旋，无为知人几案闲事。”   

不到30个字，主簿一词出现三次，表述累赘。“欲与主簿周旋”多余且费解。  
王导的办公室主任根据年度工作安排，要检查一段时间以来，办公室成员文件起草、批复等工作落实情况，做一次述职报告和查验。王导就语重心长地对主任说：犯不着和下属较真，去管人家的案头文书工作。  
东晋对于江南来说是个外来政权，建立在南方士族鼎力相扶的基础之上，但是南北矛盾和地域歧视不可能就此消除，譬如当时的歌谣就说：永嘉世，天下灾，但江南，皆康平；永嘉世，九州空，余吴土，盛且丰；永嘉世，九州荒，余广州，平且康。在南方人眼里，西晋流亡人士就是失败者。  
大量北方官员和流民涌入，各势力就在长江中下游展开了尖锐的斗争，东晋内部发生了很多次叛乱。王导认为，如果行政苛刻，一切按旧王朝的规矩办事，就会激发连续不断和大规模的反抗，从而动摇政权。执政者只有放弃原则，松弛律令，力图维持大族的力量均势，调和矛盾而不使之爆发，用满足大族的利益要求，来求得统治局面的稳定。譬如为了解决侨民问题，王导搞了“侨寄法”，就是政府搞两套班子，在各级行政单位内部，加设侨州、侨郡、侨县。侨州、郡、县有大量流亡官员，这是流亡士族的出路，虽然它肯定导致行政系统紊乱，加深人民苦难，但对东晋政权说来，却是安置流亡士族、缓和南北士族矛盾的重要措施，同时也保证了流民尽量少危害地方，避免当地人口和外来人口之间的强烈冲突。这些局面，我们只要看看现在欧洲一些国家因为接收难民，而造成极右势力获取大量选票的情况就了其大概了。  
王导不但反对主簿搞工作检查，对晋元帝司马睿318年搞整顿吏治的反腐运动也进行了否定。当时他召集各部巡视组会议，对顾和总结的“宁使纲漏吞舟，不以察察为政”大加赞赏。王导含含糊糊的、丧失原则的工作方法，“举贤不出世族，用法不及权贵”，“谓多养无赖足以维持天下”，当时还有歌谣说：“廷尉狱，平如底；有钱生，无钱死!”这让有责任感的人感到愤怒，陶侃、庾亮想有大作为的人就多次试图让王导下课， “王导务存大纲，不拘细目，委任赵胤、贾宁等诸将，并不奉法，大臣患之”，打造一个理想的政权。不过所有人都相继去世，334年，陶侃去世，339年，王导、郗鉴去世，340年，庾亮去世，这是当时政坛最重要的四个人物。  
- *周旋*：一般的意思是举止进退，在这里不好理解。  
- *无为*：无须、不必。“无为在歧路，儿女共沾巾。”  

## 6.15  
>祖士少好财，阮遥集好屐，并恒自经营，同是一累，而未判其得失。人有诣祖，见料视财物，客至，屏当未尽，余两小簏著背后，倾身障之，意未能平。或有诣阮，见自吹火蜡屐，因叹曰：“未知一生当著几量屐？”神色闲畅。于是胜负始分。  

- *祖约* 字士少，曾任侍中，民族英雄祖逖的弟弟。一直以来，东晋朝廷对北伐的祖逖没有什么支持，就听凭祖逖在前线和敌后与石勒作战。321年祖逖去世，朝廷也只能派祖约去接班，任平西将军、豫州刺史。  
- *阮孚* 字遥集，曾任侍中、吏部尚书、广州刺史。竹林七贤阮咸之子，见4.76“林无静树，川无停流”。  
- *经营*：料理。两个高官，一个要数钱数到手抽筋，一个要自己从事贱业做手工，都是为外物所累。  
- *未判其得失*：一个是贪财，一个无非是有个工艺品爱好，怎么会没有高低呢？这可能是因为玄学理论发展导致的逻辑。当时人认为，不为外物所累是圣人的理想人格，这个很难有人能做到。东汉以来的社会风气太虚伪了，“情伪万方”，我东晋人退而求其次，做人要讲真，讲自然，只要我们的言行是内心真实需求的反映，那么传统意义上的肮脏也不是肮脏，真就是美。就像现在有些网友开玩笑，真爱就是“死刑不亏，三年血赚”。虽然从当代伦理视角上看，贪财是贪婪的欲望，好屐是精神层面的爱好，是两个性质完全不同的事物，但在当时的玄学思想看来，要尊重个性的丰富性、追求的多元性和体验的自主性，两个都是可以表达丰富个性、创造力和生命力的东西，本质上是一回事。  
- *料视*：即屏当，即收拾，见1.29“恒与曹夫人并当箱箧”。  
- *余两小簏著背后，倾身障之，意未能平*：把剩下没有整理好的两小箩（）金银财宝放在身后挡住，神色很不自然。  
- *吹火蜡屐*：明代谢肇淛的《五杂俎》中说：汉时着屐尚少，至东京末年始盛。应劭《风俗通》载：“延嘉中，京师好着木履。妇人始嫁，作漆画屐，五色采为系。后党事起，以为不祥。至晋而始通用。阮孚至自蜡之，谢灵运登山陟岭，未尝须曳离也。”说明在晋代，木鞋子其实是很讲究的，有审美意义。  
- *未知一生当著几量屐*：“量”就是两只，量词。颜师古《匡谬正俗》：或问曰：“今人呼履舄屐之属一具为一量，于义何邪？”答曰：“字当作‘两’，《诗》云：‘葛屦五两’者，相偶之名，履之属二乃成具，故谓之两，两音转变，故为量耳。’”  
当代社会的风气，一般是把有钱当做成功的标志，消费主义把物质财富的享用和高消费当做人生的目的，买、买、买似乎极大地体现了人的自由，但是对金钱的崇拜恰恰扼杀了本应十分丰富的个性。阮孚的高明之处，在于他能够把爱好当做品味人生的一种途径，以此发出人生不永的感慨，其实质是超越了物欲的牵绊，而是通过它迈向了精神高地，达到了庄子在《秋水》中所说的“乘物以游心”的境地，活出了“了无尘埃”的智慧，“于是胜负始分”。  

## 6.16  
>许侍中、顾司空俱作丞相从事，尔时已被遇，游宴集聚，略无不同。尝夜至丞相许戏，二人欢极。丞相便命使入己帐眠。顾至晓回转，不得快熟；许上床便咍台大鼾。丞相顾诸客曰：“此中亦难得眠处。”  

- *许璪* 字思文，后任侍中、吏部侍郎。*顾和*字君孝，官至尚书令，死后追赠司空。《晋书-顾和传》中说，317年，王导任扬州刺史，顾和当时是王导的属官，见2.33等。顾和是东吴丞相顾雍的后裔，江南官宦大家族，许璪的祖父和父亲仅仅当过县令，虽然许璪在这次的表现中明显比顾和要胸怀高远，但从家庭背景考虑，顾和的成长空间更大一些。   
- *遇*：知遇。两个人都被王导所赏识。两个人都是江苏人，一个是高门子弟，一个是下层官僚子弟，王导有意识地任用、知遇、提拔他们，带他们出席各种场合表示姿态，以此作为缓和南北人士之间矛盾的一种举措和证明。
- *丞相许戏*：在王导的府邸里清谈。许：处所。戏：往往是清谈的意思。  
- *极*：疲劳。  
- *至晓回转*：顾和心思重，可能觉得不符合礼仪，到了天亮还辗转反侧。
- *熟*：熟睡的缩略语，快熟应作“熟寐”。  
- *咍台*：打呼噜的声音。唐代陆德明《经典释文》中说：‘诶诒，司马云解倦貌，李颐云失魂魄也。诒音台。’诶诒同从□声，咍台即诶诒也。之部，叠韵连语。”  
- *此中亦难得眠处*：费解。难得即难能。大意也许是王导在夸许璪心无挂碍：在我这里能熟睡不容易啊。  

一帮子人晚上在领导家聊天谈哲学，然后两个小年轻因为时间晚了就直接睡在领导家，领导继续和其他客人聊天到天亮，这是当时上流社会的风气，在现在是不可想象的。  

## 6.17  
>庾太尉风仪伟长，不轻举止，时人皆以为假。亮有大儿数岁，雅重之质，便自如此，人知是天性。温太真尝隐幔怛之，此儿神色恬然，乃徐跪曰：“君侯何以为此？”论者谓不减亮。苏峻时遇害。或云：“见阿恭，知元规非假。”  

- *庾亮* 风格峻整，动由礼节，闺门之内，不肃而成……时人皆惮其方俨，莫敢造之”，就是说他性格方正，一举一动都比较稳重严肃。  
- *假*：造作？这个不好理解，文中两个“假”都应该是“佳”。当时人认为，性格深沉严肃是优点，即使矫情而故作深沉，也可以算是优点。  
- 庾亮的大儿子叫*庾彬*，小名阿恭，在苏峻之乱中被杀。  
317年，刘琨派外甥、左长史温峤到南京拥戴司马睿，王导安排温峤做太子司马绍的侍从官（中庶子），这时候和中书郎、东宫侍讲、司马绍的小舅子庾亮成为好朋友。温峤性格放诞随便，据说当时晚上经常去秦淮河上的船坊上赌钱，常常付不起赌资以致被庄家扣住，温峤就大喊大叫，叫人向庾亮借钱赎自己，庾亮也都非常爽快。  
- *隐幔怛之*：躲在帷幕里突然跳出来吓小朋友。朱熹《答林择之》：人欲横流，天理几灭。今而思之，怛然震悚。  
- *君侯*：汉时对列侯的尊称，后泛指尊贵者。  
- *知元规非假*：看到了庾彬，才知道父亲庾亮不够好，青出于蓝而胜于蓝的意思。  

## 6.18  
>褚公于章安令迁太尉记室参军，名字已显而位微，人未多识。公东出，乘估客船，送故吏数人，投钱唐亭住。尔时吴兴沈充为县令，当送客过浙江，客出，亭吏驱公移牛屋下。潮水至，沈令起彷徨，问牛屋下是何物，吏云：“昨有一伧父来寄亭中，有尊贵客，权移之。”令有酒色，因遥问：“伧父欲食饼不？姓何等？可共语。”褚因举手答曰：“河南褚季野。”远近久承公名，令于是大遽。不敢移公，便于牛屋下修刺诣公，更宰杀为馔具。于公前鞭挞亭吏，欲以谢惭。公与之酌宴，言色无异，状如不觉。令送公至界。  

- *诸公*：褚裒字季野，河南阳翟人，见1.34。328年苏峻之乱时，被车骑将军郗鉴聘为参军。“裒少有简贵之风，与京兆杜乂俱有盛名，冠于中兴。”  
- *章安*：今浙江省台州市椒江区。  
- *人未多识*：按照正常语序应该是人多未识，大多数人人还不认识他（仅仅听说过名字）。  
- *东出*：不好理解，椒江在南京、杭州的东南面，如果去南京，路线有点问题，照道理是沿着钱塘江北上，不过古时候的具体旅行路线我不清楚。甚至这篇文章本来就有问题，可能第一句话和后文没有任何关系，只不过是交待时间段而已，大体意思是褚裒当时的职务是参军。有一次要告别故吏数人，而不一定是故吏送他去上任。在南宋《咸淳临志》卷之八十九，直接把“东出”给去掉了  
- *估客船*：商客船。费解，估船不难理解，就是商船，陆游《晓出城东》：“渺渺长江下估船，亭亭孤塔隐苍烟”，所以在《咸淳临志》的表述是“公乘估船，送故吏数人，投钱塘亭”。文章加个“客”干啥，累赘。也许正因为是坐商船，亭吏就不知道褚裒的官员身份。   
- *送故*：当时官员离任送别的腐败风气。东汉以来，官场“送故”活动逐渐发展，到了东晋，朝廷还出台了“送故之格”，针对送故做出一些限定，“送故”由汉代的潜规则发展为被摆上桌面公开谈论的明规矩，成了官员离任待遇和常规收入。一是由官府出面或是由故吏自发组织，将大额金钱、物资转送给离任长官，甚至以大量人力为离任长官送行。二是长官在任上亡故或是离职后亡故，原官府或故吏赙赠大额金钱。《晋书》中说，东晋范宁将出为豫章太守时，向晋孝武帝上陈时政云：“又方镇去官，皆割精兵器仗以为送故，米布之属不可称计。”就是说官员离任后，就连兵马都可以带走。还有士兵（兵户）也可以送，“送兵多者至有千余家，少者数十户。既力人私门，复资官廪布。”范宁继而提出，送故不要太过分了，时间不能再长了，因以三年为期，“送故之格，宜为限制，以三年为断”。“送故”到东晋发展为高潮，主要是举荐、门阀制度的配套产物，上下级官员彼此间的依附度加深，官场日益腐败。虽然“送故”到了后来逐渐消亡，但专制特权社会的这种腐败“礼节”和上下级官员、官商之间的人身依附不可能得到根本性的改变，类似如当下披露的某些官员及其亲属的婚丧嫁娶和节日问候礼金、礼物数目可以达到惊人的地步。  
- *钱唐亭*：杭州古称钱塘县，据南朝宋刘道真《钱唐记》中说：“防海大塘在县东一里许，郡议曹华信家议立此塘，以防海水。始开募，有能致一斜土者，即与钱一千。旬月之间，来者云集，塘未成而不复取。于是载土石者皆弃而去，塘以之成，故改名钱塘焉。”不过这无非是地名的解释性传说，没有可信度，仅仅反映民众对智慧型欺诈故事的偏爱。亭不是亭子，它在汉代是一级政府组织，类似于乡镇，“秦汉之制，十里一亭，亭有高楼，所以候望”，爵位有乡侯、亭侯、县侯等；也有时候是管治安和交通的的政府单位，《汉书》记载：“亭有两卒，一为亭父，掌开闭扫除；一为求盗，掌逐捕盗贼”。在魏晋时期，亭往往就是指国家开设的旅馆，相当于国营的对官民都开放的驿站，《太平御览》引《风俗通义》中说：“亭，留也。今语有亭留、亭待，盖行旅宿食之所馆也。”今人严耕望综合了亭的功能，他在《中国地方行政制度史》中认为：亭基皆高出地面，且树华表以识衢路；亭门有塾，检弹人民；亭内有正堂，以供重要官吏居止；又有高楼，以供候望盗贼；此其形制之大略也。  
这句话表述还是费解，其实正常表述应该是“公与送故吏数人，乘估船，投钱唐亭往”，但是问题在于既然一帮子人住在官府设置的交通客栈，难道客栈不用身份登记，工作人员看不出人群中站在C位的褚裒的官员气派？  
- *浙江*：钱塘江。钱塘江曲折，所以叫之江，浙江。  
- *客出*：费解，应该是客至啊，要么出有到达的意思，类似于出席、出勤。汉语中一个词有正反两个意思也不鲜见，我看过《管锥篇》，开头就讲了这个现象，大概是说“易”，既有变的意思，也有不变的意思。在古文中，譬如受，既有接受，也有给予，择，既有选择，还有抛弃。当然在现代汉语中是这种现象消失了。这样说来，前面的“东出”也许就是东至的意思，“公乘估船东至”，褚裒乘商船打东边来。不过 “出”作为“至”来理解的用法罕见，也没必要。  
- *何物*：有其他版本说是“何物人”，何等人。  
- *伧父*：当时南方人蔑称北方人，粗俗之人。北方人称南方人南蛮、南貉。这种以地域歧视寻找优越感的做法比比皆是，在先秦故事中，就没有南方北方的歧视，而是群嘲宋国——那里笨蛋居多，原因无非是宋国是殷商亡国后的封地。  
- *遽*：惶恐。  
- *移公*：让褚裒移驾。  
- *修刺*：置备名帖，通报姓名。  

《世说新语》里有不少偶遇的故事，在小说中，偶遇也是一个常见桥段，在旅馆相遇更是展开情节很好的手段。陌生人能够较长时间待在一起，作者就可以安排各种冲突，我们更多的是在玄幻武侠小说中看到受侮辱的人拔剑一怒，血溅十步，但那些仅仅是传奇故事。也有人说，故事里的沈充是条变色龙，前倨后恭。但这样理解未必妥当，县令听潮水而起，随性请亭吏认为的卑贱之人一起吃饼。得知实情后赔礼道歉，教训了手下的亭吏，这也是大多数人很难做到的。  


## 6.19  
>郗太傅在京口，遣门生与王丞相书，求女婿。丞相语郗信：“君往东厢，任意选之。”门生归白郗曰：“王家诸郎亦皆可嘉，闻来觅婿，咸自矜持，唯有一郎在东床上坦腹卧，如不闻。”郗公云：“正此好！”访之，乃是逸少，因嫁女与焉。  

- *王导*的祖父*王览*是*王羲之*的曾祖父，*王览*是冬天砸冰给继母抓鱼吃的*王祥*的弟弟。  
- *郗太傅*：郗鉴，见1.24。他当过太尉，不是太傅。这个故事应该在323年前后，郗鉴要么当时以尚书令的身份统领各军御王敦之乱，要么王敦之乱后任车骑将军、都督徐兖青三州军事、兖州刺史、假节，出镇广陵（今扬州）。在王敦之乱这个节骨眼上，郗鉴和王家联姻肯定是一种政治手段。  
- *逸少*：王羲之字逸少。王羲之的生卒年有争议，这次联姻也是说明王羲之到底是什么时候出生的证据之一。王羲之曾经写过“羲之不天，夙遭闵凶，不蒙过庭之训”，也就是说王羲之在蒙学前父亲就去世了。王旷310年死于与刘聪的上党之战中。蒙学一般是4—6岁，所以我认为王羲之生于306或307年。  
坦腹东床很难算雅量，而是自然。《世说新语》中没有自然这一归类，但其中的很多故事都应该归之于自然，而不是德行、方正之类的。自然是当时最受追捧的审美趣味，后来也逐渐形成我们整个民族最高的审美趣味，它的来源无疑是《道德经》中说的“人法地，地法天，天法道，道法自然”和《庄子》中所说的“性之动，谓之为；为之伪，谓之失”“同乎无欲，是谓素朴，素朴而民性得矣”“朴素而天下莫能与之争美”。晋代郭象在《庄子》的注中也说：“天地以万物为体，而万物必以自然为正。自然者，不为而自然者也”。今人宗白华写了《论<世说新语>和晋人的美》，说晋人向外发现了自然，向内发现了自己的深情。他在文中反反复复强调晋人对自然的推崇。宗白华的话并没有讲透，晋人对内最高要求也是能够自然，而不是深情。  
关于当时人对自然的崇尚无需展开，只要讲一个小故事就能了其大概。南北朝时，汤惠休评价当时的诗人谢灵运和颜延之：“谢诗如芙蓉出水，颜诗如错采镂金”。“芙蓉出水”和“错彩镂金”，就是高雅和庸俗、自然真实与矫揉造作的对立体，有着高洁与污浊的区别，于是颜延之“终身病之”——这不仅仅是对他们俩作品的评价，而是人格的评价。颜延之扛不住，“每薄汤惠休诗”，搞互相伤害。  

## 6.20  
>过江初拜官，舆饰供馔。羊曼拜丹阳尹，客来蚤者，并得佳设。日晏渐罄，不复及精，随客早晚，不同贵贱。羊固拜临海，竟日皆美供。虽晚至，亦获盛馔。时论以固之丰华，不如曼之真率。  

- *舆饰供馔*：一般认为，舆就是与，皆，或者是多的意思。饰就是整治。“都供应酒宴招待恭喜的客人”。新官上任就要大摆宴席，这又是东晋制度腐败的例子。晋代触目惊心的全方位腐败是它迅速动乱，较快灭亡的根本原因。  
从晋武帝司马炎开始，这个朝代就打上了全面腐败的印记，制度保腐，上行下效，越演越烈。问题是，根据常识，制度腐败必定导致社会动荡，各阶层离心离德。那两晋为什么就不控制腐败呢？特别是万象更新的创业之始，怎么就放任自流呢？当时的人提不出“适当的腐败是社会经济发展润滑剂”（亨廷顿《变化社会中的政治秩序》）之类的理论，它也不是九品中正制和门阀制度的产物，而主要是文化的产物，是享乐主义占据主流意识形态的产物。享乐主义来自于长期的战乱，来自于道家学说和与之密切关系的玄学理论发展到一定阶段后的必然结果，文化导致了整体貌似“合理”的腐败。  
我们可以注意到，在东汉的乐府就开始歌唱及时行乐：“出西门，步念之。今日不作乐，当待何时？夫为乐，为乐当及时。何能坐愁怫郁，当复待来兹？饮醇酒，炙肥牛，请呼心所欢，可用解愁忧。人生不满百，常怀千岁忧。昼短而夜长，何不秉烛游……”到了晋代，这种及时行乐的歌声已经响彻朝野，譬如陆机把西门换成东门：“出西门，望天庭。阳谷既虚崦嵫盈，感朝露，悲人生，逝者若斯安得停。桑枢戒，蟋蟀鸣，我今不乐岁聿征。迨未暮，及时平，置酒高堂宴友生。激朗笛，弹哀筝，取乐今日尽欢情。” 官员一上任就大摆宴席，官员一离任就获钱百万，很多官僚视特权为自然，视民众如牛马，把官职当做享乐的平台，把嗑药的幻觉当做快乐的源泉，把毫无节制的欲望当做真实的人性，完全丧失了基本的道德观——如果人生是以快乐为目的成为共识，那么人类就是自取灭亡。  
- *羊曼*：山东人，堂祖父是羊祜，他和温峤、庾亮等都为所谓的“中兴名士”，“兖州八伯”之一，在苏峻之乱时不愿逃生被杀。  
- *竟日*：整天，终日。  
韩非子注解《老子》的“居其厚而不处其薄”“居其实不处其华”，指出它的意思就是“行情实而去礼貌也”，要去掉礼貌，赞美真情实感。周到精细就是太有心思，苦心伤神；来早的吃好的，来晚的吃差的，真率自然即雅量。  

## 6.21  
>周仲智饮酒醉，瞋目还面谓伯仁曰：“君才不如弟，而横得重名！”须臾，举蜡烛火掷伯仁。伯仁笑曰：“阿奴火攻，固出下策耳！”  

- 周顗周伯仁和周嵩周仲智（仲治）是两兄弟，前已多见。周顗“性宽裕”，周嵩“矜豪傲慢”“亮直”。周顗曾上表自称“臣退自循省，学不通一经，智不效一官，止足良难，未能守分，遂忝显任，名位过量”，周嵩曾上表自称“四凶在朝，碌碌之臣”。  
- *还面*：估计是当时的口语，翻脸。可删。  
- *蜡烛*：汉代以前的烛是指火把。汉代蜡烛还很罕见，主要用油灯。在古代蜡烛基本都是珍贵的东西，曾经是皇帝赐给亲信和大户人家结婚时偶尔使用的物品，南北朝时庾信写过“洞房花烛明，燕余双舞轻”，中唐韩翃“春城无处不飞花，寒食东风御柳斜。日暮汉宫传蜡烛，轻烟散入五侯家”。民众普遍使用蜡烛是民国以后的事了，即使上世纪70年代，没电的时候我们还是使用油灯而很少蜡烛。  
- *阿奴*：当时对家中男孩子的昵称。《孙子兵法》中说：“上兵伐谋，其次伐交，其次伐兵，其下攻城”， 在“火攻”篇中说：“主不可以怒而兴师，将不可以愠而攻战”。周顗的大意估计是：阿弟你因为名声不如我而发怒用火攻，这个做法本来是出下策哦。  

## 6.22  
>顾和始为扬州从事，月旦当朝，未入顷，停车州门外。周侯诣丞相，历和车边，和觅虱，夷然不动。周既过，反还，指顾心曰：“此中何所有？”顾搏虱如故，徐应曰：“此中最是难测地。”周侯既入，语丞相曰：“卿州吏中有一令仆才。”  

- *顾和*：前已多见，王导任扬州刺史时，任命他和许璪为从事。  
- *月旦*：每月的初一。古时候朝廷初一和十五是大朝会，而且时间很早，大都是凌晨4、5点。王导位列三公，有开府的权力。  
- *未入顷*：今人吴金华认为，顷就是刻、际，还没进去的时候。  
- *州门*：应该是指府门。  
- *觅虱*：嵇康《与山巨源绝交书》中写自己“性复多虱，把搔不已”。鲁迅曾经说，魏晋名士多服用五石散，“皮肤易破，不能穿新的而宜于穿旧的，衣服便不能常洗。因不洗，便多虱。所以在文章上，虱子的地位很高，‘扪虱而谈’，当时竟传为美事”。而周作人《虱子》和钱钟书《管锥篇》曾引用各种笔记专门谈论虱子的问题，他们也许对鲁迅的观点不以为然，在当代以前，即使魏晋以前还是以后、古今中外，虱子也是人生的伴侣之一，是过去人们卫生条件不好的产物，而不是名士的专利。  
- *夷然不动*：周顗当时是尚书左仆射、吏部尚书，而顾和在大庭广众之下抓虱子没感到难为情，认识他但没有表示出必要的礼貌，周顗就有点纳闷，回过头来问顾和：你心里面装的是什么啊？  
- *此中最是难测地*：《礼记-礼运》“人藏其心，不可测度也，美恶皆在其心，不见其色也”，意思是说，人会隐藏自己的心思，旁人不能揣度，喜欢赞美和厌恶的情感都藏在心中，看不到也听不见。《庄子-杂篇-列御寇》“凡人心险于山川，难于知天。天犹有春秋冬夏旦暮之期，人者厚貌深情”，大意是说，人心比山川还要险峻，知人比知天还难。天还有春夏秋冬早晨晚上的周期变化，可人深藏其思想感情，不流露于外表或言辞。顾和的意思应该是指我的心思宽广难测，因为在《世说新语-排调》中有个类似的故事，“王丞相枕周伯仁膝，指其腹曰：‘卿此中何所有？’答曰：‘此中空洞无物，然容卿辈数百人。’”空洞无物就是难以测度的意思。  
- *令仆*：尚书令和尚书仆射等官职，宰相的才能，周顗赞赏顾和的自然从容和思维敏捷，他认为这是当宰相的基本素质。周顗的风采固然让当时的人赞誉，但其见识却让用“火攻”的弟弟周嵩批评，在稍后的“识鉴”中有这么一段言论：  
>有一次周顗全家喝酒，这三兄弟的母亲自豪地说：“我们原是渡江过来，无所依托，没料到你们兄弟个个都显贵了，站在我眼前，我还有什么忧虑的呢！”周嵩哭着说：“恐怕不像您说的那样。周顗志大而才疏，名声大却见识糊涂，喜欢乘人之危，这不是保全自己的办法。我周嵩性情耿直，也不被社会所容。只有小弟周谟平庸无能，将会服侍在你眼前。”  

举止从容，不滞于物的气度远远比其他德行、方正等更能代表魏晋风度，而前面五章的很多内容，都可归到“雅量”这个特殊词汇之中。  

## 6.23  
>庾太尉与苏峻战，败，率左右十余人乘小船西奔。乱兵相剥掠，射，误中舵工，应弦而倒，举船上咸失色分散。亮不动容，徐曰：“此手那可使著贼！”众乃安。  

- *庾太尉*：庾亮。前已介绍，325年，晋明帝司马绍去世，晋成帝司马衍5岁即位，舅舅庾亮、王导、卞壸辅政。326年，庾亮诛杀南顿王、骠骑将军司马宗，司马宗手下卞阐逃亡到苏峻处。苏峻本来在江北，“本以单家，聚众干扰攘之际”，门第与品格均不得入于士流，但因为平定王敦之乱有功，进卫建康，大破钱凤兵，奠立了灭王敦胜利基础，于是事后，苏峻晋升为使持节、冠军将军、历阳内史，封邵陵公，建康北面门户由苏峻守护。庾亮一心要振兴皇权，对流民帅一直严密防制，持打压态势，于是认定苏峻其后必为祸患，决心先下手为强。327年，庾亮认为苏峻在外迟早生乱，想下诏征他来朝廷。他跟王导商量，王导不同意，认为征召他，他肯定不会来，后果难料，不如暂时保持原状。庾亮不听。庾亮召集群臣议事，说苏峻迟早要反，迟反不如早反，不如就把他逼反，跟当年七国之乱一样。卞壸反对，说苏峻手握强兵，离京师又近，逼反他，朝廷没有制服他的把握，要从长计议。庾亮不从。于是朝廷多次下诏要苏峻来建康当官，苏峻说情愿驻守青州荒郡，来朝廷当大司农实在吃不消。于是苏峻联合祖约等人，以诛杀庾亮的名义兴兵攻打建康。大多数领导一般都以为自己是十项全能，庾亮自然也不例外，以为自己军事才能了得，但那并非事实，甚至庾亮亲自率兵在建康城外，打算与苏峻决一死战，没接战士兵们都跑光了，庾亮只好夺路狂奔，去投奔老朋友温峤。  
- *此手那可使著贼*：这射艺那肯定能够射中敌人。庾亮一箭射乱兵，误中舵工，箭法实在太好，大家一怕船不会动了，二怕庾亮的第二箭。庾亮就开玩笑说，我一射一个准，这样的手段，敌人哪里挡得住啊！不过射的主语不清，也可能是别人射的，反正大家都怕。放松紧张情绪的好办法不是上洗手间，而是开个玩笑。而在紧张时刻能开玩笑的，那就是能置生死于度外的气量。庾亮不怕骑的卢马，能够临危不惧，这可能与玄学思想有密切关系。  
宗教处理生死问题往往是期待来世天堂，而汉民族处理生死问题，高明之士往往会受庄子思想的影响，齐万物等生死。《庄子-齐物论》中说：予恶乎知悦生之非惑邪！予恶乎知恶死之非弱丧而不知归者邪！予恶乎知夫死者不悔其始之蕲生乎？大意是说：我怎么知道贪恋活在世上不是困惑呢？我又怎么知道厌恶死亡不是年幼流落他乡而老大还不知回归呢？我又怎么知道那些死去的人不会后悔当初的求生呢？  
法国加缪说过，对尚未克服死亡恐惧感的人，是无自由可言的。自由只有一种：与死亡携手，共赴纯净之境，于是一切都不成问题。

## 6.24  
>庾小征西尝出未还。妇母阮，是刘万安妻，与女上安陵城楼上。俄顷翼归，策良马，盛舆卫。阮语女：“闻庾郎能骑，我何由得见？”妇告翼，翼便为于道开卤簿盘马，始两转，坠马堕地，意色自若。  

- *庾小征西*：庾翼，庾亮的弟弟。庾亮曾任征西将军，他死后，庾翼任征西将军，所以称小征西。  
- *刘万安*：刘绥，在“赏誉”中庾亮（或庾琮）夸他“灼然玉举”、“千百人中都引人注目”，据说武艺娴熟，官至骠骑长史。在“品藻”中王导曾经评价王羲之，“遗少何缘复减万安耶”，都说明刘绥在当时很出挑。他妻子阮幼娥。  
- *安陵*：地名。陕西、河北、河南等都有安陵，或作“安陆”，湖北江夏郡所，当时庾翼是荆州刺史。  
- *庾郎能骑*：阮幼娥丈夫刘绥弓马娴熟，她也想看看女婿的技能。也许说明东晋门阀制度产生的所谓名士将领，他们的军事基本功有点问题，譬如庾亮的箭术、庾翼的骑术，他们这两次的临场发挥都不好。  
- *何由*：怎能。谢灵运诗：“美人游不还，佳期何由敦？” 《宋书-沈庆之传》：“陛下今欲伐国，而与白面书生辈谋之，事何由济？”  
- *卤薄*：仪仗。宋叶梦得 《石林燕语》卷四：“唐人谓卤，櫓也，甲楯之别名。凡兵卫以甲楯居外为前导，捍蔽其先后，皆著之簿籍，故曰‘卤簿’”。  
- *盘马*：类似策马回旋的盛装舞步。见“5•12” “大夏门下盘马”。  
庾翼表演出洋相但毫不在意，遇到挫折后气度通达，荣辱皆忘，而不是没有羞耻感。不过这种界限很模糊，需要意会。冯梦龙《笑府》中记载了一个故事，医家医死了人，被病家用绳子捆住，待安置好死人再报官。医生半夜弄断绳子，急奔回家。病家追赶。前遇一河，医生不畏酷寒，扑通跳下河，游泳回家。此时见儿子正在灯下看医书，就一把抓起把书扔了，说：“我儿，医书先不急着看，学游泳最要紧。”这个医生庶几得晋人的忘情之意。

## 6.25  
>宣武与简文、太宰共载，密令人在舆前后鸣鼓大叫。卤簿中惊扰，太宰惶怖，求下舆。顾看简文，穆然清恬。宣武语人曰：“朝廷间故复有此贤。”  

晋穆帝司马聃时期，当时桓温是太尉，司马昱是抚军大将军、司徒（那时候还没当皇帝），司马晞是太宰（司马昱的兄弟）。桓温搞吓人的小把戏，司马晞惊慌而司马昱不动声色，也许是呆如木鸡（《庄子•外篇•达生》“望之似木鸡矣，其德全矣，异鸡无敢应者”，意思是说，我这只斗鸡看上去已经像木头鸡一样，德行真可说是完备了，别的鸡没有敢对战的）。  
后来司马聃19岁去世，司马昱即位，桓温就上表告司马晞谋反、放纵儿子、“聚纳轻剽，苞藏亡命”等罪行，请求司马昱将其赐死。在简文帝的一再坚持下，司马晞被流放至新安郡。桓温看不起司马家这些无能之辈是有的，但说是这次试探是为篡位做准备未免言过其实。而且这次试探后，刘孝标在注中引用，桓温发出“厉害了，我的司马昱”的感慨，进而“温服惮也”，这也是意淫强晋的病症。司马昱在位8个月，“忧愤而崩”，甚至可以说被桓温吓死了。  

## 6.26  
>王劭、王荟共诣宣武，正值收庾希家。荟不自安，逡巡欲去；劭坚坐不动。待收信还，得不定，乃出。论者以劭为优。  

- *王劭、王荟*：王导的两个儿子。当时去拜访桓温。  
- *庾希*：庾亮的侄子，庾冰的长子，曾任北中郎将，徐、兖二州刺史，他妹妹是晋哀帝司马奕的皇后。371年，桓温废黜司马奕，立简文帝，然后指认庾希、庾倩等谋反，庾倩等被杀。庾希逃逸避难，后起事被杀。  
- *收信*：收押庾家的使者（官员）。    
- *得不定*：有学者认为，意思是得知事情还没有最终结果（庾希跑路了）。但有学者认为“不”为衍字，还有学者认为“不”或为“小”字，总的意思就是得到比较确切情况才离开。  
在桓温抄庾家的大事件中，王荟君子不立危墙，想回家避避风头。而王劭作为政坛的重要人物，八卦心够强，即便桓温这时候不出面接待，也一定要打听完消息后才走，表现出镇定稳重。  

## 6.27  
>桓宣武与郗超议芟夷朝臣，条牒既定，其夜同宿。明晨起，呼谢安、王坦之入，掷疏示之。郗犹在帐内。谢都无言，王直掷还，云：“多！”宣武取笔欲除，郗不觉窃从帐中与宣武言。谢含笑曰：“郗生可谓入幕宾也。”  

371年是东晋中期的政坛大变局之年，起因却在369年桓温第三次北伐的枋头之战。该战役由于各种原因，桓温军大败。心腹参军郗超和他讲：“你担负着天下重任，现在已经60岁了，却失败于大规模的军事行动。如果不建立非常功勋，就不足以镇服和满足百姓的愿望！建议效仿伊尹、霍光，废黜君主，这样就可以建立大威权，镇压四海。”桓温温深以为然，遂与之定议。  
由于东晋的门阀政治，桓温的兵败甚至成为他向同事发难的机会和条件。他兴兵前，先把郗超的父亲、徐、兖二州刺史郗愔安置到会稽，自己兼领刺史，安排部将刘波领五千人镇石头城，在军事上控制了建康政府；兵败后归罪于粮运不继的豫州刺史袁真（庾氏旧部），任命长子桓熙为刺史，以军事的失败赢得政治的胜利，最终获得了控制东晋王朝的军事力量，实现了桓温以北伐为名，增进自身实力和威望的目的。从此以后，“政由桓氏，祭由寡人”，朝廷大事，只要桓温和郗超商量着就可以决定。  
371年11月13日，桓温拜见褚太后，请求废掉司马奕，另立丞相司马昱为帝。11月17日，桓温命其弟桓秘逼迫新蔡王司马晃到太极殿西堂去自首，自称与武陵王司马晞及子综、著作郎殷涓、太宰长中庚倩、散骑常侍庚柔等谋反。19日，桓温处死东海王三子及其母。20日，桓温欲诛武陵王司马晞，但简文帝不许，桓温遂废武陵王及其三子的封号，徙至淳安。同时，免新蔡王司马晃为庶人，族诛殷涓、庾倩、庾柔等。  
- *王坦之* 前已多见，年轻时与郗超齐名，有谚语“盛德绝伦郗嘉宾，江东独步王文度”。他担任过桓温的参军，和桓温也是儿女亲家，“敦儒教，颇尚刑名学”，其性格算得上“方正”。故毫不客气地认为桓温要杀的大臣太多了，桓温准备有所收敛。  
- *郗超* 当时已经是中书侍郎，不再是桓温的参军。谢安一语双关，一则讽刺郗超还是桓温的幕僚，请你摆正位置哦；二则讥讽郗超和桓温是基友，两人要注意性取向哦！  
此条似与雅量无涉。但也许面临这么大的事情，谢安还敢开玩笑，足见其胆量，也算是雅量。  
372年，简文帝司马昱去世，52岁；373年，桓温去世，61岁；375年，王坦之去世，45岁；378年，郗超去世，42岁。寿命是古人的天敌，多少光复蓝图，抱负壮志都成了未竟事业，都付了这断墙残垣，唯有“绝壁天悬，腾波迅急”。  

## 6.28  
>谢太傅盘桓东山，时与孙兴公诸人泛海戏。风起浪涌，孙、王诸人色并遽，便唱使还。太傅神情方王，吟啸不言。舟人以公貌闲意说，犹去不止。既风转急，浪猛，诸人皆喧动不坐。公徐云：“如此，将无归？”众人即承响而回。于是审其量，足以镇安朝野。  

- *盘桓*：徘徊引申为暂时居住。在360年前，谢家有谢尚、谢奕、谢万先后任豫州刺史，谢安“六七年间征召不至”。后因谢万兵败被黜，谢安不得不为家族计，出任桓温的司马和吴兴太守等，以保全门户。  
东山是绍兴上虞的一个小丘陵，我曾经特意去看过一次，山下现在造了一个宾馆，山腰有谢安纪念馆，山顶是一座庙宇。上虞离东海较远，但钱塘江很宽阔，在晋代估计还要宽阔的多，当地人把钱塘江叫海，两岸叫海涂。曹植是比较早写东海的诗人：“东海广且深，由卑下百川。五岳虽高大，不逆垢与尘。良木不十围，洪条无所因。长者能博爱，天下寄其身……”  
- *孙兴公*：孙绰，前已多见，文学家，比谢安大3岁。王估计是王羲之，比谢安大10几岁，当时称病辞职，“遍游东中诸郡，穷诸名山，泛沧海”，他给谢万的信中也写道：“比当与安石东游山海，并行田视地利，颐养闲暇。”  
- *遽*：遽惶，惊恐。  
- *唱*：费解，要么是大声叫，要么是倡议。  
- *神情方王*：精神兴致正旺盛。  
- *说*：通“悦”。  
- *将无*：前已多见，应该，莫非等表肯定的猜测性语气。  

远足泛海足以陶冶性情。“魏晋风流”摆脱了儒家学说的知其不可而为之的入世情怀和追求功名的虚伪无耻，也不是佛教因对苦难的恐惧而试图通过冥想自闭获得肉体的解脱，他们站上高山之巅，处于海浪之中，上升为更为玄远的自然和人格融于一体的情怀追求。魏晋时期最杰出的代表，他们继承和发展庄子的思想，不刻意去迎接宏伟的人生挑战，去思考为未来留下什么，而是倾听心灵和自然的声音。就像谢安，凡事不紧张，即使无可奈何也要表现出不紧张，其心态对风浪处于怕与不怕之间，对事业处于用与不用之间，若即若离。  
这个故事还有一个版本：桓宣武在南州，与会稽王会于溧洲。于时漾舟江侧，谢公亦在。狂风忽起，波浪鼓涌，非人力所制，桓有惧色，会稽王亦微异，惟谢公怡然自若。顷间风止，桓问谢曰：“向那得不惧？”谢徐笑答曰：“何有三才同尽理（哪里会有老天安排我们三个有才华的人同归于尽的道理）。”（《太平御览•卷七十一》）  

## 6.29  
> 桓公伏甲设馔，广延朝士，因此欲诛谢安、王坦之。王甚遽，问谢曰：“当作何计？”谢神意不变，谓文度曰：“晋阼存亡，在此一行。”相与俱前。王之恐状，转见于色；谢之宽容，愈表于貌。望阶趋席，方作洛生咏，讽“浩浩洪流。”桓惮其旷远，乃趣解兵。王、谢旧齐名，于此始判优劣。  

自371年以来，桓温采取了很多政治、军事行动罢黜和诛杀异己，另立新帝把持朝政，引发了一系列的抵抗和不合作。因为他长期以军事首脑的身份活动，加上东晋特殊的政治体制，并没有能在南京建立起他的政治班底，更也不能放任他的军事力量，所以以大司马的身份镇姑孰，并不在中央。  
372年7月，简文帝司马昱去世前夕，一日一夜共发了四次诏书，急召桓温入朝。但桓温在那个时候如果不想推翻政权，就不可能带兵进入南京，所以他表现的很犹豫，甚至还梦想简文帝能禅位给他。而简文帝的遗诏经过太原王坦之的力争，从原来的“依周公居摄故事。少子可辅者辅之，如不可，君自取之”改成了“家国事一禀大司马，如诸葛武侯、王丞相故事”。第二天简文帝驾崩，群臣立嗣，有人说要请桓温来定夺。琅邪王彪之说：“天子崩，太子代立，大司马何容得异！若先面咨，必反为所责。”朝议乃定。而后本来要按照遗诏请桓温回来做丞相了，但是王彪之继续说：“这么大的事情，桓温一定会坚决推辞的，这样就会耽误国家大事，造成更严重的后果，因此太后的命令不能执行，只能原封不动地还回去。”就连遗诏的事情也就这样黄了。  
在中央变动之际，桓温没有从安徽当涂赶回南京。  
直到373年2月，桓温带兵入朝，拜谒皇陵，摆下了传说中的鸿门宴。但一切都没发生，桓温在京师呆了14天后患病，就率部返回了当涂，7月去世。这个故事认为，“鸿门宴”平和，主要是谢安风采过人，靠一首嵇康的《赠秀才入军》平息了一场军事政变。  
- *望阶趋席*：到台阶上就快步入座。  
- *洛生咏*：西晋时期，洛阳一带的书生在吟诗时，常常采用一种语调，其发音方法和腔调特征带有明显的洛阳方音气息，称之为洛生咏。  
- *趣*：通“促”，快速。  

在酒宴中埋伏刀斧手，最后主人居然没有采取行动，理由是“害怕谢安的志趣旷达高远”，没有可信度，无非就是民间演义的套路。

## 6.30  
>谢太傅与王文度共诣郗超，日旰未得前。王便欲去，谢曰：“不能为性命忍俄顷？”  

郗超是流民帅、太尉、司空郗鉴的孙子。郗鉴“虽在公位而冲心愈约，劳谦日厌，诵玩坟索，自少及长，身无择行。家本书生，后因丧乱，解巾从戎，非其本愿，常怀慨然”，他起家于流民，长镇京口，跻身门阀，并有所建树。其儿子郗愔平生没有什么出众的业绩，孙子郗超自幼“卓荦不羁，有旷世之度”。郗超年青时就入桓温幕府，桓温常说郗超深不可测，倾意礼待。郗超也和桓温结下忘年交，成为其左膀右臂。371年以后，桓温驻军在当涂，朝廷中由郗超担任中书侍郎，是桓温在朝中的代理人，一言可决人之进退生死。即使刚正峻整的王坦之，浩浩洪流的谢安石都得仰其鼻息。王坦之一时忍不住，是因为郗超和他年龄经历相仿，有比较之心。而谢安大郗超16岁，以桓温的接班人自诩，所图甚大，并不介意再忍一忍。  
雅量有时候是修养品性所得，有时候是志向器局而成。我的追求是捍卫世界和平，怎么会因为前面有人插队而勃然变色呢？  

## 6.31  
>支道林还东，时贤并送于征虏亭。蔡子叔前至，坐近林公；谢万石后来，坐小远。蔡暂起，谢移就其处。蔡还，见谢在焉，因合褥举谢掷地，自复坐。谢冠帻倾脱，乃徐起，振衣就席，神意甚平，不觉瞋沮。坐定，谓蔡曰：“卿奇人，殆坏我面。”蔡答曰：“我本不为卿面作计。”其后二人俱不介意。  

- *支遁 支道林* 前已多见，曾长期居住在南京东南方的绍兴。362年，晋哀帝下诏让他进京宣讲佛法，3年后会稽郡。支遁在当时有很高的声望，他是最早将玄学和佛学贯通结合的学者之一。就学识而言，由于能较早与外来优秀文化的融汇，谢安夸支遁说：“嵇康须不断努力，才能赶上支遁。” 郗超说：“支遁神理所通，玄拔独悟。数百年以来，绍明大乘佛法，令真理不绝，唯此一人而已。”  
一般而言，儒家、道家文化的特点之一是跳跃性思维，逻辑性不强，常常充斥着概念混乱、诡辩和无法自洽，而佛教与之相比表现出相当高的思辨水平，在其经典进入中国后就引起了学者的高度兴趣，很自然地会将其与本土文化相结合，来丰富玄学，同时推动佛教中国化。支遁为《逍遥游》作注，超越了郭象和向秀，东晋以后学者谈《庄子》都采用“支理”。  
他在南京居住3年，估计是身体情况不佳要回绍兴，因为谢安曾经邀请他去吴兴养病：“人生如寄耳，顷风流得意之事，殆为都尽，终日戚戚，触事惆怅，唯迟君来，以晤言消之，一日当千载耳。此多山县，闲静差可养疾，事不异剡，而医药不同。必思此缘，副其积思也。” 支遁交游很广泛，在《世说新语》中就起码有十几个好朋友，周旋于玄学名流与达官贵人中，此次有很多人来送行。征虏亭位于长江附近，东晋时要人出都坐船，大都从此出发。  
- *蔡子叔*：蔡系，东晋初重臣、司徒蔡谟的儿子。  
- *谢万石*：此处不确，谢万361年已经去世了，应该是谢安。《高僧传•支道林传》中也记载是谢安。  
- *合褥举谢掷地*：把谢安连人带坐垫一把举起扔在边上。  
- *不觉瞋沮*：没有感到愤怒或沮丧。  
- *奇人*：清人王先慎说，奇人就是闲人的意思，因为《韩非子•十过》里说：“有奇人者使治城郭之缮”。谢安和蔡系互相称卿：“你这个闲人，差点弄伤我的脸！”蔡系说：“我根本没考虑过你的脸面！”  
唐代娄师德的唾面自干无非是个比喻，而谢安能忍到这个地步，事后也没有什么官场报复行为，而且我们也多次看到前面几则故事中不少人被打而不动气，要理解他们有点难度。他们又不是人民子弟兵，没有“骂不还口，打不还手”的组织纪律，也不会因此得到表彰。  
孔子本人不怎么讲忍，他讲“知耻近乎勇”，谈忍还是为了图大谋，“小不忍则乱大谋”；至少是要替自己和家人的安全想想，“一朝之忿，忘其身以及其亲，非惑欤？”孔子是个勇敢的人，一看到人家越礼就“是可忍孰不可忍”，一看到学生睡午觉就破口大骂粪土朽木，认为要以直报怨。他的图大谋和安全发展到后来成了无耻或残忍。孟子讲的多的是“不忍”，他的忍就是对欲望的自律，是仁，是恻隐同情，类似于佛教的慈悲。  
而老子的忍根本就是统治术中的权谋，目的就是要胜，“柔之胜刚，弱之胜强”。而庄子根本不谈情绪问题，齐物论本来就是万物不系于心，在伪托的《庄子-外篇》中有个譬喻：方舟而济于河，有虚船来触舟，虽有惼心之人不怒，有一人在其上，则怒张歙之，一呼而不闻，再呼而不闻，于是三呼邪，则必以恶声随之。向也不怒而今也怒，向也虚而今也实。人能虚己以游世，其孰能害之!"意思是说，如果撞到空船人不会生气，如果对方的船上有人就会恶语相加。那么就当没有人，还有什么能伤害你的呢？  
佛教最推崇忍，《大宝积经》中说：“忍辱为十力之本，诸佛神通之原，无碍智大悲皆以忍为本。”，还说“六度万行，忍为第一”等。它诱导信徒要忍，首先是忍了就偿还了业债，对自己有好处；其次，它的世界观认为一切都是空无，不必介意；三是嗔怒本来就是烦恼心，能不介意自然生喜欢心。  
魏晋风流，名士往往能忍人所不能忍，很大一部分愿意是玄佛思想的合一和发展，是一种人格修养。但它以后逐渐成为大多数中国人的一种恶劣的品性，但和雅量风流已经没有任何关系了，令人失望。以至于罗素说，中国人的忍耐令人吃惊，“在我快要离开中国之前，有一位著名的中国作家诚恳地要求我谈谈中国人性格的主要缺点。我以犹豫的心情谈了三点：贪婪，懦弱，缺乏同情心。”  

## 6.32  
>郗嘉宾钦崇释道安德问，饷米千斛，修书累纸，意寄殷勤。道安答直云：“损米，愈觉有待之为烦。”  

- *郗超*信佛好施舍。佛教认为，僧人得到布施其实是在为施主着想。施舍出去养僧人建庙宇，就是积功德有福报，而且你捐掉财产，就断了烦恼得了智慧，布施堪称“舍一而万报”。而僧人受布施，其实是做了很大的牺牲和贡献，我承受了你的业力，谁让我是红领巾学雷锋呢！  
佛教这种理论套路还有很多，它把布施细分成很多种，还规定有很多种行为不能算布施，哪些人还不能布施。反正接受你的财物，是看得起你，你是被精挑细选的那一个！于是“有舍才有得”成为当代有名的心灵鸡汤。2018年新闻报道，有个原著名大清官胡某的烧锅炉的太太，就拉了一帮子土豪、官员捐了几个亿建了一个庙，福报让她的儿子当时国家领导人。常大妈啊，你这个可是向佛祖行贿的“垢染布施”哦，不是“六度”的法门。  
- *释道安*：前已多见，东晋名僧，是他提议所有僧人都应该姓“释”，并重修注释了很多佛教典籍，被认为是佛教中国化的奠基者，依国主立佛法的倡导者，佛门释姓的统一者，中国僧制的首创者，中国第一部佛经目录的编纂者等。 
- *问*通闻，是名声、声望的意思。令问  
- *斛*：相当于担，一斛十斗，一斗十升，总相当于十来万斤大米。  
- *累纸*：好几张纸。  
- *意寄*：寄意，寄托心意。  
- *损*：当时书信中的敬语，承蒙馈赠的意思。  
- *有待*：《庄子-逍遥游》说列子能御风，但还不够自由：“此虽免乎行，犹有所待者也。”列子能飞要靠风，道安活着要吃饭，这都是不自由的表现，“你一下子送了这么多米，我还必需接受”，我不自由，我愈感到烦恼。  
有神论常常把物质世界和精神世界给割裂对立，他们假设了一个“无待”的神圣作为最高真理，认为无待是实现万能的途径；视自己为沉重的肉身，似乎越远离物质世界，精神世界就越自由。普通信徒对自由的描述大多数就是身体能上天飞翔，生活能心想事成，情感能摆脱烦恼，寿命能长生不老。随着科学技术的发展，依靠物质世界的建设，据《人类简史》的作者认为，这些愿望某些人都已经实现或快要实现了，人终于从动物到了上帝。即使这样，这些“上帝”们在可以预见的将来，还是无法获得自由，幸福都是暂时的感受，一千个快乐也比不上一个痛苦。  
释道安虽然是名僧，但由于历史原因，还是用玄学来表达他的思想。到了南北朝时期，就思想哲学而言，成熟而又相对高超、普适的佛教理论+迷信基本战胜了云山雾罩的玄学，成为大多数中国人慰藉心灵的主要思想工具，直到今天。  

## 6.33  
>谢安南免吏部尚书还东，谢太傅赴桓公司马出西，相遇破冈。既当远别，遂停三日共语。太傅欲慰其失官，安南辄引以它端。虽信宿中涂，竟不言及此事。太傅深恨在心未尽，谓同舟曰：“谢奉故是奇士。”  

王谢家族中的谢家来自于河南太康，永嘉南渡后居住在绍兴，称为东山谢氏。在绍兴原来就有一个山阴谢氏，孙吴以来，会稽郡“孔魏虞谢”四族虽不及吴郡“顾陆朱张”显赫，却也是一方著姓。东晋初重臣何充“出为东阳太守，在郡甚有德政，荐征士虞喜，拔郡人谢奉、魏顗等以为佐吏”。谢奉后来当过丹阳尹、安南将军、广州刺史和吏部尚书。谢安出任桓温司马在360年，谢奉361年还是尚书，所以此事时间存疑。  
- *破冈*：今在江苏镇江句容县。  
- *它端*：它的本义是蛇，后来也作其他、别的解。  
- *谢奉*免官原因不详，谢安认为谢奉被免有点冤枉，想宽慰他。而谢奉宠辱不惊，不提这个事情。在等级制度森严，利益差异很大的官场，一旦进入这个游戏规则，绝大多数人都放不下。毛泽东曾经有过起落，1932年被免红军总政委，据史料说，他“忧虑成疾竟吐血”。有个笑话说，一副科长被免职后，气得一头栽倒成了植物人，家人找到医生说明病因。医生说：“找那些办假证的，弄个官复原职的红头文件，一念就好了。”家人想干脆弄个副县级的，让他好得更快。那知弄来一念，这小子挺身坐起，哈哈狂笑不止，竟死了。医生赶来，一看假文件，说：“怎么擅自加大药量呢？看，给治死了吧！”  

## 6.34  
>戴公从东出，谢太傅往看之。谢本轻戴，见但与论琴书。戴既无吝色，而谈琴书愈妙。谢悠然知其量。  

- *戴逵*戴安道是东晋中晚期的名士，王徽之雪夜访戴的当事人。他自小聪慧，心灵手巧，“善属文，能鼓瑟，工书画，其余巧艺靡不毕综”。他的演奏技能声誉很高，当时武陵王司马晞闻其善鼓琴，使人召之，逵一把砸掉琴瑟，说：“戴安道不为王门伶人！”而谢安“尤善行书”，“工琴艺”，所以这艺术方面和戴逵有共同语言。  
戴逵是安徽人，后长期隐居在绍兴，并与高门风流者交游。这次他去了南京，谢安慕名拜访。但以往谢安不知道什么原因，看不起戴逵。也许是戴逵常以礼度自处，曾特意写了《放达为非道》《竹林七贤论》文章抨击当时的风流习气，说元康名士效仿竹林七贤是“捐本殉末，舍实逐声”，“是犹美西施而学其颦眉，慕有道而折其巾角，所以为慕者，非其所以为美，徒贵貌似而已矣”，“彼非玄心，徒利其纵恣而已”。而谢安的伯父谢鲲就是元康名士，“四友”“八达”之一，当时谢家的顶梁柱，使谢家进入了高门之列的关键人物。  
谢安喜欢谈玄，而且清谈是当时聚会的“硬菜”，不上这道菜，聚会不够档次。但因为心存芥蒂，这次他就只谈琴棋书画，不涉及“道”。而戴逵不以为耻，充分阐释了他对艺术的感悟。朝廷后来多次征辟戴逵，但戴逵都拒绝了，他选择了自己的生活方式，做山林之客，亲近自然而自得其乐。他在《闲游赞》中阐述了自己的志趣：
>然如山林之客，非徒逃人患，避争门。谅所以翼顺资和，涤除机心，容养淳淑，而自适者尔。凡物莫不以适为得，以足为至。彼闲游者，奚往而不适，奚待而不足。故荫映岩流之际，偃息琴书之侧，寄心松竹，取乐鱼鸟，则澹泊之愿，於是毕矣。

大意是说，我隐居不仕，不仅仅是避免人世间的纠纷争斗，更是以此顺应和谐，清净我的心思，涵养淳厚温和的品性，自得其乐。人生如寄，闲游而已。哪有路没有尽头而感到不舒适，有所待而感到不足。我淡泊的志愿就是亲近自然，高山流水，松竹鱼鸟，音乐书籍。正如英国诗人沃尔特.兰道尔的诗歌：我从不与人争，没人值得我与之争；我爱自然，其次是艺术。我慕名而来，向那熊熊火焰伸手取暖；火快灭了，我也准备离去。这就是谢安了解的戴逵的器量。  

## 6.35  
>谢公与人围棋，俄而谢玄淮上信至，看书竟，默然无言，徐向局。客问淮上利害，答曰：“小儿辈大破贼。”意色举止，不异于常。

383年淝水之战和384年的继而反攻成就了谢安的千古美名。前秦、东晋本以以淮河——汉水——长江一线为界，至此变成了以黄河为界，整个黄河以南地区重新归入东晋版图。《晋书》记载，谢安在这个过程中前后下了两盘著名的棋。一是战前部署在和张玄下棋，赌注是别墅。谢安平时棋艺差，而张玄那天由于战事在即，心事重重，“是日惧，便为敌手而又不胜”。到了晚上，谢安才“指授将帅，各当其任。”二是当前方传来大捷消息时，谢安又正在下棋，同样表现的镇静从容。不过《晋书》上说他这是“矫情”。他下完棋后回内室，很嗨，走路很快，鞋子碰到门槛，“心甚喜，不觉屐齿之折”。  
在整个战役中，作为最高指挥官的谢安承担了巨大压力。以八万应对号称的百万军队，而且主要部队是谢安的子侄辈率领的流民北府兵，一旦战事失败，一个有责任感的政治家将背上千古骂名，一个鼎盛的谢家将遭遇灭顶之灾，一个不怎么好的东晋也就完了。而谢安认为，他该做的都做了，只能等待命运的安排，于是平时继续闲游清谈，以镇朝野人心。以至于当时的主要军事将领桓冲忧心忡忡：“谢安石有庙堂之量，不闲将略。今大敌垂至，方游谈不暇，遣诸不经事少年拒之，众又寡弱，天下事已可知，吾其左衽矣! ”  
而今不少人办公室里喜欢挂“宁静致远”，做事勉励自己“每逢大事有静气”，我们也能从各种史料了看到伟人们在重大战役前镇定自若的佳话。据说亚历山大大帝在战役前喜欢睡觉，以至于他的部下多次唤他醒来下达攻击令。李广遭遇匈奴千骑，叫士卒解鞍下马以示悠闲和诱敌。  
据说我党革命家陈毅资历老，打战前也爱下棋，但军事才能差点，下棋后打胜仗是佳话，输了那就是丑闻。于是中央派资历不高的粟裕当他的副手，专门指挥军事。粟裕就多次表态，多打几个胜仗，让陈老总安心下棋。陈毅后来在下棋之余，给粟裕写了一副含有魏晋人名的对联夸他：“轻裘缓带羊叔子，食少事繁诸葛公”，把粟裕喻成从容儒雅的名将羊祜和日夜操劳的名相诸葛亮。粟裕回忆说：他长期在陈毅领导下工作，心境是舒畅的。  
矫情现在一般是指故作姿态掩饰真情，带有贬义。但在魏晋的文化氛围中，矫情有另外含义，它可以理解为克制情感。魏晋时期士人人格觉醒，开始提供如何处置情感生活的思路。他们既推崇情感的通达放荡，也推崇情感的含蓄克制，这就像纸张的正反面，是一个整体。谢安一方面放纵欲望，喜欢歌姬音乐游玩，享受美好生活；一方面以后天的修养压制情绪，努力实现喜怒不露形色。他们认为，生活过于严肃就虚伪乏味，情感过于肤浅就不够博大。情感放纵就是宽度，情感深沉就是厚度，两者结合故能成其大。而以放纵涵养深沉也是一种思路，譬如佛教有一种理论就是极度放纵以后获得大彻大悟。  
我们还可以换个思路，放纵情感是一种对原有生活的反抗，不露声色同样是对人之天性的反抗，而在反抗之中，人的情感精神世界逐渐强大，超越了“自然”，成就其雅量。  
雅，大也。

## 6.36  
>王子猷、子敬曾俱坐一室，上忽发火。子猷遽走避，不惶取屐；子敬神色恬然，徐唤左右，扶凭而出，不异平常。世以此定二王神宇。  

王徽之是王羲之的第五子，王献之是第七子，兄弟感情很深。据《晋书》说，王献之病重，当时有种方术，只要有人愿意自折阳寿，那快死的人便能转危为安。王徽之便对道士说：“我的才位都不及我弟弟王献之，今天就请用我的阳寿为我弟弟续命。”这个道术怎么可能现场实践呢？于是道士回答道：“能够替人续命的，自己得先有未尽的阳寿。今年，你与你弟弟大限都到了，你又拿什么替你弟弟续命呢？”于是兄弟两在386年去世。  
- *不惶*：有点费解，或者是“惶不取屐”。还有一种解释是惶通“遑”，《尚书•无逸》“自朝至于日中昃，不遑暇食，用咸和万民”。孔颖达解释说：“遑，亦暇也。重言之者，古人自有复语”，不惶就是没有空闲。第三种解释是因不能而慌乱也，引申为“来不及”。刘勰 《文心雕龙 - 时序》：“爰至有汉，运接燔书，高祖尚武，戏儒简学，虽礼律草创，诗书未遑。”  
- *扶凭而出*：当时一些贵族的气派，走路要仆人搀着，以显示庄严。《颜氏家训》中说：“梁氏士大夫者，皆尚褒衣博带、大冠高履，出则车舆，入则扶持，郊郭之内，无乘马者。”  
- *神宇*：精神器宇。  

两兄弟不一起跑，哥哥不照顾弟弟，自己率先跑？于是王徽之内疚了一辈子吧。  

## 6.37  
>苻坚游魂近境，谢太博谓子敬曰：“可将当轴，了其此处。”

- *游魂*：《晋书•王导传》“且北寇游魂，伺我之隙”，《梁书•王规传》“非为功难，成功难也。羯寇游魂，为日已久。桓温得而复失，宋武竟无成功。”游魂即军事入侵的贬称，指383年前秦与东晋冬天的战争。  
苻坚当时“跨三分之二，居九州之七”，抱着统一六合的志向，由氐以及鲜卑、羌族等被征服部落组成的百万军队，“前后千里，旗鼓相望”，向东晋进军。这是中国自古以来少有的巨大军事行动，以至于苻坚认为只要“投鞭于江，足断其流”。他甚至兴奋地脱离中军，轻骑赶到寿阳成为先头部队统帅，以15万对8万，化繁就简要与谢玄在淮河淝水边决战，意图一定乾坤。  
史书记载的这场战役有不少令人费解的地方。苻坚允许谢玄过江来战，答应他可以先让出空间，再打算按照教科书的做法，到时候东晋军队一半部队在江上，一半上岸，前秦发起突击，对方焉得不败？但这种想法儿戏。  
苻坚真的这么做，他的15万军队居然事前没有收到统一的部署命令，在战场上苻坚临时下令，前头部队后撤。这时候在后军的降将朱序大喊“我们败了，快逃”。这个由神赐予的巨大声响居然响彻原野，前秦部队整体炸营，呈雪崩式溃败。  
接着鲜卑、羌族首领叛变，“自相蹈藉而死者，蔽野塞川。其走者闻风声鹤唳，皆以为晋兵且至，昼夜不敢息，草行露宿，重以饥冻，死者什七、八”。  
这些都是史书简单的记录，我们无法知道当时究竟是怎么一回事。也许在两晋南北朝的时期，各国各部落的军队多为私军，无论是汉族还是少数民族统治者，都会选择更加符合自己利益的分裂政权，作战如强盗劫掠，街巷斗殴，大多数没有训练，没有军纪，一退即溃；也许是独裁的弊端，再贤明神武的君主也会常常脑子短路，昏招迭出，进退失据；也许是苻坚的部下大多数心怀鬼胎，嘴上一天喊三次“苻核心”，“陛下听信鲜卑、羌虏谄谀之言，采纳良家少年利口之说，臣恐非但无成，亦大事去矣。垂、苌皆我之仇敌，思闻风尘之变，冀因之以逞其凶德。少年等皆富足子弟，希关军旅，苟说佞谄之言，以会陛下之意，不足采也”，手上随时准备捅刀子；也许是天气、疾病和深渊般的命运，“时来天地皆同力，运去英雄不自由”……  
对东晋而言，谢安似乎并没有什么杰出的指挥才能和周密的军事计划，他唯一的长处就是镇静，依靠这个长处静候命运的安排。朝廷内意见纷呈，基本都不看好他能赢得这场史无前例的战争，以至于皇帝司马曜心里都没底，但就是问不出什么锦囊妙计。于是派舅佬、谢安的好朋友王献之来进一步问问，“你到底有什么扭转乾坤的举措没说出来？”  
- *当轴*：《汉书》：“车丞相履伊、吕之列，当轴处中，括囊不言，容身而去，彼哉！彼哉！”昭连《啸亭杂录-成将军》：“当轴辄以养贼自重，真不解其何心。”“当轴”指官场要员。谢安豪迈地说：“我会派朝廷得力的要员去指挥，将苻坚了结在此处！”他所谓的要员是亲人谢石、谢琰、谢玄，“我全家老小都冲上去了，我已经显示玉石俱碎的信念，你们还能要求我怎么样！”  
谢安赢得了一场匪夷所思的战争，也就赢得了所有美名，他的一切行为都被历史褒奖。即使在这1600多年以后，他依旧被视为两晋时期最高的山峰和云彩，世间最和煦的清风，最安静包容的森林。他成为极少数不因艺术而名垂千古、熠熠生辉的伟大人物，甚至他的行为就是一种特殊的艺术，一种生活的美学，成为中国文化中“风流”的代名词。他无需每天在媒体头条上自夸，也不用朝廷和群众的宣扬学习。他的墓碑上不着一字，“东晋谢太傅墓碑，但树贞石，初无文字，盖重难制述之意也”；他在书籍中尽是赞美之词，“家山花柳春，侍女髻鬟绿。出处亦何心，晴云在空谷”……  
秦晋之战一年后，385年10月，谢安、苻坚去世，相隔不过4天。人间风流殆尽，要靠300多年后李白来撑场面。  

## 6.38  
>王僧弥，谢车骑共王小奴许集，僧弥举酒劝谢云：“奉使君一觞。”谢曰：“可尔。”僧弥勃然起，作色曰：“汝故是吴兴溪中钩碣耳，何敢诪张！”谢徐抚掌而笑曰：“卫军，僧弥殊不肃省，乃侵陵上国也。”  

- *王僧弥*：王珉，琅邪王氏之后，字季琰，小名僧弥，王导的孙子。王小奴：王荟，字敬文，小名小奴，王导的儿子，王珉的叔叔，镇军将军，死后追赠卫将军。  
王珉娶了谢安的女儿，但谢安不喜欢他，后来叫女儿离婚改嫁，王家“由是与谢氏有隙”。车骑将军、兖州刺史、徐州刺史（使君）谢玄是谢安的侄儿，从这个辈分上看王珉和谢玄是同辈，但错综复杂的婚姻关系和子女众多，很难算得清楚王谢两家的辈分。譬如谢安和王羲之、王献之父子都是好朋友。  
谢安执政后，扶持太原王氏的王蕴，安排王蕴的女儿王法慧为司马曜的皇后；扶持琅邪王氏的王献之；扶持司马曜的弟弟司马道子辅政；就是不安排姻亲王珣、王珉的职务，还叫侄女、女儿和他们离婚，这种政治平衡术总的目的是不想让谢家树大招风，引发君王的猜忌和其他门阀的攻击，但确实得罪了王导一系子孙。这次宴会大概发生在淝水之战后，谢家如日中天，王珉低姿态地向谢玄敬酒，谢玄没有表示出谦虚，引发了王珉的反击。  
- *碣*：谢玄小名羯奴，碣、羯通。他喜欢钓鱼，多次写信告诉家人他钓鱼的乐趣：“居家大都无所为，正以垂纶为事，足以永日。北固山下，大有鲈鱼，一出手，钓得四十九枚”，“昨日疏成后钓，出手所获鱼，以为二坩鲊，今奉送”；谢安当过吴兴太守，谢玄小时候跟随谢安生活在吴兴。  
- *许集*：那里集会。  
- *诪张*：《尚书•无逸》：“民无或胥，诪张为幻。”“诪”同“诌”，胡诌妄语。“你本来是一个在吴兴小溪沟钓鱼的蛮奴辈，怎么敢这样胡说八道！”谢家起步较晚，东晋新出门户，比太原王、琅邪王以及裴、荀、诸葛、陈、刘、阮、庾等魏晋大姓高官差上好些，他们的祖上都比谢家阔，所以王珉不免愤怒。  
- *肃省*：肃正自省。  
- *上国*：我是头等国家，你王珉才是蛮夷小国。谢玄淝水大胜，志得意满，不理睬王珉，拍了一下手，笑着和王荟说：我小名羯奴，但我才不是羯奴啊，我还打败了秦国！王珉这个小和尚居然敢来侵犯我！  

这是哪门子雅量，分明是狗咬狗嘛！无非是一个吹胡子瞪眼睛地骂，一个若无其事地补刀讥笑。不过以微笑来化解愤怒的冲突，显得大度一些。  

## 6.39  
>王东亭为桓宣武主簿，既承藉，有美誉。公甚欲其人地为一府之望。初见谢失仪，而神色自若，坐上宾客即相贬笑。公曰：“不然，观其情貌，必自不凡。吾当试之。”后，因月朝阁下伏，公于内走马直出突之，左右皆宕仆，而王不动。名价于是大重，咸云：“是公辅器也。”  

王珣曾封东亭侯，王珉的弟弟，前已多见，谢安曾经的侄女婿。他带着红色家族的光环，承蒙祖父王导的门荫，有很好的声誉。他曾经自称做梦有人送给他一支“如椽大笔”，梦后文思泉源，自诩“大手笔”。他确实是杰出的书法家，其《伯远帖》在任何书法作品比赛中，肯定都位居前列。  
他曾经是桓温的幕僚。桓温出于各种考虑，重用拉拢他，希望他靠着人品和门第成为幕府中的榜样，于是开始演双簧。  
第一次两人没有沟通好，王珣演砸了，“初见谢失仪”（“谢”为衍字，初见失仪，首次见面时有失礼仪；当然，也许“谢”在当时已有感谢的意思，第一次，王珣因升官去拜见桓温，表示感谢，举止有失礼仪）。桓温必须再给王珣机会，而且事先进行必要而充分的沟通。  
第二次，幕僚们都在官厅那边等桓温上朝议事，桓温策马扬鞭而来，只有王珣没有受到惊吓，像一棵树一样挺立在高头大马前。事后，他的同事们负责到处传播王珣的稳重——像宰相一样稳重。  
袁世凯是类似桓温一样的枭雄，演技能和桓温一拼。  
他当年官拜直隶总督后，把嫡系的新军先后成立三个协。为表示用人为共，公开招考统领。第一次第一协王士珍（龙）考取。第二次第二协冯国璋（狗）考取。  
这时段祺瑞吃不消了，第三协考不上升不了官尚在其次，可是自己是“虎”，“狗”都比他先走一步，面子实在过不去，焦急欲焚。  
谁知考试前一天，袁世凯悄悄德塞给他一张纸条。  
若干年后，段还是感激涕零，和王、冯说起这件事。王、冯两人哈哈大笑——他们也拿到过那张纸条。  
据说当时桓温执政后，曾经的公开选拔领导干部工作办公室不复存在，领导干部选拔性考试取消。也许是试题常常泄露；也许是靠考试上来的官员不会对组织忠心耿耿；也许是九品“中正”加领袖骑马检测肚量的考试，更能选中为人民服务的忠臣；也许是桓温年轻时遭遇史无前例的浩劫，曾经考不过人家，留下了深深的创伤……  

桓公啊，当时我明明和王珣一样，“不动”在你的马前，怎么史书上就落下我了呢！  

## 6.40  
>太元末，长星见，孝武心甚恶之。夜，华林园中饮酒，举杯属星云：“长星，劝尔一杯酒。自古何时有万岁天子！”  

- *属*：嘱咐。  
古代人认为，社会活动和大人物往往对应天上的星座。彗星出现是不吉利的大事件，要么预示着灾祸来临，要么大人物要死了。如果尾巴越长，自然注定灾祸越大，死的人级别越高。  
但如果没有验证怎么办？没关系的，也许预示着明年，也许预示着很多你尚未知道的灾祸，相信这个的都能找到能说服自己相信的理由。  
为什么人会相信这个东西？天空星宿确实教会人很多东西，季节，时间，气候，方向……太阳不言自明，月亮更是和潮汐有密切关系，有时候行星活动确实影响地球的旱涝。按照类推思维，太阳、月亮如此，其他星辰当然可能与伟大的自然力量有一定联系；那么“反常”的星辰变化，肯定意味着反常事件的发生。日月全食、偏食，流星和彗星的出现是肉眼可见最反常的变化，古人自然会谋求、联想人间的某种灾难性的对应解释。  
为什么越来越多的人会相信这个东西？那是因为时代变化，君权落到了普通人身上。从前普通人没有条件获得星象知识，也没有资格对应自己的星座。而人往往有自命不凡的倾向，一旦获得了这个权力和知识，就会使用它来谋求对不可测之命运的确认，甚至上升为一种文化，广泛用于解释生活和自我，并获得慰藉。  
晋孝武帝司马曜活了35岁，他不是病死的，而是被其中一个妻子杀死的。根据史书，396年9月的一个晚上，司马曜酒喝多了，对贵妃张氏说：“你年近三十，美色大不如前，明天我就废了你，另找那些年轻貌美的妹子。”张氏遂起杀心，乘孝武帝熟睡之际，和心腹宫女一起用被子将其捂死，然后谎称他在梦中去世。不过这种宫闱秘史，烛光斧影，究竟真相是什么我们无法获悉。  
司马曜“耽于酒色，末年，殆为长夜之饮，醒治既少，外人罕得接见。故多居内殿，流连于樽俎之间”。在这种酒池肉林的美好生活当中，即使“彗星提出了警告”，命运却无法改变，他甚至更加沉迷于酒色，痛饮地狱的甘泉，赢得豁达的名声。  
虽然司马曜是汉族王朝第一个公开信佛的皇帝，“姏姆尼僧，尤为亲暱，并窃弄其权”，即使佛教、道教等都有一些理论认为行善积德可以改变命运，但有几个政治大人物能真正信这个？ 他们一生干过的脏事，又怎么靠区区几件好事能洗白？至于宗教信仰能够提高道德水准，更是不着调的言辞。  
于是在这寒冬时节，司马曜把晚宴当做离别，把彗星当做朋友，把劝酒当做遗言，为了消解美好生命过于短暂的痛苦，步入最后的狂欢时刻。   

## 6.41  
>殷荆州有所识，作赋，是束皙慢戏之流。殷甚以为有才，语王恭：“适见新文，甚可观。”便于手巾函中出之。王读，殷笑之不自胜。王看竟，既不笑，亦不言好恶，但以如意帖之而已。殷怅然自失。  

- *殷荆州*：荆州刺史殷仲堪，前已多见，善于作文，  
- *有所识*：有所感受。  
- *束皙慢戏*：束皙，西晋作家，他的志向是“研习六经教诲世人，恪守静泊以安定风俗。要在天涯海角、偏远山岭与郑玄、严子陵做邻居同伴。视宇宙为一生行进的车舆，视天地为一生居住的房舍。神游于没有竞争的山林，心存无需经营的居室，功名利禄不扰动自己的感受，忧伤不进入自己的梦境……”  
他写过一些轻慢戏谑的文字开玩笑，譬如写《饼赋》，说面饼“弱如春绵，白如秋练。气勃郁以扬布，香飞散而远遍。行人失涎于下风，童仆空嚼而斜眄。擎器者舔唇，立侍者干咽”，这种绘声绘色用赋来描述一块大饼如何引发食欲，有点大材小用，显得夸张滑稽，稍微有点像当代大作家贾平凹写痔疮、放屁之类的散文。他还有一些赋体作品描写普通人生活和讽刺官吏的。这虽然是的一股写作的清流，但在当时的文化背景下，一般的读者认为登不了大雅之堂，“鄙俗”，“时人薄之”。刘勰在《文心雕龙-谐隐》中就说这种写法“辞浅会俗，皆悦笑也”“无益时用”“曾是莠言，有亏德音”。  
殷仲堪“以文义著称”，欣赏这种文笔，也试着写。他和“身无长物”的王恭是好朋友，但王恭和他的审美趣味不一样，而且“性抗直”“矜贵”“每正色直言”，曾有当面批评掌权的司马道子和谢石唱民间流行小曲“委巷之歌”等故事。殷把文章拿给他看，估计是想脏王恭的眼睛，看他吹胡子瞪眼睛的样子。但没有等来王恭的“笑点”和“薄之”，王只是看完，把文章放在桌子上，用如意压着，于是殷怅然若失。  
罗兰.巴特尔曾经说过：对“我爱你”，真正的拒绝是：“无可奉告。”这样，我由此遭受的打击比作为求爱者受挫还要惨重——我是作为一个说话的主体被否定的；被否定的是我的语言，我生存的最根本的手段，而不是我的欲求；至于求爱，我完全可以耐心等待，再次请求，再次提出；但连发问探询的权利都被否定了，我就算彻底“完蛋”了。  

## 6.42  
>羊绥第二子孚，少有俊才，与谢益寿相好。尝蚤往谢许，未食。俄而王齐、王睹来，既先不相识，王向席有不说色，欲使羊去。羊了不眄，唯脚委几上，咏瞩自若。谢与王叙寒温数语毕，还与羊谈赏；王方悟其奇，乃合共语。须曳食下，二王都不得餐，唯属羊不暇。羊不大应对之，而盛进食，食毕便退。遂苦相留，羊义不住，直云：“向者不得从命，中国尚虚。”二王是孝伯两弟。  

- *谢安*和*羊绥*要好，孙子谢混和儿子羊孚要好。羊孚就是写“资清以化，乘气以霏。遇象能鲜，即洁成辉”“启晨光于积晦，澄百流以一源”的那位作家，以文章著称，前已多见。  
- *蚤*：通“早”，起初清晨叫做“旦”，后来“蚤”先代替了旦，然后才出现“早”。  
- *王齐*（大名王熙）、*王睹*（大名王爽）是王恭的弟弟，太原王氏。王谢高门，谢混是司马曜的女婿，两王是司马曜的舅子，从这个意义上讲两王还是谢的长辈。  
- *向席*：入座。  
面对两王的逐客之意，羊孚毫不买账，实行最高的轻蔑，“眼珠子都不转一下，把脚放在茶几上，吟咏顾盼，旁若无人”。谢混也不买账，礼节性地与两王寒暄几句，便马上转过来与羊谈古论今。两王发现羊孚确实是被殷仲堪褒奖的后起之秀——“新拔者”（4.62），这时候买账了，收起国舅爷的架子向羊孚讨教。羊孚架子依旧，“不大应对之”，开始专心吃早饭，吃完走人。两王好学不倦，居然替谢混苦苦留客，想多听点教导，羊孚坚决不留（“义”，程度副词）：“我刚才知道你们的脸色，不肯走是因为要蹭饭。现在肚子（中国）饱了，还留在这里干啥！”  
这个故事是雅量而不是任诞、简傲。羊孚面对两王的逐客脸毫不在意，面对两王的恭敬脸也毫不在意，那是因为胸怀宽广做到了宠辱不惊，实现了心灵的纵横自在，它来自于庄子的“逍遥游”。两晋虽然实行九品中正制，但由于玄学产生的自由力量，使这种政治体制出现缝隙，透进光亮。即使是各式各样的铁幕之中，星依旧挂在夜空，人性依旧长出枝条，自由依旧高贵崭新。  
“请你闪到一边，不要挡住我的阳光”，第欧根尼面对亚历山大，若无其事的话语依旧从千百年前传来，闯进某些人的心灵。  

## 六、雅量 小结  
雅是一种器皿，本来是乐器，《周礼》中说：“笙师，掌教吹竽、笙、埙、籥、箫、篪、篴、管、舂牍、应、雅，以教祴乐。”东汉末郑玄注解说：“雅，状如漆筒而弇口，大二围，长五尺六寸，以羊韦鞔之，有两组疏画。”后来刘表把类似的酒具也叫做“雅”，曹丕在《典论》中说：“刘表有酒爵三，大曰伯雅，次曰仲雅，小曰季雅。伯雅受七升（胜），仲雅受六升，季雅受五升。”能喝这么多酒的人，自然就是“雅量”。雅就有了“大”的意思，到了近代还在使用其义，譬如《文明小史》中说：“这位康伯图兄，是这里发财洋行里的华总办，酒量极雅。”  
雅量就是器量，深而广的器量就是大度。在《三国志-周瑜传-注》中蒋干评价周瑜“雅量高致，非言辞所间”，就是说他器量高远。刘备离间孙权、周瑜，也说周瑜“器量广大，恐不久为人臣耳”。在《北齐书-皇甫和传》中说皇甫和：“及长，深沉有雅量，尤明礼仪。”  
雅量在词义上和高雅、从容等没有关系，有些学者理解有点马虎，望文生义，往往会说雅量是指高雅从容的气量，当然，由于大度会显得高雅、从容等，但这些都不是雅量的本义。有些学者还把世说里面其他章节的一些故事说成雅量，看似铺陈丰富了雅量的内涵，这也不过是拉扯篇幅，为情造文，理解偏差。  
雅量是德行的一个分支，那么为什么不把“雅量”放在“德行”里面呢？“德行”有涉及“雅量”，譬如郭太评价黄宪：“汪汪如万顷之陂，澄之不清，扰之不浊，其器深广，难测量也”，王戎评价嵇康“未尝见其喜愠之色”，但这两个是评价性话语，不是故事。德行主要来源于孔子学生的经历，主要是指见贤思齐、孝顺受礼、甘于贫寒等善言善行，而雅量主要是指处理个人情感的风采，和德行有区别。  
雅量是后天的修养，不是自然状态，不来源于《老子》。按照老子的说法，人的理想状态是“婴儿”“赤子”，任其自然，淳朴天真。他也说“水”，注重于水谦虚柔弱不争的“特性”，涉及包容的概念，但和大度还有距离。  
雅量首先和最集中的体现是视死如归。生死之间有恐惧，柏拉图在《斐多》中说，哲学就是死亡的练习。在雅量一章中，嵇康临刑、夏侯玄雷劈、庾亮兵败、谢安遇涛遇鸿门宴、王献之家里着火等面对生死考验，他们颜色不改，泰然自若。这种战胜天性、克服恐惧的行为来源，不是孟子的“浩然之气”，认为自己是对的而产生坚持真理的坚贞气节；也不是佛教色空学说四谛理论，把肉体人生视为苦海无明，反现世反社会，一心解脱；而是《庄子》生死观的引申发挥。无论是《庄子》的内篇和外篇，对生死的态度基本一致，“生寄死归”，如“春夏秋冬四时行也”，要忘却生死，超凡脱俗，跟随自然之道，“弃世则无累，无累则正平，正平则与彼更生，更生则几矣”。也就是说，生死是一个整体，都是自然的一部分，自然永恒存在。人要在精神上站到“道”的高处，与自然融为一体，世俗的纷乱、生死的考验无非是涵养宁静的练习，此身无非寄寓石火光中，不沾尘埃就没有尘世肉身的牵绊，人进入无限时刻，于是成就了“大”。  
除却生死，还有荣辱。比较而言，中国人善于忍，但低层次的忍是利益考量，甚至是一种权谋术，“所图甚大”。就连被称为文殊、普贤化身的佛教徒寒山、拾得也恶狠狠地说：“只是忍他、让他、由他、避他、耐他、敬他、不要理他，再待几年，你且看他”，这不是以直报怨的德行，而是阴谋家的嘴脸。魏晋玄学发挥了另一种庄子的思路——圣人在有情无情之间，“定乎内外之分，辨乎荣辱之境”。玄学家何晏认为，“圣人无喜怒哀乐”“凡人任情，喜怒违理”；另一个玄学家王弼做了一些矫正，认为圣人有情，“圣人之情，应物而无累于物者也”。他举例说，孔子在看见颜渊就高兴，听到颜渊死亡便悲哀，圣人亦“不能无哀乐以应物”，不过圣人精神高大，“神明茂于人”，“体冲和以通无”，以淡泊平和达到“无累”的境地。也就是说，只要作为人，哪怕是婴儿赤子、圣人神人，也是有情的；但通过修养，使精神壮大，性格平和，就能不为外物牵制，就在“有情无情之间”。于是我们看到了两晋时期几位名人王衍、裴遐、裴頠、周顗、谢安、谢玄等面对拳脚、羞辱等时，“徐曰”“笑曰”“徐云”“意甚平”。他们认识到，应激性的愤怒或者压制愤怒，本质都是被外物所伤害，没有必要在蜗牛角上争是非，能平静应对则进入了新境界。通过不断体悟，人可以从小境界进入大境界，从大境界进入更大的境界，如此下去，实现庄子所谓的“以游无穷”。  
雅量收获平静。作为修养，不仅仅是面对生死荣辱，而是面对一切都要心静。《大学》中说：“知止而后定，定而后能静，静而后能安”，诸葛亮说：“静以修身，俭以养德”。静实质是指和外部世界保持一定的距离，实现心境空灵。静更是一种政治修养，《庄子-天道》（外篇）更是反反复复谈“静”的重要性：圣人“万物无足以铙心者，故静也”“圣人之心静乎！天地之鉴也，万物之镜也”“虚静恬淡寂漠无为者，万物之本也”。心神宁静，像镜子一样测览世界，越是澄明，越能明察秋毫。特别作为政治人物来说，雅量越大，内心就越静越明，越能洞察世事，采取的政治行动就正确，这就是晋人所谓的“宰辅之器”。静是动中的静，是蝉噪林逾静，鸟鸣山更幽。玄学家们通宵达旦激烈辩论，哪里是静？两晋朝廷高官们始终在打打杀杀，哪里是静？不，这都是静，是玄学家面临“静”的试题，获得“静”的途径。在闹哄哄的绣球招亲项目中，王羲之坦腹东床表现了静；无论是收到噩耗还是喜报，顾雍、王导、谢安等内心都波涛汹涌，但表现了静；战马失控，兵戈纵横，司马昱、王劭、王恭等做到“穆然”“不动”，表现了静……尘世喧嚣，我自安定，“安而后能虑，虑而后能得”。  
雅量就是认清自我和他者后的心灵自由。阮孚：我喜欢鞋子，这是我的自由，没有什么见不得人。许璪：我困了就睡，即使在长官家里，我不会睡不着。庾翼：我骑术好，表演时马失前蹄，纯属意外，没啥难为情。羊曼：我家里有菜，招待你好一点，菜没了，对不起，是因为你来晚了。褚裒、羊孚：你看不起我，但我还是我，看得起看不起是你的事情，我照样和你一起吃，吃完就走。戴逵：我就是喜欢琴书艺术，你和我谈这个最好，谈其他的我还不想说……他们一起发声：大度的人会领会我的大度，狭隘的人会掉进蝇营狗苟的泥沼。  
雅量来自于对山水之美的欣赏。心斋冥想是通往“精神大道”的小道，而游山玩水是通途。雅量42则，东晋人物30则，而东晋正是开始把旅行当做精神需要的时期，自然成为主体精神的对应物，情感的直接寄托。在“言语”中我们可以直接体察名士对山水的一往情深。谢万的“渊注渟着，纳而不流”哪里是在说湖泊啊，而是说胸襟；王胡之的“非唯使人情开涤，亦觉日月清朗”，直接就是说湖泊让人心情开阔，天高地远；袁宏“江山辽落，居然有万里之势”的这种话语在前人那里看不见。“雅量”里的主人公们，很多都是不务事业、“纵意游肆”的驴友，庾亮登高赏月的佳话，谢安、王羲之等出入风浪之中，悠游江南山水，王献之“从山阴道上行，山川自相映发，使人应接不暇。若秋冬之际，尤难忘怀”，正如戴逵所说：“澹泊之愿，于是毕矣”。  
比天空更广阔的，是人的雅量。  

## 7.1  
>曹公少时见乔玄，玄谓曰：“天下方乱，群雄虎争，拨而理之，非君乎！然君实乱世之英雄，治世之奸贼。恨吾老矣，不见君富贵，当以子孙相累。”  

- *累*：拜托（使你受累）。  
- *曹操*的父亲*曹嵩*（司隶校尉、大司农、大鸿胪、太尉）本姓夏侯，后来过继给汉末大太监之一的曹腾（中常侍、大长秋，皇后近侍官首领）做养子，走上政坛。曹嵩在曹家的堂兄弟是曹炽（侍中、长水校尉，皇宫保卫军长官之一），曹炽有两个儿子曹仁、曹洪。曹嵩在夏侯家时与夏侯惇父亲是兄弟。所以曹操和曹仁、曹洪，夏侯惇、夏侯渊都是或近或远的堂兄弟，这就是安徽亳州曹操起家的班底。显然，此出身为皇家亲信，气焰熏天，又能积累司法、军事工作经验，但走的是宦官路线，很不光彩。所以曹操晚年在《明志令》中说：“自以本非岩穴知名之士，恐为海内人之所见凡愚”。  
曹操是官三代，小时候极为顽劣，“飞鹰走狗，游荡无度”。曹嵩把他送到桥玄（司徒，后任太尉、太中大夫）那里学习，扭转了一些名誉，“由是声名益重”。后来他曹操时时感念这位启蒙老师，曾经在《祀故太尉桥玄文》中说：“故太尉桥公……吾以幼年，逮升堂室，特以顽鄙之姿，为大君子所纳。增荣益观，皆由奖助，犹仲尼称不如颜渊，李生之厚叹贾复。士死知己，怀此无忘” （大意是，我于幼年拜你为师，只是以我浅陋愚钝的资质，被你这大名人所接纳器重。这给我增加了荣誉，提高了身价，凡此都是由于您的赞扬和帮助，就像孔子说自己不如颜渊，东汉初李生老师非常赞赏左将军贾复一样。古语有 “士为知己者死”，我心里记着这句话而不能忘怀）。  
桥玄还指点青年曹操去拜访当时主持人物品评的“百晓生”许劭。许劭听说了曹操小时候飞扬跋扈的故事，看了曹操写的兵法书，评价说：你是治世之能臣，乱世之奸雄（也有说是“清平之奸贼，乱世之英雄”，反正随着曹操不同的经历阶段，这个评语的版本不断修改）。  
桥玄年老，曾经对曹操说：我死后你经过我的墓地，你要用酒和鸡来祭祀请我吃。如果你做不到，到时候肚子痛不要怪我。曹操赢得官渡之战后，经过桥玄的墓地，以“太牢”的礼仪祭祀。  
这是曹操和桥玄交往比较真实而温情的故事，也许正是桥玄的这种褒奖赏识，提升了曹操的品格，使其树立了远大志向，使一个调皮捣蛋的纨绔子弟走上了正途——“欲为一郡守，好作政教，以建立名誉”。青年时期的曹操，其实都是在希望自己成为将来的一个好太守而努力。  
《世说》融合了其中一些片段，集中笔墨编了两个人的故事，盖棺定论指出曹操是乱世之英雄（聪明秀出谓之英，胆力过人谓之雄）。不过曹操的流氓气息还是时时流露，譬如他干过一些垃圾事，并说：宁我负人，毋人负我。他的破事和话也成为后世一些流氓罪犯的借口。  

## 7.2  
>曹公问裴潜曰：“卿昔与刘备共在荆州，卿以备才如何？”潜曰：“使居中国，能乱人，不能为冶；若乘边守险，足为一方之主。”  

曹操和刘备曾经惺惺相惜。刘备曾经投靠朝廷，曹操上表汉献帝让刘备做左将军，与其“出则同舆，坐则同席”，甚至夸他“体现英雄，为使君与操耳”。刘备先后投靠公孙瓒、陶谦、吕布、曹操、袁绍、刘表，就是一只丧家犬啊，他还偏偏处处受礼貌上的款待，那么刘备究竟有什么让豪强高看一眼呢？  
刘备是宗室之后，年轻的时候拜“海内大儒，士人之望”卢植为师，登了“龙门”，受到舆论肯定；刘备志向远大，始终“忧国忘家，有救世之意”，有“刘郎才气”，做事起点就高；刘备白手起家，没有任何根基，大半辈子屡败屡战，有百折不挠的精神，让人感佩；刘备用钱大方，“内丰财施”“厚树恩德”，胸怀宽广，“弘毅宽厚，知人待士”，“弘雅有信义”，对部下“尽其器能”，于是始终有人不离不弃，“年少争附”“众多归”；刘备不是影帝，他临死时还交待刘禅，“勿以恶小而为之，勿以善小而不为。惟贤惟德，能服于人。汝父德薄，勿效之”。刘备之所以反反复复投靠别人，那是因为“投靠的人器量狭窄，容不下他，并不仅仅是要和他们争权夺利，更是为了避免祸害”（终不为下者，抑揆彼之量，必不容己，非唯竞利，且以避害云尔）。对政治人物来说，道德往往“比黄金还珍贵”，刘备是自古以来极少数具有高尚德行的领导人。  
- *裴潜*为河东裴氏，山西闻喜人，先避乱投靠刘表，与刘备相识。后发现刘表有名无实，就投靠曹操，逐渐成为第一流的高官，历任兖州刺史、荆州刺史、大司农、尚书令、光禄大夫等。他的言下之意是刘备与曹操相比，在治理能力上有所不足，但也足以成为一方诸侯。刘备后来真的占领了蜀地，和曹魏长期对峙，在汉中把曹军打得落花流水，说明裴的识人之明。当时无论是敌我双方，大家都认识到刘备的不凡，称之为“雄才”“人杰”“英雄”。  

## 7.3  
>何晏、邓飏、夏侯玄并求傅嘏交，而嘏终不许。诸人乃因荀粲说合之。谓嘏曰：“夏侯太初，一时之杰士，虚心于子，而卿意怀不可交，合则好成，不合则致隙。二贤若穆，则国之休。此蔺相如所以下廉颇也。”傅曰：“夏侯太初，志大心劳，能合虚誉，诚所谓利口覆国之人。何晏、邓飏，有为而躁，博而寡要，外好利而内无关龠，贵同恶异。多言而妒前，多言多衅，妒前无亲。以吾观之，此三贤者，皆败德之人耳，远之犹恐罹祸，况可亲之邪！”后皆如其言。  

- *何晏*是曹操的干儿子、女婿，吏部尚书；夏侯玄是大将军曹爽的表弟，征西将军，玄学家、大名人，前已多见；邓飏是曹爽的铁杆亲信，侍中、尚书；一般而言，他们是一帮子皇亲国戚，傅嘏在当时排不上号，不至于扎堆主动要和傅嘏交朋友。这个故事估计出自于傅嘏事后诸葛亮之口，所以李慈铭、余嘉锡等人认为这条记录不可信，“捏造之词”。从史料看上，何晏等人是曹家帮，傅嘏是司马家的走狗，双方诋毁倾轧言行不断，最后无非是成王败寇。
- *荀粲*是荀彧的儿子，与夏侯玄、傅嘏都要好。而且这个故事中，荀粲也仅仅是说，夏侯玄想和傅嘏交朋友，和何晏、邓飏没有关系，为什么傅嘏批评完夏侯玄，接着批评何晏、 邓飏呢，这不是摆明多事吗？  
- *好成*：好事成了。或者是“成好”，成就好事。  
- *休*：美好。《易-大有》：顺天休命；《铜雀台赋》：休矣！美矣！惠泽远扬。  
荀粲居然把夏侯玄比作廉颇，傅嘏成了蔺相如，这是什么比喻啊？
- *利口覆国*：《论语》子曰：“恶紫之夺朱也，恶郑声之乱雅乐也，恶利口之覆家邦者。” 孔安国注：“利口之人，多言少实，苟能说媚时君，倾覆国家。”  
- *躁*：《论语》子曰：“侍于君子有三愆：言未及之而言谓之躁，言及之而不言谓之隐，未见颜色而言谓之瞽。”意思是说，大人物话还没谈到那里，你就抢着说了，那是急躁。  
- *博而寡要*：司马迁《太史公自序》：“儒者博而寡要，劳而少功”，意思是说，儒家学说广博但殊少抓住要领，花费了很大气力功效却很少。  
- *关龠*：门闩或者钥匙，这里指原则。《老子》：“善闭者无关籥，而不可启也；善结者无约，而不可解也。”对外好利益交换，内心没有原则。  
- *多言而妒前*：多言，孔子认为，君子讷于言而敏于行；《周易-系辞》中说：“吉人之辞寡，躁人之辞多”。妒前，嫉妒站在自己前面的人（比自己厉害的人）。话多就招惹是非，挑起战斗；嫉妒比自己厉害的，就不可能有亲近之人。  

傅嘏以人品论事业不靠谱，言下之意朝廷公正，三个人不会有好下场。即使这三个人都像傅嘏说的那样“败德”，自古以来政坛基本是黄钟毁弃，瓦釜雷鸣，而且命运混不可测，随机事件比比皆是，以道德好坏看官员的最后结局，肤浅荒诞，往往都是事后之词。  
我无法理解某些人的思路，天底下真的有人相信善有善报，恶有恶报？司马家发家极不光彩，卑鄙下作的行径令他们的子孙都掩面自惭，但是司马炎受禅之日是多么风光！嵇康如玉山孤松，而且恬静无欲，怎么就身死人手？《鲁拜集》中说：如若天下事能以公平之尺衡量，如若人世生活令人满意舒畅，如若天地间当有公平两字，正直人怎会有百结的愁肠？  

## 7.4  
>晋武帝讲武于宣武场，帝欲偃武修文，亲自临幸，悉召群臣。山公谓不宜尔，因与诸尚书言孙、吴用兵本意。遂究论，举坐无不咨嗟。皆曰：“山少傅乃天下名言。”后诸王骄汰，轻遘祸难，于是寇盗处处蚁合，郡国多以无备不能制服，遂渐炽盛，皆如公言。时人以谓山涛不学孙、吴，而暗与之理会。王夷甫亦叹云：“公暗与道合。”  

中国古时候的领导干部没条件上当代政治学、公共管理等课程。即使有的上了似乎有点关系的课程，教材的问题也很大。《老子》原则性的阴谋诡计，《韩非子》的残忍霸道，《论语》《礼记》的迂腐浅陋，即使后出的《资治通鉴》，洋洋洒洒几百万字的流水账，没有逻辑推理演绎，也见不着管理偌大国家的理论，看不完，抓不住要害。所以有些领导干部的专业知识缺乏，爱好非常奇特，见识令人瞠目结舌。譬如司马炎，居然头脑时常发热，以为天下一统后，自己管理水平高得如同日月，应该刀枪入库，马放南山，在他的卓越领导下大家一起享福；以为立下规矩裁军，把各省市的兵马都撤了，家族诸侯就没家底造反，天下就太平；以为儿子是笨蛋没有关系，只要孙子聪明，辅政大臣忠心耿耿，早点传位就江山永固；他甚至计划钓鱼执法行动方案，派人向官员行贿，然后抓住把柄惩治所谓的腐败……他的这种发烧病来源于权力的迷之自信，以为真的有大气运在身，而且自己拥有天底下最睿智的头脑，一切都在其掌握之中。他的这些举措，前后辈领导干部都在犯，留下一个个反复、无用的血腥动乱教训，直到现在有些国家改变了专制独裁的权力架构，才有所改变。  
- *偃武修文*：《晋书-职官志》：“大国中军二千人，上下军各千五百人，次国上军二千人，下军千人。其未之国者，大国置守土百人，次国八十人，小国六十人，郡侯县公亦如小国制度。”大意是说，司马炎机构改革搞分封制和裁军，其中立了数十个宗室和皇子形成的司马家诸侯国，大国军事力量5000人，中国3000人，小国1000人。同时，如果诸侯王没有去封地，那么设地方部队，大郡保留100人的军事力量，中郡80人，小郡60人。对了，中央还有禁卫军1万人。这种政治妥协和军事布局，也许在他活着的时候，靠个人光环，大家利益均沾，相安无事。但他一死，其制度弊端立刻显现，设想中的军事力量互相牵制毫无意义，八王之乱爆发，少数民族入侵，地方兵力不足，中国陷入百年战争之中，这时候自然是盗匪横行，“盗贼群起，州郡无备”。
- *遂究论*：于是研究讨论。山涛执反对意见，详尽地阐述了这种机构改革的弊端，“国者不可以忘战”，郡州不能就这么一点点兵力，大家都认为说的对。啊，说的对？说得对有什么用？说的皇上喜欢才是对的啊。  
- *轻遘祸难*：很轻易地造成祸乱。  
- *暗与之理会*：《孙子兵法》：“兵者，国之大事，死生之地，存亡之道，不可不察也”；《吴子兵法》：“昔承桑氏之君，修德废武，以灭其国；有扈氏之君，恃众好勇，以丧其社稷。明主鉴兹，必内修文德，外治武备。”  

很多政策初衷也许不错，但是现实很骨干，常常事与愿违。有些人早就发现了，不说。有些人说了，没用。已经执行了，大家都知道以前做错了，但不挽救。犯了错其实并不要紧，要紧是改正错误的决心和行为。改正错误，任何时候都不晚，改一点是一点。显然，作为后来的执政大臣王衍，也仅仅是夸山涛见识不凡，他没有采取任何行动。  

## 7.5  
>王夷甫父乂，为平北将军，有公事，使行人论，不得。时夷甫在京师，命驾见仆射羊祜、尚书山涛。夷甫时总角，姿才秀异，叙致既快，事加有理，涛甚奇之。既退，看之不辍，乃叹曰：“生儿不当如王夷甫邪？羊祜曰：“乱天下者，必此子也。”  

- *王乂*：琅邪王氏，父亲幽州刺史王雄，哥哥王浑凉州刺史，儿子王衍太傅，王澄荆州刺史，侄儿王戎太傅。  
- *行人*：使者。三国时的刘劭《人物志-流业》：“辩给之材，行人之任也。”清代王韬《星轺指掌序》：“行人之设，肇自古昔，然皆王国下逮侯邦；而诸侯亦各相聘问，藉以讲信修睦。”  
- *总角*：少年，见4.14。当时王衍14岁。  
- *叙致*：述说。见4.42：“王叙致作数百语，自谓是名理奇藻。”《宋书-刘湛传》：“善论治道，并谙前世故事，叙致铨理，听者忘疲”。宋代孔平仲《使纸甚费》诗歌：“叙致失轻重，畏慎防触抵”。  
- *快*：流畅。
- *事加有理*：处理事情有条理。《后汉书-本纪-皇后纪上》：“后自侍疾病，至乎终尽，忧哀毁损，事加于常”，《晋书-庾衮传》：“抚诸孤以慈，奉诸寡以仁，事加于厚而教之义方”  

王衍是当时第一美少年，“盛才美貌，明悟若神”。对于山涛来说，王衍是“别人家的孩子”；对于羊祜来说，王衍是他的外甥，羊祜更加了解，所以要贬低，表示不以为然。不过故事还有一个版本，《晋书》中说，涛嗟叹良久，既去，目而送之曰：“何物老妪，生宁馨儿！然误天下苍生者，未必非此人也。”“衍年十四，时在京师，造仆射羊祜，申陈事状，辞甚清辩。祜名德贵重，而衍幼年无屈下之色，众咸异之。”历史记载就是这样，“所见异辞，所闻异辞，所传闻异辞”，你愿意选择相信哪一个？  
王衍在西晋后期执政，西晋在他手里亡国，而且他被俘杀害，临终表现恶劣。他曾经反反复复装傻来逃避政治祸害，曾经布置众多手段来保全家族势力和自身安全，看似聪明；他器量大，口才好，不爱钱，见识高，看似风流；但他在其位而不谋其政，没有采取过一点点措施来纠正从前朝廷明显错误的政策和做法，作为一个政客，就是罪人。  

# 7.6  
>潘阳仲见王敦小时，谓曰：“君蜂目已露，但豺声未振耳。必能食人，亦当为人所食”。  

- *小时*不确。309年，潘滔是太傅司马越的长史，在此期间王敦任扬州刺史，已经40多了，潘滔向司马越提出了反对意见：“王处仲蜂目已露，豺声未发。今树之江外，肆其豪彊之心，是贼之也”。即使再往前推，299年，王敦和潘滔结识的时候，王敦为太子舍人，潘滔太子舍人，他也30岁了。《世说》为小说家之言，夸张之处颇多，或事出有因，但追求文学性，常常采取变形的表述。  
- *蜂目豺声*：《左传》：“蜂目而豺声，忍人也”；《史记-秦始皇本纪》：“秦王为人，峰准，长目，挚鸟膺，挚，豺声。少恩而虎狼心，居约易出人下，得志亦轻食人”；《汉书-王莽传》：“莽所谓鸱目虎吻，豺狼之声也，故能食人，亦当为人所食”。蜂目应该是指眼睛大而凸，也有人说就是指目光凶狠；豺声是声音嘶哑。古人认为这种人心狠手辣；残忍的人会有报应，“为人所食”。这种相术是原始思维的表现形式，马蜂在昆虫中算是毒的，豺在哺乳动物中很凶狠，人的长相声音具有其中一些的一些特征，就很容易让人联想到性格。从另一个方面说，桃花眼、水蛇腰贬义，不过杏眼蛮腰就成了褒义。眼睛大声音沉又何尝不是一种颜值呢？相术这种东西无非就是幸存者偏差，流传下来的都是准的证据。  

潘滔讲的不是相术，而是一种比喻。他的潜台词也许是：王敦此时居于扬州刺史的高位，具有了占据要害之地为一方诸侯的条件，如同马蜂已经筑巢；但军事力量还不强大，还不能像豺狼一样为祸一方。按他的性格和已有条件，发展下去，就是危害社会，但终将危害自己。众所周知，王敦的品德有大缺陷，他的梦想越远大，后果就越严重。这个是远见。  

## 7.7  
>石勒不知书，使人读《汉书》。闻郦食其劝立六国后，刻印将授之，大惊曰：“此法当失，云何得遂有天下！”至留侯谏，乃曰：“赖有此耳！”  

- *石勒*是山西羯族人，兵荒马乱之时从事贩卖奴隶的勾当，反而被人抓了做奴隶。然后落草为寇，投靠军阀逐渐起家。后来抱上匈奴头子刘渊、刘聪的大腿。319年脱离后汉，自立赵王，330年自称大赵天王，当了皇帝。  
他没文化，但作战勇猛，悟性高，善于投机，自信心强。322年，有一次他宴会酒酣之余，询问群臣，他可比历史上哪位皇帝？重臣徐光赞颂石勒：“神武筹略胜过了刘邦，雄艺卓荦超过了曹操，夏商周三代以来无可比拟，黄帝以下独此一人。”  
石勒哈哈大笑说：“人哪能没有自知之明，你说的太夸大。我若是碰上刘邦，当面向北侍奉他，挥鞭与韩信、彭越争先后，若是遇上刘秀，当与他在中原并驾齐驱，尚不知鹿死谁手。大丈夫做事应该像日月一样光明磊落，不能像曹操、司马懿父子，欺负人家孤儿寡母，靠阴柔手段来夺取天下。我应该在刘邦与刘秀之间，哪能与轩辕氏比拟呢！”  
他为什么莫名其妙提到曹丕、司马炎篡位的事情？因为他有块心病。他后期打天下基本靠另一个杀人魔王、干弟弟石虎，尾大不掉，儿子明显搞不过他，把权力交给他又不甘心，于是试图靠石虎良心发现。  
故事的后半场有点搞笑。杀人魔王石勒居然晚年寄希望于石虎对历史的敬畏感，在遗诏中说：石虎你要深深三思周公和霍光的德行和故事，不要写下遗臭万年的记录。石虎当然不吃他这一套，石勒死的当天石虎就杀进王宫，挟持石弘，并干掉一些不投靠他的大臣。石弘三番四次求着要禅位于他，石虎拒绝。最后一次石虎说：“石弘愚昧昏暗，服丧无礼，应当将他废黜，谈什么禅让！” 最终杀光了石勒的妻儿，自己当了皇帝。石虎杀自己的妻儿也毫不手软，匪夷所思。最终石勒、石虎家族下场比司马家有过之而无不及，说明由于制度缺陷，游牧民族权力交替过程的血腥，衰败迅速。事实说明，石勒和刘秀、曹操、司马懿差好几条街  
- *劝立六国*：刘邦和项羽争霸，战况不利。郦食其给刘邦出主意，把自己获得的资源拿出来分封给原来六国诸侯王的后裔，这样他们就会感恩戴德，站出来主动和项羽斗，牵制项羽精力，这样刘邦就能反败为胜。张良认为这样一分封，刘邦手下的部分谋臣将士肯定会去投靠那些诸侯，甚至那些诸侯看到项羽势大，反过来依附项羽和你斗，你怎么办？幸亏郦食其还没有出发，这个计划夭折。  
　　
石勒在这个方面见识强，但是一个人不可能处处见识强。议论别人容易，可是到自己身上就犯糊涂。石勒死后，石虎把他秘密埋葬，连葬哪里都不知道。“夜瘗山谷，莫知其所，备文物虚葬，号高平陵。”  

# 7.8  
>卫玠年五岁，神衿可爱。祖太保曰：“此儿有异，顾吾老，不见其大耳！”  

- *卫玠*：如同璧玉般的卫玠，“名士第一”，祖父太保卫瓘，岳父乐广、山简，前已多见。  
- *神衿*：神襟，精神胸怀。唐代吴筠《秋日望倚帝山》：“远峰列在目，杳与神襟契。”还有一个版本，卫瓘说卫玠“神爽聪令”。  
- *可爱*：让人喜欢。《世说新语-赏誉》：“士龙为人，文弱可爱”，《世说新语-纰漏》：“童少时神明可爱”。  
- *有异* ：不同寻常，非比寻常。  
- *顾*：只是。第二年卫瓘去世。  

## 7.9  
>刘越石云：“华彦夏识能不足，强果有余。”  

- *华轶*华彦夏是曹魏时期华歆的曾孙，永嘉之乱时为振威将军、江州刺史。307年，虽然司马睿在王导的辅佐下在建康自立门户，但华轶认为晋怀帝司马炽还在洛阳，不肯依附于司马睿。311年，司马炽被刘渊所俘，司马睿承制改易，重新任命官员，华轶拒不服从。后司马睿派人讨伐，华轶兵败身死。  
闻鸡起舞的刘琨认为华轶见识能力不足，强硬果敢有余。当时陶侃的侄儿陶臻任华轶的参军也对陶侃说：“华轶有匡扶天下的大志，但没有多大才能，并且和司马睿有矛盾，灾祸就快来临了。”  

## 7.10  
>张季鹰辟齐王东曹掾在洛，见秋风起，因思吴中菰菜羹，鲈鱼脍，曰：“人生贵得适意尔，何能羁宦数千里以要名爵！”遂命驾便归。俄而齐王败，时人皆谓为见机。  

权倾一时的齐王司马冏，302年和长沙王司马乂洛阳激战。司马冏兵败处斩，“徇首六军。诸党属皆夷三族。暴冏尸于西明亭，三日而莫敢收敛。”
- *江东步兵* 张翰 张季鹰，翰就是羽毛，张翰可能排行第四，所以叫季鹰。他是西晋初期的雄鹰，他的同时代老乡兼好友有好些，譬如贺循、顾荣，他们的官位后来很高很高，但除了那些在故纸堆的爬字赚养家钱、评职称的学者们，没有人记得他们。文学的力量超越一时的功名，张翰他高飞的姿态，使之成为精神世界自由的鹰，被很多人记得，并成为冶炼精神的养分。辛弃疾名词《水龙吟-登健康赏心亭怀古》：
>休说鲈鱼堪脍，尽西风、季鹰归未？求田问舍，怕应羞见，刘郎才气。可惜流年，忧愁风雨，树犹如此！

把张翰的故乡情怀，刘备的功业志向和桓温对时间流逝的叹息并列为英雄之感慨。甚至他的家乡苏州吴江，上千年过去了，还祭祀他，筑三高祠，将张翰、范蠡、陆龟蒙并称三高，纪念他们为急流勇退的高士。张翰引发了这么多的共鸣，就是因为他说了一句：我要舒服，要回家吃美食！这句话像天空传来的嘹亮鹤鸣，撩动我们的心弦，产生深深的共鸣。  
对家乡的思念，对童年的回味往往会具化为记忆中美食的味道。我们无论处于何时何地，在做什么事，其最终都是走在“回家”的路上，都是广义的乡愁。而家乡的滋味，乡愁的滋味，不正是当年长辈烧的那些饭菜吗？故乡的水煮茭白，清澈的莼菜羹，雪白、透着光的鱼片，吃上这些东西，还要追求什么呢？曾经有个长辈问张翰：“卿乃可纵适一时，独不为身后名邪？”他回答说：“使我有身后名，不如即时一杯酒。”真正让张翰陶醉的并不是酒，而是过上自在随心的生活。而自在随心的宣言，使张翰获得了身后巨大的名声，成为很多人的诗材，“功名事，今老矣，待何如。拂衣归去，谁道张翰为莼鲈。且就竹深荷静，坐看山高月小，剧饮与谁俱。长啸动林木，意气欲凌虚。”（宋 袁去华《水调歌头》）

## 7.11  
>诸葛道明初过江左，自名道明，名亚王、庾之下。先为临沂令，丞相谓曰：“明府当为黑头公。”  

- *诸葛恢*见5.25，诸葛诞的孙子，诸葛靓的儿子。他本来叫诸葛恢，但永嘉南渡后，立志要让政治清明，所以改名叫诸葛道明。他开始在山东临沂当县令，王家就是琅邪郡临沂县人，算是王导老家的父母官，所以王导尊称他为“明府”。王导喜欢夸奖人，提拔下属，所以夸诸葛恢能够在头发没白之前位列三公。这是王导的做官风格，鼓励为主，笼络人心。  
- *王、庾*：王导、庾亮。  
324年，诸葛恢任侍中，参与执政，40岁成为三公。

## 7.12  
>王平子素不知眉子，曰：“志大其量，终当死坞壁间。”  

- *不知*：不赏识。知音、知遇的“知”。  
- *坞壁*：魏晋南北朝时期为躲避战乱，民间选择宜守宜农之地，建立类似客家族的围屋建筑，大族或地方豪强自为坞主，也有以流民结集的方式出现的坞壁，坞主都由流民公推有才能或宗族势力相对强大者任之。  
琅邪王澄是王玄的叔叔，但王澄不看好“与卫玠齐名”的王玄，说他志向大过器量，做了陈留太守，由于其性格缺陷，在乱世中必将和当地土豪发生冲突，死于地头蛇之手。不过这种预测都有夸张之处，因为猜的准，所以《世说》保留了这段话。  
王澄被族弟王敦所杀，王玄被河南当地人所杀。当时没有飞机，领袖们要跑路都有点难，有时候会像士兵一样被杀。  

## 7.13  
>王大将军始下，杨朗苦谏，不从，遂为王致力。乘中鸣云露车径前，曰：“听下官鼓音，一进而捷。”王先把其手曰：“事克，当相用为荆州。”既而忘之，以为南郡。王败后，明帝收朗，欲杀之；帝寻崩，得免。后兼三公，署数十人为官属。此诸人当时并无名，后皆被知遇。于时称其知人。  

322年，王敦以讨刘隗为名，第一次自武昌东下攻打南京。城破后杀大臣戴渊、周顗，自领丞相，都督中外诸军事。此事前已多见。  
杨朗是前冀州刺史杨准的儿子，据资料说，杨准有六子，曰：乔、髦、朗、琳、俊、仲，皆得美名。论者以谓悉有台辅之望。文康庾公（亮）每追叹曰：“中朝不乱，诸杨作公未已也。”自东汉初的“四知”的杨震起，东汉四世三公，弘农杨氏一直是望族。司马炎死后，杨骏以外戚的身份执政，家族中公侯众多。然后西晋迅速衰弱，弘农杨氏遇到挫折，政治地位下降。杨朗此时就在王敦的帐下，而且坐在中鸣云露车（瞭望车）上担任指挥员的角色。  
- *先把其手曰：“事克，当相用为荆州。”*：握住他的手预先告诉他，赢了的话，荆州刺史就是你的。荆州刺史是东晋最重要的军政岗位，因为拥有荆州之后，就拥有了长江，对南京形成了遏制。王敦、庾亮、陶侃、桓温等都担任过荆州刺史，就可以当权臣。王敦当时是荆州刺史，他战前许诺无非是张空头支票，他不是忘，而是不敢把这个位置付予杨朗，事后让杨朗当上荆州首郡的南郡太守。  
324年，王敦再次进军南京，病死，杨朗被收。在“赏誉”中，王敦曾经写信给王导：“世彦识器理致，才隐明断，既为国器，且是杨侯淮之子。位望殊为陵迟，卿亦足与之处。”杨朗此时已经是王家的铁杆心腹，所以王导肯定保他，以至于司马绍要杀杨朗也受到牵制。后来杨朗在尚书省任三品的曹尚书之一，当部门一把手，负责官员的考核任免。领导最值得称道是多多提拔下属，个个有出息，同事就有干劲，然后报团取暖，形成利益集团，这样执行力上升，社会影响力也大增。   
这一节讲了杨朗的三个故事，一是见识高，苦口婆心劝阻王敦不要兴兵谋逆；二是见识高，判断战事组织进攻并获得胜利；三是见识高，选拔下级使用得当。前面两个故事是为第三个故事做铺垫。问题是，杨朗见识高啊，他为什么要上王敦的贼船，而且如此卖力？后来还下了狱，走在刀锋之上？男儿但得功名立，几人能看破。  

## 7.14  
>周伯仁母冬至举酒赐三子，曰：“吾本谓度江托足无所，尔家有相，尔等并罗列吾前，复何！”周嵩起，长跪而泣曰：“不如阿母言。伯仁为人志大而才短，名重而识暗，好乘人之弊，此非自全之道。嵩性狼抗，亦不容于世。唯阿奴碌碌，当在阿母目下耳。”  

- *周顗、周嵩、周谟*三兄弟的故事见6.21和6.22。周顗为武城侯，荆州刺史，尚书左仆射，被王敦所杀；周嵩为御史中丞，被王敦所杀；周谟侍中、中护军，西平侯，善终。  
- *冬至*是古代的大节日，九九寒冬开始。东汉《四民乐令》中说，“十一日，冬至之日荐羔。先荐玄冥于井，以及祖祢。斋、馔、扫涤如荐豚。其进酒尊长，及修谒剌贺君、师、耆老如正日”，魏晋六朝时冬至称为“亚岁”，晚辈一样要向父母长辈拜节。三周的母亲李络秀接受晚辈祝贺以后赐酒。  
- *有相*：缩略词，有福相。  
- *复何*：缩略词，夫复何求，还有什么要求呢。  
- *乘人之弊*：抓人的短处（整人）。  
- *狼抗*：傲慢暴戾，桀骜不驯。  
- *目下*：眼前，类似于“膝下”，跟前。  

此是识鉴，更是疾世之语，类似于苏轼的“人皆养子望聪明，我被聪明误一生。惟愿孩儿愚且鲁，无灾无难到公卿。”  
在《世说》“贤媛”章中说，李络秀本来是小户人家之女，高官周浚有一次路过她家，看到李的美色就提亲，要求李做他的小妾。李的父兄不答应。李络秀说：“我家门户这么困苦了，怎么还爱惜我这个女儿家呢！如果和贵族联姻，将来或许有大好处。”后来李家就受到了周浚和他三个儿子的提携，成为“方雅之族”。  
小妾生的三个孩子都有出息，在古时候这种情况很少，可能是因为刚好是乱世，即使是九品中正制的背景下，出生卑下的人也有机会出人头地。所以李秀络很得意，很满足。而儿子周嵩在其乐融融的聚会中，明锐地体察到乱世的危险，扫兴地痛哭。有些人为不能出人头地而痛哭，有些人上了床后内心痛苦，但也只能含泪做下去。  

## 7.15  
>王大将军既亡，王应欲投世儒，世儒为江州；王含欲投王舒，舒为荆州。含语应曰：“大将军平素与江州云何，而汝欲归之？”应曰：“此乃所以宜往也。江州当人强盛时，能抗同异，此非常人所行；及睹衰危，必兴愍恻。荆州守文，岂能作意表行事！”含不从，遂共投舒，舒果沉含父子于江。彬闻应当来，密具船以待之；竟不得来，深以为恨。  

324年，王敦病重。司马绍决定讨伐王敦，于是王敦命哥哥王含为元帅，进攻南京，后兵败，王敦病死。王敦无子，王含的儿子王应过继给王敦为嗣子。江州刺史王彬王世儒是王敦的堂弟，曾多次反对王敦的举措，责骂王敦。荆州刺史王舒也是王敦的堂弟，以前被王敦赏识，关系较好。  
- *云何*：怎么样，此处表示反问，其实不怎么样。  
- *抗同异*：又作“立同异”，偏义复词，发表异议。  
- *守文*：本意是遵循周文王的法度，泛指遵循先王法度。《公羊传•文公九年》：“继文王之体，守文王之法度。”又引申为守规矩，《新唐书•姚崇宋璟传赞》：“故唐史臣称崇善应变以成天下之务，璟善守文持正。”  
- *意表*：意外。  

生死寄托，要向当年反对过你的人求援而不是你当年赏识的人求援，这有点类似于另一个纳粹时期的犹太人故事，向帮助过你的人求援而不是你帮助过的人。  
二战时，纳粹迫害犹太人，犹太商人波德默家族商量向非犹太人寻求帮助。两个儿子建议向银行家奥尼尔求助，他曾多次宣称波德默家族是他的恩人，有机会一定报答；父亲认为要向本内特求助，他也是木材商人，波德默家族是跟他打工起家的，后来经他资助，波德默才有今天的家业。于是兄弟俩分头行动，从此失去联系。多年后，由木材商相助逃到日本的哥哥艾森•波德默回国寻找弟弟，但弟弟全家已死在集中营。哥哥从纳粹档案中找到了举报弟弟的电话记录，正是那位银行家奥尼尔。  
犹太人的故事也许仅仅是个故事，但王含事件却是史实，而且有内在逻辑。当年王敦杀政敌周顗，王彬就怒骂王敦“抗旌犯顺，杀戮忠良，谋图不轨，祸及门户”“后敦议举兵向京师，彬谏甚苦”，大家认为王彬“方直”。王应的思路是正直的人就会怜悯，可以信任寄托，而墨守成规的人不能生死相托。  
王舒的做法蛮出人意外的，亲戚来投奔你，你可以拒绝，但不能杀害。他看似立功，但公道自在人心，历史会有评说。唐代的《晋书》就认为“王彬舣船而厚其所薄，王舒沈江而薄其所厚，较之优劣，断乎可知”，王舒“声颓暮年”。  

## 7.16  
>武昌孟嘉作庾太尉州从事，已知名。褚太傅有知人鉴，罢豫章还，过武昌，问庾曰：“闻孟从事佳，今在此不？”庾云：“试自求之。”褚眄睐良久，指嘉曰：“此君小异，得无是乎？”庾大笑曰：“然。”于时既叹褚之默识，又欣嘉之见赏。  

- *孟嘉*是陶渊明的外公，其故事见于陶渊明《晋故征西大将军长史孟府君传》，多是说他如何高雅风流的名士风度，并无才智功业文章之事。孟嘉因为当官“不知风俗得失”得庾亮的赏识，担任荆州劝学从事（类似于教育局副局长）。  
- *褚裒*和*庾亮*一样都是外戚，庾亮是晋明帝司马绍的大舅子，褚裒是司马绍儿子晋康帝司马岳的岳父。  
- *眄睐*：顾盼，左右看。旁视曰眄，旁视曰睐。  
- *默识*：在不言中识别人物。  

集权专制社会个人的价值追求和人才选拔天然依靠伯乐相马，有不少佳话，但实质上这种方式就是权力的工具体现，更多的是伯乐不常有，或者是蛤蟆就像千里马，或者是王八看绿豆。我们抛开褚裒和孟嘉的话题，再往深处追究，真正使权力者放心的人才应该产生于断情绝欲的太监或者宗教人士之中，他们没有没有妻子，家庭关系薄弱，24小时候命，他们的忠诚天然比其他人群强的多。他们虽然可能为非作歹，但他们先天不足，势单力薄，欲望低下……但历史告诉我们，这类群体并没有想权力者所想象的那样忠诚能干。而渴望得到权力者赏识的，但不愿意斩断生理器官的人，他们就必须主动斩断或者隐藏尊严、自由、个性之类的东西，所以在《走向共和》中的伊藤博文说：贵国乃专制之地，不管天才、地才，一遇专制，俱为奴才!   
孟嘉应回答不了庾亮的问题，“既辞出外，自除吏名。便步归家，母在堂，兄弟共相欢乐，怡怡如也”。而恰恰庾亮是有雅量，能欣赏这种“官无官官之事,处事无事事之心”的风流，这是特殊时代的特殊事件。  

## 7.17  
>戴安道年十余岁，在瓦官寺画。王长史见之，曰：“此童非徒能画，亦终当致名。恨吾老，不见其盛时耳！”  

- *戴逵*戴安道见6.34，少年时期以画出名，后在音乐、书画、雕塑和文章等方面均有造诣，“其余巧艺靡不毕综”，而司徒左长史王濛“丹青甚妙，颇希高远”。  
南京瓦官寺原为官府管理陶业机构所在地，故寺名“瓦官”，始建于364年，当时王濛早已去世（347年），所以戴逵不见得是在瓦官寺画画，而是其他寺庙。  
- *王濛*（309年生）比戴逵（约326年生）大17岁，戴逵10几岁作画，王濛也就30来岁，也谈不上老，从常理讲，王濛大有可能见到戴逵成名。所以这也许仅仅是个故事，或者还有其他一个王长史。  

## 7.18  
>王仲祖、谢仁祖、刘真长俱至丹阳墓所省殷扬州，殊有确然之志。既反，王、谢相谓曰：“渊源不起，当如苍生何！”深为忧叹。刘曰：“卿诸人，真忧渊源不起邪？”  

- *王濛、谢尚、刘惔*三位名士去拜访另一个大名士殷浩（后任扬州刺史，字渊源）。殷浩当时大约母亲去世，他在守孝，同时隐居。他善于清谈，表现出能力超群，时人把他比喻做管仲和诸葛亮，盼望他来拯救世界。  
- *确然*：本意是坚定，引申为确然不群，指坚定的隐居意愿。《宋书•良吏传•陆徽》：“确然守志，不求闻达。”  
- *反*：返。  

后来司马昱总统朝政，他写信要求殷浩来辅政，称“足下去就即是时之废兴，时之废兴则家国不异（足下的去留关系到时代的兴废，时代的兴废事关朝廷的存亡）”，企图对抗威势日重的桓温。但桓温并不在乎殷浩，说：“少时吾与浩共骑竹马，我弃去，浩辄取之，故当出我下也”，“殷浩品格高洁，能言会道，假使让他担任宰辅，足以成为百官的楷模，但用于军事，那是用才不当。”  
殷浩没有谢安的好运气，也没有像谢安有子弟兵为支撑。他后来发动北伐，还没和后赵交战就多个部将叛变，被叛将大败后一蹶不振，流放到浙江衢州市的山沟沟里郁郁而终。  
刘惔一向毒舌，前已多见。  

## 7.19  
>小庾临终，自表以子园客为代。朝廷虑其不从命，未知所遣，乃共议用桓温。刘尹曰：“使伊去，必能克定西楚，然恐不可复制。”  

- *庾亮*去世后，庾亮弟弟庾翼任安西将军、荆州刺史。345年病重，上奏章推荐二儿子庾爰之（小名园客）代理荆州刺史。但朝廷不希望庾家继续坐大，又担心庾爰之是个小年轻，不足以坐镇，决定让其他人去当荆州刺史。而怕庾爰之兴兵抵抗，所以这个人必须资格老，威望高，能力强。宰辅何充认为，桓温合适，他“英略过人”，“足以镇之”。而且庾翼和桓温要好，“唯与桓温友善，相期以宁济宇宙之事”，并且多次向晋成帝举荐桓温，“桓温有英雄之才，愿陛下勿以常人遇之，常婿蓄之”，庾爰之先天比桓温低一头。但同为驸马兼桓温好友的刘惔认为，桓温会有“不臣之心”，“不可使据形胜之地，其位号常宜抑之”。  
- *西楚*：荆州古时属于楚国，现在在东晋的西部，所以叫西楚。  
- *桓温*上任后，“爰之果不敢争”，“既废爰之。又以征虏将军刘惔监沔中军事，领义成太守，代方之（庾爰之的哥哥）。而方之、爰之并迁徙于豫章。”  
- *庾亮、庾冰、庾翼*三兄弟都是5年之间去世，庾家结束了“王与马共天下”的局面，也为桓温崛起创造了条件。曾经显赫一时的庾家在桓温的运作下，迅速没落。东晋门阀转而逐渐演变为“政由桓氏，祭则寡人”。  

## 7.20  
>桓公将伐蜀，在事诸贤咸以李势在蜀既久，承藉累叶，且形据上流，三峡未易可克 。唯刘尹云：“伊必能克蜀。观其蒲博，不必得，则不为。”  

345年，晋明帝司马绍的女婿、33岁的徐州刺史，并都督青徐兖三州诸军事的桓温升任为安西将军、荆州刺史，持节都督荆司雍益梁宁六州诸军事，并领护南蛮校尉，他继承了庾家多年经营的资产，控制了长江中上流，终于可以大展宏图了。346年，他决定征讨占踞巴蜀的成汉政权。11月，桓温上疏朝廷，请求伐蜀，但未等朝廷回复，便率军西进。  
东汉末年政治动荡，中原人口十不存一，少数民族进入中原。280年西晋司马炎虽然表面上统一了中国，但由于少数民族的文化特点，内迁民族在民族、阶级矛盾的交织下，多杀长吏而自立。296年，氐、羌拥立氐人齐万年为帝，在甘肃和西晋对抗，战争造成了大量流民。李特就是其中的少数民族流民帅，他带领族人进入四川。经过反复斗争，306年，李特的儿子李雄在益州称帝，定国号为大成，后李特的侄子李寿继位，改国号为汉，所以这个蜀地的政权称之为“成汉”。343年，李寿的儿子李势继位。自李特起兵传至李势，已经六世，四十多年，所以叫“累叶（累世）”。  
四川地势险要自不必说，而且从前曹魏伐蜀，是一国之兵力，现在桓温以一州的兵力区区万人征伐，朝廷人士并不看好。而刘惔认为，我从前看桓温赌博，他没有必胜的把握不会下注，以此类推，桓温伐蜀必能成功。  
汉晋时期的蒲博类似于现代的掷骰子，从理论上讲凭运气，谁也谈不上有必胜把握。但史料上说，有些人有高超的手段，譬如在《文史资料选辑》的各种回忆录中，张宗昌、戴笠、孙殿英扔骰子水平很高，想扔几点就几点，常赢得别人面无人色。不过这些即便是回忆录，也并无可信度，因为不符合力学原理。赌徒即使有一定的技巧，5、6个骰子也无法控制。所以刘惔所谓的蒲博也许是泛指赌博，而不是仅仅凭运气的掷骰子。  
李势继位两年内采取了少数民族头人的做派，“诛残大臣，刑狱滥加，人怀危惧”，“骄吝，而性爱财色，常杀人而取其妻，荒淫不恤国事”，“亲任左右小人，群小因行威福。又常居内，少见公卿”，加上当地的其他少数民族问题，“夷獠叛乱，军守离缺，境宇日蹙”，所以成汉政权已经腐烂。  
桓温从水路而上，一路居然没有遭遇任何军队。登陆后直到离成都50公里，才遇到个别抵抗，三战三捷。据史料说，最后到了距离成都2公里的笮桥决战上演，战斗异常激烈。桓温看势头不对，下令退兵。但传令官把退兵指令变成了进军之鼓，稀里糊涂中，晋军再振精神，拼死而进，终于击溃了蜀军，获得全胜。  
最后的胜利虽然不明不白，但即使桓温输了这次战斗，还是可以再战。后来在扫除成汉其他残余势力时，都是连战连捷。不过也许由于这场阴差阳错的战斗，更进一步增加了桓温的路径依赖和赌徒心理，就像希特勒的闪电战一样，遇到俄罗斯的纵深就会失效，桓温三次北伐，都是因为纵深，先胜后败，没有办法消灭对方的主力。  

## 7.21  
>谢公在东山畜妓，简文曰：“安石必出，既与人同乐，亦不得不与人同忧。”  

隐居有富隐、穷隐、朝隐、霸隐等。  
富隐如谢安，住别墅养小姑娘玩海钓；譬如潘岳《闲居赋》写自己的隐居生活，“爱定我居，筑室穿池，长杨映沼，芳枳树樆，游鳞瀺灂，菡萏敷披，竹木蓊蔼，灵果参差”“席长筵，列孙子，柳垂荫，车洁轨，陆摘紫房，水挂赪鲤，或宴于林，或禊于汜”；明清时期的李渔写隐居情调的《闲情偶寄》，罗列了词曲、演习、声容、居室、器玩、饮馔、种植、颐养八个隐居生活类别……  
穷隐要讨饭为生，如陶渊明写乞食，“饥来驱我去，不知竟何之。行行至斯里，叩门拙言辞。主人解余意，遗赠岂虚来”；有的没饭吃，索性当了僧道，谋一条生路，“山中软草以为衣，斋食松柏随时饱”；我还见过有的讲述，说他实在没饭吃，于是开始习练传说的辟谷食气。  
朝隐当闲官，东汉应劭说“老子为柱下史，朝隐，故终身无患，是为工也”。西汉东方朔说：“陆沉于俗，避世金马门。宫殿中可以避世全身，何必深山之中，蒿庐之下。”白居易在《中隐》中写道：“大隐住朝市，小隐入丘樊。丘樊太冷落，朝市太嚣喧。不如作中隐，隐在留司官。似出复似处，非忙亦非闲。不劳心与力，又免饥与寒。终岁无公事，随月有俸钱。君若好登临，城南有秋山。君若爱游荡，城东有春园。君若欲一醉，时出赴宾筵……”朝隐生活无忧，超脱于社会，又能保障既得利益。  
霸隐不当官，但是山中宰相。北宋种放长期受朝廷礼遇，“真宗优礼种放，近世少比。一日，登龙图阁，放从行，真宗垂手援放以上。顾近臣曰：‘昔明皇优李白，御手调羹，今朕以手援放登阁，厚贤之礼，无愧前代矣。’”而种放“晚节颇饰舆服，于长安广置良田，岁利甚博，亦有强市者，遂至争讼，门人族属依倚恣横。”明代大艺术家董其昌也是这样的人物，他官至南京礼部尚书，为官18年退归27年，既营造了超迈形象，又攀上了世俗权势的巅峰，家人不免横行乡里。  
谢安本来铁了心富隐，霸隐，年轻时多次辞官，再三不接受征召，以至于朝廷宣布“历年不至，禁锢终身”。  
357年，谢安的堂哥、豫州刺史谢尚病故；358年，谢安的哥哥、豫州刺史谢奕病故；359年，谢安的弟弟、豫州刺史谢万任因在北伐途中未接战而部队奔溃，被免为庶人。这三个顶梁柱或死或贬，谢家连续遭受重创。如果再不出山，谢安的富隐就要变成穷隐了。所以在360年，桓温聘请他为军中司马，谢安立刻上任。  
简文帝司马昱的说法不成立。谢安不是为世之忧，而是家族之忧。  

## 7．22  
>郗超与谢玄不善。苻坚将问晋鼎，既已狼噬梁岐，又虎视淮阴矣。于时朝议遣玄北讨，人间颇有异同之论。唯超曰：“是必济事。吾昔尝与共在桓宣武府，见使才皆尽，虽履履之间，亦得其任。以此推之，容必能立勋。”元功既举，时人咸叹超之先觉，又重其不以爱憎匿善。  

郗家和谢家有矛盾，一是因为谢家晚出，比较嫩，郗家看不起谢家。二是谢家逐渐上升，后来爬到了郗家前面，郗超“常谓其父名公之子，位遇应在谢安右，而安入掌机权，愔优游而已。恒怀愤愤，发言慷慨，由是与谢氏不穆。”三是当年桓温和郗超为一党，谢安、王坦之受过郗超的轻慢，结下梁子。  
- *梁岐*：晋代梁州就是益州，九州之一，陕西、四川一带，岐也是陕西一带，梁岐并称，是为了与淮阴对仗。373年，“宁康元年东，秦取梁益两州”。不过宋代蔡沈说：“梁山，吕梁山也。岐山，在今汾州介休县狐岐之山。二山河水所经，治之所以开河道也。”  
- *异同*：不同。377年，谢安荐34岁的谢玄为建武将军、兖州刺史，领广陵相，监江北诸军事。他从前并没有什么作战履历和显赫的战功，完全是靠家族关系取得位置，谢安“违众举亲”。所以郗超就谈了谢玄用人本领，他能使员工各得其所，各尽其能，引申到治军能力上也是一样的。  
- *元功*：大功。指383年的淝水之战，而郗超已于378年去世。  

一般来说，回避制度是大型组织正常管理的基本要求。不过《左传》中说：“君子谓祁奚于是能举善矣。称其仇，不为谄；立其子，不为比；举其偏，不为党。《商书》曰：‘无偏无党，王道荡荡。’”但在专制体制和自私的基因作用下，所谓的举贤不避亲无非是丑脸上的涂脂抹粉。谢安使用小年轻兼侄儿谢玄，是门阀体制中不得已的做法。当年谢安弟弟谢万任豫州刺史，谢安知道谢万的能力不匹配，他并没有上书朝廷说任命不合适，而是跑到谢万那里予以参谋，这都是家族的私心。而郗超对谢玄的赞许，是有才华人士的惺惺相惜——我讨厌你，但我不怀疑你的能力。举贤不避仇的故事很少，难得。不过郗超没有执政，如果他执政，就绝不可能重用谢玄的——因为落后的体制。  

## 7.23  
>韩康伯与谢玄亦无深好。玄北征后，巷议疑其不振。康伯曰：“此人好名，必能战。”玄闻之甚忿，常于众中厉色曰：“丈夫提千兵入死地，以事君亲故发，不得复云为名。”  

- *韩伯*韩康伯，曾任丹阳尹、吏部尚书等，前已多见。他看不惯谢家子弟的骄狂，在5.57中，把谢氏比作靠亲戚关系贵显的王莽家族，“此复何异王莽时”。  
- *好名*有两个意思，一是珍惜名誉，二是追求虚名。明代庄元臣进一步阐述：“人之好名者，其等有三：有好闾阎之名者，有好士大夫之名者，有好圣贤之名者，同为名而品第殊矣。”韩伯的本意应该包含着谢玄珍惜荣誉，追求万世知名。但别人听了不免会认为是沽名钓誉的意思。于是谢玄常常表示自己不是那种虚荣的人。  

如果我们在对魏晋玄学来源做一个观察，名实之辩是第一问题。魏晋对东汉制度的反动，起源就是由于东汉的官员征辟举荐制度发展到后来自然是名与实的脱离，于是建立九品中正制，由中央派员对各地士人的才智进行品评，而不是由当地名士操控。同时在思想上提出了“辨名析理”“以无为本”，形成“慕通达”“鄙名分”的社会风气。说谢玄“好名”，谢玄自然“甚忿”“厉色”，指出他是为了君王家人朋友抗战。

## 7.24  
>褚期生少时，谢公甚知之，恒云：“褚期生若不佳者，仆不复相士！”  

- *褚爽*小字期生，《续晋阳秋》说他“及长，果俊迈有风气”。  
像伯乐相马一样，先秦自有看相之术，如勾践“长颈鸟喙，可与共患难，不可与共乐”，白起“小头而面锐，瞳子黑白分明，视瞻不转。小头而面锐者，敢断决也：瞳子黑白分明者，见事明也；视瞻不转者，执志强也。可与持久，难于争锋”。自汉以来，相术更是大为流行，在《史记》中就记载了很多相术故事，刘邦据说被吕父招为女婿，就是他“上相”，吕公“好相人，见高祖状貌，因重敬之”。相术发展到后来，甚至成为宫廷政治斗争的工具。《汉书•李陵传》中说：“陵败处去塞百余里,边塞以闻。上欲陵死战,召陵母及妇,使相者视之,无死丧色。后闻陵降,上怒甚。”   《后汉书-皇后纪下》记东汉顺烈梁皇后“永建三年，与姑俱选入掖庭，时年十三，相工茅通见后，惊，再拜贺曰：‘此所谓日角偃月，相之极贵。臣所未尝见也！’”这都说明朝廷长期养着一批专业相士，这些职业相士影响着执政者的决策。  
古人相信，命运都写在一个人的脸上和肢体上。在这种文化的影响下，民间相书出现了，据说最早是西汉许负的《相书》，它就是依据身体五官四肢划分篇目，论述不同形貌声色代表的命相吉凶。一些学者也对此深信不疑，把相术理论化、系统化。东汉王充在《论衡•命义》中说，“人有寿夭之相，亦有贫富贵贱之法，俱见于体。故寿命修短，皆禀于天；骨法善恶，皆见于体。”稍后的王符在《潜夫论》中也说，“骨法为禄相表”“人身体形貌皆有象类，骨法角肉各有分部，以著性命之期，显贵贱之表”等。一些古人。到了三国，刘劭《人物志》顺时而生。该书提出以神、精、筋、骨、气、色、仪、容、言九种质素选判人才，即“九征”。  
到了两晋，文化交融加剧，玄学、道教、佛教中的怪力乱神因素结合在一起显现。玄学家们兼职了相士行当，王导、谢安等都是这样的人，我们已经见过很多他们的故事，他们利用“相术”常常许人高官，使人如沐春风，进而拉帮结派，美其名曰“识鉴”。  

## 7.25  
>郗超与傅瑗周旋。瑗见其二子，并总发，超观之良久，谓瑗曰：“小者才名皆胜，然保卿家，终当在兄。”即傅亮兄弟也。  

- *傅瑗*曾为安城太守，与郗超友好。  
- *周旋*：周旋在《世说新语》中是常用词，多是交往的意思。《史记-晋世家》咎犯曰：“臣从君周旋天下，过亦多矣。”《资治通鉴-魏纪三》：“潘濬子翥，亦与蕃周旋。”  
- *见*：语出《论语-微子》：“止子路宿，杀鸡为黍而食之，见其二子焉”，介绍引见。  
- *总发*：总角，指幼年。傅亮当时4岁，哥哥傅迪也是幼年。  
- *傅亮*：傅亮长于文辞，后来成为刘裕的“文胆”，有拥立之功，先后任中书令，尚书仆射等职，“既居宰辅，兼总重权”。刘裕死后，立少帝刘义符，傅亮为顾命大臣之一。但据说刘登基后沉溺于声色犬马，不理国政，几个辅政大臣决定废掉刘义符，另立刘义隆为帝。随后徐羡之、傅亮、檀道济、谢晦等杀了刘裕大儿子刘义符、二儿子刘义真。这种做法如果没有门阀的支持和个人极大的权威，肯定是很不理智的。傅亮去江陵迎接刘义隆入京继位，当时刘义隆“问义真及少帝薨废本末，悲哭呜咽，侍侧者莫能仰视。亮流汗沾背，不能对”。当时吏部尚书蔡廓就对谢晦说：“卿受先帝顾命，任以社稷，废昏立明，义无不可。但杀人二兄而以之北面，挟震主之威，据上流之重，以古推今，自免为难。”这也注定了顾命大臣最后的命运，两年后，四人被杀。刘义隆下诏诛杀傅亮时说：“以公江陵之诚，当使诸子无恙。”傅亮说：“亮受先帝布衣之眷，遂蒙顾托。黜昏立明，社稷之计也。欲加之罪，其无辞乎！”傅亮的两个儿子后来逃亡。  

傅迪比傅亮早死五年，不存在“保卿家”之事，但这不是郗超预言的重点，无非是说在乱世当中，平庸者或可以保全。  

## 7.26  
>王恭随父在会稽，王大自都来拜墓，恭暂往墓下看之。二人素善，遂十余日方还。父问恭何故多日，对曰：“与阿大语，蝉连不得归。”因语之曰：“恐阿大非尔之友。”终乖爱好，果如其言。  

- *王恭*和*王忱*前已多见。  
据《世说新语-赏誉-153》注中说：
>初，（王）忱与族者恭少相善，齐声见称。及并登朝，俱为主相所待。内外始有不咸之论，共独深忧之，乃告忱曰：“悠悠之论，颇有异同，当由骠骑简于朝觐故也。将毋从容切言之邪？若主相谐睦，吾徒得戮力明时，复何忧哉？”忱以为然，而虑弗见令，乃令袁悦具言之。悦每欲间恭，乃于王坐责让恭曰：“卿何以妄生同异，疑误朝野？”其言甚切厉。恭虽惋怅，谓忱为构己也。忱虽心不负恭，而无以自亮。于是情好大离，而怨隙成矣。  

大意是说，王恭为了朝廷内外消除皇帝司马曜和执政司马道子不和的议论（主相不谐，不咸之论），建议王忱去劝劝司马道子，要向司马曜经常去汇报工作，营造团结和谐的氛围。而当时袁悦“甚为会稽王道子所亲爱，每劝道子专览朝权，道子颇纳其说”，所以王忱请袁悦和司马道子说。而王恭这种做法不靠谱，王忱层层转托传话更是不合适。所以司马道子勃然大怒：明明是你王恭在制造舆论，说我和皇帝哥哥不和，你是什么居心！于是王恭就怨恨上了王忱。  
- *父*：王蕴。  
- *蝉连*：蝉联，连续不断。  
- *乖*：违背。  
- *爱好*：喜好，交好，这里指友谊。《晋书》：“中书令王珉与嫂婢有情，爱好甚笃。”《南史》：“中书令王球以名公子遗务事外，与延之雅相爱好”。  

王恭不是什么善茬，《世说新语-谗险-2》的注中说：王恭“言于孝武。乃讬以它罪，杀悦于市中。”

## 7.27  
>车胤父作南平郡功曹，太守王胡之避司马无忌之难，置郡于酆阴。是时胤十余岁，胡之每出，尝于篱中见而异焉。谓胤父曰：“此儿当致高名。”后游集，恒命之。胤长，又为桓宣武所知，清通于多士之世，官至选曹尚书。  

- *车胤*：赫赫有名的学习榜样，囊萤映雪中囊萤讲的就是他。不过故事并非实情。车胤的父亲车育，先后当过郡功曹和郡主簿，类似于市组织部部长和市办公室主任，都是比较显赫重要的岗位，不至于家贫如洗，连油灯也没有。而且清代蒋良骐在《东华录》记载，康熙六十年三月，康熙下谕说：“囊萤读书，朕曾取百枚，盛以大囊照书，字画竟不能辨，此书之不可尽信者也”。  
当代有人做实验，测量出一只萤火虫亮度最大值约为0.0032勒克斯。黑暗中阅读所需最基本亮度是1勒克斯，至少需要310只萤火虫，而且不能装在袋子里，才能勉强看清字。如果装进非常透明的丝绸袋子，估计要千只以上。而且萤腹发光耗能，光亮只能维持2至3小时。  
清代《笑林广记》就拿“车胤囊萤读书，孙康映雪读书”开涮：“一日，康（孙康，映雪的主人公）往拜胤，不遇。问何往？门者曰：出外捉萤火虫去了。已而胤答拜康，见康闲立庭中，问何不读书？康曰：我看今日这天不像个下雪的。”  
2004年，央视推出《中华勤学故事》动画片，讲了50几个古人好学的故事。遗憾的是，其中起码20个故事瞎编，20个故事是传说，也就几个故事来自传记（也未必靠谱）。屈指一数，3000年以来，我国真没几个经得起推敲的勤学故事。拿这些胡编乱造的故事来教育学生，起不到教化的作用，反而有很大的后遗症，像潜伏的病毒那样损害社会肌体。  
- *避司马无忌之难*：司马无忌的父亲谯王司马承原为湘州刺史，在王敦起兵叛乱时被俘，押送途中，王敦派荆州刺史王廙把他杀害。王廙的儿子之一就是王胡之，怕司马无忌为父报仇，就想避开辅国将军、长沙相、兼领江夏相司马无忌。而无忌曾经要手刃王胡之的哥哥王耆之，“裒、景命左右救捍获免。御史中丞车灌奏无忌欲专杀人，付廷尉科罪。成帝诏曰：“王敦作乱，闵王（司马承谥号闵）遇祸，寻事原情，今王何责。然公私宪制，亦已有断，王当以体国为大，岂可寻绎由来，以乱朝宪。主者其申明法令，自今已往，有犯必诛。”大意是说，这次就算了，以后不要寻仇了。  
- *酆阴*：当做“澧阴”，澧水位于湖南省西北部，流域跨越湘鄂两省边境。现湖南有常德市澧县，下属有澧阳镇，在澧水北岸。澧阴应该就在澧阳对面一带。清代澧县城东四十里处还有车渚书院，“云晋车武子囊萤读书处”。   
- *每出*：每在古汉语中有经常的意思。归有光《项脊轩志》：“妪每次谓余曰”。   
- *游集*：游玩聚会。  
- *命*：邀请。元稹《莺莺传》：“郑厚张之德甚，因饰馔以命张，中堂宴之。”  
- *清通*：清明通达。车胤先后受桓温、谢安赏识，官至吏部尚书（选曹）。  

## 7.28  
>王忱死，西镇未定，朝贵人人有望。时殷仲堪在门下，虽居机要，资名轻小，人情未以方岳相许。晋孝武欲拔亲近腹心，遂以殷为荆州。事定，诏未出，王珣问殷曰：“陕西何故未有处分？”殷曰：“已有人。”王历问公卿，咸云非。王自计才地必应在己，复问：“非我邪？”殷曰：“亦似非。”其夜诏出用殷。王语所亲曰：“岂有黄门郎而受如此任！仲堪此举，乃是国之亡征。”  

原荆州刺史王忱（王大），王坦之的儿子，“末年尤嗜酒，一饮连月不醒”，392年去世。本来司马道子属意亲信王国宝继任，而孝武帝司马曜“以会稽王非社稷之臣，擢所亲幸以为藩捍”，抢先一步，不经过吏部，以“中诏”任命亲信太子中庶子、门下省黄门侍郎殷仲堪出任，而让另一个亲信尚书左仆射王珣继续留在中央。  
- *方岳*：四方之山岳，引申为诸侯，再引申为国家镇守一方的重要官员。  
在不久后出的《比丘尼传•简静寺支妙音尼传》中还有一段记载：“荆州刺史王忱死，烈宗意欲以王恭代之。时桓玄在江陵，为忱所折挫，闻恭应往，素又惮恭。殷仲堪时为恭门生。玄知殷仲堪弱，才亦易制御，意欲得之，乃遣使凭妙音尼为堪图州。既而烈宗问妙音：‘荆州缺，外问云谁应作者？’答曰：‘贫道道士，岂容及俗中论议。如闻外内谈者，并云无过殷仲堪，以其意虑深远，荆楚所须。’帝然之，遂以代忱。权倾一朝，威行内外。”从这段记录来看，居然是荆州的地头蛇、南郡公桓玄请一个叫妙音的尼姑吹耳边风，原因是桓玄喜欢殷仲堪心慈手软，容易相处并控制。当然，并不能排除殷仲堪勾结妙音，桓玄背了锅。因为在《世说•尤悔•17》的刘孝标引注中说：“仲堪以人情注于玄，疑朝廷欲以玄代己，遣道人竺僧愆赍宝物遗相王宠幸、媒尼、左右，以罪状玄。玄知其谋，而击灭之”，说明殷仲堪和尼姑也搞在一块儿。  
- *陕西*：指荆州。西周初，周成王年幼，便由周武王之弟周公旦和召）公奭）辅政，周公和召公遂决定分陕而治，两人所管辖的地区以河南三门峡市陕州区的“陕塬”为界，周公管陕地以东，召公管陕地以西。而东晋护卫首都的两个重镇是西部的荆州和东部的扬州，所以就用周公、召公分陕而治一事来比拟，称荆州为陕西或西陕。  
- *处分*：处理安排。  

司马曜以亲信郗恢镇襄阳，殷仲堪镇江陵，王恭镇京口，王珣在中央，貌似遏制了司马道子，彻底取得了权力，但他在396年被张贵妃糊里糊涂地杀死（见6.40），儿子晋安帝司马德宗是白痴，“幼而不慧，口不能言，至于寒暑饥饱亦不能辨，饮食寝兴皆非己出”，司马曜的亲信和司马道子爆发内战，东晋就快完了。  

这是识鉴的最后一个故事，王珣说出了最后的预言“国之亡征”。不过难道任命一个殷仲堪晋朝就要完吗？不是这样，而是门阀制度被彻底破坏，次等士族、军人刘裕最终占据舞台中心，他要彻底振兴皇权，以一人治天下。  

## 识鉴 小结  
识鉴就是预言人事的发展方向、成败得失，在古代往往是相术的代名词。在《世说新语》中，识鉴和九品中正制、人物审美有一定联系。在曹丕时期草创的九品中正制度中规定：“州郡皆置中正，已定其选，择州郡之贤有识鉴者为之，区别人物，第其高下”。当然，科举之前选拔官员也有一些考试制度，如汉武帝时期有策论考试“举贤良”，王莽执政时期也有从太学岁课选士，曹丕在当时也有“五经课试”，但这些考试不是完全开放式，也不是主流和常态，上位者还是喜欢伯乐相马，以自己的睿智决定个人、社会和民生。  
大多数人相信，未来会在现在投下影子。过去往往决定着今天我们遭遇什么，未来事件蕴藏在现有的线索之中。甚至我们还可以说，今天所发生的事件，起决定性作用的并非当下我们所拥有的常识判断和选择，而是前一个时代的结果。如第四则司马炎偃武修文，结果寇盗蚁合；第十九则桓温出任荆州刺史，终究会势大难制；谢玄能人尽其才，将来定有一番作为；二十八则司马曜较为彻底地打压门阀，东晋的执政基础就消失了。  
企业安全管理有“海因里希法则”，当一个企业有300个隐患或违章，必然要发生29起轻伤或故障，在这29起事件中，会有一起重伤、死亡或重大事故。不过识鉴并不需要也无法考察人事的诸多方面，它更像蝴蝶效应的“一颗铁钉”，“失了一颗铁钉，丢了一只马蹄铁；丢了一只马蹄铁，折了一匹战马；折了一匹战马，损了一位将军；损了一位将军，输了一场战争；输了一场战争，亡了一个国家”。由于“一枚铁钉”，识鉴者发出了自己的预言。  
当然，具体人事存在变量和随机，这种知微见著未必有真正严密的逻辑因果关系，但锥处囊中脱颖而出，细节定成败，性格即命运的总体趋势客观存在，从这个意义上讲，相人之术带有理性的判断。第九则华轶识能不足，十二则王玄志大其量，十三则杨朗见识高超，十五则王彬必兴愍恻，十六则孟嘉木秀于林，十七则戴逵必成大家等。这些预言不来自于神秘主义，而是评论者依靠生活阅历和智慧做出判断。就像明末洪承畴兵败被俘后，不吃不喝不动，好像要宁死不屈。旧友范文程去劝降，回来后对皇太极说：“承畴不死矣。承畴对敝袍犹爱惜若此，况其身耶？”   
识鉴中还有一些故事是权谋之术，夸句人好，结下善缘甚至结党，投入小收益大，第一则桥玄评曹操，后面的王导、谢安夸人等，是那时候常见的套路。还有一些识鉴者采取直线或跳跃性思维，未必是见识高明，无非就是幸存者偏差，蒙对了于是流传，如羊祜评王衍。有的故事还造假，把事后知葛亮当成先知的神通，如潘滔评王敦，有的是政治上的党同伐异，不足为凭，如傅嘏评何晏三人等。  
理性的识鉴很难，迷信的相术简单，民众更喜欢传奇性的故事，在口耳传说中享受精神生活。而且在快速且巨变的生活中，民众精神压力加剧，神秘主义的市场扩展，风水相术已经进入庙堂之中发出自预言，这是没法遏制的事。  
有个人做了个梦，在梦中，有个民族要伟大复兴。我们，谁不愿意相信这个梦预言成真。   

# 赏誉 {#08}
## 8.1
>陈仲举尝叹曰：“若周子居者，真治国之器。譬诸宝剑，则世之干将。”  

- *陈蕃、周乘*见1.1，1.2。周乘当过泰山太守，交州刺史。据《汝南先贤传》中说，他当刺史的时候，和李膺一样具有威慑力，“太守闻乘之威，即上疾乞骸；属县解印，四十余城。”所以陈蕃把周乘比喻成第一名剑，具有最杰出的才能，斩尽人间不平事。  

干将莫邪的故事并非史实，但这种向君王复仇的侠客故事天然正义，激励后人为之奋斗。

## 8.2  
>世目李元礼：“谡谡如劲松下风。”  

- *目*：看，引申为品评。  
- *李膺*见1.4，1.5。把人比喻成风，也许较早出现在《论语》：“君子之德风，人小之德草，草上之风必偃”，所以范晔在《后汉书》中说：“李膺振拔污险之中，蕴义生风，以鼓动流俗，激素行以耻威权，立廉尚以振贵势”。  

在当时这个比喻很常见，如袁山松《后汉书•朱穆传》“朱公叔肃肃如松柏下风”，《青州先贤传》“陈仲举，昂昂如千里骥；周孟玉，浏浏如松下风”等。  
《世说》使用“谡谡”“劲松”为修饰，突出“天下楷模”李膺清高挺拔的风采。这种叠词加具象的修辞手法在《世说》中就像手机上不时冒出来的网游广告，如“森森如千丈松”“汪汪如万顷之陂”“轩轩如朝霞举”“烂烂如岩下电”“朗朗如日月之入怀”等，生动形象，具有诗韵的舒缓摇曳之美，对后世的修辞有很大的影响。  

## 8.3  
>谢子微见许子将兄弟，曰：“平舆之渊，有二龙焉。”见许子政弱冠之时，叹曰：“若许子政者，有干国之器。正色忠謇，则陈仲举之匹； 伐恶退不肖，范孟博之风。”  

- *谢甄*谢子微，汝南名士，曾为豫章从事，以识鉴著称，后因嘲讽曹操被杀。许虔许子政、许劭许子将都是汝南郡平舆人。许虔后为郡功曹，“黜奸废恶，一郡肃然”，35岁因病去世。谢甄赞扬他德行像陈蕃、范滂，但由于没有面临重大事件的考验，其事迹并不突出。而弟弟许子将后来开创和主持“月旦评”，在当时名声极大，成为与朝廷选拔官员的重要牵制力量，开展为统治者不喜的舆论监督，以至于当时有人认为这是“更相谤讪，或至于祸”。  

## 8.4  
>公孙度目邴原：“所谓云中白鹤，非燕雀之网所能罗也。”  

- *公孙度*，东汉末辽东太守，自封辽东侯。因当时黄巾之乱，关内人士多有避难于辽东，龙腹邴原、龙尾管宁都曾在辽东居住。  

公孙度为人残暴，不肯为他效力的人常常诛杀。其虽礼遇邴原，但听说邴原家族一行想回去，就软禁了他们。邴原设法灌醉了看守他们的部落，连夜坐船走了。所以公孙度悻悻然说了这么一番话。  
哪怕是乱世，残暴的统治者对具有高尚品德和学问的人士还是会抱有一点点的敬畏，这主要是对历史的敬畏。他们虽然不相信历史是由人民书写的，不相信善恶有报，但即使再狂妄，也知道自己权力的空洞，也会担心死后遗臭万年。这就是文化的公正，历史的力量。  

# 8.5  
>钟士季目王安丰：“阿戎了了解人意。”谓裴公之谈，经日不竭。吏部郎阙，文帝问其人于钟会，会曰：“裴楷清通，王戎简要，皆其选也。”于是用裴。  

- *钟会*赏识和提拔王戎、裴楷，前已多见。  
钟会是司马昭的心腹，伐蜀后居然想拥兵自立，最后被乱兵所杀，颇有疑点。难道钟会其实是东汉的大忠臣，或者是怕功高震主，怕落得韩信的下场？伐蜀后的一团乱麻，两位杰出人才钟会、邓艾先后以谋反罪被杀，史书虽然好像解释清楚了，但情理上有问题。
- *了了*：聪慧。  
- *谓裴公之谈，经日不竭*：此句多余，似为窜入的衍文。  
- *清通*：内心清明，处事通达。《晋书》中说，裴楷“明悟有识量”“通理有才义”。  
- *简要*：干净利落。《晋书》中说，王戎“任率不修威仪，善发谈端，赏其要会”，《世说新语-俭啬》刘孝标注中说：“戎性简要，不治仪望，自遇甚薄。”  

后来王戎、裴楷都曾是西晋的辅政大臣。

## 8.6  
>王浚冲、裴叔则二人总角诣钟士季，须臾去，后客问钟曰：“向二童何如？”钟曰：“裴楷清通，王戎简要。后二十年，此二贤当为吏部尚书。冀尔时天下无滞才。”  

- *王戎*大*裴楷*四岁，此事不确，无非是上一则的细化演义版本。  

## 8.7  
>谚曰：“后来领袖有裴秀。”  

河东裴氏，裴秀生母出身婢女，主妇宣氏曾让她给客人端饭菜，客人见她后都站起来致礼。裴秀母亲说：“我这样微贱，客人致礼是因为我儿子的缘故。”宣氏就不再轻视她了。当时谚语说：“后进领袖有裴秀。”这是后起之秀的出典。  
裴秀世袭清阳亭侯，最后官至司空，他是当时的制图专家和礼仪、法律专家。

## 8.8  
>裴令公目夏侯太初：“肃肃如入廊庙中，不修敬而人自敬。一曰：“如入宗庙，琅琅但见礼乐器。”“见钟士季，如观武库，但睹矛戟。见傅兰硕，汪廧靡所不有。见山巨源，如登山临下，幽然深远。”  

- *裴楷、夏侯玄、钟会、傅嘏、山涛*前已多见，这些人不仅是高官，而且是名士、玄学家。  
- *肃肃如入廊庙中*：《礼记-檀弓下》：鲁人有周丰也者，哀公执挚请见之。而曰：“不可。”公曰：“我其已夫？”使人问焉曰：“有虞氏未施信于民而民信之，夏后氏未施敬于民而民敬之，何施而得斯于民也？”对曰：“墟墓之间，未施哀于民而民哀；社稷宗庙之中，未施敬于民而民敬。殷人作誓而民始畔，周人作会而民始疑。苟无礼仪忠信诚悫之心以莅之，虽固结之，民其不解乎？”。大意是说，鲁哀公提问：为什么虞舜没有对百姓进行信义教化，而百姓却信任他；夏禹没有对百姓进行诚敬教化，而百姓却敬重他？周丰回答说：人们到了墓地，自然会产生悲伤的情绪；人们到了宗庙，自然就会肃然起敬。殷商统治者喜欢发誓，但人们还是会叛乱；周朝统治者喜欢开会统一思想，但人们还会怀疑统治者。如果没有忠信诚实的心思对待百姓，即使采取各种仪式，人们还是会离散。  
- *琅琅但见礼乐器*：把人比喻成宗庙中的礼乐之器，见《论语•公冶长》和2.105。《论语•先进》中有一句，“如其礼乐，以俟君子”，礼乐是古代社会的大事，有教化之功。这是比喻夏侯玄举止庄重，是栋梁之才，令人敬重。  

钟会“时人谓之子房”，把他比喻成“武库、矛戟”，应该是形容他为运筹帷幄的智者，战略家，钟会也自称“我自淮南以来，画无遗策，四海所共知也”。  
- *傅嘏*字兰石，石，硕通。汪廧通汪翔，即汪洋。这是夸他广博。据他从兄傅玄说，傅嘏当河南尹的时候，“其治以德教为本，然持法有恒，简而不可犯，见理识情，狱讼不加槚楚而得其实。不为小惠，有所荐达及大有益於民事，皆隐其端迹，若不由己出。故当时无赫赫之名，吏民久而后安之”。  
- *山涛* “性好老庄，每隐身自晦”，他后来任高官，“虽爵同千乘，而无嫔媵；禄赐俸秩，散之亲故”。司马炎对他的评价是“先帝识君远意，吾将倚君以穆风俗”，“以德素为朝之望，而常深退让，至于恳切”，王衍对他的评价是“晻晻为与道合，其深不可测”，孙盛评价是“雅素恢达，度量弘远，心存事外，而与时俛仰”，这些意思都是说山涛有出世之意，志趣举止深远，品德高尚。裴楷评山涛的言辞比其他人更为形象生动，把自己放在评价之中，并抓住了山涛的气质，“我看山涛，山涛也在看我”。  

## 8.9  
>羊公还洛，郭奕为野王令，羊至界，遣人要之，郭便自往。既见，叹曰：“羊叔子何必减郭太业！”复往羊许，小悉还，又叹曰：“羊叔子去人远矣！”羊既去，郭送之弥日，一举数百里，遂以出境免官。复叹曰：“羊叔子何必减颜子！”  

- *郭奕*三次送别羊祜，三次赞叹一浪高一浪，“和我差不多”、“是杰出人物”、“接近于圣人”，以至于因为离境免官（古代朝廷往往规定，刺史、县令等地方官员没有命令，不得离开所辖之境），毫不后悔，这就是见贤思齐的人格。  

类似的故事是书法家欧阳询：率更令（官名）欧阳询，行见古碑，索靖所书，驻马观之，良久而去。数百步复还，下马伫立，疲则布毯坐观。因宿其旁，三日而后去。（唐•刘餗《隋唐嘉话》）这种层层推进的叙事手法营造出一山更比一山高的高山仰止效果。  
不过《儒林外史》有个别开生面的反讽桥段，“周学道校士拔真才”：周学道将范进卷子用心用意看了一遍。心里不喜道：“这样的文字，都说的是些甚么话！怪不得不进学。”——周进心里想道：“何不把范进的卷子再看一遍？倘有一线之明，也可怜他苦志。”从头至尾，又看了一遍，觉得有些意思。——周进又取过范进卷子来看，看罢，不觉叹息道：“这样文字，连我看一两遍也不能解，直到三遍之后，才晓得是天地间之至文，真乃一字一珠！可见世上糊涂试官，不知屈煞了多少英才！”周进的眼光和郭奕是两回事。周进因为同情范进，移情到他的垃圾八股文中去了（故事中范进连当代刘基、宋朝苏轼为何人都不曾知晓）。而郭奕和欧阳询的一往深情来源于他们本身高明的审美情致，是为高山流水之知音。  

## 8.10  
>王戎目山巨源：“如璞玉浑金，人皆钦其宝，莫知名其器。”  

- *王戎*评价山涛是金、玉矿，大家都知道他是有宝贝的矿，还不知道他的内在是什么（有什么才华）。王戎的说法大概来源于《孔子家语•五仪解》：“下民不知其德，睹者不识其邻，此圣者也。”  
璞玉浑金意思后来有所转移，一般是指人品纯真朴实。

## 8.11  
>羊长和父繇与太博祜同堂相善，仕至车骑掾，蚤卒。长和兄弟五人，幼孤。祜来哭，见长和哀容举止，宛若成人，乃叹曰：“从兄不亡矣！”  

- *同堂*：泰山羊氏是当时望族，汉末南阳“悬鱼太守”羊续是羊繇和羊祜的祖父。羊忱是羊繇的五个儿子之一，后来曾做过徐州刺史、侍中等。羊祜以传承儒学为己任，看到幼年的羊忱（见5•19等）服丧期间的行为举止，完全符合礼仪，深感欣慰，觉得堂兄后继有人。  

## 8．12  
>山公举阮咸为吏部郎，目曰：“清真寡欲，万物不能移也。”  

山涛和阮咸本是竹林之好，当时山涛可能是吏部尚书，阮咸是散骑侍郎，山涛向司马炎推荐阮咸为吏部郎，司马炎认为不合适。  
山涛的评价刘孝标的注中说是“真素寡欲，深识清浊”，意思一样，是说阮咸纯真质朴，生活简单，原则坚定。  

## 8.13  
>王戎目阮文业：“清伦有鉴识，汉元以来未有此人。”  

- *阮武*是阮籍的族兄，阮籍少孤，多受亲戚阮谌、阮武父子的照顾。  
- *清伦*：伦指辈、类。清高超出同时代的人。  
- *汉元*：汉初。  

阮武有著作叫《阮子》，当过曹魏的清河太守。  
王戎以见识高明著称，所以多品评人物。

## 8.16  
>王戎云：“太尉神姿高彻，如瑶林琼树，自然是风尘外物。”  

- *王衍*是*王戎*堂弟，他自幼颜值满分，气质满分，在《世说新语》里满屏都是颜狗（主要是他亲戚）对他的入迷和夸奖，甚至说他的长相“入道”。  
- *瑶林琼树*：仙境神木。晋陆云《九愍-纡思》：“怀瑶林之珍秀，握兰野之芳香。”   《晋书-文苑传-曹毗》：“未若澄虚心于玄圃，荫瑶林于蓬莱。”《汉书-司马相如传-颜师古注》：“琼树生昆仑西流沙滨，大三百围，高万仞。”也可指大雪中的高树。南北朝谢惠连 《雪赋》：“庭列瑶阶，林挺琼树。” 唐韩愈《春雪映早梅》：“未许琼华比，从将玉树亲”。  
- *风尘*：人间尘世，偏向于贬义的凡间。晋陆机《与赵王伦笺荐戴渊》：“安穷乐志，无风尘之慕；砥节砺行，有井渫之洁。”他堂弟王敦说王衍“处众中，如珠玉在瓦石间”。  

## 8.17  
>王汝南既除所生服，遂停墓所。兄子济每来拜墓，略不过叔，叔亦不候。济脱时过，止寒温而已。后聊试问近事，答对甚有音辞，出济意外，济极惋愕；仍与语，转造精微。济先略无子侄之敬，既闻其言，不觉懔然，心形惧肃。遂留共语，弥日累夜。济虽俊爽，自视缺然，乃唱然叹曰:“家有名士，三十年而不知！”  
济去，叔送至门。济从骑有一马，绝难乘，少能骑者。济聊问叔：“好骑乘不？”曰：“亦好尔。”济又使骑难乘马，叔姿形既妙，回策如萦，名骑无以过之。济益叹其难测，非复一事。  
既还，浑问济：“何以暂行累日？”济曰：“始得一叔。”浑问其故，济具叹述如此。浑曰：“何如我？”济：“济以上人。”   
武帝每见济，辄以湛调之，曰：“卿家痴叔死未？”济常无以答。既而得叔，后武帝又问如前，济曰：“臣叔不痴。”称其实美。帝曰：“谁比？”济曰：“山涛以下，魏舒以上。”于是显名，年二十八始宦。  

- *王汝南*：王湛字处冲，太原王氏，曾任汝南内史。  
- *除所生服*：父母死后，守孝期满，脱去孝服。所生，父母所生，这里指父亲骠骑大将军、司空王昶，259年去世。王湛守孝结束，为表示沉痛，按照礼仪继续留在墓地结庐居住。
- *兄子济*：王济是司徒王浑的儿子，司马昭之婿。“少有逸才，风姿英爽，气盖一时，好弓马，勇力绝人，善《易》及《庄》《老》”，“内多忌刻，好以言伤物”。这一些，都可以从这个故事里有所窥见。  
- *略不过叔*：基本上不去拜访叔叔。过，拜访。《史记•魏公子传》：“臣有客在市屠中，愿枉车骑过之。” 王湛“兄弟宗族皆以为痴”，王济“才气抗迈，于湛略无子侄之敬”。  
- *脱时*：或然，偶或之时。  
- *三十年*：虚指，后文说王湛“年二十八始宦”。  
- *回策如萦*：盘马来回如带子一样萦绕自如，苏轼《书韩干二马》“赤髯碧眼老鲜卑，回策如萦独善骑”。  
- *始得一叔*：荷尔德林是黑格尔的好朋友，后来发了疯，黑格尔从没去看过他，认为没有了理性的人等于死亡。他说，人是靠头脑，也就是靠思想站着的，并按照思想创造现实世界。  
- *济以上人*：《礼记》要求“父不言子之德，子不言父之过”，所以拿自己相比，取言外之意。  
- *调*：调侃。  
- *魏舒*：司徒山涛去世后，魏舒是接任者。他箭法高超，见识深邃，为人谦逊，器量宏大。譬如“后遇朋人不足，以舒满数……舒容范闲雅，发无不中。举坐愕然，莫有敌者”，“府朝碎务，未尝见是非；至于废兴大事，众人莫能断者，舒徐为筹之，多出众议之表。文帝深器重之，每朝会坐罢，目送之曰：‘魏舒堂堂，人之领袖也。’”  

这则塑造人物的故事也采取层层推进的方法，这是我们最常用的理性表达手段，文章营造出一唱三叹的氛围，仿佛美景一个接一个地映入眼帘。刘孝标的注引用邓粲的《晋纪》，故事更夸张，说王湛“未尝骑马，卒然便驰骋，步骤不异于济”，后面又喋喋不休夸张描述王湛的骑术，失去了尺度，这就是讲故事的败笔了。  
>民歌《书记报的产》：  
清树的叶子要算密了，没有把树枝压断；  
七八月的雨水要算多了，从没有把大海填满；  
只有我们书记报的产，胀破了大海，压平了秤杆。  
大青树密密的叶子，可以消暑解汗；  
老天下的雨水，可以浇地灌田；  
唯有书记报的产，使农民的肚皮饿扁。  

松风是后世经常歌咏的事物，以此为自然之美，使人身心皆旷。如王维名句“松风吹解带，山月照弹琴”，李白诗集中出现不下十余次……宋代有词牌《风入松》，多地有叫“松风亭”“松风阁”“松风堂”……日本诗歌“无上尊贵的山顶松风”“飒飒松风，伴和早晚撞钟声”，地名也有“松风町”…..松风是东亚文化中有名的审美对象，寄托了我们向往着屹立和超越于凡俗的情怀。  

## 8.18  
>裴仆射时人谓为言谈之林薮。

- *裴仆射*：裴頠曾任左仆射，王戎的女婿，前已多见。他“博学稽古”，著有《崇有论》、《辩才论》。“裴頠谈理，与王夷甫不相推下”，王衍说：“裴仆射善谈名理，混混有雅致”，周弼说：“頠若武库，五兵纵横，一时之杰也”等。  
- *薮*：草木丛聚处。  

## 8.19  
>张华见褚陶，语陆平原曰:“君兄弟龙跃云津，顾彦先凤鸣朝阳，谓东南之宝已尽，不意复见褚生。”陆曰：“公未睹不鸣不跃者耳！”  

- *褚陶*：褚陶字季雅，吴国杭州人，后入晋朝为尚书郎，官至中尉（禁军首领），“聪慧绝伦，年十三作《鸥鸟》、《水硙》二赋，见者奇之”。  
- *陆平原*：陆机，前已多见，曾任平原内史。  
- *君兄弟*：陆机、陆云。  
- *顾彦先*：顾荣。吴亡后，他与陆机兄弟到洛阳，时人称之为“三俊”。张华特别看重“二陆”，曾经说：“伐吴之役，利获二俊”。而陆机兄弟“初入洛，不推中国人士，见华一面如旧，钦其德范，如师资之礼焉。”  
- *云津*：银河。银河在古籍中名字很多，如天河、天汉、天津、高河、高影、星汉、星津、云川、云津、银湾、玉津、灵津、鹊河、鹊渚等近百种。  
- *东南之宝*：义同2.34“东南之美”。张华当时是三公之一，而且“性好人物，诱进不倦，至于穷贱侯门之士，有一介之善者，便咨嗟称咏，为之延誉”。他的政治任务之一就是尽量笼络吴国的士人来巩固政权，所以要隔三差五夸奖一下他们，使用“二俊”“三俊”“五俊”“南金”“东南之宝”等夸张的称呼。  
- *不鸣不跃*：还有好些凤凰不鸣，潜龙于渊的，指那些隐居不仕的人。陆机兄弟为家族、功名出仕西晋，总归德行有亏，有时候要被某些西晋征服者歧视。有一次王浑酒酣之时讽刺吴人：“诸君亡国之余，得无戚乎！”周处就回击说：“汉末分崩，三国鼎立。魏灭于前，吴亡于后。亡国之感，岂惟一人！”  

## 8.20  
>有问秀才：“吴旧姓何如?”答曰：“吴府君，圣王之老成，明时之俊乂；朱永长，理物之至德，清选之高望；严仲弼，九皋之鸣鹤，空谷之白驹；顾彦先，八音之琴瑟，五色之龙章；张威伯，岁寒之茂松，幽夜之逸光；陆士衡、士龙，鸿鹄之裴回，悬鼓之待槌。凡此诸君，以洪笔为鉏耒，以纸札为良田，以玄默为稼穑，以义理为丰年，以谈论为英华，以忠恕为珍宝，著文章为锦绣，蕴《五经》为缯帛，坐谦虚为席荐，张义让为帷幙，行仁义为室宇，修道德为广宅。”  

这段文字居然没有明确是谁说的，疑有漏字。也许情况是，这些被褒奖的人的评价，本是原吴国的共识，在类似“月旦评”的清议场合屡屡被人提及，“秀才”无非是汇总而已。  
在刘孝标的注中解释说，这是西晋扬州刺史周俊询问原东吴人士蔡洪（太康年间被举荐为秀才），请他推荐人才。蔡洪回家后写了一篇赋，举荐了这些人。《世说》是该赋的节录，且文字有不同版本，有的版本没有陆云、陆机两个人。  
- *旧姓*：旧家，世家，大户人家。“世上几百年旧家无非积德，天下第一件好事还是读书”。  
- *吴府君*：吴展，曾任吴国广州刺史、吴郡太守，所以称府君，他吴亡后“闭门自守”。在有圣明君主的时候，他是老城谋算的大臣；在政治清明的时候，他是百里挑一的人物（才德过千人为俊，百人为乂）。  
- *朱永长*：朱诞，曾任吴国建安太守、淮南内史，吴亡后吴平归家。理物即治民，班固 《白虎通-诛伐》：“王者承天理物，故率天下静，不復行役，扶助微气，成万物也。”刘基《顺斋箴为夏仲珍作》：“尧舜理物，因利除恶。”   “清”通“精”，清选，精心挑选出来的人才。《三国志-高柔传》：“然今博士，皆经明行修，一国清选。”  
- 严仲弼：严隐，曾任吴国宛陵令。九皋：九折之泽。《诗经-鹤鸣》：“鹤鸣于九皋，声闻于天”。《诗经-白驹》：“皎皎白驹，在彼空谷”。仙鹤和白驹，都包含隐居的意思。  
- *顾彦先*：顾荣，前已多见。八音指金、石、土、木、丝、竹、匏、革的乐器分类，琴瑟是八音中的丝，五色泛指所有颜色（图案），龙章指龙纹，引申为最美的图案，再引申为最高的才华。  
- *张威伯*：张畅，吴郡张氏子弟。陆机有一篇《荐张畅表》可略见其生平：伏见司徒，下谏议大夫张畅除，当为豫章内史丞（此处标点有点困难，大概是陆机写给司徒的表，谏议大夫也许有上下之分；也许是伏见司徒下，司徒下类似陛下的敬称；也许司徒下谏议大夫就是官名，“伏见，司徒下谏议大夫张畅除”）。畅才思清敏，志节贞厉，秉心立操，早有名誉。其年时旧比，多历郡守，惟畅陵迟，白首末齿而佐下藩，遂蹈碎浊，於畅名实损。愚以为宜解举，试以近县。  
- *幽夜之逸光*：黑夜中的月亮。即使宇宙总体而言是一篇漆黑，而真正令人敬畏赞叹的是那闪烁的星光。  
- *裴回*：通徘徊，盘旋留恋。  
- *悬鼓之待槌*：化用《礼记》，“庙堂之上，罍樽在阼，牺樽在西。庙堂之下，悬鼓在西，应鼓在东……礼交动乎上，乐交应乎下，和之至也”，“善待问者如撞钟，叩之以小者则小鸣，叩之以大者则大鸣；待其从容，然后尽其声”；以及《《淮南子》，“禹之时，以五音听治。悬钟鼓磬铎，置鼗，以待四方之士。为号曰：教寡人以道者击鼓，谕寡人以义者击钟，告寡人以事者振铎，语寡人以忧者击磬，有狱讼者摇鼗”，意思是说陆云、陆机已经得道，就在等待有人来咨询。  
- *洪笔*：大笔，后面12句都是说这些人笔耕、学习、修身不辍。这种差不多意思的排比铺陈修辞手法如果超过4句，就显得过分渲染，句式过于整齐，内容空洞，情感缺乏转折、递进等起伏，现在看来没有必要，而是错误的写法。只是当时人并未意识到这一点，往往还会变本加厉，于是长赋走入死胡同。它的流变就是现在的某些公文，动辄几十页，喋喋不休讲道理，搞面面俱到，小标题呆板对仗，内容避实就虚，而只有自媒体时代，作者为吸引读者，才避免了这种体现衙门权力的写法。蔡洪的推荐信的某个版本里，没有这12个累句。  

## 8.21  
>人问王夷甫：“山巨源义理何如？是谁辈？”曰：“此人初不肯以谈自居，然不读老庄，时闻其咏，往往与其旨合。”  

- *初*：当初。  
因为山涛平时不太说话，后世的顾恺之说山涛“无所标明，淳深渊默，人莫见其际”。而王衍幼年见过山涛，堂兄王戎更是山涛的竹林之友，故能有所回忆，评价山涛的玄学水准，但没有明说“和谁差不多”。
- *“不读老庄”*是夸张的说法。《晋书》中说山涛“好庄老，与嵇康善”，他的学理才情和嵇康阮籍有距离，以至于《世说新语•贤媛》中山涛妻子韩氏评价说：“君才致殊不如，正当以识度相友耳”（你的才华情致和他们差得远，而正是因为见识气度和他们相仿交游）。  

## 8.22  
>洛中雅雅有三嘏。刘粹字纯嘏，宏字终嘏，漠字冲嘏，是亲兄弟，王安丰甥，并是王安丰女婿。宏，真长祖也。  
洛中铮铮冯惠卿。名荪，是播子。荪与邢乔俱司徒李胤外孙，及胤子顺并知名。时称：“冯才清，李才明，纯粹邢。”  

- *雅雅*：叠词表众多，雅雅指风流雅士多。铮铮：叠词表响亮，铮铮指名声显赫。  
- *嘏*：祭祀祝福，就是福气的意思，语出《诗•小雅•宾之初筵》：锡尔纯嘏，子孙甚湛。  
刘粹三兄弟是刘邠的儿子，刘邠是西晋平原太守；刘粹西晋侍中，南中郎将；刘宏，秘书监，光禄大夫；刘漠，湘州刺史。刘宏是东晋大名士刘惔的祖父。三人和王戎没有亲戚关系。
- *冯荪*：曾任西晋侍中。荪是楚辞中的一种香草，惠是指美好。  
- *邢乔*：曾任西晋司隶校尉。  
- *李顺*：曾任西晋太仆卿。  
- *纯粹*：纯正完美。语出《易•乾》：“大哉乾乎，刚健中正，纯粹精也”，“纯粹邢”为了押韵。  

## 8.23  
>卫伯玉为尚书令，见乐广与中朝名士谈议，奇之，曰：“自昔诸人没已来，常恐微言将绝，今乃复闻斯言于君矣！”命子弟造之，曰：“此人人之水镜也，见之若披云雾睹青天。”  

- *卫瓘*赞*乐广*。他是魏晋老臣，年轻的时候见过何晏、夏侯玄这些“正始名士”（诸人）。278年，卫瓘已经58岁，从征北大将军入朝为尚书令，见到“中朝名士”（乐广、王衍、裴楷、张华等）清谈玄理，他欣慰夸奖。  
- *微言*：精妙的言论。现在认为，乐广等人在学理上并没有多大造就。但在当时，他们集体努力把儒学转入“三玄”，个人人格觉醒，对人生重新考量，用道家学说来注儒家的易经，“有无”“才性”“名理”“自然”“言意”等的反复辩论，引导时代风尚，普及新“三观”，很了不起。  
- *水镜*：东晋习凿齿：“水至平而邪者取法，镜至明而丑者无怒，水镜之所以能穷物而无怨者，以其无私也”，“诸葛孔明为卧龙，庞士元为凤雏，司马德操为水镜”。李世民：“夫以铜为镜，可以正衣冠；以史为镜，可以知兴替；以人为镜，可以明得失。”意思是说，和乐广交流，可以去掉疑惑，认识自我，见贤思齐。王衍评价乐广：“与人语甚简至，及见广，便觉己之烦。” 《晋阳秋》中说：“乐广善以约言厌人心，其所不知，默如也。”  

这个故事的成语是“乐广披云”。拨（豁）开云雾见青天的来源于此，它的变体有“拨开云雾见天日”，“守得云开见月明”，月明最美。  
仓洋嘉措《情歌》：在那东方山顶，升起洁白的月亮。美丽姑娘的面容，渐渐浮现心上。  
普通的起兴和比喻，由于长期积淀的语言形象的关系，凸现出美感来。苏珊•朗格在《情感与形式》中说：“艺术是表现人类情感的符号，在人类生活中存在着极为复杂的生命感受，它们像在森林中的灯火那样变化不定，互相交叉和重叠……组成了我们称之为‘内在生命’的东西。”  


## 8.24  
>王太尉曰：“见裴令公精明朗然，笼盖人上，非凡识也。若死而可作，当与之同归。”或云王戎语。  

“容止•10”中说，（裴令公）有疾，至困，惠帝使王夷甫往看。裴方向壁卧，闻王使至，强回视之。王出，语人曰：“双眸闪闪，若岩下电；精神挺动，体中故小恶。”  
刘孝标注引《名士传》：楷病困，诏遣黄门郎王夷甫省之，楷回眸属夷甫云：“竟未相识。”夷甫还，亦叹其神俊。这一段王衍谈到“死”，也许就是他在裴楷去世后，就其“神俊”具体阐述。  
- *精明朗然*：精明与郎然搭配不太合适，精明或当做“清明”。“裴楷清通”为一时公认，裴楷“风神高迈，容仪俊爽，博涉群书，特精理义”，“性宽厚，与物无忤”。王衍也不会夸裴楷精明。  
- *笼盖*：超越。《晋中兴书》曰：郗超……倜傥高俊，笼盖当时。《明史•王世贞传》：“（世贞 ）才最高，地望最显，声华意气笼盖海内。”  
- *死而可作，当与之同归*：作，起，复活。归：归随，同道。语出《礼记•檀弓》：赵文子与叔誉观乎九原。文子曰：“死者如可作也，吾谁与归？”叔誉曰：“其阳处父乎？”文子曰：“行并植于晋国，不没其身，其知不足称也。”“其舅犯乎？”文子曰：“见利不顾其君，其仁不足称也。我则随武子乎，利其君不忘其身，谋其身不遗其友。”又见刘向《新序•杂事》：晋平公过九原而叹曰：“嗟乎！此地之蕴吾良臣多矣，若使死者起也，吾将谁与归乎？”王衍自诩与裴楷是同道中人，大意是说，如果裴楷能死而复生，那么我王衍将追随他（一起追寻大道）。  是啊，人的一生，真正的同道很少，同志是珍贵的称呼。所以清朝何溱说：“人生得一知已足矣，斯世当以同怀视之”。  
但裴楷和王衍未必是一路人，所以裴楷临终时说，我不认识你！王衍是自作多情。自抬身价。  
我们可以理解成另一种意思，“你是谁，我不认识你？”也许裴楷发起了哲学拷问，也许是说“人生只若初见”，这样是把王衍当做了同道。  
我们从苏轼的词中获得成另一种解释，“纵使相逢应不识，尘满面，鬓如霜”，“我病得重，形象已改，不是王衍你以前认识的我了。”而王衍认为裴楷虽然形象已改，但精神依旧，“你还是你”，“神俊”。  
由于文言简约，我们常常要穿梭在词语的丛林中，面前是一个个没有钥匙的黑箱子。  


## 8.25  
>王夷甫自叹：“我与乐令谈，未尝不觉我言为烦。”  

中朝名士乐广与王衍齐名，“故天下人言风流者以王、乐为首焉”，王衍“信口雌黄”，乐广“约言析理”。  
乐广“辞约而旨达”，见4.16的解释。而王衍往往能整天谈论不休，见4.11“王昨已语多”。

## 8.26  
>郭子玄有俊才，能言老庄，庾敳尝称之，每曰：“郭子玄何必减庾子嵩！”    

- *减*：逊，不如。《资治通鉴•陈纪五》：“君才不减关羽矣”  

郭象和王弼是魏晋玄学的理论领袖，著作等身，后世研究玄学必谈之人。庾敳是哪位？他连《庄子》都没看几行，“开卷一尺许便放去”。  
不过郭象是理论家，出身似为寻常，史料未记载其家族里籍，其一到高位，没有什么老庄之风，据说“熏灼内外”“倾动一府”，“操弄天权，刑赏由己”，被门户官宦所嫉恨；庾敳是实践者，颍川庾氏发迹于曹魏之时，当时已是权贵门户，他“常静默无为”，“处众人中，居然独立”。

## 8.27  
>王平子目太尉：“阿兄形似道，而神锋太俊。”太尉答曰：“诚不如卿落落穆穆”   

王澄、王衍兄弟互相吹捧。王衍曾经说，天下英才，王澄第一，庾敳第二，王敦第三。
- *形似道* 费解，王衍颜值固然高，但不至于有六块腹肌；即使他有马甲线，又与“道”何干？在《后汉书•黄宪传论》中涉及“似道”：“宪隤然其处顺，渊乎其似道。”这是说黄宪处世顺其自然，修养深远如“道”那样不可知。可哪有形体以道为比喻的？此处 “形”或为衍字。  
- *神锋*，又作“神峰”，指风度气质。《南史•王规传》：“王威明风韵遒上，神峰标映，千里绝迹，百尺无枝，实俊人也。”宋代洪皓《彦清生日》诗：“卓尔神峰秀，昭然冰鉴清。”这是说王衍修养高深，但长得太出众，明明是实力派，却靠颜值吃饭，掩盖了他的真正特质。  
- *落落穆穆*：洒落大方之美。唐杨炯 《和刘长史答十九兄》：“风标自落落，文质且彬彬。”《毛传》：“穆穆，美也。”《荀子•大略》:“言语之美，穆穆皇皇。”明李之世《赠王尧韭》：“生无媚骨供时人，落穆情怀一任真。”王澄上任荆州刺史时当众掏鸟窝，“神气萧然，傍若无人”；期间日夜纵酒，“虽寇戎急务，亦不以在怀”，确是做到了匪夷所思的“落穆”。这种庄子式的性格无法任事，原中国女曲教练韩国人金昶伯说：“生活和训练（工作）就该区别开，如果生活像训练一样严肃就失去情趣；反过来训练如果像生活一样松散，就失去原则，不会进步。”  

## 8.28  
>太傅府有三才：刘庆孙长才，潘阳仲大才，裴景声清才。  

- *司马越*是司马懿弟弟的孙子，晋惠帝司马衷的远房叔叔，“八王之乱”的最后获胜者，任太傅，录尚书事，传说他后来毒杀了司马衷，另立司马衷的弟弟司马炽为帝，把持朝政。其帐下有三个杰出人物，一是刘琨的哥哥刘舆刘庆孙（见6.10），二是潘滔潘阳仲（见7.6），三是裴邈裴景声（见6.11）。刘长于处事，潘博学，裴方正。  

## 8.29  
>林下诸贤，各有俊才子：籍子浑，器量弘旷：康子绍，清远雅正；涛子简，疏通高素；咸子瞻，虚夷有远志；瞻弟孚，爽朗多所遗；秀子纯、悌，并令淑有清流；戎子万子，有大成之风，苗而不秀；唯伶子无闻。凡此诸子，唯瞻为冠，绍、简亦见重当世。  

- *嵇康*的儿子*嵇绍*故事最多，最后因保护晋惠帝被司马颖的军队杀害。司马家杀了嵇康，其儿子为司马家死节，颇为后人非议，但历朝皇帝是很喜欢的。  
- *阮瞻*为人退让（谦虚平易），为当时所重。有故事说，他持无鬼论，有一天和一个客人辩论有没有鬼，客人说不过他，就显出鬼形，一年后阮瞻病逝，时年30。  
阮孚不计世事，终日酣纵，喜欢鞋子，见6.15等。
- *令淑有清流*：美好文雅高洁。  
- *王绥*字万子，19岁去世，“不秀”。  

当时的才俊标准和现在不一样，当时以气度为美，现在以地位为美。

## 8.30  
>庾子躬有废疾，甚知名。家在城西，号曰城西公府。  

- *庾子躬*：庾琮，颍川庾氏前辈，“卿卿我我”庾敳的哥哥，庾亮的叔叔，官至太尉掾。太尉是三公之一，庾琮由于很有名望，时人认为他的才能不亚于三公，于是住宅也被称为公府。这种词语用法常见，譬如把县令、知府称之为“公”，把丈夫称之为“相公”等。  
- *废疾*：唐代《户令》对废疾的解释是“痴哑、侏儒、腰脊折、一肢废，如此之类，皆为废疾”，“恶疾、癫狂、两肢废、两目盲，如此之类，皆为笃疾”。  

## 8.31  
>王夷甫语乐令：“名士无多人，故当容平子知。”  

- *王衍*抬举他弟弟*王澄*，常常说，只要王澄评价过了，我就不发表意见了。为了让王澄的评价更具有权威性，当时最大的名士王衍就对另一个大名士乐广商量说，我们这些名士不常常夸人的，这个人物品评的要诀要让王澄知道哦。王澄记住了，于是有后面的“王平子迈世有俊才，少所推眼”。  
- *多*：点赞。《史记-管仲列传》：“天下不多管仲之贤，而多鲍叔能知人也。”  

王衍精明由此可见，他认为人物品评滥用表扬，那表扬就一钱不值了。

## 8.32  
>王太尉云：“郭子玄语议如悬河写水，注而不竭。”  

- *语议*：言辞议论。写同泻。  
- *郭象*前已多见，字子玄，河南人，生卒年不详，年轻时曾“辟召不就”，后任黄门郎，也曾是司马越幕僚，“任职当权，熏灼内外”。他对《庄子》、《老子》和《论语》都写过注解，现在仅存《庄子注》，虽然有人就揭发他是抄袭向秀注解的，但就像我注解《世说新语》一样，我参考过很多书籍，但抄是谈不上的。正是因为他注《庄子》，多有创见发挥，成为玄学领域最重要的学者。譬如他谈“独化”，就指出世界不是无中生有的，如果世界起源于无，那无怎么造物呢？他又提出，物质有自性，有自性才有本质，才有差别…..这些认识都是真知灼见，高于老庄学说，至今仍对我们的世界观有指导思想  
郭象思想深邃，而且表达能力强，言意相得，是杰出的学者。

## 8.33  
>司马太傅府多名士，一时俊异。庾文康云：“见子嵩在其中，常自神王。”  

司马越是八王之乱的最后胜出者，其帐下幕佐现可考知79人，分布在15州近50郡，绝大多数为士族，其中琅琊王氏占据了重要地位，成为司马越幕府的中坚力量，这也直接左右了东晋“王与马，共天下”的政治结构。  
司马越之帐下多名士，是因为司马越仅仅是宗室的远亲，执政时中枢势力不够，就和名士领袖王衍交好。这样司马越提供职位，王衍推荐人员.   
- *庾亮*谥号“文康”，他是庾敳的从侄儿，他在夸奖自己的叔叔，后面还有两则继续在夸。但用庾敳的字称呼他，与礼不合，这并非庾亮的原话，8.41中称之为“家从”。  
- 神王：通“神旺”，精神振奋，出自《庄子•养生主》：“泽雉十步一啄，百步一饮，不蕲畜乎樊中， 虽神王不善也。”大意是说，沼泽里的野鸡走十步才啄到一口食物，走百步才饮到一口水，可它并不祈求被养在笼子里。（养在笼子里的鸡）神态虽然旺盛，但它并不觉得好。  

庾敳和阮籍一样，也当过陈留相，他追慕先贤，“未尝以事婴心，从容酣畅”，“颓然渊放”，“神气融散”，庾亮认为他最具有名士的风范。  

## 8.34  
>太傅东海王镇许昌，以王安期为记室参军，雅相知重。敕世子毗曰：“夫学之所益者浅，体之所安者深。闲习礼度，不如式瞻仪形；讽味遗言，不如亲承音旨，王参军人伦之表，汝其师之。”或曰：“王、赵、邓三参军，人伦之表，汝其师之。”谓安期，邓伯道，赵穆也。袁宏作《名士传》，直云王参军。或云赵家先犹有此本。  

306年11月，晋怀帝司马炽继位，亲理政事，司马越不能专权，求引退回封地，晋怀帝不许。307年，司马越出镇许昌，王承（见3.9）为其掌管文书机要。  
- *雅相*：素来对他。  
- *学之所益者浅，体之所安者深*：纸上得来终觉浅，绝知此事要躬行的意思。  
- *闲习*：闲通“娴”，熟习。  
- *式瞻*：看，瞻仰。  
- *仪形*：仪表举止。司马越希望儿子得到王承的言传身教。  
- *讽味*：朗诵体会。  
- *人伦*：社会。  
- *邓伯道、赵穆*：在刘孝标的注中说，这是司马越写信给赵穆、王承、阮瞻和邓攸，请他们教育自己的孩子司马毗，“毗既无令淑之资，未闻道德之风，欲屈诸君，时以闲豫，周旋燕诲也。”  

司马越的历史评价不好，其执政期间“大失众望，而多有猜嫌”，“专擅威权，图为霸业”，“不臣之迹，四海所知”，“公私罄乏，所在寇乱，州郡携贰，上下崩离，祸结衅深”，但主要原因并不在他，而是西晋建国时设计的政治架构和继承人问题引发的。而他早年“少有令名，谦虚持布衣之操，为中外所宗”；在这封信中表现的情感也谦逊文雅，对孩子的期望与普通父亲并没有什么两样。只不过当时地动山摇，海水倾覆，无策回天了。  

## 8.35
> 庾太尉少为王眉子所知。庾过江，叹王曰：“庇其宇下，使人忘寒暑。”  

庾亮年轻时候被王衍的儿子王玄所赏识褒奖。永嘉南渡后，庾亮回忆起被陈留豪强所杀害的故人，赞美他曾经让年轻的自己如沐春风。“庇其宇下”，在其屋檐下，比喻得到他的照顾。

## 8.36  
>谢幼舆曰：“友人王眉子清通简畅，嵇延祖弘雅劭长，董仲道卓荦有致度。”  

- *谢幼舆*谢鲲，见2.46，谢安的伯父，谢家开始发达的始祖，年少时受到士王衍、嵇绍的赏识，与王敦、庾敳、阮修并称四友。  
- *王眉子*，王衍的儿子王玄；  
- *嵇延祖*，嵇康的儿子嵇绍；  
- *董仲道*，隐士董养。  

清通简畅，水平高的人能把复杂的事情处理的清爽通达，道德品质高的人不追求感官的奢靡繁复；弘雅劭长，有高尚品德的人宽宏大量，意味深长；卓荦有致度，卓越的人自然就有高雅的风采。  
当时朝廷有大赦，除了孙子杀祖父母，儿子杀父母罪不可赦，其他十恶不赦也都可赦免。董养认为，杀直系血亲确实不可赦免，但贾南风假借晋惠帝的名头，幽闭饿死了婆婆杨芷，这也是大罪，但朝廷里的大臣们文过饰非，落井下石，这是没有任何原则的朝廷。没有任何原则的朝廷，必将引发天下大乱。谢鲲，阮孚是我的朋友，你们也要注意乱世即将来临，早点躲藏自保姓名。董养于是和妻子躲到蜀地去了，不知所踪。八王之乱中，谢鲲渡江躲到江西，阮孚渡江去了南京，都在司马睿那里得以保全。  

## 8.37  
>王公目太尉：“岩岩清峙，壁立千仞。”  

王导夸从兄王衍，以壁立千仞形容人的出典。王导的说法也许来自西晋末文学家张载的《剑阁铭》：“是曰剑阁，壁立千仞。穷地之险，极路之峻。世浊则逆，道清斯顺。”   世浊则逆，道清斯顺令人感慨。我的叔叔是个小企业主，他说过的一句话我印象很深：“太平世道好赚钱”。是啊，老百姓谋生不易，如果老是打打杀杀，老百姓哪有什么经济条件啊。王衍如果生活在顺世，以他的颜值风采，必定流芳于后。不过按照林则徐的说法，真正壁立千仞，无论什么世道，像王衍这样的人都会发出耀眼的光亮。但“狡兔三窟”的王衍欲望太多，王导仅仅是吹捧而非其人格事实。

## 　8.38  
>庾太尉在洛下，问讯中郎，中郎留之云：“诸人当来。”寻温元甫、刘王乔、裴叔则俱至，酬酢终日。庾公犹忆刘、裴之才俊，元甫之清中。  

- *庾亮*是庾敳的侄儿。据前人考据，裴楷去世时，庾亮还是幼儿，此事不确。  
- *问讯*：问候。《后汉书•清河孝王庆传》：“庆多被病，或时不安，帝朝夕问讯，进膳药，所以垂意甚备。”  
- *温元甫*：温几，在湘州刺史任上去世。  
- *刘王乔*：刘畴。官至司徒左长史。  
- *裴叔则*：裴楷，前已多见。  

帕斯捷尔纳克《日瓦戈医生》：
>因此在早春的时候，  
朋友们常常聚首，  
我们把晚会当作别离，  
把酒宴当作遗言，  
为的是用这内心的痛苦，  
温暖那凄凉无情的生活。

## 8.39  
>蔡司徒在洛，见陆机兄弟住参佐廨中。三间瓦屋，士龙住东头，士衡住西头。士龙为人，文弱可爱；士衡长七尺余，声作钟声，言多慷慨。  

- *蔡司徒*：嘲笑王导怕老婆的蔡谟，东晋时官至司徒，见5.40等。陆云、陆机去世时蔡谟才19岁，比陆云小20岁。估计当时相遇是因为蔡谟随着父亲蔡克在洛阳成都王司马颖那里做事，陆云、陆机也在那里。后来陆云、陆机被司马颖处死前，“蔡克入至颖前，叩头流血，曰：‘云为孟玖所怨，远近莫不闻。今果见杀，罪无彰验，将令群心疑惑，窃为明公惜之。’”陆云兄弟和蔡克交情很深，所以蔡谟回忆当年陆云、陆机的风采。   
- *参佐廨*：参谋等属官的宿舍。
- *文弱可爱*：见5.18，卢志直呼陆逊、陆抗的名字，陆机奋起反击，陆云“失色”。平时陆机自比乐毅，而陆云被张华比之为“颜回”，可见两人性格有很大差异。  
- *长七尺余*：古代尺度有很多变化，但在当时长七尺五寸以上，可以作为特点载入《三国志》。譬如刘表“刘表长八尺余，姿貌甚伟”，刘备“身长七尺五寸”，诸葛亮“身高八尺”，程昱“长八尺三寸，美须髯”，太史慈“长七尺七寸，美须髯”……反过来说，不到七尺五寸的，不配在史书上留下身高。明确史料记载身高惊人的，可能是孔子。据《史记•孔子世家》中说，“孔子长九尺有六寸，人皆谓之‘长人’而异之”，即使鲁国的度再奇怪，孔子都是巨人。  
- *声作钟声*：据冯玉祥回忆，他在袁世凯的新军中当兵，因为声音洪亮，喊口令好，所以入伍不就就当哨长了。陆机身材高，声音响，言辞慷慨，更是著名的文学家，在后人眼里与曹植同列，魏收《魏书》中说：“曹植信魏世之英，陆机则晋朝之秀，虽同时并列，分途争远。”  

## 8.40  
>王长史是庾子躬外孙。丞相目子躬云：“入理泓然，我已上人。”  

- *王长史*：顾镜自夸“王讷生了这么好的儿子”的王濛，曾在王导手下做司徒掾，前已多见。  
- *庾子躬*：“西城公府”的庾琮，他身有残疾，后来就没有做官，但名声大，所以王导向王濛夸奖他外祖父，其中包含长者对晚辈的期望：当年你外公学术水平比我高哦，希望你不要辱没他。  
- *入理泓然*：体会玄理深广。  

说到残疾，《庄子》里常常拿残疾人做譬喻。在其笔下，这些畸人形体虽然残缺，但个个都是“哲学王”，成为思想的代言人。有的是“无用之用”的代表，有的品德高尚见识深邃，有的对不幸命运安之若素，精神居于常人之上……就像《巴黎圣母院》里，给人印象最深的往往是卡西莫多而不是其他人物。  
《庄子》选择残疾人为譬喻也许别有深意。世界残缺黑暗，所以人体也残缺；人体的残缺更要尝尽酸甜苦辣，有助于擦亮自性，靠近真理；人世间的种种遭遇荣辱皆如烟云，心灵才是唯一的世外桃源……  

## 8.41  
>庾太尉目庾中郎：“家从谈谈之许。”  

41则与42则两次都是庾亮夸其叔叔庾敳，他明明在33则刚夸过，刘义庆编著的时候不认真？
此则费解，或有漏字，或为衍文。

## 8.42  
>庾公目中郎：“神气融散，差如得上。”  

- *融散*：旷达。这个词语大约出自庾敳写的《意赋》：“兀与自然并体兮，融液忽而四散”，其大意是说精神与自然像液体一样交融，弥漫一体。融液就是融汇的意思。神气相当于现在所说的精气神，道教分的比较细，说什么“炼精化气、炼气化神，炼神还虚”。古人大致认为，精本意是精液，引申为生命的内核；气本意是呼吸，引申为维持生命的动力；神大约就是指人活动表现出来的精神气质。神气融散大意是说庾敳言行举止表现出的气质旷达，与自然交融。  
- *差如*：大体比得上。差强人意。昨天中国足球队输球，足协居然使用差强人，意这个成语，引来吐槽。差其实是蛮能够的意思，虽然后来词义转移，弱化为大体，但并非否定的意思。“差如得上”，蛮算得上是第一流的人物，因为有竹林七贤等先贤在前面，总要谦虚一点。  
